import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { useTheme } from '@/providers/ThemeProvider';
import { ShieldCheck, Activity, Star, Users, CircleCheckBig, Clock, ArrowRight, Zap, ChevronRight } from 'lucide-react-native';
import AgentFeatures from '@/components/ai-agent/AgentFeatures';
import { useRouter } from 'expo-router';
export default function AgentPage(){const{theme}=useTheme();const router=useRouter();
const stats=[{label:'Controls Mapped',value:'2,890',icon:CircleCheckBig,color:'#34C759'},{label:'Uptime',value:'99.8%',icon:Activity,color:'#007AFF'},{label:'Response',value:'0.4s',icon:Clock,color:'#FF9500'},{label:'Accuracy',value:'99.8%',icon:Zap,color:'#C62828'}];
const capabilities=['Compliance Management','Framework Mapping','Evidence Gathering','Audit Support','Regulatory Compliance','Control Assessment','Compliance Reporting','Gap Analysis'];
const responsibilities=['Manage security compliance programs and initiatives','Map security controls to compliance frameworks','Gather and organize compliance evidence','Support internal and external audit activities','Ensure regulatory compliance across all requirements','Assess control effectiveness and coverage','Generate compliance reports and dashboards','Conduct gap analysis and remediation planning'];
const activities=[{time:'3 min ago',text:'Mapped 45 controls to SOC2'},{time:'20 min ago',text:'Gathered evidence for audit'},{time:'1 hour ago',text:'Generated compliance report'},{time:'3 hours ago',text:'Conducted gap analysis for PCI-DSS'}];
const subAgents=[{name:'AI Framework Mapper',route:'/ai-agent/security/sub-agents/framework-mapper',desc:'Framework mapping & alignment'},{name:'AI Evidence Gatherer',route:'/ai-agent/security/sub-agents/evidence-gatherer',desc:'Evidence gathering & organization'},{name:'AI Audit Liaison',route:'/ai-agent/security/sub-agents/audit-liaison',desc:'Audit liaison & coordination'}];
return(<ScrollView style={[styles.container,{backgroundColor:theme.colors.background}]}><View style={[styles.hero,{borderBottomColor:theme.colors.border||'#E5E5EA'}]}><View style={[styles.heroIconWrap,{backgroundColor:'#C6282820'}]}><ShieldCheck size={48} color="#C62828"/></View><Text style={[styles.heroTitle,{color:theme.colors.text}]}>AI Security Compliance Specialist</Text><Text style={[styles.heroSubtitle,{color:theme.colors.textSecondary}]}>Security & Risk Department</Text><View style={styles.badgesRow}><View style={[styles.badge,{backgroundColor:'#34C75922'}]}><Activity size={12}color="#34C759"/><Text style={[styles.badgeText,{color:'#34C759'}]}>Active</Text></View><View style={[styles.badge,{backgroundColor:'#C6282822'}]}><Star size={12}color="#C62828"/><Text style={[styles.badgeText,{color:'#C62828'}]}>Specialist</Text></View><View style={[styles.badge,{backgroundColor:'#FF950022'}]}><Users size={12}color="#FF9500"/><Text style={[styles.badgeText,{color:'#FF9500'}]}>{subAgents.length} Sub-Agents</Text></View></View></View>
<View style={styles.statsContainer}>{stats.map((s,i)=>(<View key={i}style={[styles.statCard,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><s.icon size={22}color={s.color}/><Text style={[styles.statValue,{color:theme.colors.text}]}>{s.value}</Text><Text style={[styles.statLabel,{color:theme.colors.textSecondary}]}>{s.label}</Text></View>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Overview</Text><Text style={[styles.description,{color:theme.colors.textSecondary}]}>The AI Security Compliance Specialist manages compliance programs, maps controls, and supports audits. It oversees 3 specialized sub-agents for comprehensive compliance coverage.</Text></View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Core Capabilities</Text><View style={styles.tagsRow}>{capabilities.map((c,i)=>(<View key={i}style={[styles.tag,{backgroundColor:'#C6282815'}]}><Text style={[styles.tagText,{color:'#C62828'}]}>{c}</Text></View>))}</View></View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Key Responsibilities</Text>{responsibilities.map((r,i)=>(<View key={i}style={styles.respItem}><CircleCheckBig size={16}color="#34C759"/><Text style={[styles.respText,{color:theme.colors.textSecondary}]}>{r}</Text></View>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Recent Activity</Text>{activities.map((a,i)=>(<View key={i}style={styles.actItem}><Clock size={14}color="#FF9500"/><Text style={[styles.actText,{color:theme.colors.textSecondary}]}>{a.time} - {a.text}</Text></View>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>A2A Endpoints</Text>{['/consult/compliance-security','/compliance-security/execute','/compliance-security/analyze'].map((e,i)=>(<View key={i}style={styles.epItem}><Zap size={14}color="#007AFF"/><Text style={[styles.epText,{color:theme.colors.textSecondary}]}>{e}</Text></View>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Sub-Agents</Text>{subAgents.map((s,i)=>(<TouchableOpacity key={i}style={styles.subCard}onPress={()=>router.push(s.route as any)}><View style={styles.subInfo}><Text style={[styles.subName,{color:theme.colors.text}]}>{s.name}</Text><Text style={[styles.subDesc,{color:theme.colors.textSecondary}]}>{s.desc}</Text></View><ChevronRight size={20}color="#C62828"/></TouchableOpacity>))}</View>
<AgentFeatures agentId="compliance-security" agentName="AI Security Compliance Specialist" />
</ScrollView>);}
const styles=StyleSheet.create({container:{flex:1},hero:{padding:20,alignItems:'center',borderBottomWidth:1},heroIconWrap:{width:80,height:80,borderRadius:40,alignItems:'center',justifyContent:'center',marginBottom:12},heroTitle:{fontSize:22,fontWeight:'700',textAlign:'center',marginBottom:4},heroSubtitle:{fontSize:14,textAlign:'center',marginBottom:12},badgesRow:{flexDirection:'row',gap:8},badge:{flexDirection:'row',alignItems:'center',paddingHorizontal:8,paddingVertical:4,borderRadius:12,gap:4},badgeText:{fontSize:11,fontWeight:'600'},statsContainer:{flexDirection:'row',flexWrap:'wrap',padding:12,gap:8},statCard:{flex:1,minWidth:'45%',padding:12,borderRadius:12,alignItems:'center'},statValue:{fontSize:18,fontWeight:'700',marginTop:4},statLabel:{fontSize:11,marginTop:2},section:{padding:16,marginHorizontal:12,marginTop:12,borderRadius:12},sectionTitle:{fontSize:16,fontWeight:'700',marginBottom:12},description:{fontSize:14,lineHeight:20},tagsRow:{flexDirection:'row',flexWrap:'wrap',gap:6},tag:{paddingHorizontal:10,paddingVertical:5,borderRadius:16},tagText:{fontSize:12,fontWeight:'500'},respItem:{flexDirection:'row',alignItems:'flex-start',marginBottom:8,gap:8},respText:{flex:1,fontSize:13,lineHeight:18},actItem:{flexDirection:'row',alignItems:'center',marginBottom:6,gap:8},actText:{fontSize:12},epItem:{flexDirection:'row',alignItems:'center',marginBottom:6,gap:8},epText:{fontSize:12,fontFamily:'monospace'},subCard:{flexDirection:'row',alignItems:'center',padding:12,backgroundColor:'#F2F2F7',borderRadius:10,marginBottom:8},subInfo:{flex:1},subName:{fontSize:14,fontWeight:'600',marginBottom:2},subDesc:{fontSize:12}});