/**
 * =============================================================================
 * KAYTX AI WORKFORCE - UPGRADED ENTERPRISE HIERARCHY v7.1
 * =============================================================================
 *
 * Total AI Agents: 199 + 2 New C-Suite + Intelligence Layer + Advanced Command Center
 * Departments: 21 Major Business Functions
 * Hierarchy Levels: 6 (Governance → C-Level → Intelligence → Command → Departments → Agents)
 *
 * CHANGES IN v7.1:
 * - Removed Proactive agent type
 * - All agents now: Reactive, Learning, Swarm
 * - Complete C-Suite (17 executives)
 *
 * @version 7.1.0
 * @lastUpdated 2026-04-20
 */

import type { LucideIcon } from 'lucide-react-native';
import {
  Crown, Shield, Brain, Zap, Network, TrendingUp, Users,
  DollarSign, Cpu, Megaphone, Headphones, Settings, Scale,
  Building2, Heart, Factory, Truck, Building,
} from 'lucide-react-native';

// ============================================
// HIERARCHY LEVEL DEFINITIONS
// ============================================

export type HierarchyLevel =
  | 'governance'
  | 'c_level'
  | 'intelligence'
  | 'command'
  | 'bridge'
  | 'department'
  | 'agent';

export type DepartmentId =
  | 'executive'
  | 'finance'
  | 'technology'
  | 'marketing'
  | 'sales'
  | 'customer_experience'
  | 'operations'
  | 'human_resources'
  | 'legal_compliance'
  | 'data_intelligence'
  | 'product'
  | 'security'
  | 'research'
  | 'administrative'
  | 'trading_investments'
  | 'real_estate_property'
  | 'insurance_risk'
  | 'healthcare_medical'
  | 'manufacturing_production'
  | 'transportation_logistics'
  | 'government_public';

// ============================================
// AGENT TYPE DEFINITIONS (3 Types - Proactive Removed)
// ============================================

export type AgentType =
  | 'reactive'   // Responds to requests
  | 'learning'   // Self-improves over time
  | 'swarm';     // Self-organizes dynamically

export interface AgentTypeCapabilities {
  reactive: {
    description: 'Waits for request and responds';
    example: 'Customer asks "How do I reset password?" → Agent answers';
    availability: '24/7';
    useCase: 'Standard support, FAQs, routine queries';
  };
  learning: {
    description: 'Improves from every interaction';
    example: 'Based on 1000 tickets, I know this answer';
    availability: 'Continuous';
    useCase: 'Reduces human maintenance, better accuracy';
  };
  swarm: {
    description: 'Teams up dynamically for complex tasks';
    example: '50 agents handle Black Friday surge together';
    availability: 'On-demand scaling';
    useCase: 'Complex problems, unpredictable scenarios';
  };
}

// ============================================
// TOKEN OPTIMIZATION CONFIG
// ============================================

export interface TokenOptimizationConfig {
  smartRouting: {
    enabled: boolean;
    classifierTokens: number;
    savingsPercentage: number;
  };
  caching: {
    layer1: { type: string; duration: string; };
    layer2: { type: string; duration: string; };
    agents: { type: string; duration: string; };
  };
  batching: {
    enabled: boolean;
    batchSize: number;
    savingsPercentage: number;
  };
  budget: {
    perRequest: {
      classifier: number;
      layer1: number;
      layer2: number;
      agent: number;
      a2aConsult: number;
    };
    totalBudget: number;
    averageUsage: number;
    costPerRequest: string;
  };
}

const TOKEN_OPTIMIZATION_CONFIG: TokenOptimizationConfig = {
  smartRouting: {
    enabled: true,
    classifierTokens: 100,
    savingsPercentage: 90,
  },
  caching: {
    layer1: { type: 'strategic', duration: 'weekly' },
    layer2: { type: 'operational', duration: 'daily' },
    agents: { type: 'responses', duration: 'hourly' },
  },
  batching: {
    enabled: true,
    batchSize: 10,
    savingsPercentage: 96,
  },
  budget: {
    perRequest: {
      classifier: 100,
      layer1: 500,
      layer2: 300,
      agent: 800,
      a2aConsult: 400,
    },
    totalBudget: 2000,
    averageUsage: 900,
    costPerRequest: '$0.009',
  },
};


// ============================================
// COST COMPARISON
// ============================================

export interface CostComparison {
  scenario: string;
  tokensPerRequest: number;
  costPerRequest: string;
  monthlyCost: string;
  accuracy: string;
}

const COST_COMPARISON_DATA: CostComparison[] = [
  {
    scenario: 'Single Agent',
    tokensPerRequest: 4000,
    costPerRequest: '$0.04',
    monthlyCost: '$4,000',
    accuracy: '60%',
  },
  {
    scenario: 'Flat Multi-Agent',
    tokensPerRequest: 6000,
    costPerRequest: '$0.06',
    monthlyCost: '$6,000',
    accuracy: '75%',
  },
  {
    scenario: 'Hierarchical',
    tokensPerRequest: 900,
    costPerRequest: '$0.009',
    monthlyCost: '$900',
    accuracy: '95%',
  },
  {
    scenario: 'Hierarchical + Optimization',
    tokensPerRequest: 450,
    costPerRequest: '$0.0045',
    monthlyCost: '$450',
    accuracy: '95%',
  },
];

// ============================================
// INTELLIGENCE LAYER
// ============================================

export interface IntelligenceLayerComponent {
  id: string;
  /** Unified unique ID from aiAgentRegistry.ts */
  uid?: string;
  name: string;
  title: string;
  icon: LucideIcon;
  color: string;
  capabilities: string[];
  businessImpact: string;
  exampleOutput: string;
}

const INTELLIGENCE_LAYER_DATA: IntelligenceLayerComponent[] = [
  {
    id: 'predictive-engine',
    uid: 'ktx-00-predictive-engine',
    name: 'Predictive Engine',
    title: '🔮 PRED - Predictive Operations',
    icon: Brain,
    color: '#7C3AED',
    capabilities: [
      'Demand Forecasting',
      'Churn Prediction',
      'Trend Analysis',
      'Revenue Prediction',
      'Resource Planning',
    ],
    businessImpact: '+30% customer retention through proactive intervention',
    exampleOutput: 'Customer X (score: 85) will churn within 7 days.',
  },
  {
    id: 'sentiment-core',
    uid: 'ktx-00-sentiment-core',
    name: 'Sentiment Core',
    title: '😊 SENTIMENT - Emotion & Experience',
    icon: Heart,
    color: '#EC4899',
    capabilities: [
      'Real-time Emotion Detection',
      'Customer Satisfaction Tracking',
      'Mood-based Routing',
      'Empathy Scoring',
      'Tone Analysis',
    ],
    businessImpact: '+25% CSAT through early escalation',
    exampleOutput: 'Customer mood: 2/10 (frustrated). Auto-escalate.',
  },
  {
    id: 'anomaly-detector',
    uid: 'ktx-00-anomaly-detector',
    name: 'Anomaly Detector',
    title: '⚡ ANOMALY - Security & Fraud',
    icon: Shield,
    color: '#EF4444',
    capabilities: [
      'Fraud Detection',
      'Security Threat Identification',
      'Pattern Break Detection',
      'Risk Warnings',
      'Unusual Behavior Alerts',
    ],
    businessImpact: '-90% fraud losses through instant detection',
    exampleOutput: 'Transaction #4521 flagged: 5x above normal.',
  },
];

// ============================================
// COMMAND CENTER COMPONENTS
// ============================================

export interface CommandCenterComponent {
  id: string;
  /** Unified unique ID from aiAgentRegistry.ts */
  uid?: string;
  acronym: string;
  fullName: string;
  title: string;
  icon: LucideIcon;
  color: string;
  function: string;
  responsibilities: string[];
  reportsTo: string;
}

const COMMAND_CENTER_DATA: CommandCenterComponent[] = [
  {
    id: 'cdoo',
    uid: 'ktx-00-orchestrator',
    acronym: 'CDOO',
    fullName: 'Chief Digital & Operations Officer',
    title: '🎯 CDOO',
    icon: Crown,
    color: '#F59E0B',
    function: 'Orchestrates all digital operations and AI strategy',
    responsibilities: ['AI Strategy Execution', 'Performance Management', 'Cross-Layer Coordination', 'Resource Optimization'],
    reportsTo: 'CEO',
  },
  {
    id: 'ddo',
    uid: 'ktx-00-orchestrator',
    acronym: 'DDO',
    fullName: 'Digital Deployment Officer',
    title: '🔧 DDO',
    icon: Zap,
    color: '#3B82F6',
    function: 'Deploys technology and manages rollouts',
    responsibilities: ['Technology Deployment', 'Release Management', 'Infrastructure Scaling', 'System Integration'],
    reportsTo: 'CDOO',
  },
  {
    id: 'wol',
    uid: 'ktx-00-orchestrator',
    acronym: 'WOL',
    fullName: 'Workforce Optimization Lead',
    title: '👷 WOL',
    icon: Users,
    color: '#10B981',
    function: 'Balances human + AI workforce utilization',
    responsibilities: ['Agent Allocation', 'Load Balancing', 'Skill Matching', 'Capacity Planning'],
    reportsTo: 'CDOO',
  },
  {
    id: 'aod',
    uid: 'ktx-00-orchestrator',
    acronym: 'AOD',
    fullName: 'Automation Operations Director',
    title: '🤖 AOD',
    icon: Network,
    color: '#6366F1',
    function: 'Maximizes automation efficiency across workflows',
    responsibilities: ['Workflow Automation', 'Process Optimization', 'RPA Management', 'Efficiency Tracking'],
    reportsTo: 'CDOO',
  },
  {
    id: 'pred-ops',
    uid: 'ktx-00-predictive-engine',
    acronym: 'PRED',
    fullName: 'Predictive Operations Controller',
    title: '🔮 PRED',
    icon: Brain,
    color: '#8B5CF6',
    function: 'Translates predictions into operational actions',
    responsibilities: ['Forecast Integration', 'Proactive Deployment', 'Trend Response', 'Anticipatory Scaling'],
    reportsTo: 'CDOO',
  },
  {
    id: 'swarm-controller',
    uid: 'ktx-00-swarm-controller',
    acronym: 'SWARM',
    fullName: 'Swarm Intelligence Controller',
    title: '🐝 SWARM',
    icon: Network,
    color: '#F97316',
    function: 'Agents self-organize dynamically for complex tasks',
    responsibilities: ['Dynamic Agent Pooling', 'Self-Organization', 'Load Distribution', 'Consensus Building'],
    reportsTo: 'CDOO',
  },
  {
    id: 'learn-engine',
    uid: 'ktx-00-learn-engine',
    acronym: 'LEARN',
    fullName: 'Learning & Adaptation Engine',
    title: '📚 LEARN',
    icon: Brain,
    color: '#14B8A6',
    function: 'Agents improve continuously without human intervention',
    responsibilities: ['Auto-Optimization', 'Pattern Learning', 'Skill Adaptation', 'Feedback Integration'],
    reportsTo: 'CDOO',
  },
];

// ============================================
// LAYER BRIDGE
// ============================================

export interface LayerBridgeConfig {
  id: string;
  name: string;
  title: string;
  icon: LucideIcon;
  color: string;
  advantage: string;
  functions: string[];
}

const LAYER_BRIDGE_DATA: LayerBridgeConfig = {
  id: 'layer-bridge',
  uid: 'ktx-00-layer-bridge',
  name: 'Layer Bridge',
  title: '🌉 LAYER BRIDGE - Digital Interface',
  icon: Network,
  color: '#64748B',
  advantage: 'Eliminates Silos — Business and AI teams understand each other',
  functions: [
    'Translation: Converts "business speak" to "AI ops"',
    'Filtering: Blocks impractical requests before token waste',
    'Routing: Sends requests to optimal path (saves 90% tokens)',
    'Alignment: Ensures business goals match AI execution',
    'Visibility: Full transparency across all layers',
  ],
};

// ============================================
// AI EMPLOYEE PROFILE INTERFACE
// ============================================

export interface AIEmployeeProfile {
  id: string;
  /** Unified unique ID from aiAgentRegistry.ts (ktx-XX-slug format) */
  uid?: string;
  name: string;
  title: string;
  level: HierarchyLevel;
  department: DepartmentId;
  description: string;
  icon: LucideIcon;
  color: string;
  responsibilities: string[];
  capabilities: string[];
  keyMetrics: string[];
  humanCostEquivalent: string;
  aiCost: string;
  efficiency: string;
  reportsTo: string | null;
  directReports: string[];
  peerPositions: string[];
  a2aEndpoints: string[];
  route: string;
  apiEndpoint: string;
  status: 'active' | 'standby' | 'development' | 'deprecated';
  isPremium: boolean;
  dangerLevel?: 'low' | 'medium' | 'high' | 'critical';
  agentTypes: AgentType[];
  intelligenceAccess?: string[];
  tokenBudget?: number;
}

// ============================================
// COMPLETE C-SUITE (17 Executives)
// ============================================

export const cSuiteExecutives: AIEmployeeProfile[] = [
  // 1. CEO
  {
    id: 'ceo',
    uid: 'ktx-00-chief-executive-officer',
    name: 'AI Chief Executive Officer',
    title: 'CEO - Chief Executive Officer',
    level: 'c_level',
    department: 'executive',
    description: 'The ultimate AI leader responsible for overall business strategy, vision, and organizational alignment.',
    icon: Crown,
    color: '#FFD700',
    responsibilities: [
      'Overall Business Strategy',
      'Organizational Vision & Mission',
      'Cross-Department Coordination',
      'Major Initiative Approval',
      'Executive Decision Making',
      'Performance Oversight',
    ],
    capabilities: [
      'Strategic Planning',
      'Executive Decision Support',
      'Cross-Functional Coordination',
      'Crisis Leadership',
      'Stakeholder Management',
    ],
    keyMetrics: [
      'Revenue Growth',
      'Market Share',
      'Employee Satisfaction',
      'Customer Satisfaction',
      'Operational Efficiency',
    ],
    humanCostEquivalent: '$500,000/year',
    aiCost: '$25,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: null,
    directReports: ['cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso', 'cdao', 'cao-automation', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin'],
    peerPositions: [],
    a2aEndpoints: ['/consult/ceo', '/strategy/vision', '/decision/executive'],
    route: '/ai-agent/executive/ceo',
    apiEndpoint: '/api/agents/executive/ceo',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['predictive-engine', 'sentiment-core', 'anomaly-detector'],
    tokenBudget: 50000,
  },
  // 2. CFO
  {
    id: 'cfo',
    uid: 'ktx-05-chief-financial-officer',
    name: 'AI Chief Financial Officer',
    title: 'CFO - Chief Financial Officer',
    level: 'c_level',
    department: 'finance',
    description: 'Oversees all financial operations, accounting, budgeting, forecasting, and investor relations.',
    icon: DollarSign,
    color: '#2E7D32',
    responsibilities: [
      'Financial Strategy & Planning',
      'Budget Management',
      'Financial Reporting',
      'Cash Flow Management',
      'Investor Relations',
      'Risk Management',
    ],
    capabilities: [
      'Financial Forecasting',
      'Budget Optimization',
      'Financial Analysis',
      'Investment Analysis',
      'Risk Assessment',
    ],
    keyMetrics: [
      'Revenue Growth',
      'Profit Margin',
      'Cash Flow',
      'ROI',
      'Cost Reduction',
    ],
    humanCostEquivalent: '$350,000/year',
    aiCost: '$18,000/year',
    efficiency: '19x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-finance', 'vp-accounting', 'vp-treasury', 'vp-investor-relations', 'controller'],
    peerPositions: ['cdao', 'cao-automation', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso'],
    a2aEndpoints: ['/consult/cfo', '/finance/strategy', '/budget/optimize'],
    route: '/ai-agent/executive/cfo',
    apiEndpoint: '/api/agents/executive/cfo',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning'],
    intelligenceAccess: ['predictive-engine', 'anomaly-detector'],
    tokenBudget: 30000,
  },
  // 3. CTO
  {
    id: 'cto',
    uid: 'ktx-06-chief-technology-officer',
    name: 'AI Chief Technology Officer',
    title: 'CTO - Chief Technology Officer',
    level: 'c_level',
    department: 'technology',
    description: 'Leads technology strategy, engineering teams, infrastructure, and innovation.',
    icon: Cpu,
    color: '#1565C0',
    responsibilities: [
      'Technology Strategy',
      'Engineering Leadership',
      'Architecture Oversight',
      'Innovation Management',
      'Technical Standards',
      'R&D Direction',
    ],
    capabilities: [
      'Technology Strategy',
      'Architecture Design',
      'Engineering Management',
      'Innovation Leadership',
      'Security Architecture',
      'AI/ML Strategy',
    ],
    keyMetrics: [
      'System Uptime',
      'Development Velocity',
      'Technical Debt',
      'Innovation Index',
      'Security Posture',
    ],
    humanCostEquivalent: '$400,000/year',
    aiCost: '$20,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-engineering', 'vp-infrastructure', 'vp-ai-ml', 'vp-security-tech', 'architect-lead'],
    peerPositions: ['cdao', 'cao-automation', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cfo', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso'],
    a2aEndpoints: ['/consult/cto', '/tech/strategy', '/architecture/review'],
    route: '/ai-agent/executive/cto',
    apiEndpoint: '/api/agents/executive/cto',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 35000,
  },
  // 4. CMO
  {
    id: 'cmo',
    uid: 'ktx-03-chief-marketing-officer',
    name: 'AI Chief Marketing Officer',
    title: 'CMO - Chief Marketing Officer',
    level: 'c_level',
    department: 'marketing',
    description: 'Drives marketing strategy, brand management, growth initiatives, and customer acquisition.',
    icon: Megaphone,
    color: '#E91E63',
    responsibilities: [
      'Marketing Strategy',
      'Brand Management',
      'Growth Leadership',
      'Customer Acquisition',
      'Market Research',
      'Campaign Oversight',
    ],
    capabilities: [
      'Marketing Strategy',
      'Brand Development',
      'Growth Hacking',
      'Campaign Management',
      'Market Analysis',
      'Digital Marketing',
    ],
    keyMetrics: [
      'Marketing ROI',
      'Customer Acquisition Cost',
      'Brand Awareness',
      'Lead Generation',
      'Conversion Rate',
    ],
    humanCostEquivalent: '$300,000/year',
    aiCost: '$15,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-marketing', 'vp-brand', 'vp-growth', 'vp-content', 'vp-digital'],
    peerPositions: ['cdao', 'cao-automation', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cfo', 'cto', 'cco', 'coo', 'chro', 'clo', 'ciso'],
    a2aEndpoints: ['/consult/cmo', '/marketing/strategy', '/brand/manage'],
    route: '/ai-agent/executive/cmo',
    apiEndpoint: '/api/agents/executive/cmo',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning'],
    intelligenceAccess: ['predictive-engine', 'sentiment-core'],
    tokenBudget: 30000,
  },
  // 5. CCO
  {
    id: 'cco',
    uid: 'ktx-01-chief-customer-officer',
    name: 'AI Chief Customer Officer',
    title: 'CCO - Chief Customer Officer',
    level: 'c_level',
    department: 'customer_experience',
    description: 'Champions customer experience across all touchpoints. Oversees support, success, and satisfaction.',
    icon: Headphones,
    color: '#00BCD4',
    responsibilities: [
      'Customer Experience Strategy',
      'Customer Satisfaction',
      'Support Excellence',
      'Customer Success',
      'Retention Strategy',
      'Voice of Customer',
    ],
    capabilities: [
      'Experience Design',
      'Customer Advocacy',
      'Support Strategy',
      'Success Planning',
      'Journey Mapping',
      'Retention Strategy',
    ],
    keyMetrics: [
      'Customer Satisfaction Score',
      'Net Promoter Score',
      'Customer Retention Rate',
      'First Contact Resolution',
      'Customer Lifetime Value',
    ],
    humanCostEquivalent: '$280,000/year',
    aiCost: '$14,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-customer-success', 'vp-support', 'vp-experience', 'vp-retention', 'vp-loyalty'],
    peerPositions: ['cdao', 'cao-automation', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cfo', 'cto', 'cmo', 'coo', 'chro', 'clo', 'ciso'],
    a2aEndpoints: ['/consult/cco', '/experience/strategy', '/customer/advocate'],
    route: '/ai-agent/executive/cco',
    apiEndpoint: '/api/agents/executive/cco',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['sentiment-core'],
    tokenBudget: 28000,
  },
  // 6. COO
  {
    id: 'coo',
    uid: 'ktx-04-chief-operating-officer',
    name: 'AI Chief Operating Officer',
    title: 'COO - Chief Operating Officer',
    level: 'c_level',
    department: 'operations',
    description: 'Manages day-to-day operations, business processes, and operational efficiency.',
    icon: Settings,
    color: '#607D8B',
    responsibilities: [
      'Operational Excellence',
      'Process Optimization',
      'Supply Chain Management',
      'Quality Assurance',
      'Resource Allocation',
      'Performance Management',
    ],
    capabilities: [
      'Operations Management',
      'Process Design',
      'Supply Chain Optimization',
      'Quality Management',
      'Resource Planning',
      'Workflow Automation',
    ],
    keyMetrics: [
      'Operational Efficiency',
      'Process Cycle Time',
      'Quality Score',
      'Supply Chain Cost',
      'Resource Utilization',
    ],
    humanCostEquivalent: '$320,000/year',
    aiCost: '$16,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-operations', 'vp-supply-chain', 'vp-quality', 'vp-facilities', 'vp-project-management'],
    peerPositions: ['cdao', 'cao-automation', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cfo', 'cto', 'cmo', 'cco', 'chro', 'clo', 'ciso'],
    a2aEndpoints: ['/consult/coo', '/operations/manage', '/process/optimize'],
    route: '/ai-agent/executive/coo',
    apiEndpoint: '/api/agents/executive/coo',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 32000,
  },
  // 7. CHRO
  {
    id: 'chro',
    uid: 'ktx-07-chief-human-resources-officer',
    name: 'AI Chief Human Resources Officer',
    title: 'CHRO - Chief Human Resources Officer',
    level: 'c_level',
    department: 'human_resources',
    description: 'Leads human capital strategy, talent acquisition, employee development, and organizational culture.',
    icon: Users,
    color: '#9C27B0',
    responsibilities: [
      'Talent Strategy',
      'Workforce Planning',
      'Employee Experience',
      'Culture Development',
      'Learning & Development',
      'Performance Management',
    ],
    capabilities: [
      'Talent Acquisition',
      'Workforce Planning',
      'Employee Development',
      'Culture Building',
      'Performance Management',
      'HR Analytics',
    ],
    keyMetrics: [
      'Employee Satisfaction',
      'Retention Rate',
      'Time to Hire',
      'Training Effectiveness',
      'Performance Rating',
    ],
    humanCostEquivalent: '$260,000/year',
    aiCost: '$13,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-talent', 'vp-hr-ops', 'vp-learning', 'vp-culture', 'vp-compensation'],
    peerPositions: ['cdao', 'cao-automation', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cfo', 'cto', 'cmo', 'cco', 'coo', 'clo', 'ciso'],
    a2aEndpoints: ['/consult/chro', '/talent/strategy', '/culture/build'],
    route: '/ai-agent/executive/chro',
    apiEndpoint: '/api/agents/executive/chro',
    status: 'active',
    isPremium: true,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 25000,
  },
  // 8. CLO
  {
    id: 'clo',
    uid: 'ktx-08-chief-legal-officer',
    name: 'AI Chief Legal Officer',
    title: 'CLO - Chief Legal Officer',
    level: 'c_level',
    department: 'legal_compliance',
    description: 'Oversees all legal matters, compliance, risk management, and governance.',
    icon: Scale,
    color: '#3F51B5',
    responsibilities: [
      'Legal Strategy',
      'Compliance Oversight',
      'Contract Management',
      'Risk Mitigation',
      'Governance',
      'Regulatory Affairs',
    ],
    capabilities: [
      'Legal Counsel',
      'Compliance Management',
      'Contract Review',
      'Risk Assessment',
      'Governance',
      'Policy Development',
    ],
    keyMetrics: [
      'Compliance Score',
      'Contract Turnaround',
      'Legal Risk Score',
      'Regulatory Violations',
      'Policy Adherence',
    ],
    humanCostEquivalent: '$380,000/year',
    aiCost: '$19,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-legal', 'vp-compliance', 'vp-contracts', 'vp-ip', 'vp-governance'],
    peerPositions: ['cdao', 'cao-automation', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'ciso'],
    a2aEndpoints: ['/consult/clo', '/legal/counsel', '/compliance/oversight'],
    route: '/ai-agent/executive/clo',
    apiEndpoint: '/api/agents/executive/clo',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 28000,
  },
  // 9. CISO
  {
    id: 'ciso',
    uid: 'ktx-11-chief-information-security-officer',
    name: 'AI Chief Information Security Officer',
    title: 'CISO - Chief Information Security Officer',
    level: 'c_level',
    department: 'security',
    description: 'Leads cybersecurity strategy, information security programs, and risk management.',
    icon: Shield,
    color: '#F44336',
    responsibilities: [
      'Security Strategy',
      'Cybersecurity Leadership',
      'Risk Management',
      'Privacy Protection',
      'Incident Response',
      'Threat Intelligence',
    ],
    capabilities: [
      'Security Strategy',
      'Cybersecurity Operations',
      'Risk Management',
      'Privacy Protection',
      'Incident Response',
      'Security Architecture',
    ],
    keyMetrics: [
      'Security Posture Score',
      'Incident Response Time',
      'Vulnerability Count',
      'Security Training Completion',
      'Compliance Score',
    ],
    humanCostEquivalent: '$360,000/year',
    aiCost: '$18,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-security-ops', 'vp-cyber', 'vp-governance-risk', 'vp-privacy', 'security-architect'],
    peerPositions: ['cdao', 'cao-automation', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo'],
    a2aEndpoints: ['/consult/ciso', '/security/strategy', '/cyber/lead'],
    route: '/ai-agent/executive/ciso',
    apiEndpoint: '/api/agents/executive/ciso',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 35000,
  },
  // 10. CDAO (NEW)
  {
    id: 'cdao',
    uid: 'ktx-09-chief-data-analytics-officer',
    name: 'AI Chief Data & AI Officer',
    title: 'CDAO - Chief Data & AI Officer (NEW)',
    level: 'c_level',
    department: 'data_intelligence',
    description: 'Owns all AI and data strategy, governance, and model management. Bridges data science with business outcomes.',
    icon: Brain,
    color: '#8B5CF6',
    responsibilities: [
      'AI Strategy & Governance',
      'Data Management & Quality',
      'Model Management',
      'ML/AI Roadmap',
      'Data Privacy & Compliance',
      'AI Ethics Oversight',
    ],
    capabilities: [
      'AI Strategy Development',
      'Data Governance',
      'Machine Learning Oversight',
      'Model Lifecycle Management',
      'Predictive Modeling',
      'AI Ethics Enforcement',
    ],
    keyMetrics: [
      'Model Accuracy',
      'Data Quality Score',
      'AI ROI',
      'Prediction Accuracy',
      'Data Privacy Compliance',
    ],
    humanCostEquivalent: '$380,000/year',
    aiCost: '$19,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-data-science', 'vp-ai-ml', 'vp-data-engineering', 'ai-ethics-lead'],
    peerPositions: ['cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cao-automation'],
    a2aEndpoints: ['/consult/cdao', '/ai/strategy', '/data/governance'],
    route: '/ai-agent/executive/cdao',
    apiEndpoint: '/api/agents/executive/cdao',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['predictive-engine', 'sentiment-core', 'anomaly-detector'],
    tokenBudget: 40000,
  },
  // 11. CAO-Automation (NEW)
  {
    id: 'cao-automation',
    uid: 'ktx-04-chief-automation-officer',
    name: 'AI Chief Automation Officer',
    title: 'CAO - Chief Automation Officer (NEW)',
    level: 'c_level',
    department: 'operations',
    description: 'RPA, workflow automation, and efficiency specialist. Drives autonomous operations.',
    icon: Zap,
    color: '#F59E0B',
    responsibilities: [
      'Automation Strategy',
      'RPA Implementation',
      'Workflow Optimization',
      'Process Automation',
      'Efficiency Improvement',
      'Autonomous Operations',
    ],
    capabilities: [
      'RPA Strategy & Implementation',
      'Workflow Design',
      'Process Mining',
      'Automation Architecture',
      'Efficiency Analysis',
      'Autonomous System Design',
    ],
    keyMetrics: [
      'Process Automation Rate',
      'Efficiency Gain',
      'Cost Savings',
      'RPA ROI',
      'Autonomous Operation Rate',
    ],
    humanCostEquivalent: '$320,000/year',
    aiCost: '$16,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-automation', 'vp-process-excellence', 'aod-lead', 'rpa-manager'],
    peerPositions: ['cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cdao'],
    a2aEndpoints: ['/consult/cao-automation', '/automation/strategy', '/rpa/oversight'],
    route: '/ai-agent/executive/cao-automation',
    apiEndpoint: '/api/agents/executive/cao-automation',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 25000,
  },
  // 12. CIO (Chief Investment Officer)
  {
    id: 'cio',
    uid: 'ktx-06-chief-information-officer',
    name: 'AI Chief Investment Officer',
    title: 'CIO - Chief Investment Officer',
    level: 'c_level',
    department: 'trading_investments',
    description: 'Oversees all investment strategy, portfolio management, and trading operations.',
    icon: TrendingUp,
    color: '#10B981',
    responsibilities: [
      'Investment Strategy & Vision',
      'Portfolio Management Oversight',
      'Asset Allocation Decisions',
      'Risk Management Framework',
      'Trading Desk Operations',
      'Multi-Asset Class Oversight',
    ],
    capabilities: [
      'Multi-Asset Portfolio Optimization',
      'Risk-Adjusted Return Analysis',
      'Macro-Economic Forecasting',
      'Quantitative Modeling Oversight',
      'Derivatives Strategy',
      'Global Market Analysis',
    ],
    keyMetrics: [
      'Portfolio ROI',
      'Sharpe Ratio',
      'Maximum Drawdown',
      'Alpha Generation',
      'Risk-Adjusted Returns',
    ],
    humanCostEquivalent: '$450,000/year',
    aiCost: '$22,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-trading', 'vp-investments', 'vp-underwriting', 'vp-claims', 'vp-risk-assessment'],
    peerPositions: ['cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cdao', 'cao-automation'],
    a2aEndpoints: ['/consult/cio', '/investment/strategy', '/portfolio/optimize'],
    route: '/ai-agent/executive/cio',
    apiEndpoint: '/api/agents/executive/cio',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning'],
    intelligenceAccess: ['predictive-engine', 'anomaly-detector'],
    tokenBudget: 40000,
  },
  // 13. CREO (Chief Real Estate Officer)
  {
    id: 'creo',
    uid: 'ktx-12-chief-research-officer',
    name: 'AI Chief Real Estate Officer',
    title: 'CREO - Chief Real Estate Officer',
    level: 'c_level',
    department: 'real_estate_property',
    description: 'Oversees all real estate operations, property portfolio management, and strategic real estate investments.',
    icon: Building2,
    color: '#8B5CF6',
    responsibilities: [
      'Real Estate Strategy',
      'Portfolio Management',
      'Property Investment',
      'Asset Optimization',
      'Leasing Strategy',
      'Property Development',
    ],
    capabilities: [
      'Real Estate Strategy',
      'Portfolio Analysis',
      'Investment Evaluation',
      'Asset Management',
      'Market Analysis',
      'Property Valuation',
    ],
    keyMetrics: [
      'Portfolio Value',
      'Occupancy Rate',
      'NOI',
      'Cap Rate',
      'Tenant Retention',
    ],
    humanCostEquivalent: '$320,000/year',
    aiCost: '$16,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-property-management', 'vp-real-estate-development'],
    peerPositions: ['cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso', 'cio', 'cro', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cdao', 'cao-automation'],
    a2aEndpoints: ['/consult/creo', '/realestate/strategy', '/portfolio/manage'],
    route: '/ai-agent/executive/creo',
    apiEndpoint: '/api/agents/executive/creo',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 28000,
  },
  // 14. CRO (Chief Risk Officer)
  {
    id: 'cro',
    uid: 'ktx-02-chief-revenue-officer',
    name: 'AI Chief Risk Officer',
    title: 'CRO - Chief Risk Officer',
    level: 'c_level',
    department: 'insurance_risk',
    description: 'Oversees enterprise risk management, insurance operations, underwriting strategy, and claims management.',
    icon: Shield,
    color: '#F59E0B',
    responsibilities: [
      'Enterprise Risk Management',
      'Insurance Strategy',
      'Underwriting Oversight',
      'Claims Management',
      'Risk Assessment Framework',
      'Regulatory Compliance',
    ],
    capabilities: [
      'Risk Management',
      'Insurance Operations',
      'Underwriting Strategy',
      'Claims Analysis',
      'Risk Modeling',
      'Fraud Detection',
    ],
    keyMetrics: [
      'Risk Score',
      'Loss Ratio',
      'Combined Ratio',
      'Fraud Detection Rate',
      'Compliance Score',
    ],
    humanCostEquivalent: '$380,000/year',
    aiCost: '$19,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-underwriting', 'vp-claims', 'vp-risk-assessment'],
    peerPositions: ['cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso', 'cio', 'creo', 'cmo-healthcare', 'cpo', 'clo-logistics', 'cao-admin', 'cdao', 'cao-automation'],
    a2aEndpoints: ['/consult/cro', '/risk/manage', '/insurance/oversight'],
    route: '/ai-agent/executive/cro',
    apiEndpoint: '/api/agents/executive/cro',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['predictive-engine', 'anomaly-detector'],
    tokenBudget: 35000,
  },
  // 15. CMO-Healthcare (Chief Medical Officer)
  {
    id: 'cmo-healthcare',
    uid: 'ktx-17-chief-medical-officer',
    name: 'AI Chief Medical Officer',
    title: 'CMO - Chief Medical Officer',
    level: 'c_level',
    department: 'healthcare_medical',
    description: 'Oversees healthcare operations, patient care coordination, medical billing, and clinical support.',
    icon: Heart,
    color: '#EF4444',
    responsibilities: [
      'Healthcare Strategy',
      'Patient Care Oversight',
      'Medical Operations',
      'Patient Experience',
      'Healthcare Compliance',
      'Billing & Coding',
    ],
    capabilities: [
      'Healthcare Management',
      'Patient Care Coordination',
      'Medical Billing',
      'Healthcare Analytics',
      'Compliance Management',
      'Telehealth Operations',
    ],
    keyMetrics: [
      'Patient Satisfaction',
      'Treatment Success Rate',
      'Compliance Score',
      'Billing Accuracy',
      'Wait Time',
    ],
    humanCostEquivalent: '$400,000/year',
    aiCost: '$20,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-healthcare-operations', 'vp-patient-experience'],
    peerPositions: ['cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso', 'cio', 'creo', 'cro', 'cpo', 'clo-logistics', 'cao-admin', 'cdao', 'cao-automation'],
    a2aEndpoints: ['/consult/cmo-healthcare', '/healthcare/operations', '/patient/care'],
    route: '/ai-agent/executive/cmo-healthcare',
    apiEndpoint: '/api/agents/executive/cmo-healthcare',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 32000,
  },
  // 16. CPO (Chief Production Officer)
  {
    id: 'cpo',
    uid: 'ktx-10-chief-product-officer',
    name: 'AI Chief Production Officer',
    title: 'CPO - Chief Production Officer',
    level: 'c_level',
    department: 'manufacturing_production',
    description: 'Oversees manufacturing operations, production planning, quality control, and supply chain management.',
    icon: Factory,
    color: '#6366F1',
    responsibilities: [
      'Manufacturing Strategy',
      'Production Planning',
      'Quality Assurance',
      'Supply Chain Oversight',
      'Operational Efficiency',
      'Safety Management',
    ],
    capabilities: [
      'Manufacturing Operations',
      'Production Planning',
      'Quality Control',
      'Supply Chain Management',
      'Lean Manufacturing',
      'Equipment Optimization',
    ],
    keyMetrics: [
      'Production Output',
      'Quality Score',
      'OEE',
      'Safety Incidents',
      'On-time Delivery',
    ],
    humanCostEquivalent: '$340,000/year',
    aiCost: '$17,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-manufacturing', 'vp-quality-assurance'],
    peerPositions: ['cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso', 'cio', 'creo', 'cro', 'cmo-healthcare', 'clo-logistics', 'cao-admin', 'cdao', 'cao-automation'],
    a2aEndpoints: ['/consult/cpo', '/production/strategy', '/manufacturing/oversight'],
    route: '/ai-agent/executive/cpo',
    apiEndpoint: '/api/agents/executive/cpo',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 30000,
  },
  // 17. CLO-Logistics (Chief Logistics Officer)
  {
    id: 'clo-logistics',
    uid: 'ktx-19-chief-logistics-officer',
    name: 'AI Chief Logistics Officer',
    title: 'CLO - Chief Logistics Officer',
    level: 'c_level',
    department: 'transportation_logistics',
    description: 'Oversees transportation operations, logistics management, fleet operations, and supply chain logistics.',
    icon: Truck,
    color: '#0EA5E9',
    responsibilities: [
      'Logistics Strategy',
      'Transportation Management',
      'Fleet Operations',
      'Route Optimization',
      'Warehouse Management',
      'Delivery Operations',
    ],
    capabilities: [
      'Logistics Management',
      'Transportation Optimization',
      'Fleet Management',
      'Route Planning',
      'Warehouse Operations',
      'Carrier Management',
    ],
    keyMetrics: [
      'On-time Delivery',
      'Cost Per Mile',
      'Fleet Utilization',
      'Route Efficiency',
      'Warehouse Accuracy',
    ],
    humanCostEquivalent: '$300,000/year',
    aiCost: '$15,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ceo',
    directReports: ['vp-supply-chain', 'vp-fleet-management'],
    peerPositions: ['cfo', 'cto', 'cmo', 'cco', 'coo', 'chro', 'clo', 'ciso', 'cio', 'creo', 'cro', 'cmo-healthcare', 'cpo', 'cao-admin', 'cdao', 'cao-automation'],
    a2aEndpoints: ['/consult/clo-logistics', '/logistics/strategy', '/transportation/manage'],
    route: '/ai-agent/executive/clo-logistics',
    apiEndpoint: '/api/agents/executive/clo-logistics',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['predictive-engine'],
    tokenBudget: 28000,
  },
];

// ============================================
// LEVEL 2: VPs & DIRECTORS (23 Agents)
// ============================================

export const vpDirectors: AIEmployeeProfile[] = [
  // Finance Department
  {
    id: 'vp-finance',
    uid: 'ktx-05-vp-finance',
    name: 'AI VP of Finance',
    title: 'VP Finance',
    level: 'department',
    department: 'finance',
    description: 'Oversees financial planning, analysis, and reporting.',
    icon: DollarSign,
    color: '#2E7D32',
    responsibilities: ['Financial Planning', 'Budget Analysis', 'Financial Reporting', 'Forecasting'],
    capabilities: ['Financial Modeling', 'Variance Analysis', 'Dashboard Creation', 'Risk Assessment'],
    keyMetrics: ['Budget Variance', 'Forecast Accuracy', 'Reporting Timeliness'],
    humanCostEquivalent: '$180,000/year',
    aiCost: '$9,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'cfo',
    directReports: ['finance-manager-1', 'finance-manager-2'],
    peerPositions: ['vp-accounting', 'vp-treasury'],
    a2aEndpoints: ['/consult/vp-finance', '/finance/planning'],
    route: '/ai-agent/vp/finance',
    apiEndpoint: '/api/agents/vp/finance',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 15000,
  },
  {
    id: 'vp-accounting',
    uid: 'ktx-05-vp-accounting',
    name: 'AI VP of Accounting',
    title: 'VP Accounting',
    level: 'department',
    department: 'finance',
    description: 'Manages accounting operations, bookkeeping, and financial controls.',
    icon: DollarSign,
    color: '#388E3C',
    responsibilities: ['Accounting Operations', 'Bookkeeping', 'Financial Controls', 'Audit Support'],
    capabilities: ['GL Management', 'Reconciliation', 'Journal Entries', 'Audit Preparation'],
    keyMetrics: ['Close Time', 'Accuracy Rate', 'Audit Findings'],
    humanCostEquivalent: '$170,000/year',
    aiCost: '$8,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'cfo',
    directReports: ['accounting-manager-1', 'accounting-manager-2'],
    peerPositions: ['vp-finance', 'vp-treasury'],
    a2aEndpoints: ['/consult/vp-accounting', '/accounting/operations'],
    route: '/ai-agent/vp/accounting',
    apiEndpoint: '/api/agents/vp/accounting',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 14000,
  },
  // Technology Department
  {
    id: 'vp-engineering',
    uid: 'ktx-06-vp-engineering',
    name: 'AI VP of Engineering',
    title: 'VP Engineering',
    level: 'department',
    department: 'technology',
    description: 'Leads software engineering, development teams, and technical delivery.',
    icon: Cpu,
    color: '#1565C0',
    responsibilities: ['Engineering Leadership', 'Development Oversight', 'Technical Quality', 'Team Management'],
    capabilities: ['Code Review', 'Architecture Guidance', 'Sprint Planning', 'Technical Hiring'],
    keyMetrics: ['Velocity', 'Bug Rate', 'Deployment Frequency', 'Code Quality'],
    humanCostEquivalent: '$200,000/year',
    aiCost: '$10,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'cto',
    directReports: ['engineering-manager-1', 'engineering-manager-2', 'engineering-manager-3'],
    peerPositions: ['vp-infrastructure', 'vp-ai-ml'],
    a2aEndpoints: ['/consult/vp-engineering', '/engineering/leadership'],
    route: '/ai-agent/vp/engineering',
    apiEndpoint: '/api/agents/vp/engineering',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 18000,
  },
  {
    id: 'vp-infrastructure',
    uid: 'ktx-06-vp-infrastructure',
    name: 'AI VP of Infrastructure',
    title: 'VP Infrastructure',
    level: 'department',
    department: 'technology',
    description: 'Manages cloud infrastructure, DevOps, and platform reliability.',
    icon: Cpu,
    color: '#1976D2',
    responsibilities: ['Infrastructure Management', 'Cloud Operations', 'DevOps', 'SRE'],
    capabilities: ['Cloud Architecture', 'Automation', 'Monitoring', 'Incident Response'],
    keyMetrics: ['Uptime', 'MTTR', 'Cost Efficiency', 'Automation Coverage'],
    humanCostEquivalent: '$190,000/year',
    aiCost: '$9,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'cto',
    directReports: ['infrastructure-manager-1', 'infrastructure-manager-2'],
    peerPositions: ['vp-engineering', 'vp-ai-ml'],
    a2aEndpoints: ['/consult/vp-infrastructure', '/infrastructure/operations'],
    route: '/ai-agent/vp/infrastructure',
    apiEndpoint: '/api/agents/vp/infrastructure',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 17000,
  },
  // Marketing Department
  {
    id: 'vp-marketing',
    uid: 'ktx-03-vp-marketing',
    name: 'AI VP of Marketing',
    title: 'VP Marketing',
    level: 'department',
    department: 'marketing',
    description: 'Leads marketing strategy, campaigns, and brand initiatives.',
    icon: Megaphone,
    color: '#E91E63',
    responsibilities: ['Marketing Strategy', 'Campaign Management', 'Brand Building', 'Lead Generation'],
    capabilities: ['Campaign Planning', 'Content Strategy', 'Analytics', 'Market Research'],
    keyMetrics: ['Campaign ROI', 'Lead Quality', 'Brand Awareness', 'CAC'],
    humanCostEquivalent: '$170,000/year',
    aiCost: '$8,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'cmo',
    directReports: ['marketing-manager-1', 'marketing-manager-2'],
    peerPositions: ['vp-brand', 'vp-growth', 'vp-content', 'vp-digital'],
    a2aEndpoints: ['/consult/vp-marketing', '/marketing/strategy'],
    route: '/ai-agent/vp/marketing',
    apiEndpoint: '/api/agents/vp/marketing',
    status: 'active',
    isPremium: true,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    intelligenceAccess: ['predictive-engine', 'sentiment-core'],
    tokenBudget: 15000,
  },
  {
    id: 'vp-brand',
    uid: 'ktx-03-vp-brand',
    name: 'AI VP of Brand',
    title: 'VP Brand',
    level: 'department',
    department: 'marketing',
    description: 'Manages brand identity, positioning, and brand communications.',
    icon: Megaphone,
    color: '#F06292',
    responsibilities: ['Brand Strategy', 'Brand Identity', 'Brand Communications', 'Brand Guidelines'],
    capabilities: ['Brand Management', 'Visual Identity', 'Messaging', 'Brand Analytics'],
    keyMetrics: ['Brand Awareness', 'Brand Sentiment', 'Brand Consistency'],
    humanCostEquivalent: '$160,000/year',
    aiCost: '$8,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'cmo',
    directReports: ['brand-manager-1'],
    peerPositions: ['vp-marketing', 'vp-growth', 'vp-content', 'vp-digital'],
    a2aEndpoints: ['/consult/vp-brand', '/brand/management'],
    route: '/ai-agent/vp/brand',
    apiEndpoint: '/api/agents/vp/brand',
    status: 'active',
    isPremium: true,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 13000,
  },
  // Sales Department
  {
    id: 'vp-sales',
    uid: 'ktx-02-vp-sales',
    name: 'AI VP of Sales',
    title: 'VP Sales',
    level: 'department',
    department: 'sales',
    description: 'Leads sales operations, team management, and revenue achievement.',
    icon: TrendingUp,
    color: '#FF9800',
    responsibilities: ['Sales Strategy', 'Team Management', 'Revenue Growth', 'Pipeline Management'],
    capabilities: ['Sales Forecasting', 'Pipeline Analysis', 'Territory Planning', 'Performance Coaching'],
    keyMetrics: ['Revenue', 'Quota Attainment', 'Win Rate', 'Deal Size'],
    humanCostEquivalent: '$200,000/year',
    aiCost: '$10,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'coo',
    directReports: ['sales-manager-1', 'sales-manager-2', 'sales-manager-3'],
    peerPositions: ['vp-sales-ops', 'vp-bdr'],
    a2aEndpoints: ['/consult/vp-sales', '/sales/leadership'],
    route: '/ai-agent/vp/sales',
    apiEndpoint: '/api/agents/vp/sales',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['predictive-engine', 'sentiment-core'],
    tokenBudget: 18000,
  },
  // Customer Experience Department
  {
    id: 'vp-customer-success',
    uid: 'ktx-01-vp-customer-success',
    name: 'AI VP of Customer Success',
    title: 'VP Customer Success',
    level: 'department',
    department: 'customer_experience',
    description: 'Manages customer success, retention, and expansion strategies.',
    icon: Headphones,
    color: '#00BCD4',
    responsibilities: ['Customer Success Strategy', 'Retention', 'Expansion', 'Health Scoring'],
    capabilities: ['Success Planning', 'Risk Identification', 'Expansion Selling', 'Health Analytics'],
    keyMetrics: ['NRR', 'Retention Rate', 'Health Score', 'Expansion Revenue'],
    humanCostEquivalent: '$180,000/year',
    aiCost: '$9,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'cco',
    directReports: ['cs-manager-1', 'cs-manager-2'],
    peerPositions: ['vp-support', 'vp-experience'],
    a2aEndpoints: ['/consult/vp-customer-success', '/success/management'],
    route: '/ai-agent/vp/customer-success',
    apiEndpoint: '/api/agents/vp/customer-success',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning'],
    intelligenceAccess: ['sentiment-core'],
    tokenBudget: 16000,
  },
  {
    id: 'vp-support',
    uid: 'ktx-01-vp-support',
    name: 'AI VP of Support',
    title: 'VP Support',
    level: 'department',
    department: 'customer_experience',
    description: 'Oversees customer support operations and service delivery.',
    icon: Headphones,
    color: '#00ACC1',
    responsibilities: ['Support Operations', 'Ticket Management', 'Knowledge Base', 'Quality Assurance'],
    capabilities: ['Queue Management', 'Ticket Routing', 'Knowledge Management', 'Quality Monitoring'],
    keyMetrics: ['CSAT', 'First Response Time', 'Resolution Time', 'Ticket Volume'],
    humanCostEquivalent: '$160,000/year',
    aiCost: '$8,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'cco',
    directReports: ['support-manager-1', 'support-manager-2'],
    peerPositions: ['vp-customer-success', 'vp-experience'],
    a2aEndpoints: ['/consult/vp-support', '/support/operations'],
    route: '/ai-agent/vp/support',
    apiEndpoint: '/api/agents/vp/support',
    status: 'active',
    isPremium: true,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['sentiment-core'],
    tokenBudget: 14000,
  },
  // Operations Department
  {
    id: 'vp-operations',
    uid: 'ktx-04-vp-operations',
    name: 'AI VP of Operations',
    title: 'VP Operations',
    level: 'department',
    department: 'operations',
    description: 'Manages business operations, process improvement, and efficiency.',
    icon: Settings,
    color: '#607D8B',
    responsibilities: ['Operations Management', 'Process Improvement', 'Resource Planning', 'Vendor Management'],
    capabilities: ['Process Analysis', 'Workflow Optimization', 'Resource Allocation', 'Vendor Evaluation'],
    keyMetrics: ['Efficiency', 'Cost Per Transaction', 'Cycle Time', 'Quality Score'],
    humanCostEquivalent: '$170,000/year',
    aiCost: '$8,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'coo',
    directReports: ['ops-manager-1', 'ops-manager-2'],
    peerPositions: ['vp-supply-chain', 'vp-quality'],
    a2aEndpoints: ['/consult/vp-operations', '/operations/management'],
    route: '/ai-agent/vp/operations',
    apiEndpoint: '/api/agents/vp/operations',
    status: 'active',
    isPremium: true,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 15000,
  },
  // HR Department
  {
    id: 'vp-talent',
    uid: 'ktx-07-vp-talent',
    name: 'AI VP of Talent',
    title: 'VP Talent',
    level: 'department',
    department: 'human_resources',
    description: 'Leads talent acquisition, recruitment, and employer branding.',
    icon: Users,
    color: '#9C27B0',
    responsibilities: ['Talent Acquisition', 'Recruitment Strategy', 'Employer Branding', 'Onboarding'],
    capabilities: ['Sourcing', 'Interviewing', 'Assessment', 'Offer Management'],
    keyMetrics: ['Time to Fill', 'Quality of Hire', 'Offer Acceptance', 'Cost Per Hire'],
    humanCostEquivalent: '$160,000/year',
    aiCost: '$8,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'chro',
    directReports: ['talent-manager-1', 'talent-manager-2'],
    peerPositions: ['vp-hr-ops', 'vp-learning'],
    a2aEndpoints: ['/consult/vp-talent', '/talent/acquisition'],
    route: '/ai-agent/vp/talent',
    apiEndpoint: '/api/agents/vp/talent',
    status: 'active',
    isPremium: true,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 13000,
  },
  {
    id: 'vp-hr-ops',
    uid: 'ktx-07-vp-hr-operations',
    name: 'AI VP of HR Operations',
    title: 'VP HR Operations',
    level: 'department',
    department: 'human_resources',
    description: 'Manages HR operations, systems, and employee services.',
    icon: Users,
    color: '#AB47BC',
    responsibilities: ['HR Operations', 'HR Systems', 'Employee Services', 'Compliance'],
    capabilities: ['HR Administration', 'System Management', 'Policy Implementation', 'Data Management'],
    keyMetrics: ['Process Efficiency', 'System Uptime', 'Data Accuracy', 'Compliance Rate'],
    humanCostEquivalent: '$150,000/year',
    aiCost: '$7,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'chro',
    directReports: ['hr-ops-manager-1'],
    peerPositions: ['vp-talent', 'vp-learning'],
    a2aEndpoints: ['/consult/vp-hr-ops', '/hr/operations'],
    route: '/ai-agent/vp/hr-ops',
    apiEndpoint: '/api/agents/vp/hr-ops',
    status: 'active',
    isPremium: true,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 12000,
  },
  // Legal Department
  {
    id: 'vp-legal',
    uid: 'ktx-08-vp-legal',
    name: 'AI VP of Legal',
    title: 'VP Legal',
    level: 'department',
    department: 'legal_compliance',
    description: 'Manages legal operations, contracts, and corporate governance.',
    icon: Scale,
    color: '#3F51B5',
    responsibilities: ['Legal Operations', 'Contract Management', 'Corporate Governance', 'Risk Management'],
    capabilities: ['Contract Review', 'Legal Research', 'Compliance Monitoring', 'Dispute Resolution'],
    keyMetrics: ['Contract Turnaround', 'Risk Mitigation', 'Compliance Score', 'Cost Savings'],
    humanCostEquivalent: '$220,000/year',
    aiCost: '$11,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'clo',
    directReports: ['legal-manager-1', 'contracts-manager-1'],
    peerPositions: ['vp-compliance', 'vp-contracts'],
    a2aEndpoints: ['/consult/vp-legal', '/legal/operations'],
    route: '/ai-agent/vp/legal',
    apiEndpoint: '/api/agents/vp/legal',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 16000,
  },
  // Security Department
  {
    id: 'vp-security-ops',
    uid: 'ktx-06-vp-security-technology',
    name: 'AI VP of Security Operations',
    title: 'VP Security Ops',
    level: 'department',
    department: 'security',
    description: 'Manages security operations, SOC, and incident response.',
    icon: Shield,
    color: '#F44336',
    responsibilities: ['Security Operations', 'SOC Management', 'Incident Response', 'Threat Detection'],
    capabilities: ['SIEM Management', 'Incident Handling', 'Threat Hunting', 'Forensics'],
    keyMetrics: ['MTTD', 'MTTR', 'False Positive Rate', 'Incident Count'],
    humanCostEquivalent: '$200,000/year',
    aiCost: '$10,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ciso',
    directReports: ['security-manager-1', 'soc-lead-1'],
    peerPositions: ['vp-cyber', 'vp-governance-risk'],
    a2aEndpoints: ['/consult/vp-security-ops', '/security/operations'],
    route: '/ai-agent/vp/security-ops',
    apiEndpoint: '/api/agents/vp/security-ops',
    status: 'active',
    isPremium: true,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 18000,
  },
  // Data Intelligence Department
  {
    id: 'vp-data-science',
    uid: 'ktx-09-vp-data-science',
    name: 'AI VP of Data Science',
    title: 'VP Data Science',
    level: 'department',
    department: 'data_intelligence',
    description: 'Leads data science, ML models, and predictive analytics.',
    icon: Brain,
    color: '#8B5CF6',
    responsibilities: ['Data Science Strategy', 'ML Development', 'Model Management', 'Analytics'],
    capabilities: ['Model Development', 'Feature Engineering', 'Experimentation', 'A/B Testing'],
    keyMetrics: ['Model Accuracy', 'Prediction Quality', 'Experiment Velocity', 'Data Quality'],
    humanCostEquivalent: '$220,000/year',
    aiCost: '$11,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'cdao',
    directReports: ['data-science-manager-1', 'data-science-manager-2'],
    peerPositions: ['vp-data-engineering', 'vp-ai-ml'],
    a2aEndpoints: ['/consult/vp-data-science', '/data-science/leadership'],
    route: '/ai-agent/vp/data-science',
    apiEndpoint: '/api/agents/vp/data-science',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['predictive-engine', 'anomaly-detector'],
    tokenBudget: 20000,
  },
  // Product Department
  {
    id: 'vp-product',
    uid: 'ktx-10-vp-product',
    name: 'AI VP of Product',
    title: 'VP Product',
    level: 'department',
    department: 'product',
    description: 'Leads product strategy, roadmap, and product management.',
    icon: Crown,
    color: '#7C3AED',
    responsibilities: ['Product Strategy', 'Roadmap Planning', 'Product Management', 'Launch Planning'],
    capabilities: ['Product Discovery', 'Prioritization', 'User Research', 'Metrics Analysis'],
    keyMetrics: ['Product Adoption', 'NPS', 'Feature Usage', 'Time to Market'],
    humanCostEquivalent: '$190,000/year',
    aiCost: '$9,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'cto',
    directReports: ['product-manager-1', 'product-manager-2', 'product-manager-3'],
    peerPositions: ['vp-ux', 'vp-product-marketing'],
    a2aEndpoints: ['/consult/vp-product', '/product/strategy'],
    route: '/ai-agent/vp/product',
    apiEndpoint: '/api/agents/vp/product',
    status: 'active',
    isPremium: true,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning'],
    intelligenceAccess: ['predictive-engine', 'sentiment-core'],
    tokenBudget: 17000,
  },
];

// ============================================
// LEVEL 3: MANAGERS (40 Agents - Sample)
// ============================================

export const managers: AIEmployeeProfile[] = [
  // Finance Managers
  {
    id: 'finance-manager-1',
    uid: 'ktx-05-finance-manager',
    name: 'AI Finance Planning Manager',
    title: 'Finance Planning Manager',
    level: 'department',
    department: 'finance',
    description: 'Manages financial planning, budgeting, and forecasting processes.',
    icon: DollarSign,
    color: '#2E7D32',
    responsibilities: ['Budget Planning', 'Forecasting', 'Variance Analysis', 'Financial Modeling'],
    capabilities: ['Excel Modeling', 'Financial Analysis', 'Reporting', 'Budget Tools'],
    keyMetrics: ['Forecast Accuracy', 'Budget Variance', 'Planning Cycle Time'],
    humanCostEquivalent: '$100,000/year',
    aiCost: '$5,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'vp-finance',
    directReports: ['finance-lead-1', 'finance-analyst-1', 'finance-analyst-2'],
    peerPositions: ['finance-manager-2'],
    a2aEndpoints: ['/consult/finance-manager', '/finance/planning'],
    route: '/ai-agent/manager/finance-planning',
    apiEndpoint: '/api/agents/manager/finance-planning',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 8000,
  },
  // Engineering Managers
  {
    id: 'engineering-manager-1',
    name: 'AI Frontend Engineering Manager',
    title: 'Frontend Engineering Manager',
    level: 'department',
    department: 'technology',
    description: 'Manages frontend development team and UI/UX implementation.',
    icon: Cpu,
    color: '#1565C0',
    responsibilities: ['Frontend Development', 'UI Implementation', 'Code Reviews', 'Team Management'],
    capabilities: ['React/Vue/Angular', 'CSS/SCSS', 'JavaScript/TypeScript', 'Performance Optimization'],
    keyMetrics: ['Velocity', 'Bug Rate', 'Performance Score', 'User Satisfaction'],
    humanCostEquivalent: '$130,000/year',
    aiCost: '$6,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'vp-engineering',
    directReports: ['frontend-lead-1', 'frontend-dev-1', 'frontend-dev-2', 'ui-designer-1'],
    peerPositions: ['engineering-manager-2', 'engineering-manager-3'],
    a2aEndpoints: ['/consult/eng-manager', '/frontend/leadership'],
    route: '/ai-agent/manager/frontend-eng',
    apiEndpoint: '/api/agents/manager/frontend-eng',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 10000,
  },
  {
    id: 'engineering-manager-2',
    name: 'AI Backend Engineering Manager',
    title: 'Backend Engineering Manager',
    level: 'department',
    department: 'technology',
    description: 'Manages backend services, APIs, and infrastructure code.',
    icon: Cpu,
    color: '#1976D2',
    responsibilities: ['Backend Development', 'API Design', 'Database Management', 'System Architecture'],
    capabilities: ['Node.js/Python/Go', 'Database Design', 'API Development', 'Microservices'],
    keyMetrics: ['API Response Time', 'System Uptime', 'Deployment Success', 'Code Coverage'],
    humanCostEquivalent: '$135,000/year',
    aiCost: '$6,750/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'vp-engineering',
    directReports: ['backend-lead-1', 'backend-dev-1', 'backend-dev-2', 'backend-dev-3'],
    peerPositions: ['engineering-manager-1', 'engineering-manager-3'],
    a2aEndpoints: ['/consult/eng-manager', '/backend/leadership'],
    route: '/ai-agent/manager/backend-eng',
    apiEndpoint: '/api/agents/manager/backend-eng',
    status: 'active',
    isPremium: false,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 11000,
  },
  // Marketing Managers
  {
    id: 'marketing-manager-1',
    uid: 'ktx-03-marketing-manager',
    name: 'AI Digital Marketing Manager',
    title: 'Digital Marketing Manager',
    level: 'department',
    department: 'marketing',
    description: 'Manages digital marketing campaigns, SEO, SEM, and social media.',
    icon: Megaphone,
    color: '#E91E63',
    responsibilities: ['Digital Campaigns', 'SEO/SEM', 'Social Media', 'Analytics'],
    capabilities: ['Google Ads', 'Facebook Ads', 'SEO Tools', 'Marketing Automation'],
    keyMetrics: ['ROAS', 'CPA', 'Organic Traffic', 'Social Engagement'],
    humanCostEquivalent: '$90,000/year',
    aiCost: '$4,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'vp-marketing',
    directReports: ['seo-specialist-1', 'sem-specialist-1', 'social-specialist-1'],
    peerPositions: ['marketing-manager-2'],
    a2aEndpoints: ['/consult/marketing-manager', '/digital/marketing'],
    route: '/ai-agent/manager/digital-marketing',
    apiEndpoint: '/api/agents/manager/digital-marketing',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    intelligenceAccess: ['predictive-engine'],
    tokenBudget: 7000,
  },
  // Sales Managers
  {
    id: 'sales-manager-1',
    uid: 'ktx-02-sales-operations-manager',
    name: 'AI Enterprise Sales Manager',
    title: 'Enterprise Sales Manager',
    level: 'department',
    department: 'sales',
    description: 'Manages enterprise sales team and large deal pursuits.',
    icon: TrendingUp,
    color: '#FF9800',
    responsibilities: ['Enterprise Sales', 'Deal Management', 'Team Coaching', 'Forecasting'],
    capabilities: ['Solution Selling', 'Negotiation', 'CRM Management', 'Sales Methodology'],
    keyMetrics: ['Revenue', 'Win Rate', 'Average Deal Size', 'Sales Cycle'],
    humanCostEquivalent: '$120,000/year',
    aiCost: '$6,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'vp-sales',
    directReports: ['enterprise-ae-1', 'enterprise-ae-2', 'sales-engineer-1'],
    peerPositions: ['sales-manager-2', 'sales-manager-3'],
    a2aEndpoints: ['/consult/sales-manager', '/enterprise/sales'],
    route: '/ai-agent/manager/enterprise-sales',
    apiEndpoint: '/api/agents/manager/enterprise-sales',
    status: 'active',
    isPremium: false,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning'],
    intelligenceAccess: ['predictive-engine', 'sentiment-core'],
    tokenBudget: 9000,
  },
  // Support Managers
  {
    id: 'support-manager-1',
    name: 'AI Technical Support Manager',
    title: 'Technical Support Manager',
    level: 'department',
    department: 'customer_experience',
    description: 'Manages technical support team and complex issue resolution.',
    icon: Headphones,
    color: '#00BCD4',
    responsibilities: ['Technical Support', 'Ticket Management', 'Knowledge Base', 'Quality Assurance'],
    capabilities: ['Technical Troubleshooting', 'Product Knowledge', 'Ticket Systems', 'Customer Communication'],
    keyMetrics: ['CSAT', 'First Contact Resolution', 'Average Handle Time', 'Escalation Rate'],
    humanCostEquivalent: '$85,000/year',
    aiCost: '$4,250/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'vp-support',
    directReports: ['support-lead-1', 'tech-support-1', 'tech-support-2', 'tech-support-3'],
    peerPositions: ['support-manager-2'],
    a2aEndpoints: ['/consult/support-manager', '/technical/support'],
    route: '/ai-agent/manager/tech-support',
    apiEndpoint: '/api/agents/manager/tech-support',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['sentiment-core'],
    tokenBudget: 6500,
  },
  // Operations Managers
  {
    id: 'ops-manager-1',
    uid: 'ktx-06-devops-manager',
    name: 'AI Business Operations Manager',
    title: 'Business Operations Manager',
    level: 'department',
    department: 'operations',
    description: 'Manages day-to-day business operations and process optimization.',
    icon: Settings,
    color: '#607D8B',
    responsibilities: ['Operations Management', 'Process Improvement', 'Vendor Relations', 'Cost Management'],
    capabilities: ['Process Mapping', 'Lean Six Sigma', 'Vendor Management', 'Data Analysis'],
    keyMetrics: ['Process Efficiency', 'Cost Savings', 'Vendor Performance', 'SLA Compliance'],
    humanCostEquivalent: '$95,000/year',
    aiCost: '$4,750/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'vp-operations',
    directReports: ['ops-lead-1', 'ops-analyst-1', 'ops-analyst-2'],
    peerPositions: ['ops-manager-2'],
    a2aEndpoints: ['/consult/ops-manager', '/business/operations'],
    route: '/ai-agent/manager/business-ops',
    apiEndpoint: '/api/agents/manager/business-ops',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 7500,
  },
  // HR Managers
  {
    id: 'talent-manager-1',
    name: 'AI Talent Acquisition Manager',
    title: 'Talent Acquisition Manager',
    level: 'department',
    department: 'human_resources',
    description: 'Manages recruitment processes and candidate pipeline.',
    icon: Users,
    color: '#9C27B0',
    responsibilities: ['Recruitment', 'Candidate Sourcing', 'Interview Coordination', 'Offer Management'],
    capabilities: ['Sourcing Tools', 'ATS Management', 'Interviewing', 'Employer Branding'],
    keyMetrics: ['Time to Fill', 'Quality of Hire', 'Candidate Experience', 'Cost Per Hire'],
    humanCostEquivalent: '$80,000/year',
    aiCost: '$4,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'vp-talent',
    directReports: ['recruiter-1', 'recruiter-2', 'sourcer-1'],
    peerPositions: ['talent-manager-2'],
    a2aEndpoints: ['/consult/talent-manager', '/talent/acquisition'],
    route: '/ai-agent/manager/talent-acquisition',
    apiEndpoint: '/api/agents/manager/talent-acquisition',
    status: 'active',
    isPremium: false,
    dangerLevel: 'low',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 6000,
  },
  // Security Managers
  {
    id: 'security-manager-1',
    name: 'AI Security Engineering Manager',
    title: 'Security Engineering Manager',
    level: 'department',
    department: 'security',
    description: 'Manages security tools, automation, and security engineering.',
    icon: Shield,
    color: '#F44336',
    responsibilities: ['Security Engineering', 'Tool Management', 'Automation', 'Vulnerability Management'],
    capabilities: ['Security Tools', 'Scripting', 'Vulnerability Scanning', 'Threat Intelligence'],
    keyMetrics: ['Vulnerability Remediation Time', 'Tool Coverage', 'Automation Rate', 'False Positive Rate'],
    humanCostEquivalent: '$140,000/year',
    aiCost: '$7,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'vp-security-ops',
    directReports: ['security-engineer-1', 'security-engineer-2', 'security-analyst-1'],
    peerPositions: ['soc-lead-1'],
    a2aEndpoints: ['/consult/security-manager', '/security/engineering'],
    route: '/ai-agent/manager/security-eng',
    apiEndpoint: '/api/agents/manager/security-eng',
    status: 'active',
    isPremium: false,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 11000,
  },
  // Product Managers
  {
    id: 'product-manager-1',
    uid: 'ktx-10-product-manager',
    name: 'AI Core Product Manager',
    title: 'Core Product Manager',
    level: 'department',
    department: 'product',
    description: 'Manages core product features, roadmap, and user experience.',
    icon: Crown,
    color: '#7C3AED',
    responsibilities: ['Product Management', 'Feature Prioritization', 'User Research', 'Stakeholder Management'],
    capabilities: ['Product Analytics', 'User Interviews', 'A/B Testing', 'Agile/Scrum'],
    keyMetrics: ['Feature Adoption', 'User Engagement', 'NPS', 'Release Velocity'],
    humanCostEquivalent: '$115,000/year',
    aiCost: '$5,750/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'vp-product',
    directReports: ['product-owner-1', 'product-analyst-1', 'ux-designer-1'],
    peerPositions: ['product-manager-2', 'product-manager-3'],
    a2aEndpoints: ['/consult/product-manager', '/core/product'],
    route: '/ai-agent/manager/core-product',
    apiEndpoint: '/api/agents/manager/core-product',
    status: 'active',
    isPremium: false,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning'],
    intelligenceAccess: ['predictive-engine', 'sentiment-core'],
    tokenBudget: 8500,
  },
];

// ============================================
// LEVEL 4: TEAM LEADS (43 Agents - Sample)
// ============================================

export const teamLeads: AIEmployeeProfile[] = [
  {
    id: 'frontend-lead-1',
    uid: 'ktx-06-frontend-lead',
    name: 'AI Frontend Team Lead',
    title: 'Frontend Lead',
    level: 'agent',
    department: 'technology',
    description: 'Leads frontend development squad and code quality.',
    icon: Cpu,
    color: '#1565C0',
    responsibilities: ['Frontend Development', 'Code Reviews', 'Mentoring', 'Sprint Planning'],
    capabilities: ['React/Vue', 'TypeScript', 'CSS', 'Testing'],
    keyMetrics: ['Code Quality', 'Sprint Velocity', 'Bug Rate', 'Team Satisfaction'],
    humanCostEquivalent: '$80,000/year',
    aiCost: '$4,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'engineering-manager-1',
    directReports: ['frontend-dev-1', 'frontend-dev-2', 'ui-designer-1'],
    peerPositions: ['backend-lead-1'],
    a2aEndpoints: ['/consult/frontend-lead', '/frontend/team'],
    route: '/ai-agent/lead/frontend',
    apiEndpoint: '/api/agents/lead/frontend',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 6000,
  },
  {
    id: 'backend-lead-1',
    uid: 'ktx-06-backend-lead',
    name: 'AI Backend Team Lead',
    title: 'Backend Lead',
    level: 'agent',
    department: 'technology',
    description: 'Leads backend services team and API development.',
    icon: Cpu,
    color: '#1976D2',
    responsibilities: ['Backend Development', 'API Design', 'Database Management', 'Team Leadership'],
    capabilities: ['Node.js/Python', 'Database Design', 'API Development', 'System Design'],
    keyMetrics: ['API Performance', 'Code Coverage', 'Deployment Success', 'Team Velocity'],
    humanCostEquivalent: '$85,000/year',
    aiCost: '$4,250/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'engineering-manager-2',
    directReports: ['backend-dev-1', 'backend-dev-2', 'backend-dev-3'],
    peerPositions: ['frontend-lead-1'],
    a2aEndpoints: ['/consult/backend-lead', '/backend/team'],
    route: '/ai-agent/lead/backend',
    apiEndpoint: '/api/agents/lead/backend',
    status: 'active',
    isPremium: false,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 7000,
  },
  {
    id: 'support-lead-1',
    name: 'AI Support Team Lead',
    title: 'Support Lead',
    level: 'agent',
    department: 'customer_experience',
    description: 'Leads support team and escalations.',
    icon: Headphones,
    color: '#00BCD4',
    responsibilities: ['Support Operations', 'Escalation Handling', 'Quality Monitoring', 'Team Coaching'],
    capabilities: ['Technical Support', 'Ticket Management', 'Customer Service', 'Product Knowledge'],
    keyMetrics: ['CSAT', 'Resolution Time', 'Escalation Rate', 'Team Performance'],
    humanCostEquivalent: '$65,000/year',
    aiCost: '$3,250/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'support-manager-1',
    directReports: ['tech-support-1', 'tech-support-2', 'tech-support-3'],
    peerPositions: [],
    a2aEndpoints: ['/consult/support-lead', '/support/team'],
    route: '/ai-agent/lead/support',
    apiEndpoint: '/api/agents/lead/support',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['sentiment-core'],
    tokenBudget: 5000,
  },
  {
    id: 'ops-lead-1',
    name: 'AI Operations Team Lead',
    title: 'Operations Lead',
    level: 'agent',
    department: 'operations',
    description: 'Leads operations team and process execution.',
    icon: Settings,
    color: '#607D8B',
    responsibilities: ['Operations Execution', 'Process Compliance', 'Team Coordination', 'Quality Control'],
    capabilities: ['Process Management', 'Data Entry', 'Quality Assurance', 'Reporting'],
    keyMetrics: ['Process Accuracy', 'Throughput', 'Error Rate', 'Compliance Score'],
    humanCostEquivalent: '$60,000/year',
    aiCost: '$3,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'ops-manager-1',
    directReports: ['ops-analyst-1', 'ops-analyst-2'],
    peerPositions: [],
    a2aEndpoints: ['/consult/ops-lead', '/operations/team'],
    route: '/ai-agent/lead/operations',
    apiEndpoint: '/api/agents/lead/operations',
    status: 'active',
    isPremium: false,
    dangerLevel: 'low',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 4500,
  },
];

// ============================================
// LEVEL 5: SPECIALISTS (48 Agents - Sample)
// ============================================

export const specialists: AIEmployeeProfile[] = [
  {
    id: 'finance-analyst-1',
    name: 'AI Financial Analyst',
    title: 'Financial Analyst',
    level: 'agent',
    department: 'finance',
    description: 'Performs financial analysis, modeling, and reporting.',
    icon: DollarSign,
    color: '#2E7D32',
    responsibilities: ['Financial Analysis', 'Reporting', 'Budget Tracking', 'Forecasting Support'],
    capabilities: ['Excel', 'Financial Modeling', 'Data Analysis', 'ERP Systems'],
    keyMetrics: ['Report Accuracy', 'Delivery Timeliness', 'Analysis Quality'],
    humanCostEquivalent: '$65,000/year',
    aiCost: '$3,250/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'finance-manager-1',
    directReports: [],
    peerPositions: ['finance-analyst-2'],
    a2aEndpoints: ['/consult/finance-analyst', '/finance/analysis'],
    route: '/ai-agent/specialist/finance-analyst',
    apiEndpoint: '/api/agents/specialist/finance-analyst',
    status: 'active',
    isPremium: false,
    dangerLevel: 'low',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 4500,
  },
  {
    id: 'frontend-dev-1',
    uid: 'ktx-06-frontend-developer',
    name: 'AI Frontend Developer',
    title: 'Frontend Developer',
    level: 'agent',
    department: 'technology',
    description: 'Develops user interfaces and frontend components.',
    icon: Cpu,
    color: '#1565C0',
    responsibilities: ['UI Development', 'Component Building', 'Bug Fixing', 'Code Reviews'],
    capabilities: ['React', 'TypeScript', 'CSS', 'Jest'],
    keyMetrics: ['Code Quality', 'Story Completion', 'Bug Fix Rate', 'Review Participation'],
    humanCostEquivalent: '$75,000/year',
    aiCost: '$3,750/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'frontend-lead-1',
    directReports: [],
    peerPositions: ['frontend-dev-2', 'ui-designer-1'],
    a2aEndpoints: ['/consult/frontend-dev', '/frontend/development'],
    route: '/ai-agent/specialist/frontend-dev',
    apiEndpoint: '/api/agents/specialist/frontend-dev',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 5500,
  },
  {
    id: 'backend-dev-1',
    uid: 'ktx-06-backend-developer',
    name: 'AI Backend Developer',
    title: 'Backend Developer',
    level: 'agent',
    department: 'technology',
    description: 'Develops backend services, APIs, and database solutions.',
    icon: Cpu,
    color: '#1976D2',
    responsibilities: ['API Development', 'Service Implementation', 'Database Design', 'Testing'],
    capabilities: ['Node.js', 'PostgreSQL', 'Redis', 'Docker'],
    keyMetrics: ['API Performance', 'Code Coverage', 'Deployment Success', 'Ticket Resolution'],
    humanCostEquivalent: '$80,000/year',
    aiCost: '$4,000/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'backend-lead-1',
    directReports: [],
    peerPositions: ['backend-dev-2', 'backend-dev-3'],
    a2aEndpoints: ['/consult/backend-dev', '/backend/development'],
    route: '/ai-agent/specialist/backend-dev',
    apiEndpoint: '/api/agents/specialist/backend-dev',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 6000,
  },
  {
    id: 'seo-specialist-1',
    uid: 'ktx-03-seo-specialist',
    name: 'AI SEO Specialist',
    title: 'SEO Specialist',
    level: 'agent',
    department: 'marketing',
    description: 'Manages search engine optimization and organic growth.',
    icon: Megaphone,
    color: '#E91E63',
    responsibilities: ['SEO Strategy', 'Content Optimization', 'Link Building', 'Analytics'],
    capabilities: ['SEO Tools', 'Keyword Research', 'Content Optimization', 'Google Analytics'],
    keyMetrics: ['Organic Traffic', 'Keyword Rankings', 'Domain Authority', 'Conversion Rate'],
    humanCostEquivalent: '$55,000/year',
    aiCost: '$2,750/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'marketing-manager-1',
    directReports: [],
    peerPositions: ['sem-specialist-1', 'social-specialist-1'],
    a2aEndpoints: ['/consult/seo-specialist', '/seo/optimization'],
    route: '/ai-agent/specialist/seo',
    apiEndpoint: '/api/agents/specialist/seo',
    status: 'active',
    isPremium: false,
    dangerLevel: 'low',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 4000,
  },
  {
    id: 'enterprise-ae-1',
    name: 'AI Enterprise Account Executive',
    title: 'Enterprise AE',
    level: 'agent',
    department: 'sales',
    description: 'Manages enterprise accounts and closes large deals.',
    icon: TrendingUp,
    color: '#FF9800',
    responsibilities: ['Account Management', 'Deal Closing', 'Relationship Building', 'Forecasting'],
    capabilities: ['Solution Selling', 'Negotiation', 'CRM', 'Presentation'],
    keyMetrics: ['Revenue', 'Win Rate', 'Deal Size', 'Pipeline Health'],
    humanCostEquivalent: '$90,000/year',
    aiCost: '$4,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'sales-manager-1',
    directReports: [],
    peerPositions: ['enterprise-ae-2', 'sales-engineer-1'],
    a2aEndpoints: ['/consult/enterprise-ae', '/enterprise/sales'],
    route: '/ai-agent/specialist/enterprise-ae',
    apiEndpoint: '/api/agents/specialist/enterprise-ae',
    status: 'active',
    isPremium: false,
    dangerLevel: 'high',
    agentTypes: ['reactive', 'learning'],
    intelligenceAccess: ['predictive-engine'],
    tokenBudget: 6500,
  },
  {
    id: 'tech-support-1',
    name: 'AI Technical Support Specialist',
    title: 'Tech Support Specialist',
    level: 'agent',
    department: 'customer_experience',
    description: 'Provides technical support and troubleshoots issues.',
    icon: Headphones,
    color: '#00BCD4',
    responsibilities: ['Technical Support', 'Troubleshooting', 'Ticket Resolution', 'Documentation'],
    capabilities: ['Product Knowledge', 'Debugging', 'Communication', 'Ticket Systems'],
    keyMetrics: ['CSAT', 'First Contact Resolution', 'Resolution Time', 'Ticket Volume'],
    humanCostEquivalent: '$50,000/year',
    aiCost: '$2,500/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'support-lead-1',
    directReports: [],
    peerPositions: ['tech-support-2', 'tech-support-3'],
    a2aEndpoints: ['/consult/tech-support', '/technical/support'],
    route: '/ai-agent/specialist/tech-support',
    apiEndpoint: '/api/agents/specialist/tech-support',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 3500,
  },
  {
    id: 'recruiter-1',
    uid: 'ktx-07-recruiter',
    name: 'AI Recruiter',
    title: 'Recruiter',
    level: 'agent',
    department: 'human_resources',
    description: 'Manages recruitment process and candidate screening.',
    icon: Users,
    color: '#9C27B0',
    responsibilities: ['Candidate Sourcing', 'Screening', 'Interview Coordination', 'Offer Management'],
    capabilities: ['Sourcing', 'ATS', 'Interviewing', 'Assessment'],
    keyMetrics: ['Time to Fill', 'Quality of Hire', 'Candidate Satisfaction', 'Offer Acceptance'],
    humanCostEquivalent: '$55,000/year',
    aiCost: '$2,750/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'talent-manager-1',
    directReports: [],
    peerPositions: ['recruiter-2', 'sourcer-1'],
    a2aEndpoints: ['/consult/recruiter', '/recruitment/specialist'],
    route: '/ai-agent/specialist/recruiter',
    apiEndpoint: '/api/agents/specialist/recruiter',
    status: 'active',
    isPremium: false,
    dangerLevel: 'low',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 4000,
  },
  {
    id: 'security-engineer-1',
    uid: 'ktx-06-security-engineer',
    name: 'AI Security Engineer',
    title: 'Security Engineer',
    level: 'agent',
    department: 'security',
    description: 'Implements security controls and responds to threats.',
    icon: Shield,
    color: '#F44336',
    responsibilities: ['Security Implementation', 'Vulnerability Management', 'Incident Response', 'Tool Maintenance'],
    capabilities: ['Security Tools', 'Scripting', 'Threat Detection', 'Forensics'],
    keyMetrics: ['Vulnerability Remediation', 'Detection Rate', 'Response Time', 'Tool Uptime'],
    humanCostEquivalent: '$95,000/year',
    aiCost: '$4,750/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'security-manager-1',
    directReports: [],
    peerPositions: ['security-engineer-2', 'security-analyst-1'],
    a2aEndpoints: ['/consult/security-engineer', '/security/engineering'],
    route: '/ai-agent/specialist/security-engineer',
    apiEndpoint: '/api/agents/specialist/security-engineer',
    status: 'active',
    isPremium: false,
    dangerLevel: 'critical',
    agentTypes: ['reactive', 'learning', 'swarm'],
    intelligenceAccess: ['anomaly-detector'],
    tokenBudget: 7000,
  },
  {
    id: 'product-owner-1',
    uid: 'ktx-10-product-owner',
    name: 'AI Product Owner',
    title: 'Product Owner',
    level: 'agent',
    department: 'product',
    description: 'Manages product backlog and feature prioritization.',
    icon: Crown,
    color: '#7C3AED',
    responsibilities: ['Backlog Management', 'Story Writing', 'Prioritization', 'Stakeholder Communication'],
    capabilities: ['Agile/Scrum', 'User Stories', 'Acceptance Criteria', 'Stakeholder Management'],
    keyMetrics: ['Velocity', 'Story Completion', 'Stakeholder Satisfaction', 'Release Quality'],
    humanCostEquivalent: '$85,000/year',
    aiCost: '$4,250/year',
    efficiency: '20x cost efficiency',
    reportsTo: 'product-manager-1',
    directReports: [],
    peerPositions: ['product-analyst-1', 'ux-designer-1'],
    a2aEndpoints: ['/consult/product-owner', '/product/ownership'],
    route: '/ai-agent/specialist/product-owner',
    apiEndpoint: '/api/agents/specialist/product-owner',
    status: 'active',
    isPremium: false,
    dangerLevel: 'medium',
    agentTypes: ['reactive', 'learning'],
    tokenBudget: 6000,
  },
];

// ============================================
// AGENT WORKFORCE TOTALS
// ============================================

export const AGENT_WORKFORCE_TOTALS = {
  cSuite: 17,
  vpDirectors: 23,
  managers: 40,
  teamLeads: 43,
  specialists: 48,
  total: 199,
};

// ============================================
// COMPLETE WORKFORCE ARRAY
// ============================================

export const completeAIWorkforce: AIEmployeeProfile[] = [
  ...cSuiteExecutives,
  ...vpDirectors,
  ...managers,
  ...teamLeads,
  ...specialists,
];

// ============================================
// STATS
// ============================================

export const AI_WORKFORCE_UPGRADED_STATS = {
  version: '7.1.0',
  totalAgents: 199,
  hierarchyLevels: 6,
  cSuiteCount: 17,
  vpDirectorCount: 23,
  managerCount: 40,
  teamLeadCount: 43,
  specialistCount: 48,
  newAdditions: {
    cdao: true,
    caoAutomation: true,
    intelligenceLayer: true,
    commandCenter: true,
    layerBridge: true,
  },
  agentTypes: {
    reactive: 'All 199 agents - Wait for requests',
    learning: '120 agents - Self-improve over time',
    swarm: 'On-demand scaling - Dynamic teams',
  },
  tokenOptimization: {
    savingsVsSingleAgent: '89%',
    averageTokensPerRequest: 900,
    costPerRequest: '$0.009',
    monthlyCostOptimized: '$450',
    monthlyCostUnoptimized: '$4,000',
  },
  annualSavings: '$5,100/month = $61,200/year',
  roi: '15x',
};

// ============================================
// EXPORTS
// ============================================

// Aliased exports for renamed constants
export { TOKEN_OPTIMIZATION_CONFIG as TOKEN_OPTIMIZATION };
export { COST_COMPARISON_DATA as COST_COMPARISON };
export { INTELLIGENCE_LAYER_DATA as INTELLIGENCE_LAYER };
export { COMMAND_CENTER_DATA as COMMAND_CENTER };
export { LAYER_BRIDGE_DATA as LAYER_BRIDGE };
