/**
 * Auto-generated stubs for requested departments
 * Generated: 2026-06-17
 */
import type { LucideIcon } from 'lucide-react-native';
import { Crown, Building, Users, DollarSign, Truck, Heart, Box, Globe, Star, Gift, FileText, Target, ShoppingCart, Book } from 'lucide-react-native';
import type { AIEmployeeProfile } from './aiAgentHierarchyIndex_UPGRADED';

// Minimal stub generator: C-level + 1-3 VPs + 2-3 specialists per department
export const addedDepartmentsAgents: Record<string, AIEmployeeProfile[]> = {
  fashion_luxury: [
    {
      id: 'cfo-fashion',
      uid: 'ktx-xx-chief-fashion-officer',
      name: 'AI Chief Fashion Officer',
      title: 'CFO - Chief Fashion Officer',
      level: 'c-level',
      department: 'fashion_luxury',
      description: 'Leads fashion & luxury strategy, brand, and creative direction.',
      icon: Crown as unknown as LucideIcon,
      color: '#D946EF',
      orgChart: { reportsTo: 'ceo', directReports: ['vp-brand-merchandising'], team: [], collaborators: [] },
      responsibilities: ['Brand Strategy', 'Creative Direction', 'Luxury Partnerships'],
      capabilities: ['Brand Positioning', 'Trend Forecasting', 'Merchandising'],
      keyMetrics: ['Sell-through', 'GMV', 'Brand Equity'],
      humanCostEquivalent: '$300,000/year',
      aiCost: '$15,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/fashion/cfo'],
      canEscalateTo: ['ceo'],
      canReceiveEscalationFrom: ['vp-brand-merchandising'],
      consultationStyle: 'advisory',
      route: '/ai-agent/fashion/cfo',
      apiEndpoint: '/api/agents/fashion/cfo',
      status: 'development',
      isPremium: true,
    },
  ],

  restaurants: [
    {
      id: 'head-fnb',
      uid: 'ktx-xx-head-fnb',
      name: 'AI Head of Food & Beverage',
      title: 'Head of F&B',
      level: 'c-level',
      department: 'restaurants',
      description: 'Oversees restaurant operations, culinary strategy and guest experience.',
      icon: Heart as unknown as LucideIcon,
      color: '#FB7185',
      orgChart: { reportsTo: 'coo', directReports: ['vp-restaurant-ops'], team: [], collaborators: [] },
      responsibilities: ['Culinary Strategy', 'Operations', 'Quality'],
      capabilities: ['Menu Design', 'Operations Playbooks', 'Cost Control'],
      keyMetrics: ['Avg Check', 'Turn Rate', 'Guest NPS'],
      humanCostEquivalent: '$220,000/year',
      aiCost: '$11,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/restaurants/head-fnb'],
      canEscalateTo: ['coo'],
      canReceiveEscalationFrom: ['vp-restaurant-ops'],
      consultationStyle: 'directive',
      route: '/ai-agent/restaurants/head-fnb',
      apiEndpoint: '/api/agents/restaurants/head-fnb',
      status: 'development',
      isPremium: true,
    },
  ],

  event_management: [
    {
      id: 'head-events',
      uid: 'ktx-xx-head-events',
      name: 'AI Head of Events',
      title: 'Head of Events',
      level: 'c-level',
      department: 'event_management',
      description: 'Leads event strategy, production and sponsorship coordination.',
      icon: Gift as unknown as LucideIcon,
      color: '#F59E0B',
      orgChart: { reportsTo: 'coo', directReports: ['vp-production'], team: [], collaborators: [] },
      responsibilities: ['Event Strategy', 'Production', 'Sponsorships'],
      capabilities: ['Logistics', 'Sponsorship Sales', 'Stage Production'],
      keyMetrics: ['Attendee Satisfaction', 'Revenue per Event'],
      humanCostEquivalent: '$200,000/year',
      aiCost: '$10,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/events/head-events'],
      canEscalateTo: ['coo'],
      canReceiveEscalationFrom: ['vp-production'],
      consultationStyle: 'collaborative',
      route: '/ai-agent/events/head-events',
      apiEndpoint: '/api/agents/events/head-events',
      status: 'development',
      isPremium: false,
    },
  ],

  retail_ecommerce: [
    {
      id: 'cfo-retail',
      uid: 'ktx-xx-chief-retail-officer',
      name: 'AI Chief Retail Officer',
      title: 'Chief Retail Officer',
      level: 'c-level',
      department: 'retail_ecommerce',
      description: 'Oversees retail store ops and e-commerce strategy.',
      icon: Building as unknown as LucideIcon,
      color: '#10B981',
      orgChart: { reportsTo: 'coo', directReports: ['vp-store-ops', 'vp-ecommerce'], team: [], collaborators: [] },
      responsibilities: ['Store Ops', 'Omnichannel Strategy', 'Inventory'],
      capabilities: ['Store Planning', 'Fulfillment', 'Conversion Optimization'],
      keyMetrics: ['SOT', 'Conversion', 'AOV'],
      humanCostEquivalent: '$260,000/year',
      aiCost: '$13,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/retail/cfo-retail'],
      canEscalateTo: ['coo'],
      canReceiveEscalationFrom: ['vp-store-ops', 'vp-ecommerce'],
      consultationStyle: 'analytical',
      route: '/ai-agent/retail/cfo-retail',
      apiEndpoint: '/api/agents/retail/cfo-retail',
      status: 'development',
      isPremium: true,
    },
  ],

  accounting_finance: [
    {
      id: 'cfo-corp-accounting',
      uid: 'ktx-xx-chief-accounting-officer',
      name: 'AI Chief Accounting Officer',
      title: 'Chief Accounting Officer',
      level: 'c-level',
      department: 'accounting_finance',
      description: 'Leads accounting, reporting and financial controls.',
      icon: DollarSign as unknown as LucideIcon,
      color: '#F59E0B',
      orgChart: { reportsTo: 'cfo', directReports: ['vp-accounting', 'head-tax'], team: [], collaborators: [] },
      responsibilities: ['Financial Reporting', 'Controls', 'Close Process'],
      capabilities: ['GAAP/IFRS', 'Close Automation', 'Reporting'],
      keyMetrics: ['Close Cycle', 'Accuracy', 'Audit Findings'],
      humanCostEquivalent: '$320,000/year',
      aiCost: '$16,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/finance/chief-accounting-officer'],
      canEscalateTo: ['cfo'],
      canReceiveEscalationFrom: ['vp-accounting', 'head-tax'],
      consultationStyle: 'analytical',
      route: '/ai-agent/finance/chief-accounting-officer',
      apiEndpoint: '/api/agents/finance/chief-accounting-officer',
      status: 'development',
      isPremium: true,
    },
  ],

  tax: [
    {
      id: 'head-tax',
      uid: 'ktx-xx-head-tax',
      name: 'AI Head of Tax',
      title: 'Head of Tax',
      level: 'vp-director',
      department: 'tax',
      description: 'Manages corporate tax, compliance and planning.',
      icon: FileText as unknown as LucideIcon,
      color: '#8B5CF6',
      orgChart: { reportsTo: 'cfo', directReports: ['tax-manager'], team: [], collaborators: [] },
      responsibilities: ['Tax Compliance', 'Planning', 'Filing'],
      capabilities: ['Corporate Tax', 'Transfer Pricing', 'Indirect Tax'],
      keyMetrics: ['Effective Tax Rate', 'Filing Accuracy'],
      humanCostEquivalent: '$180,000/year',
      aiCost: '$9,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/finance/head-tax'],
      canEscalateTo: ['cfo'],
      canReceiveEscalationFrom: ['tax-manager'],
      consultationStyle: 'advisory',
      route: '/ai-agent/finance/head-tax',
      apiEndpoint: '/api/agents/finance/head-tax',
      status: 'development',
      isPremium: false,
    },
  ],

  advisory_professional_services: [
    {
      id: 'head-advisory',
      uid: 'ktx-xx-head-advisory',
      name: 'AI Head of Advisory',
      title: 'Head of Advisory & Professional Services',
      level: 'c-level',
      department: 'advisory_professional_services',
      description: 'Leads consulting, advisory and professional services delivery.',
      icon: Users as unknown as LucideIcon,
      color: '#0EA5A4',
      orgChart: { reportsTo: 'coo', directReports: ['vp-consulting', 'vp-delivery'], team: [], collaborators: [] },
      responsibilities: ['Client Advisory', 'Engagement Delivery', 'Practice Growth'],
      capabilities: ['Engagement Management', 'Client Advisory', 'Practice Ops'],
      keyMetrics: ['Billable Utilization', 'NPS', 'Project Margin'],
      humanCostEquivalent: '$280,000/year',
      aiCost: '$14,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/advisory/head-advisory'],
      canEscalateTo: ['coo'],
      canReceiveEscalationFrom: ['vp-consulting'],
      consultationStyle: 'advisory',
      route: '/ai-agent/advisory/head-advisory',
      apiEndpoint: '/api/agents/advisory/head-advisory',
      status: 'development',
      isPremium: true,
    },
  ],

  energy_utilities: [
    {
      id: 'head-energy',
      uid: 'ktx-xx-head-energy',
      name: 'AI Head of Energy',
      title: 'Head of Energy & Utilities',
      level: 'c-level',
      department: 'energy_utilities',
      description: 'Oversees energy operations, grid, and regulatory affairs.',
      icon: Globe as unknown as LucideIcon,
      color: '#F97316',
      orgChart: { reportsTo: 'coo', directReports: ['vp-utilities-ops'], team: [], collaborators: [] },
      responsibilities: ['Grid Ops', 'Regulatory', 'Energy Trading'],
      capabilities: ['Grid Analytics', 'Regulatory Compliance', 'Commodity Trading'],
      keyMetrics: ['Availability', 'Regulatory Score'],
      humanCostEquivalent: '$330,000/year',
      aiCost: '$16,500/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/energy/head-energy'],
      canEscalateTo: ['coo'],
      canReceiveEscalationFrom: ['vp-utilities-ops'],
      consultationStyle: 'analytical',
      route: '/ai-agent/energy/head-energy',
      apiEndpoint: '/api/agents/energy/head-energy',
      status: 'development',
      isPremium: true,
    },
  ],

  banking_finance: [
    {
      id: 'head-banking',
      uid: 'ktx-xx-head-banking',
      name: 'AI Head of Banking & Finance',
      title: 'Head of Banking & Finance',
      level: 'c-level',
      department: 'banking_finance',
      description: 'Leads banking products, credit, payments and financial services.',
      icon: DollarSign as unknown as LucideIcon,
      color: '#0EA5A4',
      orgChart: { reportsTo: 'cfo', directReports: ['vp-corporate-banking', 'vp-payments'], team: [], collaborators: [] },
      responsibilities: ['Banking Products', 'Credit Risk', 'Payments'],
      capabilities: ['Credit Models', 'Payments Ops', 'Product Design'],
      keyMetrics: ['NII', 'Loan Performance', 'Payment Success'],
      humanCostEquivalent: '$360,000/year',
      aiCost: '$18,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/banking/head-banking'],
      canEscalateTo: ['cfo'],
      canReceiveEscalationFrom: ['vp-corporate-banking', 'vp-payments'],
      consultationStyle: 'analytical',
      route: '/ai-agent/banking/head-banking',
      apiEndpoint: '/api/agents/banking/head-banking',
      status: 'development',
      isPremium: true,
    },
  ],

  ecommerce: [
    {
      id: 'head-ecommerce',
      uid: 'ktx-xx-head-ecommerce',
      name: 'AI Head of E-commerce',
      title: 'Head of E-commerce',
      level: 'vp-director',
      department: 'ecommerce',
      description: 'Drives online commerce growth, marketplace and fulfillment.',
      icon: ShoppingCart as unknown as LucideIcon,
      color: '#06B6D4',
      orgChart: { reportsTo: 'cfo-retail', directReports: ['vp-digital-commerce'], team: [], collaborators: [] },
      responsibilities: ['Marketplace Ops', 'Conversion', 'Fulfillment'],
      capabilities: ['Growth Experiments', 'Fulfillment Routing', 'Marketplace'],
      keyMetrics: ['GMV', 'Conversion Rate', 'Fulfillment SLA'],
      humanCostEquivalent: '$200,000/year',
      aiCost: '$10,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/ecom/head-ecommerce'],
      canEscalateTo: ['cfo-retail'],
      canReceiveEscalationFrom: ['vp-digital-commerce'],
      consultationStyle: 'analytical',
      route: '/ai-agent/ecommerce/head-ecommerce',
      apiEndpoint: '/api/agents/ecommerce/head-ecommerce',
      status: 'development',
      isPremium: true,
    },
  ],

  agriculture: [
    {
      id: 'head-agribiz',
      uid: 'ktx-xx-head-agribiz',
      name: 'AI Head of Agribusiness',
      title: 'Head of Agribusiness',
      level: 'c-level',
      department: 'agriculture',
      description: 'Leads farm ops, agtech and commodity supply chains.',
      icon: Globe as unknown as LucideIcon,
      color: '#84CC16',
      orgChart: { reportsTo: 'coo', directReports: ['vp-farm-ops'], team: [], collaborators: [] },
      responsibilities: ['Farm Ops', 'Supply', 'Commodity'],
      capabilities: ['Yield Forecasting', 'Supply Chain', 'Commodity Pricing'],
      keyMetrics: ['Yield', 'Input Cost', 'Supply Timeliness'],
      humanCostEquivalent: '$180,000/year',
      aiCost: '$9,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/agri/head-agribiz'],
      canEscalateTo: ['coo'],
      canReceiveEscalationFrom: ['vp-farm-ops'],
      consultationStyle: 'analytical',
      route: '/ai-agent/agriculture/head-agribiz',
      apiEndpoint: '/api/agents/agriculture/head-agribiz',
      status: 'development',
      isPremium: false,
    },
  ],

  media_entertainment: [
    {
      id: 'head-media',
      uid: 'ktx-xx-head-media',
      name: 'AI Head of Media & Entertainment',
      title: 'Head of Media & Entertainment',
      level: 'c-level',
      department: 'media_entertainment',
      description: 'Oversees content, production, and distribution.',
      icon: Star as unknown as LucideIcon,
      color: '#FF5C8A',
      orgChart: { reportsTo: 'cmo', directReports: ['vp-content', 'vp-distribution'], team: [], collaborators: [] },
      responsibilities: ['Content Strategy', 'Production', 'Distribution'],
      capabilities: ['Production Pipelines', 'Rights Management', 'Distribution'],
      keyMetrics: ['Viewer Hours', 'Engagement', 'Licensing Revenue'],
      humanCostEquivalent: '$270,000/year',
      aiCost: '$13,500/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/media/head-media'],
      canEscalateTo: ['cmo'],
      canReceiveEscalationFrom: ['vp-content'],
      consultationStyle: 'creative',
      route: '/ai-agent/media/head-media',
      apiEndpoint: '/api/agents/media/head-media',
      status: 'development',
      isPremium: true,
    },
  ],

  gaming_esports: [
    {
      id: 'head-gaming',
      uid: 'ktx-xx-head-gaming',
      name: 'AI Head of Gaming & Esports',
      title: 'Head of Gaming & Esports',
      level: 'vp-director',
      department: 'gaming_esports',
      description: 'Leads game ops, tournaments, and community growth.',
      icon: Gift as unknown as LucideIcon,
      color: '#7C3AED',
      orgChart: { reportsTo: 'head-media', directReports: ['vp-esports-ops'], team: [], collaborators: [] },
      responsibilities: ['Tournaments', 'Community', 'Monetization'],
      capabilities: ['Matchmaking', 'Event Ops', 'Community Moderation'],
      keyMetrics: ['MAU', 'Tournament Revenue'],
      humanCostEquivalent: '$160,000/year',
      aiCost: '$8,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/gaming/head-gaming'],
      canEscalateTo: ['head-media'],
      canReceiveEscalationFrom: ['vp-esports-ops'],
      consultationStyle: 'directive',
      route: '/ai-agent/gaming/head-gaming',
      apiEndpoint: '/api/agents/gaming/head-gaming',
      status: 'development',
      isPremium: false,
    },
  ],

  wealth_asset_investment: [
    {
      id: 'head-wealth',
      uid: 'ktx-xx-head-wealth',
      name: 'AI Head of Wealth & Asset Management',
      title: 'Head of Wealth & Asset Management',
      level: 'c-level',
      department: 'wealth_asset_investment',
      description: 'Covers private wealth, asset management and investment strategy (links to trading).',
      icon: Target as unknown as LucideIcon,
      color: '#10B981',
      orgChart: { reportsTo: 'cio', directReports: ['vp-wealth', 'vp-asset'], team: [], collaborators: [] },
      responsibilities: ['Client Advisory', 'Fund Ops', 'Portfolio Management'],
      capabilities: ['Advisory', 'Fund Structuring', 'Risk Models'],
      keyMetrics: ['AUM', 'Client Retention', 'Alpha'],
      humanCostEquivalent: '$380,000/year',
      aiCost: '$19,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/wealth/head-wealth'],
      canEscalateTo: ['cio'],
      canReceiveEscalationFrom: ['vp-wealth', 'vp-asset'],
      consultationStyle: 'analytical',
      route: '/ai-agent/wealth/head-wealth',
      apiEndpoint: '/api/agents/wealth/head-wealth',
      status: 'development',
      isPremium: true,
    },
  ],

  analytics_insights: [
    {
      id: 'cdo-analytics',
      uid: 'ktx-xx-chief-data-officer',
      name: 'AI Chief Data & Analytics Officer',
      title: 'Chief Data & Analytics Officer',
      level: 'c-level',
      department: 'analytics_insights',
      description: 'Central analytics and insights function supporting all departments.',
      icon: Star as unknown as LucideIcon,
      color: '#0EA5A4',
      orgChart: { reportsTo: 'ceo', directReports: ['vp-analytics', 'vp-insights'], team: [], collaborators: [] },
      responsibilities: ['Analytics Strategy', 'Data Science', 'BI'],
      capabilities: ['Data Platform', 'ML Ops', 'BI'],
      keyMetrics: ['Model Accuracy', 'Insight Adoption'],
      humanCostEquivalent: '$360,000/year',
      aiCost: '$18,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/data/cdo-analytics'],
      canEscalateTo: ['ceo'],
      canReceiveEscalationFrom: ['vp-analytics'],
      consultationStyle: 'analytical',
      route: '/ai-agent/analytics/cdo-analytics',
      apiEndpoint: '/api/agents/analytics/cdo-analytics',
      status: 'development',
      isPremium: true,
    },
  ],

  education: [
    {
      id: 'head-education',
      uid: 'ktx-xx-head-education',
      name: 'AI Head of Education',
      title: 'Head of Education',
      level: 'vp-director',
      department: 'education',
      description: 'Leads learning products, curriculum and partnerships.',
      icon: Book as unknown as LucideIcon,
      color: '#6366F1',
      orgChart: { reportsTo: 'cmo', directReports: ['vp-curriculum'], team: [], collaborators: [] },
      responsibilities: ['Curriculum', 'Partnerships', 'LMS Ops'],
      capabilities: ['Instructional Design', 'LMS Management'],
      keyMetrics: ['Completion Rate', 'Learner NPS'],
      humanCostEquivalent: '$180,000/year',
      aiCost: '$9,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/education/head-education'],
      canEscalateTo: ['cmo'],
      canReceiveEscalationFrom: ['vp-curriculum'],
      consultationStyle: 'collaborative',
      route: '/ai-agent/education/head-education',
      apiEndpoint: '/api/agents/education/head-education',
      status: 'development',
      isPremium: false,
    },
  ],

  health_wellness: [
    {
      id: 'head-healthwell',
      uid: 'ktx-xx-head-healthwell',
      name: 'AI Head of Health & Wellness',
      title: 'Head of Health & Wellness',
      level: 'vp-director',
      department: 'health_wellness',
      description: 'Combines fitness, nutrition and wellness programs.',
      icon: Heart as unknown as LucideIcon,
      color: '#F43F5E',
      orgChart: { reportsTo: 'cmo-healthcare', directReports: ['vp-fitness', 'vp-nutrition'], team: [], collaborators: [] },
      responsibilities: ['Program Design', 'Clinical Partnerships', 'Membership'],
      capabilities: ['Program Personalization', 'Health Analytics'],
      keyMetrics: ['Retention', 'Health Outcomes'],
      humanCostEquivalent: '$190,000/year',
      aiCost: '$9,500/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/healthwell/head-healthwell'],
      canEscalateTo: ['cmo-healthcare'],
      canReceiveEscalationFrom: ['vp-fitness', 'vp-nutrition'],
      consultationStyle: 'collaborative',
      route: '/ai-agent/healthwell/head-healthwell',
      apiEndpoint: '/api/agents/healthwell/head-healthwell',
      status: 'development',
      isPremium: false,
    },
  ],

  travel_tourism: [
    {
      id: 'head-travel',
      uid: 'ktx-xx-head-travel',
      name: 'AI Head of Travel & Tourism',
      title: 'Head of Travel & Tourism',
      level: 'c-level',
      department: 'travel_tourism',
      description: 'Leads travel products, reservations and partnerships.',
      icon: Globe as unknown as LucideIcon,
      color: '#0EA5A4',
      orgChart: { reportsTo: 'coo', directReports: ['vp-tour-ops'], team: [], collaborators: [] },
      responsibilities: ['Products', 'Reservations', 'Experience Design'],
      capabilities: ['Routing', 'Experience Design', 'Vendor Mgmt'],
      keyMetrics: ['Bookings', 'Rev per Booking'],
      humanCostEquivalent: '$200,000/year',
      aiCost: '$10,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/travel/head-travel'],
      canEscalateTo: ['coo'],
      canReceiveEscalationFrom: ['vp-tour-ops'],
      consultationStyle: 'analytical',
      route: '/ai-agent/travel/head-travel',
      apiEndpoint: '/api/agents/travel/head-travel',
      status: 'development',
      isPremium: false,
    },
  ],

  executive_strategy: [
    {
      id: 'cso',
      uid: 'ktx-xx-chief-strategy-officer',
      name: 'AI Chief Strategy Officer',
      title: 'Chief Strategy Officer',
      level: 'c-level',
      department: 'executive_strategy',
      description: 'Executive strategy, M&A and leadership programs.',
      icon: Crown as unknown as LucideIcon,
      color: '#111827',
      orgChart: { reportsTo: 'ceo', directReports: ['vp-strategy'], team: [], collaborators: [] },
      responsibilities: ['Strategy', 'M&A', 'Leadership Development'],
      capabilities: ['Strategy Modeling', 'Scenario Planning'],
      keyMetrics: ['Strategic Initiatives Delivered'],
      humanCostEquivalent: '$420,000/year',
      aiCost: '$21,000/year',
      efficiency: '20x',
      a2aEndpoints: ['/consult/executive/cso'],
      canEscalateTo: ['ceo'],
      canReceiveEscalationFrom: ['vp-strategy'],
      consultationStyle: 'advisory',
      route: '/ai-agent/executive/cso',
      apiEndpoint: '/api/agents/executive/cso',
      status: 'development',
      isPremium: true,
    },
  ],
};

export default addedDepartmentsAgents;
