import type { LucideIcon } from 'lucide-react-native';
import {
  Shield,
  Crown,
  Microscope,
  Brain,
  Database,
  Globe,
  Workflow,
  Building2,
  Zap,
  Users,
  BarChart3,
  Scale,
  Target,
  Binoculars,
  Lightbulb,
  MessageSquare,
  Command,
  Layers,
  Play,
  CheckCircle,
  AlertTriangle,
  TrendingUp,
  Search,
  FileText,
  Settings,
  Gauge,
  Bot,
  Network,
  Factory,
  Lock,
  Eye,
  FileCheck,
  ClipboardList,
  ShieldCheck,
  ShieldAlert,
  Fingerprint,
  ScanEye,
  Lock as LockIcon,
  Key,
  Server,
  Cloud,
  HardDrive,
  Cpu,
  Activity,
  Timer,
  Clock,
  Calendar,
  Bell,
  Flag,
  Star,
  Trophy,
  Medal,
  Award,
  Sparkles,
  Rocket,
  Compass,
  Telescope,
  Microscope as MicroscopeIcon,
  Box,
  Package,
  Truck,
  Plane,
  Ship,
  Train,
  Car,
  MapPin,
  Flag as FlagIcon,
  Bookmark,
  Tag,
  DollarSign,
  CreditCard,
  Wallet,
  PiggyBank,
  Landmark,
  Receipt,
  Calculator,
  Coins,
  Banknote,
  TrendingDown,
  Percent,
  FileSpreadsheet,
  FileCode,
  FileJson,
  File,
  Folder,
  FolderOpen,
  Archive,
  Inbox,
  Mail,
  MailOpen,
  Send,
  Paperclip,
  MessageCircle,
  MessageSquare as MessageSquareIcon,
  Phone,
  PhoneCall,
  PhoneForward,
  Video,
  VideoIcon,
  Camera,
  Image,
  ImageIcon,
  FileImage,
  Printer,
  Scanner,
  Keyboard,
  Mouse,
  Monitor,
  Laptop,
  Tablet,
  Smartphone,
  Watch,
  Wifi,
  Signal,
  Antenna,
  Satellite,
  CloudLightning,
  CloudRain,
  Sun,
  Moon,
  Star as StarIcon,
  Heart,
  HeartHandshake,
  Smile,
  Frown,
  Meh,
  Angry,
  PartyPopper,
  Gift,
  Cake,
  Coffee,
  Utensils,
  UtensilsCrossed,
  Beer,
  Wine,
  GlassWater,
  Dumbbell,
  Bike,
  Footprints,
  Accessibility,
  Armchair,
  Bed,
  Home,
  Building,
  Store,
  Banknote as BanknoteIcon,
  Landmark as LandmarkIcon,
  Government,
  University,
  School,
  GraduationCap,
  Book,
  BookOpen,
  BookMarked,
  Library,
  PenTool,
  Pencil,
  Eraser,
  Highlighter,
  Ruler,
  Scissors,
  Paperclip as PaperclipIcon,
  Stapler,
  Clipboard,
  ClipboardCheck,
  ClipboardList as ClipboardListIcon,
  ListChecks,
  ListTodo,
  ListPlus,
  ListMinus,
  ListOrdered,
  CheckSquare,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Diamond,
  Square as SquareIcon,
  Triangle as TriangleIcon,
  Hexagon as HexagonIcon,
  Cloud as CloudIcon,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning as CloudLightningIcon,
  CloudMoon,
  CloudOff,
  CloudRain as CloudRainIcon,
  CloudSnow,
  CloudSun,
  Moon as MoonIcon,
  Sun as SunIcon,
  Sunrise,
  Sunset,
  Wind,
  Thermometer,
  ThermometerSun,
  ThermometerSnowflake,
  Droplets,
  Waves,
  Flame,
  Zap as ZapIcon,
  Bomb,
  BombIcon,
  Skull,
  SkullIcon,
  Ghost,
  Alien,
  Bug,
  Beetle,
  Bug as BugIcon,
  Worm,
  Sprout,
  TreeDeciduous,
  TreeEvergreen,
  Flower2,
  Leaf,
  Feather,
  PawPrint,
  Fish,
  FishIcon,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Hamster,
  Turtle,
  Snake,
  Crocodile,
  Whale,
  Shell,
  Bug as BugIconAlt,
  Leaf as LeafIcon,
  Mountain,
  Volcano,
  Campfire,
  Tent,
  Map,
  Map as MapIcon,
  Compass as CompassIcon,
  Navigation,
  Navigation as NavigationIcon,
  Location,
  LocationOn,
  MapPin as MapPinIcon,
  Crosshair,
  Target as TargetIcon,
  Aim,
  Crosshair as CrosshairIcon,
  Swords,
  Shield as ShieldIcon,
  Sword,
  Axe,
  Hammer,
  Wrench as WrenchIcon,
  Screwdriver,
  Tool,
  Tools,
  Pickaxe,
  Shovel,
  Rake,
  Bucket,
  SprayCan,
  Paintbucket,
  Palette as PaletteIcon,
  Pen,
  PenNib,
  Marker,
  Highlighter as HighlighterIcon,
  Eraser as EraserIcon,
  Ruler as RulerIcon,
  SquareTerminal,
  Terminal,
  Code,
  Code2,
  CodeSquare,
  FileCode as FileCodeIcon,
  FileJson as FileJsonIcon,
  FileType,
  Braces,
  Brackets,
  Parentheses,
  Variable,
  Function,
  Cpu as CpuIcon,
  HardDrive as HardDriveIcon,
  Server as ServerIcon,
  Database as DatabaseIcon,
  Cloud as CloudIconAlt,
  Wifi as WifiIcon,
  WifiOff,
  Signal as SignalIcon,
  SignalLow,
  SignalMedium,
  SignalHigh,
  Ethernet,
  Plug,
  PlugZap,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryMedium,
  BatteryLow,
  BatteryWarning,
  Speaker,
  Volume,
  Volume2,
  VolumeX,
  Music,
  Music2,
  Disc,
  Disc2,
  CassetteTape,
  Radio,
  Tv,
  Tv2,
  Monitor as MonitorIcon,
  Projector,
  Camera as CameraIcon,
  Video as VideoIconAlt,
  Film,
  Clapperboard,
  VideoCamera,
  VideoCameraFront,
  VideoCameraRear,
  Image as ImageIconAlt,
  ImagePlus,
  ImageMinus,
  ImageSearch,
  Images,
  Scan,
  ScanLine,
  QrCode,
  Barcode,
  Focus,
  Aperture,
  CameraOff,
  ImageOff,
  Mic,
  MicOff,
  MicVocal,
  Microscope as MicroscopeIconAlt,
  Telescope as TelescopeIconAlt,
  Binary,
  Box as BoxIcon,
  Case,
  Briefcase,
  Handshake,
  HandHeart,
  HandHelping,
  HandHolding,
  Hand,
  HandPointer,
  HandGrabbing,
  HandPeace,
  HandRaised,
  HandSlashed,
  HandsClapping,
  HandCoins,
  HandMetal,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  UserMinus,
  UserX,
  Users as UsersIcon,
  UsersRound,
  UserRound,
  UserSearch,
  UserShield,
  UserSquare,
  UserPlus2,
  UserMinus2,
  UserCheck2,
  UserX2,
  Contact,
  Contact2,
  IdCard,
  BadgeCheck,
  BadgeDollarSign,
  BadgeHelp,
  BadgeInfo,
  BadgeMinus,
  BadgePlus,
  BadgePercent,
  BadgePlus2,
  BadgeX,
  Award as AwardIcon,
  Certificate,
  Medal as MedalIcon,
  Trophy as TrophyIcon,
  Crown as CrownIcon,
  Gem,
  Diamond as DiamondIcon,
  Star as StarIconAlt,
  Stars,
  Sparkles as SparklesIcon,
  Sun as SunIconAlt,
  Moon as MoonIconAlt,
  Cloud as CloudIconAlt2,
  Umbrella,
  Shirt,
  Scarf,
  Footprints as FootprintsIcon,
  Accessibility as AccessibilityIcon,
  PersonStanding,
  PersonWalking,
  PersonRunning,
  PersonSwimming,
  PersonSnowboarding,
  PersonSurfing,
  PersonMountain,
  PersonHiking,
  PersonBiking,
} from 'lucide-react-native';

export type LayerId =
  | 'governance'
  | 'leadership'
  | 'simulation'
  | 'intelligence'
  | 'memory'
  | 'translation'
  | 'command'
  | 'enterprise'
  | 'execution'
  | 'workforce'
  | 'review';

export interface LayerComponent {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  color: string;
  route?: string;
}

export interface AILayer {
  id: LayerId;
  layerNumber: number;
  name: string;
  shortName: string;
  description: string;
  icon: LucideIcon;
  color: string;
  gradient: [string, string];
  tokenUsage: number;
  optimizedTokenUsage: number;
  useCase: string;
  workType: string;
  flow: string;
  route?: string;
  components: LayerComponent[];
  agentCount: number;
  features: string[];
}

export const layerColors: Record<LayerId, string> = {
  governance: '#6366F1',
  leadership: '#F59E0B',
  simulation: '#8B5CF6',
  intelligence: '#06B6D4',
  memory: '#10B981',
  translation: '#F97316',
  command: '#EF4444',
  enterprise: '#3B82F6',
  execution: '#EC4899',
  workforce: '#14B8A6',
  review: '#84CC16',
};

export const layerGradients: Record<LayerId, [string, string]> = {
  governance: ['#6366F1', '#4F46E5'],
  leadership: ['#F59E0B', '#D97706'],
  simulation: ['#8B5CF6', '#7C3AED'],
  intelligence: ['#06B6D4', '#0891B2'],
  memory: ['#10B981', '#059669'],
  translation: ['#F97316', '#EA580C'],
  command: ['#EF4444', '#DC2626'],
  enterprise: ['#3B82F6', '#2563EB'],
  execution: ['#EC4899', '#DB2777'],
  workforce: ['#14B8A6', '#0D9488'],
  review: ['#84CC16', '#65A30D'],
};

export const aiAgentLayers: AILayer[] = [
  {
    id: 'governance',
    layerNumber: 1,
    name: 'Governance',
    shortName: 'Governance',
    description: 'Sets rules, ensures compliance, and manages ethical AI usage across the entire organization.',
    icon: Shield,
    color: layerColors.governance,
    gradient: layerGradients.governance,
    tokenUsage: 0,
    optimizedTokenUsage: 0,
    useCase: 'Set rules, ensure compliance, ethical AI usage',
    workType: 'Security',
    flow: 'Rules',
    route: '/ai-agent/layer-governance',
    agentCount: 28,
    components: [
      { id: 'ethics-board', name: 'AI Ethics Board', description: 'Oversees ethical AI practices and decision-making', icon: Scale, color: '#6366F1', route: '/ai-agent/governance/ethics' },
      { id: 'ciso-ai', name: 'CISO-AI', description: 'AI Security and threat protection', icon: Shield, color: '#EF4444', route: '/ai-agent/governance/security' },
      { id: 'data-privacy', name: 'Data Privacy Council', description: 'Manages data privacy and compliance', icon: Shield, color: '#8B5CF6', route: '/ai-agent/governance/privacy' },
      { id: 'compliance-monitor', name: 'Compliance Monitor', description: 'Real-time compliance tracking', icon: CheckCircle, color: '#10B981', route: '/ai-agent/governance/compliance' },
      { id: 'audit-trail', name: 'Audit Trail System', description: 'Complete activity logging and auditing', icon: FileText, color: '#06B6D4', route: '/ai-agent/governance/audit' },
      { id: 'policy-enforcer', name: 'Policy Enforcer', description: 'Automated policy enforcement', icon: AlertTriangle, color: '#F59E0B', route: '/ai-agent/governance/policy' },
      { id: 'risk-committee', name: 'AI Risk Committee', description: 'Enterprise risk assessment and mitigation', icon: AlertTriangle, color: '#DC2626', route: '/ai-agent/governance/risk-committee' },
      { id: 'data-governance', name: 'Data Governance', description: 'Data quality and management', icon: Database, color: '#0891B2', route: '/ai-agent/governance/data-governance' },
      { id: 'access-control', name: 'Access Control Manager', description: 'Role-based access management', icon: Lock, color: '#7C3AED', route: '/ai-agent/governance/access-control' },
      { id: 'threat-detection', name: 'Threat Detection AI', description: 'Real-time threat identification', icon: ShieldAlert, color: '#DC2626', route: '/ai-agent/governance/threat-detection' },
      { id: 'incident-response', name: 'Incident Response Team', description: 'Security incident handling', icon: AlertTriangle, color: '#EF4444', route: '/ai-agent/governance/incident-response' },
      { id: 'vulnerability-scanner', name: 'Vulnerability Scanner', description: 'Automated vulnerability detection', icon: ScanEye, color: '#F59E0B', route: '/ai-agent/governance/vulnerability' },
      { id: 'security-audit', name: 'Security Audit System', description: 'Regular security assessments', icon: FileCheck, color: '#10B981', route: '/ai-agent/governance/security-audit' },
      { id: 'encryption-manager', name: 'Encryption Manager', description: 'Data encryption at rest and transit', icon: LockIcon, color: '#8B5CF6', route: '/ai-agent/governance/encryption' },
    ],
    features: [
      'Policy Management',
      'Compliance Tracking',
      'Risk Assessment',
      'Audit Logging',
      'Ethical AI Oversight',
      'Security Enforcement',
    ],
  },
  {
    id: 'leadership',
    layerNumber: 2,
    name: 'Leadership',
    shortName: 'Leadership',
    description: 'Strategic vision, board decisions, and high-level direction for the entire organization.',
    icon: Crown,
    color: layerColors.leadership,
    gradient: layerGradients.leadership,
    tokenUsage: 0,
    optimizedTokenUsage: 0,
    useCase: 'Strategic direction, company vision, major decisions',
    workType: 'Strategy',
    flow: 'Vision',
    route: '/ai-agent/layer-leadership',
    agentCount: 32,
    components: [
      { id: 'ceo', name: 'AI CEO', description: 'Chief Executive Officer - Overall strategy', icon: Crown, color: '#F59E0B', route: '/ai-agent/executive/ceo' },
      { id: 'cfo', name: 'AI CFO', description: 'Chief Financial Officer - Financial strategy', icon: TrendingUp, color: '#10B981', route: '/ai-agent/executive/cfo' },
      { id: 'cto', name: 'AI CTO', description: 'Chief Technology Officer - Tech vision', icon: Brain, color: '#3B82F6', route: '/ai-agent/executive/cto' },
      { id: 'cmo', name: 'AI CMO', description: 'Chief Marketing Officer - Growth strategy', icon: Target, color: '#EC4899', route: '/ai-agent/executive/cmo' },
      { id: 'coo', name: 'AI COO', description: 'Chief Operating Officer - Operations', icon: Settings, color: '#6366F1', route: '/ai-agent/executive/coo' },
      { id: 'chro', name: 'AI CHRO', description: 'Chief HR Officer - Talent strategy', icon: Users, color: '#8B5CF6', route: '/ai-agent/executive/chro' },
      { id: 'clo', name: 'AI CLO', description: 'Chief Legal Officer - Legal strategy', icon: Scale, color: '#F97316', route: '/ai-agent/executive/clo' },
      { id: 'ciso', name: 'AI CISO', description: 'Chief Security Officer - Security vision', icon: Shield, color: '#EF4444', route: '/ai-agent/executive/ciso' },
      { id: 'cio', name: 'AI CIO', description: 'Chief Investment Officer', icon: TrendingUp, color: '#14B8A6', route: '/ai-agent/executive/cio' },
      { id: 'creo', name: 'AI CREO', description: 'Chief Real Estate Officer', icon: Building2, color: '#06B6D4', route: '/ai-agent/executive/creo' },
      { id: 'cro', name: 'AI CRO', description: 'Chief Risk Officer', icon: AlertTriangle, color: '#F59E0B', route: '/ai-agent/executive/cro' },
      { id: 'cmo-healthcare', name: 'AI CMO-Health', description: 'Chief Medical Officer', icon: Shield, color: '#10B981', route: '/ai-agent/executive/cmo-healthcare' },
      { id: 'cpo', name: 'AI CPO', description: 'Chief Product Officer', icon: Zap, color: '#EC4899', route: '/ai-agent/executive/cpo' },
      { id: 'clo-logistics', name: 'AI CLO-Logistics', description: 'Chief Logistics Officer', icon: Layers, color: '#3B82F6', route: '/ai-agent/executive/clo-logistics' },
      { id: 'cao', name: 'AI CAO', description: 'Chief Analytics Officer', icon: BarChart3, color: '#8B5CF6', route: '/ai-agent/executive/cao' },
      { id: 'ccio', name: 'AI CCIO', description: 'Chief Customer Innovation Officer', icon: Lightbulb, color: '#F97316', route: '/ai-agent/executive/ccio' },
      { id: 'cdo', name: 'AI CDO', description: 'Chief Data Officer', icon: Database, color: '#06B6D4', route: '/ai-agent/executive/cdo' },
      { id: 'cso', name: 'AI CSO', description: 'Chief Strategy Officer', icon: Target, color: '#8B5CF6', route: '/ai-agent/executive/cso' },
      { id: 'cpo-ops', name: 'AI CPO-Ops', description: 'Chief Process Officer', icon: Workflow, color: '#14B8A6', route: '/ai-agent/executive/cpo-ops' },
      { id: 'cmo-digital', name: 'AI CMO-Digital', description: 'Chief Digital Marketing Officer', icon: Globe, color: '#F97316', route: '/ai-agent/executive/cmo-digital' },
      { id: 'cfo-operations', name: 'AI CFO-Ops', description: 'Chief Financial Operations Officer', icon: Calculator, color: '#10B981', route: '/ai-agent/executive/cfo-ops' },
      { id: 'cto-infrastructure', name: 'AI CTO-Infra', description: 'Chief Infrastructure Officer', icon: Server, color: '#3B82F6', route: '/ai-agent/executive/cto-infra' },
      { id: 'cto-security', name: 'AI CTO-Sec', description: 'Chief Security Technology Officer', icon: ShieldCheck, color: '#EF4444', route: '/ai-agent/executive/cto-security' },
      { id: 'chief-sustainability', name: 'AI CSUO', description: 'Chief Sustainability Officer', icon: Leaf, color: '#10B981', route: '/ai-agent/executive/csuo' },
    ],
    features: [
      'Strategic Planning',
      'Board Decisions',
      'Vision Casting',
      'Major Initiative Approval',
      'Stakeholder Communication',
      'Performance Oversight',
    ],
  },
  {
    id: 'simulation',
    layerNumber: 3,
    name: 'Simulation',
    shortName: 'Simulation',
    description: 'Test scenarios BEFORE execution using digital twins and multi-agent simulations.',
    icon: Microscope,
    color: layerColors.simulation,
    gradient: layerGradients.simulation,
    tokenUsage: 800,
    optimizedTokenUsage: 200,
    useCase: 'Test scenarios BEFORE execution, predict outcomes, risk-free decisions',
    workType: 'Testing',
    flow: 'Test',
    route: '/ai-agent/layer-simulation',
    agentCount: 24,
    components: [
      { id: 'mirofish-engine', name: 'MiroFish Engine', description: '10K-1M virtual agent simulations', icon: Microscope, color: '#8B5CF6', route: '/ai-agent/simulation/mirofish' },
      { id: 'digital-twin-core', name: 'Digital Twin Core', description: 'Customer, Employee, Business twins', icon: Layers, color: '#6366F1', route: '/ai-agent/simulation/digital-twin' },
      { id: 'customer-twin', name: 'Customer Digital Twins', description: 'Virtual customer profiles for testing', icon: Users, color: '#06B6D4', route: '/ai-agent/simulation/customer-twin' },
      { id: 'employee-twin', name: 'Employee Digital Twins', description: 'Virtual employee simulations', icon: Bot, color: '#10B981', route: '/ai-agent/simulation/employee-twin' },
      { id: 'business-twin', name: 'Business Process Twins', description: 'Process simulation environments', icon: Workflow, color: '#EC4899', route: '/ai-agent/simulation/business-twin' },
      { id: 'scenario-lab', name: 'Scenario Lab', description: 'Stress testing and risk simulation', icon: Binoculars, color: '#F59E0B', route: '/ai-agent/simulation/scenario-lab' },
      { id: 'stress-testing', name: 'Stress Testing Suite', description: 'Test extreme scenarios', icon: AlertTriangle, color: '#EF4444', route: '/ai-agent/simulation/stress-testing' },
      { id: 'risk-simulation', name: 'Risk Simulation Engine', description: 'Simulate operational risks', icon: TrendingUp, color: '#F97316', route: '/ai-agent/simulation/risk-simulation' },
      { id: 'opportunity-explorer', name: 'Opportunity Explorer', description: 'Find new market opportunities', icon: Search, color: '#14B8A6', route: '/ai-agent/simulation/opportunity' },
      { id: 'decision-validation', name: 'Decision Validation', description: 'A/B testing and ROI forecasting', icon: CheckCircle, color: '#84CC16', route: '/ai-agent/simulation/decision-validation' },
      { id: 'ab-test-simulator', name: 'A/B Test Simulator', description: 'Virtual A/B testing', icon: Play, color: '#3B82F6', route: '/ai-agent/simulation/ab-test' },
      { id: 'roi-forecaster', name: 'ROI Forecaster', description: 'Predict return on investment', icon: TrendingUp, color: '#10B981', route: '/ai-agent/simulation/roi-forecaster' },
    ],
    features: [
      'Multi-Agent Simulations',
      'Digital Twin Technology',
      'Scenario Stress-Testing',
      'Real-Time Decision Testing',
      'Market Digital Twin',
      'Crisis Simulator',
    ],
  },
  {
    id: 'intelligence',
    layerNumber: 4,
    name: 'Intelligence',
    shortName: 'Intelligence',
    description: 'Analyze data, predict trends, detect anomalies, and provide actionable insights.',
    icon: Brain,
    color: layerColors.intelligence,
    gradient: layerGradients.intelligence,
    tokenUsage: 500,
    optimizedTokenUsage: 150,
    useCase: 'Analyze data, predict trends, detect anomalies',
    workType: 'Analysis',
    flow: 'Predict',
    route: '/ai-agent/layer-intelligence',
    agentCount: 36,
    components: [
      { id: 'predictive-engine', name: 'Predictive Engine', description: 'Demand, churn, revenue forecasting', icon: TrendingUp, color: '#06B6D4', route: '/ai-agent/intelligence/predictive' },
      { id: 'demand-predictor', name: 'Demand Predictor', description: 'Forecast product demand', icon: BarChart3, color: '#3B82F6', route: '/ai-agent/intelligence/demand' },
      { id: 'churn-predictor', name: 'Churn Predictor', description: 'Predict customer churn', icon: Users, color: '#EF4444', route: '/ai-agent/intelligence/churn' },
      { id: 'revenue-forecaster', name: 'Revenue Forecaster', description: 'Predict revenue trends', icon: TrendingUp, color: '#10B981', route: '/ai-agent/intelligence/revenue' },
      { id: 'sentiment-core', name: 'Sentiment Core', description: 'Emotion detection and CSAT analysis', icon: Brain, color: '#EC4899', route: '/ai-agent/intelligence/sentiment' },
      { id: 'emotion-detection', name: 'Emotion Detection', description: 'Analyze customer emotions', icon: Lightbulb, color: '#F59E0B', route: '/ai-agent/intelligence/emotion' },
      { id: 'csat-analyzer', name: 'CSAT Analyzer', description: 'Customer satisfaction analysis', icon: Target, color: '#14B8A6', route: '/ai-agent/intelligence/csat' },
      { id: 'anomaly-detector', name: 'Anomaly Detector', description: 'Fraud, security, risk detection', icon: AlertTriangle, color: '#EF4444', route: '/ai-agent/intelligence/anomaly' },
      { id: 'fraud-detector', name: 'Fraud Detector', description: 'Detect fraudulent activities', icon: Shield, color: '#F97316', route: '/ai-agent/intelligence/fraud' },
      { id: 'security-analyzer', name: 'Security Analyzer', description: 'Identify security threats', icon: Shield, color: '#6366F1', route: '/ai-agent/intelligence/security' },
      { id: 'risk-analyzer', name: 'Risk Analyzer', description: 'Analyze operational risks', icon: AlertTriangle, color: '#F59E0B', route: '/ai-agent/intelligence/risk' },
      { id: 'market-intelligence', name: 'Market Intelligence', description: 'Competitive analysis', icon: Binoculars, color: '#8B5CF6', route: '/ai-agent/intelligence/market' },
    ],
    features: [
      'Predictive Analytics',
      'Sentiment Analysis',
      'Anomaly Detection',
      'Trend Forecasting',
      'Risk Assessment',
      'Competitive Intelligence',
    ],
  },
  {
    id: 'memory',
    layerNumber: 5,
    name: 'Memory',
    shortName: 'Memory',
    description: 'Remember everything, learn from past interactions, and improve over time.',
    icon: Database,
    color: layerColors.memory,
    gradient: layerGradients.memory,
    tokenUsage: 100,
    optimizedTokenUsage: 30,
    useCase: 'Remember everything, learn from past, improve over time',
    workType: 'Learning',
    flow: 'Remember',
    route: '/ai-agent/layer-memory',
    agentCount: 18,
    components: [
      { id: 'enterprise-memory', name: 'Enterprise Memory Bank', description: 'All past decisions and outcomes', icon: Database, color: '#10B981', route: '/ai-agent/memory/enterprise' },
      { id: 'decision-memory', name: 'Decision Memory', description: 'Store and recall decisions', icon: FileText, color: '#3B82F6', route: '/ai-agent/memory/decisions' },
      { id: 'outcome-memory', name: 'Outcome Memory', description: 'Track decision outcomes', icon: TrendingUp, color: '#14B8A6', route: '/ai-agent/memory/outcomes' },
      { id: 'agent-learning', name: 'Agent Learning Memory', description: 'What worked/didnt work', icon: Brain, color: '#8B5CF6', route: '/ai-agent/memory/agent-learning' },
      { id: 'success-patterns', name: 'Success Patterns', description: 'Learn from successes', icon: CheckCircle, color: '#10B981', route: '/ai-agent/memory/success' },
      { id: 'failure-patterns', name: 'Failure Patterns', description: 'Learn from failures', icon: AlertTriangle, color: '#EF4444', route: '/ai-agent/memory/failure' },
      { id: 'customer-history', name: 'Customer Interaction History', description: 'Every customer touchpoint', icon: Users, color: '#EC4899', route: '/ai-agent/memory/customer' },
      { id: 'interaction-log', name: 'Interaction Log', description: 'Complete interaction records', icon: MessageSquare, color: '#F59E0B', route: '/ai-agent/memory/interactions' },
      { id: 'preference-store', name: 'Preference Store', description: 'Customer preferences', icon: Settings, color: '#06B6D4', route: '/ai-agent/memory/preferences' },
      { id: 'process-memory', name: 'Business Process Memory', description: 'Workflow patterns', icon: Workflow, color: '#6366F1', route: '/ai-agent/memory/process' },
      { id: 'workflow-patterns', name: 'Workflow Patterns', description: 'Optimized workflow templates', icon: Layers, color: '#8B5CF6', route: '/ai-agent/memory/workflows' },
      { id: 'context-store', name: 'Context Store', description: 'Session and context data', icon: Database, color: '#F97316', route: '/ai-agent/memory/context' },
    ],
    features: [
      'Long-term Memory',
      'Learning from History',
      'Pattern Recognition',
      'Customer Insights',
      'Process Optimization',
      'Context Retention',
    ],
  },
  {
    id: 'translation',
    layerNumber: 6,
    name: 'Translation',
    shortName: 'Translation',
    description: 'Bridge between business language and AI, filtering and routing requests.',
    icon: Globe,
    color: layerColors.translation,
    gradient: layerGradients.translation,
    tokenUsage: 50,
    optimizedTokenUsage: 15,
    useCase: 'Convert business language to AI, filter requests',
    workType: 'Communication',
    flow: 'Bridge',
    route: '/ai-agent/layer-translation',
    agentCount: 15,
    components: [
      { id: 'business-translator', name: 'Business → AI Translation', description: 'Convert business language to AI commands', icon: Globe, color: '#F97316', route: '/ai-agent/translation/business' },
      { id: 'natural-language', name: 'Natural Language Processor', description: 'Understand human language', icon: MessageSquare, color: '#EC4899', route: '/ai-agent/translation/nlp' },
      { id: 'intent-detector', name: 'Intent Detector', description: 'Identify user intent', icon: Search, color: '#06B6D4', route: '/ai-agent/translation/intent' },
      { id: 'request-filter', name: 'Request Filtering & Routing', description: 'Filter and route requests', icon: Workflow, color: '#3B82F6', route: '/ai-agent/translation/filter' },
      { id: 'priority-router', name: 'Priority Router', description: 'Route by priority', icon: Zap, color: '#F59E0B', route: '/ai-agent/translation/priority' },
      { id: 'department-router', name: 'Department Router', description: 'Route to correct department', icon: Layers, color: '#14B8A6', route: '/ai-agent/translation/department' },
      { id: 'cross-layer', name: 'Cross-Layer Coordination', description: 'Coordinate between layers', icon: Network, color: '#8B5CF6', route: '/ai-agent/translation/cross-layer' },
      { id: 'context-bridge', name: 'Context Bridge', description: 'Pass context between layers', icon: Database, color: '#10B981', route: '/ai-agent/translation/context' },
      { id: 'language-normalizer', name: 'Language Normalizer', description: 'Standardize input formats', icon: Globe, color: '#6366F1', route: '/ai-agent/translation/normalize' },
    ],
    features: [
      'Natural Language Understanding',
      'Intent Recognition',
      'Request Routing',
      'Priority Management',
      'Cross-Layer Coordination',
      'Language Normalization',
    ],
  },
  {
    id: 'command',
    layerNumber: 7,
    name: 'Command',
    shortName: 'Command',
    description: 'Orchestrate, control, and coordinate all AI operations across the platform.',
    icon: Command,
    color: layerColors.command,
    gradient: layerGradients.command,
    tokenUsage: 300,
    optimizedTokenUsage: 80,
    useCase: 'Orchestrate, control, coordinate all AI operations',
    workType: 'Control',
    flow: 'Orchestrate',
    route: '/ai-agent/layer-command',
    agentCount: 22,
    components: [
      { id: 'cdoo', name: 'CDOO', description: 'Chief Digital & Operations Officer', icon: Command, color: '#EF4444', route: '/ai-agent/command/cdoo' },
      { id: 'ddo', name: 'DDO', description: 'Digital Deployment Officer', icon: Zap, color: '#F59E0B', route: '/ai-agent/command/ddo' },
      { id: 'wol', name: 'WOL', description: 'Workforce Optimization Lead', icon: Users, color: '#3B82F6', route: '/ai-agent/command/wol' },
      { id: 'aod', name: 'AOD', description: 'Automation Operations Director', icon: Settings, color: '#8B5CF6', route: '/ai-agent/command/aod' },
      { id: 'pred', name: 'PRED', description: 'Prediction & Resource Director', icon: TrendingUp, color: '#06B6D4', route: '/ai-agent/command/pred' },
      { id: 'swarm', name: 'SWARM', description: 'Swarm Coordination System', icon: Network, color: '#10B981', route: '/ai-agent/command/swarm' },
      { id: 'orchestrator', name: 'Orchestrator', description: 'Main workflow orchestrator', icon: Workflow, color: '#EC4899', route: '/ai-agent/command/orchestrator' },
      { id: 'task-scheduler', name: 'Task Scheduler', description: 'Schedule and allocate tasks', icon: Zap, color: '#F97316', route: '/ai-agent/command/scheduler' },
      { id: 'resource-allocator', name: 'Resource Allocator', description: 'Allocate AI resources', icon: Layers, color: '#14B8A6', route: '/ai-agent/command/resource' },
      { id: 'load-balancer', name: 'Load Balancer', description: 'Balance workload across agents', icon: Gauge, color: '#6366F1', route: '/ai-agent/command/load-balancer' },
      { id: 'health-monitor', name: 'Health Monitor', description: 'Monitor agent health', icon: AlertTriangle, color: '#EF4444', route: '/ai-agent/command/health' },
      { id: 'failover-controller', name: 'Failover Controller', description: 'Handle agent failures', icon: Shield, color: '#10B981', route: '/ai-agent/command/failover' },
    ],
    features: [
      'Workflow Orchestration',
      'Resource Management',
      'Task Scheduling',
      'Load Balancing',
      'Health Monitoring',
      'Failover Control',
    ],
  },
  {
    id: 'enterprise',
    layerNumber: 8,
    name: 'Enterprise',
    shortName: 'Enterprise',
    description: 'Enterprise operations, automation, and cross-department workflows.',
    icon: Building2,
    color: layerColors.enterprise,
    gradient: layerGradients.enterprise,
    tokenUsage: 400,
    optimizedTokenUsage: 100,
    useCase: 'Enterprise operations, automation, cross-department workflows',
    workType: 'Operations',
    flow: 'Automate',
    route: '/ai-agent/layer-enterprise',
    agentCount: 45,
    components: [
      { id: 'executive-decision', name: 'Executive Decision System', description: 'Board-level recommendations', icon: Crown, color: '#F59E0B', route: '/ai-agent/enterprise/executive-decision' },
      { id: 'risk-matrix', name: 'Risk Assessment Matrix', description: 'Enterprise-wide risk analysis', icon: AlertTriangle, color: '#EF4444', route: '/ai-agent/enterprise/risk-matrix' },
      { id: 'opportunity-scanner', name: 'Opportunity Scanner', description: 'Market opportunity identification', icon: Search, color: '#14B8A6', route: '/ai-agent/enterprise/opportunity' },
      { id: 'investment-prioritizer', name: 'Investment Prioritizer', description: 'Capital allocation AI', icon: TrendingUp, color: '#10B981', route: '/ai-agent/enterprise/investment' },
      { id: 'work-orchestration', name: 'Work Orchestration Engine', description: '22 departments synchronized', icon: Workflow, color: '#6366F1', route: '/ai-agent/enterprise/work-orchestration' },
      { id: 'resource-optimizer', name: 'Resource Allocation Optimizer', description: 'AI-powered staffing', icon: Users, color: '#3B82F6', route: '/ai-agent/enterprise/resource' },
      { id: 'portfolio-manager', name: 'Project Portfolio Manager', description: 'Enterprise project tracking', icon: Layers, color: '#8B5CF6', route: '/ai-agent/enterprise/portfolio' },
      { id: 'sla-monitor', name: 'SLA Compliance Monitor', description: 'Guarantee fulfillment AI', icon: CheckCircle, color: '#10B981', route: '/ai-agent/enterprise/sla' },
      { id: 'bi-hub', name: 'Business Intelligence Hub', description: 'Real-time enterprise metrics', icon: BarChart3, color: '#06B6D4', route: '/ai-agent/enterprise/bi' },
      { id: 'kpi-dashboard', name: 'KPI Dashboard Engine', description: 'Real-time metrics', icon: Gauge, color: '#EC4899', route: '/ai-agent/enterprise/kpi' },
      { id: 'customer-value', name: 'Customer Value Predictor', description: 'LTV & churn prediction', icon: Users, color: '#F97316', route: '/ai-agent/enterprise/customer-value' },
      { id: 'competitive-intel', name: 'Competitive Intelligence', description: 'Market position analyzer', icon: Binoculars, color: '#F59E0B', route: '/ai-agent/enterprise/competitive' },
      { id: 'process-automation', name: 'Process Automation Core', description: 'Full business cycle automation', icon: Zap, color: '#14B8A6', route: '/ai-agent/enterprise/process' },
      { id: 'e2e-manager', name: 'End-to-End Process Manager', description: 'Full business cycle', icon: Workflow, color: '#6366F1', route: '/ai-agent/enterprise/e2e' },
      { id: 'approval-chain', name: 'Approval Chain AI', description: 'Intelligent routing & authorization', icon: CheckCircle, color: '#10B981', route: '/ai-agent/enterprise/approval' },
      { id: 'exception-handler', name: 'Exception Handler', description: 'Auto-resolve workflow issues', icon: AlertTriangle, color: '#EF4444', route: '/ai-agent/enterprise/exception' },
      { id: 'compliance-guard', name: 'Compliance Guard', description: 'Real-time policy enforcement', icon: Shield, color: '#8B5CF6', route: '/ai-agent/enterprise/compliance' },
      { id: 'strategic-planning', name: 'Strategic Planning AI', description: 'Long-term planning', icon: Target, color: '#F59E0B', route: '/ai-agent/enterprise/strategic' },
      { id: 'scenario-modeler', name: '5-Year Scenario Modeler', description: 'Long-term planning simulations', icon: Microscope, color: '#8B5CF6', route: '/ai-agent/enterprise/scenario' },
      { id: 'ma-analyzer', name: 'M&A Target Analyzer', description: 'Acquisition evaluation', icon: Search, color: '#3B82F6', route: '/ai-agent/enterprise/ma' },
      { id: 'market-entry', name: 'Market Entry Strategist', description: 'New market launch planning', icon: Globe, color: '#F97316', route: '/ai-agent/enterprise/market-entry' },
      { id: 'crisis-planner', name: 'Crisis Response Planner', description: 'Contingency playbooks', icon: AlertTriangle, color: '#EF4444', route: '/ai-agent/enterprise/crisis' },
    ],
    features: [
      'Cross-Department Workflows',
      'Enterprise Automation',
      'SLA Management',
      'Business Intelligence',
      'Process Optimization',
      'Strategic Planning',
    ],
  },
  {
    id: 'execution',
    layerNumber: 9,
    name: 'Execution',
    shortName: 'Execution',
    description: 'Execute business functions across 22 departments for day-to-day operations.',
    icon: Zap,
    color: layerColors.execution,
    gradient: layerGradients.execution,
    tokenUsage: 800,
    optimizedTokenUsage: 200,
    useCase: 'Execute business functions',
    workType: 'Operations',
    flow: 'Execute',
    route: '/ai-agent/layer-execution',
    agentCount: 220,
    components: [
      { id: 'customer-experience', name: 'Customer Experience', description: 'Support, success, CX', icon: Users, color: '#EC4899', route: '/ai-agent/customer' },
      { id: 'sales', name: 'Sales', description: 'Sales and revenue generation', icon: TrendingUp, color: '#10B981', route: '/ai-agent/sales' },
      { id: 'marketing', name: 'Marketing', description: 'Marketing and growth', icon: Target, color: '#F59E0B', route: '/ai-agent/marketing' },
      { id: 'finance', name: 'Finance', description: 'Financial operations', icon: TrendingUp, color: '#3B82F6', route: '/ai-agent/accounting' },
      { id: 'technology', name: 'Technology', description: 'Tech and engineering', icon: Brain, color: '#6366F1', route: '/ai-agent/it' },
      { id: 'operations', name: 'Operations', description: 'Operations management', icon: Settings, color: '#8B5CF6', route: '/ai-agent/operations' },
      { id: 'hr', name: 'Human Resources', description: 'HR and talent', icon: Users, color: '#9C27B0', route: '/ai-agent/hr' },
      { id: 'legal', name: 'Legal & Compliance', description: 'Legal and compliance', icon: Scale, color: '#3F51B5', route: '/ai-agent/legal' },
      { id: 'data-intelligence', name: 'Data & Intelligence', description: 'Data and analytics', icon: BarChart3, color: '#06B6D4', route: '/ai-agent/data' },
      { id: 'product', name: 'Product', description: 'Product development', icon: Zap, color: '#E91E63', route: '/ai-agent/product' },
      { id: 'security', name: 'Security', description: 'Security and risk', icon: Shield, color: '#F44336', route: '/ai-agent/security' },
      { id: 'research', name: 'Research & Innovation', description: 'R&D and innovation', icon: Lightbulb, color: '#FF9800', route: '/ai-agent/research' },
      { id: 'trading', name: 'Trading & Investments', description: 'Trading operations', icon: TrendingUp, color: '#10B981', route: '/ai-agent/trading' },
      { id: 'realestate', name: 'Real Estate', description: 'Property management', icon: Building2, color: '#795548', route: '/ai-agent/real-estate' },
      { id: 'insurance', name: 'Insurance', description: 'Insurance operations', icon: Shield, color: '#607D8B', route: '/ai-agent/insurance' },
      { id: 'healthcare', name: 'Healthcare', description: 'Medical services', icon: Shield, color: '#4CAF50', route: '/ai-agent/healthcare' },
      { id: 'manufacturing', name: 'Manufacturing', description: 'Production operations', icon: Factory as any, color: '#9E9E9E', route: '/ai-agent/manufacturing' },
      { id: 'transportation', name: 'Transportation', description: 'Logistics', icon: Layers, color: '#00BCD4', route: '/ai-agent/transportation' },
      { id: 'government', name: 'Government', description: 'Public sector', icon: Building2, color: '#455A64', route: '/ai-agent/government' },
      { id: 'supplychain', name: 'Supply Chain', description: 'Supply chain management', icon: Layers, color: '#FF5722', route: '/ai-agent/supply-chain' },
      { id: 'administrative', name: 'Administrative', description: 'Support services', icon: Settings, color: '#795548', route: '/ai-agent/admin' },
      { id: 'analytics', name: 'Customer Insights', description: 'Analytics', icon: BarChart3, color: '#9C27B0', route: '/ai-agent/analytics' },
    ],
    features: [
      'Department-Specific Tasks',
      'Day-to-Day Operations',
      'Cross-Functional Coordination',
      'Process Execution',
      'Service Delivery',
      'Performance Tracking',
    ],
  },
  {
    id: 'workforce',
    layerNumber: 10,
    name: 'Workforce',
    shortName: 'Workforce',
    description: '1108+ AI Agents handling task execution with 24/7 productivity.',
    icon: Users,
    color: layerColors.workforce,
    gradient: layerGradients.workforce,
    tokenUsage: 800,
    optimizedTokenUsage: 200,
    useCase: '24/7 productivity, handle all tasks',
    workType: 'Execution',
    flow: 'Do tasks',
    route: '/ai-agent/layer-workforce',
    agentCount: 1108,
    components: [
      { id: 'reactive-agents', name: 'Reactive Agents', description: 'Respond to specific triggers', icon: Bot, color: '#14B8A6', route: '/ai-agent/workforce/reactive' },
      { id: 'learning-agents', name: 'Learning Agents', description: 'Improve from feedback', icon: Brain, color: '#8B5CF6', route: '/ai-agent/workforce/learning' },
      { id: 'swarm-agents', name: 'Swarm Agents', description: 'Collaborative task handling', icon: Network, color: '#06B6D4', route: '/ai-agent/workforce/swarm' },
      { id: 'specialist-agents', name: 'Specialist Agents', description: 'Domain-specific experts', icon: Lightbulb, color: '#F59E0B', route: '/ai-agent/workforce/specialist' },
      { id: 'general-agents', name: 'General Agents', description: 'Multi-purpose agents', icon: Bot, color: '#3B82F6', route: '/ai-agent/workforce/general' },
      { id: 'assistant-agents', name: 'Assistant Agents', description: 'Helpdesk and support', icon: Users, color: '#EC4899', route: '/ai-agent/workforce/assistant' },
      { id: 'automation-agents', name: 'Automation Agents', description: 'Process automation', icon: Zap, color: '#10B981', route: '/ai-agent/workforce/automation' },
      { id: 'analysis-agents', name: 'Analysis Agents', description: 'Data analysis', icon: BarChart3, color: '#6366F1', route: '/ai-agent/workforce/analysis' },
    ],
    features: [
      '1108+ Specialized Agents',
      '24/7 Availability',
      'Task Distribution',
      'Performance Optimization',
      'Continuous Learning',
      'Scalable Execution',
    ],
  },
  {
    id: 'review',
    layerNumber: 11,
    name: 'Review',
    shortName: 'Review',
    description: 'Review AI work, analyze performance, and display results to leadership and users.',
    icon: BarChart3,
    color: layerColors.review,
    gradient: layerGradients.review,
    tokenUsage: 200,
    optimizedTokenUsage: 50,
    useCase: 'Review AI agents work → Show results to leadership, users, customers',
    workType: 'Feedback',
    flow: 'Review & show',
    route: '/ai-agent/layer-review',
    agentCount: 28,
    components: [
      { id: 'performance-review', name: 'Performance Review Engine', description: 'Analyze AI work', icon: Gauge, color: '#84CC16', route: '/ai-agent/review/performance' },
      { id: 'kpi-analysis', name: 'KPI Analysis Dashboard', description: 'Track KPIs', icon: BarChart3, color: '#10B981', route: '/ai-agent/review/kpi' },
      { id: 'success-analyzer', name: 'Success/Failure Analyzer', description: 'Analyze outcomes', icon: CheckCircle, color: '#14B8A6', route: '/ai-agent/review/success' },
      { id: 'failure-analyzer', name: 'Failure Analysis', description: 'Analyze failures', icon: AlertTriangle, color: '#EF4444', route: '/ai-agent/review/failure' },
      { id: 'executive-reporting', name: 'Executive Reporting', description: 'Board-level reports', icon: FileText, color: '#F59E0B', route: '/ai-agent/review/executive' },
      { id: 'dashboard-viz', name: 'Dashboard Visualization', description: 'Charts and graphs', icon: BarChart3, color: '#3B82F6', route: '/ai-agent/review/dashboard' },
      { id: 'real-time-alerts', name: 'Real-Time Alerts', description: 'Live notifications', icon: AlertTriangle, color: '#F97316', route: '/ai-agent/review/alerts' },
      { id: 'interactive-reports', name: 'Interactive Reports', description: 'Drill-down analysis', icon: Search, color: '#8B5CF6', route: '/ai-agent/review/interactive' },
      { id: 'user-portal', name: 'Customer/User Portal', description: 'User access', icon: Users, color: '#EC4899', route: '/ai-agent/review/portal' },
      { id: 'trend-analysis', name: 'Trend Analysis', description: 'Track trends over time', icon: TrendingUp, color: '#06B6D4', route: '/ai-agent/review/trends' },
      { id: 'comparison-reports', name: 'Comparison Reports', description: 'Compare performance', icon: Layers, color: '#6366F1', route: '/ai-agent/review/comparison' },
      { id: 'export-tools', name: 'Export Tools', description: 'Export reports', icon: FileText, color: '#10B981', route: '/ai-agent/review/export' },
    ],
    features: [
      'Performance Analytics',
      'KPI Tracking',
      'Real-Time Alerts',
      'Executive Dashboards',
      'Interactive Reports',
      'User Portal Access',
    ],
  },
];

export const getLayerById = (id: LayerId): AILayer | undefined => {
  return aiAgentLayers.find(layer => layer.id === id);
};

export const getLayerByNumber = (layerNumber: number): AILayer | undefined => {
  return aiAgentLayers.find(layer => layer.layerNumber === layerNumber);
};

export const LAYER_STATS = {
  totalLayers: 11,
  totalAgents: 1608,
  totalTokenUsage: 1025, // Optimized (default)
  standardTokenUsage: 3950, // Standard (for high-stakes decisions)
  costPerRequest: '$0.009', // Optimized (default)
  standardCostPerRequest: '$0.04', // Standard (for high-stakes decisions)
  efficiencyGain: '74%', // Optimized vs Normal Agent
};

// Mode Selection Guide
export const MODE_SELECTION = {
  optimized: {
    useCase: 'Routine Operations',
    description: 'Cost-effective, still 99% accurate',
    tokenUsage: 1025,
    costPerRequest: '$0.009',
  },
  standard: {
    useCase: 'High-Stakes Decisions, Regulated Industries',
    description: 'Maximum accuracy, compliance required',
    tokenUsage: 3950,
    costPerRequest: '$0.04',
  },
  normalAgent: {
    useCase: 'Simple Tasks',
    description: 'Overkill for KAYTX - use single agent',
    tokenUsage: 3000,
    costPerRequest: '$0.03',
  },
};

export const layerFlowOrder: LayerId[] = [
  'governance',
  'leadership',
  'simulation',
  'intelligence',
  'memory',
  'translation',
  'command',
  'enterprise',
  'execution',
  'workforce',
  'review',
];
