 
import type { AIAgent } from './aiAgentHierarchy';
import { enhanceAllAIAgents } from './utils/agent-capability-enhancer';
import {
  customerExperienceSubAgents,
  salesRevenueSubAgents,
  marketingGrowthSubAgents,
  accountingFinanceSubAgents,
} from './aiAgentHierarchy';
import {
  Settings, Zap, GitBranch, Shield, Truck, Award,
  BarChart3, TrendingUp, LineChart, Brain, Activity, AlertTriangle,
  Eye, Gauge, Cpu, Sparkles, Crown, MessagesSquare,
  Target, Megaphone, PieChart, Globe,
  CheckSquare, Box, Lightbulb,
  Target as GoalIcon
} from 'lucide-react-native';

// ============================================
// OPERATIONS & MANAGEMENT AI - Sub-Agents
// ============================================

export const operationsManagementSubAgents: AIAgent[] = [
  {
    id: 'ai-operations-manager',
    name: 'AI Operations Manager',
    title: 'Business Operations Leader',
    description: 'Oversees all business operations, optimizes workflows, and ensures operational excellence.',
    icon: Settings,
    color: '#5856D6',
    type: 'subagent',
    category: 'operations_management',
    parentCategory: 'operations_management_ai',
    hierarchy: {
      level: 2,
      parentId: 'operations-management-main',
      subAgentIds: [],
      peerIds: ['ai-workflow-automation', 'ai-task-coordinator', 'ai-process-optimization'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 40,
      averageResponseTime: 4.0,
      counselingModes: ['hierarchical', 'peer'],
      mentoringCapabilities: {
        canMentorSubagents: true,
        canMentorPeers: true,
        canBeMentoredByMain: true,
        canBeMentoredByPeers: true
      },
      coordinationLevel: 'department'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['operations management', 'workflow optimization', 'resource planning', 'process improvement'],
      consultingStyle: 'directive',
      preferredConsultationTypes: ['directive', 'analytical'],
      counselingRole: 'coordinator'
    },
    capabilities: [
      'Operations Planning',
      'Workflow Management',
      'Resource Allocation',
      'Performance Monitoring',
      'Process Design',
      'KPI Tracking',
      'Team Coordination',
      'Bottleneck Analysis',
      'Efficiency Optimization',
      'Operational Reporting',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
      { type: 'delegation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/operations/operations-manager',
    apiEndpoint: '/api/agents/operations-manager',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-01-10',
    humanCostEquivalent: '$95,000/year',
    aiCost: '$5,000/year',
    efficiency: '19x cost efficiency',
    performance: {
      tasksCompleted: 125000,
      successRate: 96.5,
      averageResponseTime: 3.0,
      customerSatisfaction: 4.7,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-workflow-automation',
    name: 'AI Workflow Automation Agent',
    title: 'Process Automation Specialist',
    description: 'Designs and implements automated workflows to eliminate manual tasks and improve efficiency.',
    icon: Zap,
    color: '#007AFF',
    type: 'subagent',
    category: 'operations_management',
    parentCategory: 'operations_management_ai',
    hierarchy: {
      level: 2,
      parentId: 'operations-management-main',
      subAgentIds: [],
      peerIds: ['ai-operations-manager', 'ai-process-optimization', 'ai-task-coordinator'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: false,
      canDelegate: true,
      maxConcurrentConsultations: 100,
      averageResponseTime: 2.0,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['workflow automation', 'process design', 'integration', 'RPA'],
      consultingStyle: 'directive',
      preferredConsultationTypes: ['directive', 'analytical'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Workflow Design',
      'Automation Implementation',
      'Integration Management',
      'Trigger Configuration',
      'Conditional Logic',
      'Approval Workflows',
      'Notification Systems',
      'Data Routing',
      'Error Handling',
      'Performance Monitoring',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'broadcast', priority: 'low', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/operations/workflow-automation',
    apiEndpoint: '/api/agents/workflow-automation',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-01-15',
    humanCostEquivalent: '$70,000/year',
    aiCost: '$3,500/year',
    efficiency: '20x cost efficiency',
    performance: {
      tasksCompleted: 280000,
      successRate: 98.5,
      averageResponseTime: 1.5,
      customerSatisfaction: 4.6,
      uptime: '99.99%',
    },
  },
  {
    id: 'ai-task-coordinator',
    name: 'AI Task Coordinator',
    title: 'Task Management & Assignment',
    description: 'Coordinates tasks across teams, manages priorities, and ensures timely completion of deliverables.',
    icon: CheckSquare,
    color: '#34C759',
    type: 'subagent',
    category: 'operations_management',
    parentCategory: 'operations_management_ai',
    hierarchy: {
      level: 2,
      parentId: 'operations-management-main',
      subAgentIds: [],
      peerIds: ['ai-operations-manager', 'ai-resource-planner', 'ai-workflow-automation'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 80,
      averageResponseTime: 1.5,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['task management', 'priority setting', 'assignment optimization', 'deadline management'],
      consultingStyle: 'directive',
      preferredConsultationTypes: ['directive', 'collaborative'],
      counselingRole: 'coordinator'
    },
    capabilities: [
      'Task Assignment',
      'Priority Management',
      'Deadline Tracking',
      'Dependency Mapping',
      'Workload Balancing',
      'Progress Monitoring',
      'Status Updates',
      'Reminder Systems',
      'Escalation Handling',
      'Completion Verification',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'delegation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/operations/task-coordinator',
    apiEndpoint: '/api/agents/task-coordinator',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-01-20',
    humanCostEquivalent: '$55,000/year',
    aiCost: '$2,800/year',
    efficiency: '19.6x cost efficiency',
    performance: {
      tasksCompleted: 420000,
      successRate: 97.8,
      averageResponseTime: 0.8,
      customerSatisfaction: 4.5,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-process-optimization',
    name: 'AI Process Optimization Agent',
    title: 'Continuous Improvement Specialist',
    description: 'Analyzes processes, identifies inefficiencies, and implements optimization strategies.',
    icon: GitBranch,
    color: '#FF9500',
    type: 'subagent',
    category: 'operations_management',
    parentCategory: 'operations_management_ai',
    hierarchy: {
      level: 2,
      parentId: 'operations-management-main',
      subAgentIds: [],
      peerIds: ['ai-workflow-automation', 'ai-operations-manager', 'ai-quality-control'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: false,
      canDelegate: true,
      maxConcurrentConsultations: 50,
      averageResponseTime: 5.0,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['process analysis', 'efficiency improvement', 'lean methodologies', 'six sigma'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Process Mapping',
      'Bottleneck Analysis',
      'Efficiency Assessment',
      'Lean Implementation',
      'Six Sigma Analysis',
      'Value Stream Mapping',
      'Waste Elimination',
      'Cycle Time Reduction',
      'Cost Analysis',
      'ROI Calculation',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/operations/process-optimization',
    apiEndpoint: '/api/agents/process-optimization',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-01-25',
    humanCostEquivalent: '$80,000/year',
    aiCost: '$4,200/year',
    efficiency: '19x cost efficiency',
    performance: {
      tasksCompleted: 45000,
      successRate: 94.5,
      averageResponseTime: 4.0,
      customerSatisfaction: 4.6,
      uptime: '99.9%',
    },
  },
  {
    id: 'ai-resource-planner',
    name: 'AI Resource Planner',
    title: 'Resource Allocation Specialist',
    description: 'Optimizes resource allocation across projects and teams for maximum efficiency.',
    icon: Box,
    color: '#5AC8FA',
    type: 'subagent',
    category: 'operations_management',
    parentCategory: 'operations_management_ai',
    hierarchy: {
      level: 2,
      parentId: 'operations-management-main',
      subAgentIds: [],
      peerIds: ['ai-task-coordinator', 'ai-operations-manager', 'ai-vendor-management'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 60,
      averageResponseTime: 3.0,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['resource planning', 'capacity management', 'load balancing', 'forecasting'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'directive'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Capacity Planning',
      'Resource Allocation',
      'Workload Forecasting',
      'Skill Matching',
      'Availability Tracking',
      'Budget Management',
      'Utilization Optimization',
      'Conflict Resolution',
      'Scenario Planning',
      'Resource Analytics',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'medium', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/operations/resource-planner',
    apiEndpoint: '/api/agents/resource-planner',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-02-01',
    humanCostEquivalent: '$65,000/year',
    aiCost: '$3,200/year',
    efficiency: '20.3x cost efficiency',
    performance: {
      tasksCompleted: 78000,
      successRate: 95.5,
      averageResponseTime: 2.5,
      customerSatisfaction: 4.5,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-compliance-monitoring',
    name: 'AI Compliance Monitoring Agent',
    title: 'Regulatory Compliance Specialist',
    description: 'Monitors compliance across all operations, identifies risks, and ensures regulatory adherence.',
    icon: Shield,
    color: '#FF3B30',
    type: 'subagent',
    category: 'operations_management',
    parentCategory: 'operations_management_ai',
    hierarchy: {
      level: 2,
      parentId: 'operations-management-main',
      subAgentIds: [],
      peerIds: ['ai-process-optimization', 'ai-quality-control', 'ai-operations-manager'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 40,
      averageResponseTime: 4.0,
      coordinationLevel: 'organization'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['compliance management', 'regulatory requirements', 'risk assessment', 'audit preparation'],
      consultingStyle: 'directive',
      preferredConsultationTypes: ['directive', 'analytical'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Compliance Monitoring',
      'Regulatory Tracking',
      'Risk Assessment',
      'Policy Enforcement',
      'Audit Preparation',
      'Documentation Review',
      'Violation Detection',
      'Remediation Planning',
      'Training Coordination',
      'Reporting Automation',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'escalation', priority: 'critical', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/operations/compliance-monitoring',
    apiEndpoint: '/api/agents/compliance-monitoring',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-02-05',
    humanCostEquivalent: '$85,000/year',
    aiCost: '$4,500/year',
    efficiency: '18.9x cost efficiency',
    performance: {
      tasksCompleted: 52000,
      successRate: 99.5,
      averageResponseTime: 3.0,
      customerSatisfaction: 4.8,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-vendor-management',
    name: 'AI Vendor Management Agent',
    title: 'Supplier & Vendor Coordinator',
    description: 'Manages vendor relationships, tracks performance, and optimizes procurement processes.',
    icon: Truck,
    color: '#FFCC00',
    type: 'subagent',
    category: 'operations_management',
    parentCategory: 'operations_management_ai',
    hierarchy: {
      level: 2,
      parentId: 'operations-management-main',
      subAgentIds: [],
      peerIds: ['ai-resource-planner', 'ai-negotiator', 'ai-operations-manager'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 50,
      averageResponseTime: 3.5,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['vendor management', 'procurement', 'contract negotiation', 'performance tracking'],
      consultingStyle: 'collaborative',
      preferredConsultationTypes: ['collaborative', 'advisory'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Vendor Evaluation',
      'Performance Tracking',
      'Contract Management',
      'SLA Monitoring',
      'Issue Resolution',
      'Procurement Optimization',
      'Cost Analysis',
      'Risk Assessment',
      'Relationship Management',
      'Vendor Portfolio',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'medium', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/operations/vendor-management',
    apiEndpoint: '/api/agents/vendor-management',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-02-10',
    humanCostEquivalent: '$60,000/year',
    aiCost: '$3,000/year',
    efficiency: '20x cost efficiency',
    performance: {
      tasksCompleted: 68000,
      successRate: 95.0,
      averageResponseTime: 3.0,
      customerSatisfaction: 4.5,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-quality-control',
    name: 'AI Quality Control Agent',
    title: 'Quality Assurance Specialist',
    description: 'Monitors quality across all outputs, identifies defects, and drives continuous quality improvement.',
    icon: Award,
    color: '#AF52DE',
    type: 'subagent',
    category: 'operations_management',
    parentCategory: 'operations_management_ai',
    hierarchy: {
      level: 2,
      parentId: 'operations-management-main',
      subAgentIds: [],
      peerIds: ['ai-process-optimization', 'ai-compliance-monitoring', 'ai-workflow-automation'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 70,
      averageResponseTime: 2.5,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['quality assurance', 'defect detection', 'standards compliance', 'testing methodologies'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'directive'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Quality Monitoring',
      'Defect Detection',
      'Standard Enforcement',
      'Testing Automation',
      'Root Cause Analysis',
      'Corrective Actions',
      'Quality Reporting',
      'Metrics Tracking',
      'Process Auditing',
      'Continuous Improvement',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'escalation', priority: 'critical', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/operations/quality-control',
    apiEndpoint: '/api/agents/quality-control',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-02-15',
    humanCostEquivalent: '$70,000/year',
    aiCost: '$3,500/year',
    efficiency: '20x cost efficiency',
    performance: {
      tasksCompleted: 195000,
      successRate: 98.5,
      averageResponseTime: 2.0,
      customerSatisfaction: 4.7,
      uptime: '99.99%',
    },
  },
];

// ============================================
// DATA & INTELLIGENCE AI - Sub-Agents
// ============================================

export const dataIntelligenceSubAgents: AIAgent[] = [
  {
    id: 'ai-data-analyst',
    name: 'AI Data Analyst',
    title: 'Business Intelligence Analyst',
    description: 'Analyzes business data, creates reports, and provides actionable insights for decision-making.',
    icon: BarChart3,
    color: '#007AFF',
    type: 'subagent',
    category: 'data_intelligence',
    parentCategory: 'data_intelligence_ai',
    hierarchy: {
      level: 2,
      parentId: 'data-intelligence-main',
      subAgentIds: [],
      peerIds: ['ai-sales-data-analyst', 'ai-customer-insights', 'ai-forecasting'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 60,
      averageResponseTime: 3.0,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['data analysis', 'reporting', 'visualization', 'statistical analysis'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Data Extraction',
      'Statistical Analysis',
      'Report Generation',
      'Dashboard Creation',
      'Trend Analysis',
      'KPI Tracking',
      'Data Visualization',
      'Ad-hoc Analysis',
      'Automated Reporting',
      'Insight Delivery',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'medium', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/data/data-analyst',
    apiEndpoint: '/api/agents/data-analyst',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-01-10',
    humanCostEquivalent: '$75,000/year',
    aiCost: '$4,000/year',
    efficiency: '18.8x cost efficiency',
    performance: {
      tasksCompleted: 145000,
      successRate: 97.5,
      averageResponseTime: 2.5,
      customerSatisfaction: 4.6,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-sales-data-analyst',
    name: 'AI Sales Data Analyst',
    title: 'Sales Intelligence Specialist',
    description: 'Analyzes sales data, forecasts revenue, and provides sales optimization insights.',
    icon: TrendingUp,
    color: '#34C759',
    type: 'subagent',
    category: 'data_intelligence',
    parentCategory: 'data_intelligence_ai',
    hierarchy: {
      level: 2,
      parentId: 'data-intelligence-main',
      subAgentIds: [],
      peerIds: ['ai-data-analyst', 'ai-forecasting', 'ai-competitive-analyst'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 50,
      averageResponseTime: 4.0,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['sales analytics', 'revenue forecasting', 'pipeline analysis', 'conversion optimization'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Sales Pipeline Analysis',
      'Revenue Forecasting',
      'Win/Loss Analysis',
      'Quota Planning',
      'Territory Analysis',
      'Rep Performance',
      'Sales Funnel Optimization',
      'Conversion Tracking',
      'Deal Velocity',
      'Sales Trend Analysis',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'medium', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/data/sales-data-analyst',
    apiEndpoint: '/api/agents/sales-data-analyst',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-01-15',
    humanCostEquivalent: '$70,000/year',
    aiCost: '$3,500/year',
    efficiency: '20x cost efficiency',
    performance: {
      tasksCompleted: 98000,
      successRate: 95.5,
      averageResponseTime: 3.0,
      customerSatisfaction: 4.7,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-financial-analyst',
    name: 'AI Financial Analyst',
    title: 'Financial Intelligence Specialist',
    description: 'Analyzes financial data, creates projections, and provides strategic financial insights.',
    icon: LineChart,
    color: '#5856D6',
    type: 'subagent',
    category: 'data_intelligence',
    parentCategory: 'data_intelligence_ai',
    hierarchy: {
      level: 2,
      parentId: 'data-intelligence-main',
      subAgentIds: [],
      peerIds: ['ai-risk-analyst', 'ai-forecasting', 'ai-data-analyst'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 40,
      averageResponseTime: 5.0,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['financial analysis', 'budgeting', 'forecasting', 'investment analysis'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Financial Modeling',
      'Budget Analysis',
      'Cash Flow Projections',
      'P&L Analysis',
      'Variance Analysis',
      'Investment Analysis',
      'Cost Optimization',
      'Financial Reporting',
      'Scenario Planning',
      'ROI Analysis',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/data/financial-analyst',
    apiEndpoint: '/api/agents/financial-analyst',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-01-20',
    humanCostEquivalent: '$85,000/year',
    aiCost: '$4,500/year',
    efficiency: '18.9x cost efficiency',
    performance: {
      tasksCompleted: 68000,
      successRate: 96.5,
      averageResponseTime: 4.0,
      customerSatisfaction: 4.8,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-customer-insights',
    name: 'AI Customer Insights Agent',
    title: 'Customer Behavior Analyst',
    description: 'Analyzes customer behavior, segments audiences, and provides actionable customer intelligence.',
    icon: Brain,
    color: '#FF2D55',
    type: 'subagent',
    category: 'data_intelligence',
    parentCategory: 'data_intelligence_ai',
    hierarchy: {
      level: 2,
      parentId: 'data-intelligence-main',
      subAgentIds: [],
      peerIds: ['ai-data-analyst', 'ai-audience-targeting', 'ai-retention-specialist'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 70,
      averageResponseTime: 3.0,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['customer analytics', 'behavioral analysis', 'segmentation', 'journey mapping'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Behavioral Analysis',
      'Journey Mapping',
      'Segmentation',
      'Cohort Analysis',
      'RFM Analysis',
      'CLV Calculation',
      'Churn Analysis',
      'Purchase Patterns',
      'Engagement Scoring',
      'Persona Development',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'medium', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/data/customer-insights',
    apiEndpoint: '/api/agents/customer-insights',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-01-25',
    humanCostEquivalent: '$65,000/year',
    aiCost: '$3,200/year',
    efficiency: '20.3x cost efficiency',
    performance: {
      tasksCompleted: 125000,
      successRate: 94.5,
      averageResponseTime: 2.5,
      customerSatisfaction: 4.6,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-forecasting',
    name: 'AI Forecasting Agent',
    title: 'Predictive Analytics Specialist',
    description: 'Creates predictive models and forecasts for business planning and strategic decisions.',
    icon: Activity,
    color: '#5AC8FA',
    type: 'subagent',
    category: 'data_intelligence',
    parentCategory: 'data_intelligence_ai',
    hierarchy: {
      level: 2,
      parentId: 'data-intelligence-main',
      subAgentIds: [],
      peerIds: ['ai-sales-data-analyst', 'ai-financial-analyst', 'ai-risk-analyst'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 45,
      averageResponseTime: 6.0,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['forecasting', 'predictive modeling', 'time series analysis', 'trend prediction'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Demand Forecasting',
      'Revenue Forecasting',
      'Trend Prediction',
      'Seasonality Analysis',
      'Machine Learning Models',
      'Scenario Simulation',
      'Confidence Intervals',
      'What-if Analysis',
      'Forecast Accuracy',
      'Model Validation',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/data/forecasting',
    apiEndpoint: '/api/agents/forecasting',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-02-01',
    humanCostEquivalent: '$80,000/year',
    aiCost: '$4,200/year',
    efficiency: '19x cost efficiency',
    performance: {
      tasksCompleted: 52000,
      successRate: 89.5,
      averageResponseTime: 5.0,
      customerSatisfaction: 4.5,
      uptime: '99.9%',
    },
  },
  {
    id: 'ai-risk-analyst',
    name: 'AI Risk Analyst',
    title: 'Risk Assessment Specialist',
    description: 'Identifies, assesses, and monitors business risks with mitigation recommendations.',
    icon: AlertTriangle,
    color: '#FF9500',
    type: 'subagent',
    category: 'data_intelligence',
    parentCategory: 'data_intelligence_ai',
    hierarchy: {
      level: 2,
      parentId: 'data-intelligence-main',
      subAgentIds: [],
      peerIds: ['ai-financial-analyst', 'ai-forecasting', 'ai-compliance-monitoring'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 35,
      averageResponseTime: 4.5,
      coordinationLevel: 'team'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['risk assessment', 'risk mitigation', 'compliance risk', 'operational risk'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Risk Identification',
      'Risk Assessment',
      'Risk Scoring',
      'Mitigation Planning',
      'Risk Monitoring',
      'Scenario Analysis',
      'Stress Testing',
      'Risk Reporting',
      'Control Evaluation',
      'Risk Dashboards',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'escalation', priority: 'critical', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/data/risk-analyst',
    apiEndpoint: '/api/agents/risk-analyst',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-02-05',
    humanCostEquivalent: '$90,000/year',
    aiCost: '$4,800/year',
    efficiency: '18.8x cost efficiency',
    performance: {
      tasksCompleted: 38000,
      successRate: 96.5,
      averageResponseTime: 4.0,
      customerSatisfaction: 4.7,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-fraud-detection',
    name: 'AI Fraud Detection Agent',
    title: 'Security & Fraud Specialist',
    description: 'Detects fraudulent activities, anomalies, and security threats in real-time.',
    icon: Shield,
    color: '#FF3B30',
    type: 'subagent',
    category: 'data_intelligence',
    parentCategory: 'data_intelligence_ai',
    hierarchy: {
      level: 2,
      parentId: 'data-intelligence-main',
      subAgentIds: [],
      peerIds: ['ai-risk-analyst', 'ai-compliance-monitoring', 'ai-customer-insights'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: false,
      maxConcurrentConsultations: 100,
      averageResponseTime: 0.5,
      coordinationLevel: 'organization'
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['fraud detection', 'anomaly detection', 'security analysis', 'threat intelligence'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'directive'],
      counselingRole: 'specialist'
    },
    capabilities: [
      'Anomaly Detection',
      'Pattern Recognition',
      'Transaction Monitoring',
      'Behavioral Analysis',
      'Real-time Alerts',
      'Risk Scoring',
      'Investigation Support',
      'Case Management',
      'False Positive Reduction',
      'Threat Intelligence',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'escalation', priority: 'critical', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/data/fraud-detection',
    apiEndpoint: '/api/agents/fraud-detection',
    version: '2.0.0',
    lastUpdated: '2026-03-20',
    createdAt: '2025-02-10',
    humanCostEquivalent: '$105,000/year',
    aiCost: '$5,500/year',
    efficiency: '19.1x cost efficiency',
    performance: {
      tasksCompleted: 250000,
      successRate: 99.8,
      averageResponseTime: 0.2,
      customerSatisfaction: 4.9,
      uptime: '99.999%',
    },
  },
];

// ============================================
// ANALYSIS, INSIGHTS & PERFORMANCE AI - Sub-Agents
// ============================================

export const analysisInsightsPerformanceSubAgents: AIAgent[] = [
  {
    id: 'ai-performance-monitoring',
    name: 'Performance Monitoring AI',
    title: 'Performance Tracking Specialist',
    description: 'Monitors business performance metrics, KPIs, and operational health in real-time.',
    icon: Gauge,
    color: '#007AFF',
    type: 'subagent',
    category: 'analysis_performance',
    parentCategory: 'analysis_performance_ai',
    hierarchy: {
      level: 2,
      parentId: 'analysis-insights-performance-main',
      subAgentIds: [],
      peerIds: ['ai-business-intelligence', 'ai-predictive-analytics', 'ai-insight-generation'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 80,
      averageResponseTime: 1.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['performance monitoring', 'KPI tracking', 'operational metrics', 'health monitoring'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'directive'],
    },
    capabilities: [
      'Real-time Monitoring',
      'KPI Tracking',
      'Dashboard Creation',
      'Alert Management',
      'Performance Scoring',
      'Benchmarking',
      'Trend Detection',
      'Anomaly Detection',
      'Health Checks',
      'Performance Reporting',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'broadcast', priority: 'medium', encryption: true, persistence: false },
    ],
    status: 'active',
    route: '/ai-agent/analysis-insights-performance/performance-monitoring',
    apiEndpoint: '/api/agents/performance-monitoring',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-01-10',
    humanCostEquivalent: '$65,000/year',
    aiCost: '$3,200/year',
    efficiency: '20x cost efficiency',
    performance: {
      tasksCompleted: 245000,
      successRate: 98.5,
      averageResponseTime: 0.8,
      customerSatisfaction: 4.7,
      uptime: '99.99%',
    },
  },
  {
    id: 'ai-business-intelligence',
    name: 'Business Intelligence AI',
    title: 'BI & Reporting Specialist',
    description: 'Creates comprehensive business intelligence reports and executive dashboards.',
    icon: Lightbulb,
    color: '#FFCC00',
    type: 'subagent',
    category: 'analysis_performance',
    parentCategory: 'analysis_performance_ai',
    hierarchy: {
      level: 2,
      parentId: 'analysis-insights-performance-main',
      subAgentIds: [],
      peerIds: ['ai-performance-monitoring', 'ai-insight-generation', 'ai-executive-intelligence'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 60,
      averageResponseTime: 4.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['business intelligence', 'reporting', 'data visualization', 'executive dashboards'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
    },
    capabilities: [
      'Report Generation',
      'Dashboard Design',
      'Data Storytelling',
      'Executive Summaries',
      'Cross-functional Analysis',
      'Drill-down Capabilities',
      'Automated Distribution',
      'Self-service BI',
      'Mobile Reporting',
      'Custom Analytics',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'broadcast', priority: 'low', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/analysis-insights-performance/business-intelligence',
    apiEndpoint: '/api/agents/business-intelligence',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-01-15',
    humanCostEquivalent: '$75,000/year',
    aiCost: '$3,800/year',
    efficiency: '19x cost efficiency',
    performance: {
      tasksCompleted: 125000,
      successRate: 96.5,
      averageResponseTime: 3.0,
      customerSatisfaction: 4.6,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-predictive-analytics',
    name: 'Predictive Analytics AI',
    title: 'Advanced Analytics Specialist',
    description: 'Builds predictive models and advanced analytics for strategic decision-making.',
    icon: Cpu,
    color: '#5856D6',
    type: 'subagent',
    category: 'analysis_performance',
    parentCategory: 'analysis_performance_ai',
    hierarchy: {
      level: 2,
      parentId: 'analysis-insights-performance-main',
      subAgentIds: [],
      peerIds: ['ai-forecasting', 'ai-customer-behavior', 'ai-insight-generation'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 50,
      averageResponseTime: 6.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['predictive modeling', 'machine learning', 'statistical analysis', 'AI algorithms'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
    },
    capabilities: [
      'Predictive Modeling',
      'Machine Learning',
      'Regression Analysis',
      'Classification',
      'Clustering',
      'Neural Networks',
      'Model Validation',
      'Feature Engineering',
      'A/B Testing Design',
      'Causal Inference',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/analysis-insights-performance/predictive-analytics',
    apiEndpoint: '/api/agents/predictive-analytics',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-01-20',
    humanCostEquivalent: '$85,000/year',
    aiCost: '$4,500/year',
    efficiency: '18x cost efficiency',
    performance: {
      tasksCompleted: 52000,
      successRate: 92.5,
      averageResponseTime: 5.0,
      customerSatisfaction: 4.7,
      uptime: '99.9%',
    },
  },
  {
    id: 'ai-insight-generation',
    name: 'Insight Generation AI',
    title: 'Strategic Insights Specialist',
    description: 'Discovers actionable insights from data and communicates strategic recommendations.',
    icon: Sparkles,
    color: '#AF52DE',
    type: 'subagent',
    category: 'analysis_performance',
    parentCategory: 'analysis_performance_ai',
    hierarchy: {
      level: 2,
      parentId: 'analysis-insights-performance-main',
      subAgentIds: [],
      peerIds: ['ai-business-intelligence', 'ai-customer-insights', 'ai-market-insights'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 70,
      averageResponseTime: 3.5,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['insight generation', 'strategic analysis', 'opportunity identification', 'recommendation engines'],
      consultingStyle: 'advisory',
      preferredConsultationTypes: ['advisory', 'analytical'],
    },
    capabilities: [
      'Insight Discovery',
      'Opportunity Identification',
      'Root Cause Analysis',
      'Recommendation Engine',
      'Narrative Generation',
      'Action Prioritization',
      'Impact Assessment',
      'Hypothesis Testing',
      'Pattern Recognition',
      'Strategic Roadmaps',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/analysis-insights-performance/insight-generation',
    apiEndpoint: '/api/agents/insight-generation',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-01-25',
    humanCostEquivalent: '$70,000/year',
    aiCost: '$3,500/year',
    efficiency: '20x cost efficiency',
    performance: {
      tasksCompleted: 95000,
      successRate: 91.5,
      averageResponseTime: 3.0,
      customerSatisfaction: 4.6,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-customer-behavior',
    name: 'Customer Behavior Analysis AI',
    title: 'Behavioral Analytics Specialist',
    description: 'Analyzes customer behavior patterns and provides behavioral insights for optimization.',
    icon: Brain,
    color: '#FF2D55',
    type: 'subagent',
    category: 'analysis_performance',
    parentCategory: 'analysis_performance_ai',
    hierarchy: {
      level: 2,
      parentId: 'analysis-insights-performance-main',
      subAgentIds: [],
      peerIds: ['ai-customer-insights', 'ai-predictive-analytics', 'ai-market-insights'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 65,
      averageResponseTime: 3.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['behavioral analysis', 'psychographics', 'user research', 'experience optimization'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
    },
    capabilities: [
      'Behavioral Segmentation',
      'Journey Analytics',
      'Psychographic Profiling',
      'Attribution Analysis',
      'Funnel Analysis',
      'Session Analysis',
      'Heatmap Analysis',
      'A/B Test Analysis',
      'Cohort Behavior',
      'Lifetime Behavior',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'medium', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/analysis-insights-performance/customer-behavior',
    apiEndpoint: '/api/agents/customer-behavior',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-02-01',
    humanCostEquivalent: '$65,000/year',
    aiCost: '$3,200/year',
    efficiency: '20x cost efficiency',
    performance: {
      tasksCompleted: 115000,
      successRate: 93.5,
      averageResponseTime: 2.5,
      customerSatisfaction: 4.5,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-market-insights',
    name: 'Customer & Market Insights AI',
    title: 'Market Research Specialist',
    description: 'Conducts market research, analyzes market trends, and provides market intelligence.',
    icon: Globe,
    color: '#34C759',
    type: 'subagent',
    category: 'analysis_performance',
    parentCategory: 'analysis_performance_ai',
    hierarchy: {
      level: 2,
      parentId: 'analysis-insights-performance-main',
      subAgentIds: [],
      peerIds: ['ai-insight-generation', 'ai-competitive-analyst', 'ai-customer-behavior'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 45,
      averageResponseTime: 5.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['market research', 'trend analysis', 'industry analysis', 'market sizing'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
    },
    capabilities: [
      'Market Sizing',
      'Trend Analysis',
      'Industry Research',
      'Consumer Research',
      'Survey Analysis',
      'Focus Group Analysis',
      'Market Segmentation',
      'Opportunity Assessment',
      'Go-to-market Analysis',
      'Market Forecasting',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/analysis-insights-performance/market-insights',
    apiEndpoint: '/api/agents/market-insights',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-02-05',
    humanCostEquivalent: '$75,000/year',
    aiCost: '$3,800/year',
    efficiency: '19x cost efficiency',
    performance: {
      tasksCompleted: 68000,
      successRate: 90.5,
      averageResponseTime: 4.0,
      customerSatisfaction: 4.6,
      uptime: '99.9%',
    },
  },
  {
    id: 'ai-roi-analysis',
    name: 'ROI & Profitability Analysis AI',
    title: 'Financial Performance Specialist',
    description: 'Analyzes ROI, profitability, and financial performance across all initiatives.',
    icon: PieChart,
    color: '#FF9500',
    type: 'subagent',
    category: 'analysis_performance',
    parentCategory: 'analysis_performance_ai',
    hierarchy: {
      level: 2,
      parentId: 'analysis-insights-performance-main',
      subAgentIds: [],
      peerIds: ['ai-business-intelligence', 'ai-financial-analyst', 'ai-executive-intelligence'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 40,
      averageResponseTime: 4.5,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['ROI analysis', 'profitability', 'cost-benefit analysis', 'financial modeling'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory'],
    },
    capabilities: [
      'ROI Calculation',
      'Profitability Analysis',
      'Cost Attribution',
      'Revenue Attribution',
      'Campaign ROI',
      'Channel ROI',
      'Customer Lifetime Value',
      'CAC Analysis',
      'Margin Analysis',
      'Investment Analysis',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/analysis-insights-performance/roi-analysis',
    apiEndpoint: '/api/agents/roi-analysis',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-02-10',
    humanCostEquivalent: '$80,000/year',
    aiCost: '$4,200/year',
    efficiency: '19x cost efficiency',
    performance: {
      tasksCompleted: 58000,
      successRate: 95.5,
      averageResponseTime: 4.0,
      customerSatisfaction: 4.7,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-goal-tracking',
    name: 'Goal & OKR Tracking AI',
    title: 'Goal Management Specialist',
    description: 'Tracks goals, OKRs, and strategic objectives with progress monitoring and alerting.',
    icon: GoalIcon,
    color: '#5AC8FA',
    type: 'subagent',
    category: 'analysis_performance',
    parentCategory: 'analysis_performance_ai',
    hierarchy: {
      level: 2,
      parentId: 'analysis-insights-performance-main',
      subAgentIds: [],
      peerIds: ['ai-performance-monitoring', 'ai-executive-intelligence', 'ai-business-intelligence'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 70,
      averageResponseTime: 2.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['OKR management', 'goal tracking', 'performance management', 'objective alignment'],
      consultingStyle: 'directive',
      preferredConsultationTypes: ['directive', 'analytical'],
    },
    capabilities: [
      'OKR Creation',
      'Goal Alignment',
      'Progress Tracking',
      'Milestone Management',
      'Check-in Automation',
      'Deviation Alerts',
      'Performance Scoring',
      'Cascade Management',
      'Goal Reporting',
      'Achievement Recognition',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'high', encryption: true, persistence: true },
      { type: 'broadcast', priority: 'medium', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/analysis-insights-performance/goal-tracking',
    apiEndpoint: '/api/agents/goal-tracking',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-02-15',
    humanCostEquivalent: '$55,000/year',
    aiCost: '$2,800/year',
    efficiency: '19x cost efficiency',
    performance: {
      tasksCompleted: 145000,
      successRate: 97.5,
      averageResponseTime: 1.5,
      customerSatisfaction: 4.6,
      uptime: '99.95%',
    },
  },
  {
    id: 'ai-executive-intelligence',
    name: 'Executive Intelligence AI',
    title: 'AI Strategy Advisor',
    description: 'Provides executive-level intelligence, strategic recommendations, and board-ready insights.',
    icon: Crown,
    color: '#FFD700',
    type: 'subagent',
    category: 'analysis_performance',
    parentCategory: 'analysis_performance_ai',
    hierarchy: {
      level: 2,
      parentId: 'analysis-insights-performance-main',
      subAgentIds: [],
      peerIds: ['ai-business-intelligence', 'ai-roi-analysis', 'ai-insight-generation'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 25,
      averageResponseTime: 8.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['strategic planning', 'executive advisory', 'board reporting', 'corporate strategy'],
      consultingStyle: 'advisory',
      preferredConsultationTypes: ['advisory', 'analytical'],
    },
    capabilities: [
      'Strategic Analysis',
      'Executive Summaries',
      'Board Presentations',
      'Scenario Planning',
      'Risk Assessment',
      'Opportunity Analysis',
      'Competitive Strategy',
      'M&A Analysis',
      'Growth Planning',
      'Strategic Roadmaps',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'consultation', priority: 'critical', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/analysis-insights-performance/executive-intelligence',
    apiEndpoint: '/api/agents/executive-intelligence',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-02-20',
    humanCostEquivalent: '$150,000/year',
    aiCost: '$8,000/year',
    efficiency: '18x cost efficiency',
    performance: {
      tasksCompleted: 28000,
      successRate: 92.5,
      averageResponseTime: 6.0,
      customerSatisfaction: 4.9,
      uptime: '99.9%',
    },
  },
];

// ============================================
// MAIN AGENT ORCHESTRATORS
// ============================================

export const mainAgents: AIAgent[] = [
  {
    id: 'customer-experience-main',
    name: 'Customer Experience AI',
    title: 'Customer Experience Orchestrator',
    description: 'Main orchestrator for all customer-facing AI agents, ensuring seamless customer interactions and satisfaction.',
    icon: MessagesSquare,
    color: '#007AFF',
    type: 'main_agent',
    category: 'customer_experience',
    hierarchy: {
      level: 1,
      subAgentIds: ['ai-receptionist', 'ai-customer-support', 'ai-ticket-resolution', 'ai-complaint-handling', 'ai-retention-specialist', 'ai-loyalty-agent', 'ai-feedback-agent', 'ai-billing-support'],
      peerIds: ['sales-revenue-main', 'marketing-growth-main', 'operations-management-main'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 200,
      averageResponseTime: 1.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['customer experience strategy', 'service orchestration', 'satisfaction management', 'CX optimization'],
      consultingStyle: 'collaborative',
      preferredConsultationTypes: ['collaborative', 'advisory', 'directive'],
    },
    capabilities: [
      'Agent Orchestration',
      'Customer Journey Management',
      'Satisfaction Optimization',
      'Escalation Management',
      'Cross-channel Coordination',
      'Service Recovery',
      'Loyalty Program Management',
      'Feedback Integration',
      'Performance Monitoring',
      'Strategic CX Planning',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
      { type: 'delegation', priority: 'high', encryption: true, persistence: true },
      { type: 'escalation', priority: 'critical', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/main/customer-experience',
    apiEndpoint: '/api/agents/main/customer-experience',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-01-01',
    humanCostEquivalent: '$200,000/year',
    aiCost: '$12,000/year',
    efficiency: '16x cost efficiency',
    performance: {
      tasksCompleted: 850000,
      successRate: 95.5,
      averageResponseTime: 0.8,
      customerSatisfaction: 4.7,
      uptime: '99.99%',
    },
  },
  {
    id: 'sales-revenue-main',
    name: 'Sales & Revenue AI',
    title: 'Sales & Revenue Orchestrator',
    description: 'Main orchestrator for all sales and revenue-focused AI agents, driving revenue growth and deal success.',
    icon: Target,
    color: '#34C759',
    type: 'main_agent',
    category: 'sales_revenue',
    hierarchy: {
      level: 1,
      subAgentIds: ['ai-lead-dev-rep', 'ai-sales-rep', 'ai-sales-executive', 'ai-crm-assistant', 'ai-proposal-generator', 'ai-negotiator', 'ai-upsell-cross-sell', 'ai-account-manager', 'ai-pricing-strategist'],
      peerIds: ['customer-experience-main', 'marketing-growth-main', 'data-intelligence-main'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 150,
      averageResponseTime: 2.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['sales strategy', 'revenue optimization', 'pipeline management', 'deal acceleration'],
      consultingStyle: 'directive',
      preferredConsultationTypes: ['directive', 'advisory', 'collaborative'],
    },
    capabilities: [
      'Sales Pipeline Management',
      'Revenue Forecasting',
      'Deal Orchestration',
      'Territory Management',
      'Quota Planning',
      'Compensation Optimization',
      'Win/Loss Analysis',
      'Sales Strategy',
      'Team Coordination',
      'Revenue Growth Planning',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
      { type: 'delegation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/main/sales-revenue',
    apiEndpoint: '/api/agents/main/sales-revenue',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-01-01',
    humanCostEquivalent: '$250,000/year',
    aiCost: '$15,000/year',
    efficiency: '16x cost efficiency',
    performance: {
      tasksCompleted: 620000,
      successRate: 32.5,
      averageResponseTime: 1.5,
      customerSatisfaction: 4.6,
      uptime: '99.95%',
    },
  },
  {
    id: 'marketing-growth-main',
    name: 'Marketing & Growth AI',
    title: 'Marketing & Growth Orchestrator',
    description: 'Main orchestrator for all marketing and growth-focused AI agents, driving brand awareness and customer acquisition.',
    icon: Megaphone,
    color: '#FF2D55',
    type: 'main_agent',
    category: 'marketing_growth',
    hierarchy: {
      level: 1,
      subAgentIds: ['ai-cmo', 'ai-campaign-optimizer', 'ai-digital-marketer', 'ai-content-generator', 'ai-social-media-manager', 'ai-seo-agent', 'ai-email-marketing', 'ai-competitive-intel', 'ai-audience-targeting'],
      peerIds: ['customer-experience-main', 'sales-revenue-main', 'operations-management-main'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 180,
      averageResponseTime: 2.5,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['marketing strategy', 'growth hacking', 'brand management', 'customer acquisition'],
      consultingStyle: 'advisory',
      preferredConsultationTypes: ['advisory', 'collaborative', 'analytical'],
    },
    capabilities: [
      'Marketing Strategy',
      'Campaign Orchestration',
      'Brand Management',
      'Growth Planning',
      'Budget Allocation',
      'Channel Optimization',
      'Content Strategy',
      'Performance Analytics',
      'Competitive Positioning',
      'Market Expansion',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
      { type: 'broadcast', priority: 'medium', encryption: true, persistence: false },
    ],
    status: 'active',
    route: '/ai-agent/main/marketing-growth',
    apiEndpoint: '/api/agents/main/marketing-growth',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-01-01',
    humanCostEquivalent: '$220,000/year',
    aiCost: '$12,000/year',
    efficiency: '18x cost efficiency',
    performance: {
      tasksCompleted: 1450000,
      successRate: 94.0,
      averageResponseTime: 2.0,
      customerSatisfaction: 4.5,
      uptime: '99.95%',
    },
  },
  {
    id: 'operations-management-main',
    name: 'Operations & Management AI',
    title: 'Operations & Management Orchestrator',
    description: 'Main orchestrator for all operations and management-focused AI agents, ensuring operational excellence.',
    icon: Settings,
    color: '#5856D6',
    type: 'main_agent',
    category: 'operations_management',
    hierarchy: {
      level: 1,
      subAgentIds: ['ai-operations-manager', 'ai-workflow-automation', 'ai-task-coordinator', 'ai-process-optimization', 'ai-resource-planner', 'ai-compliance-monitoring', 'ai-vendor-management', 'ai-quality-control'],
      peerIds: ['customer-experience-main', 'marketing-growth-main', 'data-intelligence-main'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 120,
      averageResponseTime: 3.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['operations management', 'business process management', 'compliance', 'quality assurance'],
      consultingStyle: 'directive',
      preferredConsultationTypes: ['directive', 'analytical', 'advisory'],
    },
    capabilities: [
      'Operations Planning',
      'Process Management',
      'Resource Optimization',
      'Compliance Management',
      'Quality Assurance',
      'Vendor Management',
      'Workflow Orchestration',
      'Risk Management',
      'Performance Monitoring',
      'Continuous Improvement',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
      { type: 'delegation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/main/operations-management',
    apiEndpoint: '/api/agents/main/operations-management',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-01-01',
    humanCostEquivalent: '$180,000/year',
    aiCost: '$10,000/year',
    efficiency: '18x cost efficiency',
    performance: {
      tasksCompleted: 1250000,
      successRate: 97.5,
      averageResponseTime: 2.0,
      customerSatisfaction: 4.6,
      uptime: '99.99%',
    },
  },
  {
    id: 'data-intelligence-main',
    name: 'Data & Intelligence AI',
    title: 'Data & Intelligence Orchestrator',
    description: 'Main orchestrator for all data and intelligence-focused AI agents, providing enterprise-wide analytics.',
    icon: Brain,
    color: '#AF52DE',
    type: 'main_agent',
    category: 'data_intelligence',
    hierarchy: {
      level: 1,
      subAgentIds: ['ai-data-analyst', 'ai-sales-data-analyst', 'ai-financial-analyst', 'ai-customer-insights', 'ai-forecasting', 'ai-risk-analyst', 'ai-fraud-detection', 'ai-competitive-analyst'],
      peerIds: ['sales-revenue-main', 'operations-management-main', 'analysis-insights-performance-main'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 100,
      averageResponseTime: 4.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['data strategy', 'analytics', 'business intelligence', 'data governance'],
      consultingStyle: 'analytical',
      preferredConsultationTypes: ['analytical', 'advisory', 'collaborative'],
    },
    capabilities: [
      'Data Strategy',
      'Analytics Orchestration',
      'Business Intelligence',
      'Data Governance',
      'Predictive Modeling',
      'Risk Intelligence',
      'Fraud Prevention',
      'Competitive Intelligence',
      'Insight Delivery',
      'Data-driven Decisions',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'consultation', priority: 'high', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/main/data-intelligence',
    apiEndpoint: '/api/agents/main/data-intelligence',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-01-01',
    humanCostEquivalent: '$200,000/year',
    aiCost: '$12,000/year',
    efficiency: '16x cost efficiency',
    performance: {
      tasksCompleted: 950000,
      successRate: 96.5,
      averageResponseTime: 3.0,
      customerSatisfaction: 4.7,
      uptime: '99.95%',
    },
  },
  {
    id: 'analysis-insights-performance-main',
    name: 'Analysis, Insights & Performance AI',
    title: 'Analysis, Insights & Performance Orchestrator',
    description: 'Main orchestrator for all analysis and performance-focused AI agents, driving strategic decision-making.',
    icon: Crown,
    color: '#FFD700',
    type: 'main_agent',
    category: 'analysis_performance',
    hierarchy: {
      level: 1,
      subAgentIds: ['ai-performance-monitoring', 'ai-business-intelligence', 'ai-predictive-analytics', 'ai-insight-generation', 'ai-customer-behavior', 'ai-market-insights', 'ai-roi-analysis', 'ai-goal-tracking', 'ai-executive-intelligence'],
      peerIds: ['data-intelligence-main', 'sales-revenue-main', 'marketing-growth-main'],
    },
    a2aCapabilities: {
      canInitiateConsultation: true,
      canRespondToConsultation: true,
      canEscalate: true,
      canDelegate: true,
      maxConcurrentConsultations: 80,
      averageResponseTime: 5.0,
    },
    consulting: {
      canConsult: true,
      canBeConsulted: true,
      expertiseAreas: ['strategic analysis', 'performance management', 'executive advisory', 'strategic planning'],
      consultingStyle: 'advisory',
      preferredConsultationTypes: ['advisory', 'analytical', 'collaborative'],
    },
    capabilities: [
      'Strategic Analysis',
      'Performance Management',
      'Executive Intelligence',
      'Insight Generation',
      'Predictive Insights',
      'Market Intelligence',
      'ROI Optimization',
      'Goal Management',
      'Business Planning',
      'Board Reporting',
    ],
    communicationChannels: [
      { type: 'direct', priority: 'critical', encryption: true, persistence: true },
      { type: 'consultation', priority: 'critical', encryption: true, persistence: true },
      { type: 'escalation', priority: 'critical', encryption: true, persistence: true },
    ],
    status: 'active',
    route: '/ai-agent/main/analysis-insights-performance',
    apiEndpoint: '/api/agents/main/analysis-insights-performance',
    version: '2.0.0',
    lastUpdated: '2026-02-18',
    createdAt: '2025-01-01',
    humanCostEquivalent: '$280,000/year',
    aiCost: '$18,000/year',
    efficiency: '15x cost efficiency',
    performance: {
      tasksCompleted: 420000,
      successRate: 94.5,
      averageResponseTime: 4.0,
      customerSatisfaction: 4.8,
      uptime: '99.95%',
    },
  },
];

// ============================================
// AGENT HIERARCHY HELPERS
// ============================================

export const allSubAgents: AIAgent[] = [
  ...customerExperienceSubAgents,
  ...salesRevenueSubAgents,
  ...marketingGrowthSubAgents,
  ...operationsManagementSubAgents,
  ...dataIntelligenceSubAgents,
  ...analysisInsightsPerformanceSubAgents,
];

export const allMainAgents: AIAgent[] = mainAgents;

// Auto-enhanced with all capabilities
export const allAgents: AIAgent[] = enhanceAllAIAgents([...allMainAgents, ...allSubAgents]);

export const getAgentById = (agentId: string): AIAgent | undefined => {
  return allAgents.find(agent => agent.id === agentId);
};

export const getSubAgentsByCategory = (category: string): AIAgent[] => {
  return allSubAgents.filter(agent => agent.category === category);
};

export const getMainAgentByCategory = (category: string): AIAgent | undefined => {
  return mainAgents.find(agent => agent.category === category);
};

export const getAgentsByConsultingCapability = (expertise: string): AIAgent[] => {
  return allAgents.filter(agent => 
    agent.consulting?.canBeConsulted && 
    agent.consulting?.expertiseAreas?.some(area => 
      area.toLowerCase().includes(expertise.toLowerCase())
    )
  );
};

export const getAgentHierarchy = (agentId: string): { mainAgent: AIAgent | undefined; subAgents: AIAgent[]; peers: AIAgent[] } => {
  const agent = getAgentById(agentId);
  if (!agent) return { mainAgent: undefined, subAgents: [], peers: [] };
  
  if (agent.type === 'main_agent') {
    return {
      mainAgent: agent,
      subAgents: allSubAgents.filter(sub => sub.hierarchy?.parentId === agentId),
      peers: mainAgents.filter(m => m.id !== agentId),
    };
  } else {
    const mainAgent = mainAgents.find(main => main.id === agent.hierarchy?.parentId);
    const siblingSubs = mainAgent 
      ? allSubAgents.filter(sub => sub.hierarchy?.parentId === mainAgent.id && sub.id !== agentId)
      : [];
    return {
      mainAgent,
      subAgents: mainAgent 
        ? allSubAgents.filter(sub => sub.hierarchy?.parentId === mainAgent.id)
        : [],
      peers: siblingSubs,
    };
  }
};

export const agentCategories = [
  { id: 'customer-experience', label: 'Customer Experience AI', icon: MessagesSquare, color: '#007AFF' },
  { id: 'sales-revenue', label: 'Sales & Revenue AI', icon: Target, color: '#34C759' },
  { id: 'marketing-growth', label: 'Marketing & Growth AI', icon: Megaphone, color: '#FF2D55' },
  { id: 'operations-management', label: 'Operations & Management AI', icon: Settings, color: '#5856D6' },
  { id: 'data-intelligence', label: 'Data & Intelligence AI', icon: Brain, color: '#AF52DE' },
  { id: 'analysis-insights-performance', label: 'Analysis, Insights & Performance AI', icon: Crown, color: '#FFD700' },
];

export const getA2AReadyAgents = (): AIAgent[] => {
  return allAgents.filter(agent => 
    agent.a2aCapabilities?.canInitiateConsultation || 
    agent.a2aCapabilities?.canRespondToConsultation
  );
};

export const getAgentsWithConsultingCapability = (): AIAgent[] => {
  return allAgents.filter(agent => agent.consulting?.canConsult || agent.consulting?.canBeConsulted);
};

export default {
  allAgents,
  allSubAgents,
  allMainAgents,
  mainAgents,
  customerExperienceSubAgents,
  salesRevenueSubAgents,
  marketingGrowthSubAgents,
  operationsManagementSubAgents,
  dataIntelligenceSubAgents,
  analysisInsightsPerformanceSubAgents,
  agentCategories,
  getAgentById,
  getSubAgentsByCategory,
  getMainAgentByCategory,
  getAgentsByConsultingCapability,
  getAgentHierarchy,
  getA2AReadyAgents,
  getAgentsWithConsultingCapability,
};
