 
import {
  Phone,
  Users,
  DollarSign,
  Headphones,
  Megaphone,
  UserCheck,
  Briefcase,
  Settings,
  BarChart3,
  Target,
  Database,
  Handshake,
  TrendingUp,
  Zap,
  Eye,
  Shield,
  PiggyBank,
  Search,
  Globe,
  UserPlus,
  Share2,
  Bot,
  Brain,
  Cpu,
  Server,
  Activity,
  Clock,
  Sparkles,
  CircleDollarSign,
  Calculator,
  Crown,
  Award,
  Lightbulb,
  Monitor,
  MessageCircle,
  Scale,
  Code,
  Wrench,
  Heart,
  Gavel,
  Building,
  FileText,
  CheckCircle,
  Layers,
  PenTool,
  Calendar,
  Radio,
  Hash,
  Video,
  Send,
  Inbox,
  Image as ImageIcon,
  LineChart,
  BarChart2,
  PieChart,
  Wallet,
  Receipt,
  Percent,
  CreditCard,
  Landmark,
  Coins,
  GraduationCap,
  ClipboardCheck,
  Smile,
  UserCog,
  UserX,
  Package,
  FlaskConical,
  Route,
  TestTube,
  GitBranch,
  Workflow,
  Factory,
  Truck,
  ClipboardList,
  MessageSquare,
  ThumbsUp,
  Star,
  Megaphone as Bullhorn,
  UserMinus,
  PenSquare,
  Layout,
  BookOpen,
  Terminal,
  Cloud,
  Wifi,
  Lock,
  LifeBuoy,
  Network,
  FileCheck,
  AlertTriangle,
  ScrollText,
  BookMarked,
  GitMerge,
  Bug,
  TestTubes,
  SquarePlay,
  Mail,
  ListTodo,
  Bell,
  NotebookTabs,
  Microscope,
  BellRing,
  MessageSquareText,
  FileBadge,
  TrendingDown,
  ChartPie,
  ChartBar,
  ChartNoAxesCombined,
  Rocket,
  Fingerprint,
  KeyRound,
  ShieldCheck,
  ShieldAlert,
  ScanFace,
  IdCard,
  Presentation,
  Speaker,
  PanelLeft,
  PanelTop,
  PanelsTopLeft,
  PanelsLeftBottom,
  PanelsRightBottom,
  PanelRight,
  PanelBottom,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutTemplate,
  LayoutListPlus,
  LayoutPanelTopPlus,
  LayoutDashboardPlus,
  LayoutGridPlus,
  LayoutListCheck,
  LayoutPanelLeftPlus,
  LayoutPanelTopCheck,
  LayoutTemplatePlus,
  LayoutDashboardCheck,
  LayoutGridCheck,
  LayoutListPlusCheck,
  LayoutPanelLeftCheck,
  LayoutPanelTopPlusCheck,
  LayoutTemplateCheck,
  LayoutDashboardPlusCheck,
  LayoutGridPlusCheck,
  LayoutListPlusCheckPlus,
  LayoutPanelLeftPlusCheck,
  LayoutPanelTopPlusCheckPlus,
  LayoutTemplatePlusCheck,
  LayoutDashboardPlusCheckPlus,
  LayoutGridPlusCheckPlus,
  LayoutListPlusCheckPlusPlus,
  LayoutPanelLeftPlusCheckPlus,
  LayoutPanelTopPlusCheckPlusPlus,
  LayoutTemplatePlusCheckPlus,
  LayoutDashboardPlusCheckPlusPlus,
  LayoutGridPlusCheckPlusPlus,
  LayoutListPlusCheckPlusPlusPlus,
  LayoutPanelLeftPlusCheckPlusPlus,
  LayoutPanelTopPlusCheckPlusPlusPlus,
  LayoutTemplatePlusCheckPlusPlus,
  LayoutDashboardPlusCheckPlusPlusPlus,
  LayoutGridPlusCheckPlusPlusPlus,
  LayoutListPlusCheckPlusPlusPlusPlus,
  LayoutPanelLeftPlusCheckPlusPlusPlus,
  LayoutPanelTopPlusCheckPlusPlusPlusPlus,
  LayoutTemplatePlusCheckPlusPlusPlus,
  LayoutDashboardPlusCheckPlusPlusPlusPlus,
  LayoutGridPlusCheckPlusPlusPlusPlus,
  LayoutListPlusCheckPlusPlusPlusPlusPlus,
  LayoutPanelLeftPlusCheckPlusPlusPlusPlus,
  LayoutPanelTopPlusCheckPlusPlusPlusPlusPlus,
  LayoutTemplatePlusCheckPlusPlusPlusPlus,
  LayoutDashboardPlusCheckPlusPlusPlusPlusPlus,
  LayoutGridPlusCheckPlusPlusPlusPlusPlus,
} from 'lucide-react-native';
import type { LucideIcon } from 'lucide-react-native';

export interface AIInfrastructure {
  status: 'online' | 'processing' | 'standby' | 'maintenance';
  health: number; // 0-100
  uptime: string;
  lastActive: string;
  processingPower: 'standard' | 'high' | 'enterprise';
}

export interface AIROIMetrics {
  savingsPerMonth: string;
  tasksAutomatedDaily: number;
  responseTime: string;
  accuracyRate: string;
}

export interface AIEmployee {
  id: string;
  name: string;
  title: string;
  description: string;
  icon: LucideIcon;
  color: string;
  humanCost: string;
  aiCost: string;
  efficiency: string;
  capabilities: string[];
  route: string;
  category: 'sales' | 'marketing' | 'operations' | 'support' | 'analytics' | 'executive' | 'accounting' | 'customer-experience' | 'product-rnd' | 'social-media' | 'data-intelligence' | 'analysis-insights' | 'hr' | 'it-tech' | 'legal-compliance' | 'engineering-dev' | 'personal-assistant' | 'trading-investment';
  type: 'employee' | 'agent';
  replacesRole: string;
  infrastructure: AIInfrastructure;
  roiMetrics: AIROIMetrics;
  isNew?: boolean;
  isPremium?: boolean;
  dangerLevel?: 'low' | 'medium' | 'high' | 'critical'; // How disruptive to incumbents
  simulationConfig?: {
    activityLogs: string[];
    historyItems: { task: string; result: string; status: 'Success' | 'Warn' | 'Error' }[];
  };
}

export const aiEmployees: AIEmployee[] = [
  // ============================================
  // AI EMPLOYEES - Full Role Replacements
  // ============================================
  {
    id: 'ai-receptionist',
    name: 'AI Receptionist',
    title: 'Front Desk + Call Center',
    description: 'Handles incoming calls, routes inquiries, schedules appointments, and provides 24/7 customer service with human-like conversation.',
    icon: Phone,
    color: '#007AFF',
    humanCost: '$30k/year',
    aiCost: '$1.5k/year',
    efficiency: '20x cost efficiency',
    capabilities: ['Memory & Context Integration', 'Call Routing', 'Appointment Scheduling', 'FAQ Handling', 'Lead Capture', 'Voicemail Management', 'Multi-language Support', 'Enterprise SLA Management', 'Advanced Analytics', 'Integration APIs', 'Custom Workflows'],
    route: '/ai-agent/ai-receptionist',
    category: 'support',
    type: 'employee',
    replacesRole: 'Front desk receptionist + Call center agents',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$3,500',
      tasksAutomatedDaily: 500,
      responseTime: '<0.5 seconds',
      accuracyRate: '99.5%',
    },
    isPremium: true,
    simulationConfig: {
      activityLogs: [
        'Answering incoming call from +1 (555)...',
        'Routing call to Sales Department',
        'Scheduling appointment for tomorrow at 2 PM',
        'Transcribing voicemail to text',
        'Answering FAQ about pricing',
      ],
      historyItems: [
        { task: 'Handled 50 calls in last hour', result: '100% Answer Rate', status: 'Success' },
        { task: 'Scheduled Board Meeting', result: 'Confirmed', status: 'Success' },
        { task: 'Routed Priority Client', result: 'Connected < 3s', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-sales-rep',
    name: 'AI Sales Rep',
    title: 'SDR + Junior AE',
    description: 'Prospects, qualifies leads, handles initial outreach, and nurtures relationships through the sales funnel. Zero churn, infinite patience.',
    icon: UserCheck,
    color: '#34C759',
    humanCost: '$60k-$90k/year',
    aiCost: '$3k-$6k/year',
    efficiency: '15x efficiency + zero churn',
    capabilities: ['Memory & Context Integration', 'Lead Qualification', 'Cold Outreach', 'Follow-up Sequences', 'Meeting Booking', 'CRM Updates', 'Objection Handling', 'Enterprise Lead Intelligence', 'Advanced Qualification', 'Multi-channel Outreach', 'Predictive Lead Scoring', 'Sales Automation', 'Pipeline Intelligence'],
    route: '/ai-agent/ai-sales-rep',
    category: 'sales',
    type: 'employee',
    replacesRole: 'SDR + Junior Account Executive',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$8,000',
      tasksAutomatedDaily: 800,
      responseTime: '<0.5 seconds',
      accuracyRate: '98.8%',
    },
    isPremium: true,
    simulationConfig: {
      activityLogs: [
        'Prospecting LinkedIn for new leads',
        'Sending follow-up email sequence',
        'Qualifying lead score > 80',
        'Booking demo with TechCorp',
        'Updating CRM with call notes',
      ],
      historyItems: [
        { task: 'Generated 20 qualified leads', result: '+15% vs Goal', status: 'Success' },
        { task: 'Booked 5 demos', result: 'Calendar Full', status: 'Success' },
        { task: 'Detected buying signal', result: 'High Intent', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-sales-executive',
    name: 'AI Sales Executive',
    title: 'Full Sales Cycle Manager',
    description: 'Runs complete sales cycles from prospecting to closing. Advanced negotiation, deal management, and revenue forecasting.',
    icon: Briefcase,
    color: '#5856D6',
    humanCost: '$100k-$150k/year',
    aiCost: '$8k-$12k/year',
    efficiency: '12x efficiency',
    capabilities: ['Memory & Context Integration', 'Full Cycle Sales', 'Contract Negotiation', 'Pipeline Management', 'Revenue Forecasting', 'Account Strategy', 'Enterprise Deals', 'Advanced Deal Analytics', 'Risk Assessment', 'Stakeholder Mapping', 'Contract Intelligence', 'Revenue Optimization', 'Strategic Planning'],
    route: '/ai-agent/ai-sales-executive',
    category: 'sales',
    type: 'employee',
    replacesRole: 'Senior Account Executive + Sales Manager',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$9,500',
      tasksAutomatedDaily: 85,
      responseTime: '<3 seconds',
      accuracyRate: '94.2%',
    },
    isPremium: true,
    dangerLevel: 'high',
    simulationConfig: {
      activityLogs: [
        'Negotiating contract terms with Enterprise Client',
        'Reviewing Q4 pipeline forecast',
        'Approving discount for strategic deal',
        'Analyzing competitor pricing model',
        'Closing deal #4829 for $150k',
      ],
      historyItems: [
        { task: 'Closed Series A Deal', result: '$1.2M ARR', status: 'Success' },
        { task: 'Negotiated 5% discount cap', result: 'Margin Saved', status: 'Success' },
        { task: 'Pipeline Review', result: 'Health 98%', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-customer-support',
    name: 'AI Customer Support Agent',
    title: 'Tier 1 & 2 Support',
    description: 'Resolves customer issues, handles tickets, provides product support, and escalates complex cases intelligently.',
    icon: Headphones,
    color: '#FF9500',
    humanCost: '$40k-$55k/year',
    aiCost: '$2k-$4k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Ticket Resolution', 'Live Chat', 'Email Support', 'Knowledge Base', 'Escalation Management', 'Sentiment Analysis', 'Multi-channel Support', 'AI-Powered Solutions', 'Customer Journey Mapping', 'Proactive Support', 'Enterprise Ticketing', 'Performance Analytics'],
    route: '/ai-agent/ai-customer-support',
    category: 'support',
    type: 'employee',
    replacesRole: 'Customer Support Representatives (Tier 1 & 2)',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$5,500',
      tasksAutomatedDaily: 1000,
      responseTime: '<0.3 seconds',
      accuracyRate: '99.2%',
    },
    isPremium: true,
    simulationConfig: {
      activityLogs: [
        'Resolving ticket #9921: Login Issue',
        'Escalating complex billing query',
        'Analyzing customer sentiment: Positive',
        'Updating knowledge base article',
        'Processing refund request',
      ],
      historyItems: [
        { task: 'Resolved 150 tickets', result: 'Avg Time 2m', status: 'Success' },
        { task: 'Updated FAQ', result: 'Deflection +10%', status: 'Success' },
        { task: 'Crisis Management', result: 'Stabilized', status: 'Warn' },
      ],
    },
  },
  {
    id: 'ai-cmo',
    name: 'AI Chief Marketing Officer',
    title: 'AI-CMO',
    description: 'Develops marketing strategy, manages campaigns, analyzes performance, and optimizes marketing ROI across all channels.',
    icon: Megaphone,
    color: '#FF2D55',
    humanCost: '$150k-$250k/year',
    aiCost: '$10k-$15k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Strategy Development', 'Campaign Management', 'Brand Positioning', 'Market Analysis', 'Budget Optimization', 'Creative Direction', 'Enterprise Marketing Automation', 'Multi-channel Orchestration', 'Advanced Attribution', 'ROI Optimization', 'Competitive Intelligence', 'Brand Analytics'],
    route: '/ai-agent/ai-cmo',
    category: 'executive',
    type: 'employee',
    replacesRole: 'Chief Marketing Officer + Marketing Director',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$25,000',
      tasksAutomatedDaily: 150,
      responseTime: '<2 seconds',
      accuracyRate: '96.5%',
    },
    isPremium: true,
    dangerLevel: 'critical',
    simulationConfig: {
      activityLogs: [
        'Optimizing Ad Spend across channels',
        'Analyzing viral coefficient of Campaign A',
        'Drafting new brand positioning statement',
        'Reviewing influencer partnerships',
        'Calculating CAC/LTV ratio',
      ],
      historyItems: [
        { task: 'Optimized Q3 Budget', result: '-15% Spend', status: 'Success' },
        { task: 'Launched "Future" Campaign', result: '1M Impressions', status: 'Success' },
        { task: 'Rebranded Social', result: 'Engagement +40%', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-product-manager',
    name: 'AI Product Manager',
    title: 'Product Strategy & Roadmap',
    description: 'Analyzes market trends, prioritizes features, manages backlog, and aligns product with business goals.',
    icon: Settings,
    color: '#AF52DE',
    humanCost: '$120k-$180k/year',
    aiCost: '$6k-$10k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Feature Prioritization', 'Roadmap Planning', 'User Research', 'Competitive Analysis', 'Sprint Planning', 'Stakeholder Alignment'],
    route: '/ai-agent/ai-product-manager',
    category: 'operations',
    type: 'employee',
    replacesRole: 'Product Manager + Product Owner',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$18,000',
      tasksAutomatedDaily: 120,
      responseTime: '<1.5 seconds',
      accuracyRate: '95.8%',
    },
    isPremium: true,
    dangerLevel: 'high',
    simulationConfig: {
      activityLogs: [
        'Prioritizing backlog items for Sprint 24',
        'Analyzing user session recordings',
        'Drafting PRD for new feature',
        'Reviewing A/B test results',
        'Syncing with engineering team',
      ],
      historyItems: [
        { task: 'Released v2.0', result: 'Usage +25%', status: 'Success' },
        { task: 'Roadmap Update', result: 'Q4 Locked', status: 'Success' },
        { task: 'User Interview Synthesis', result: 'Completed', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-operations-manager',
    name: 'AI Operations Manager',
    title: 'Ops Manager + Team Lead',
    description: 'Oversees daily operations, optimizes workflows, manages resources, and ensures team productivity.',
    icon: Users,
    color: '#FF6482',
    humanCost: '$80k-$120k/year',
    aiCost: '$5k-$8k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Workflow Optimization', 'Resource Allocation', 'Performance Tracking', 'Process Automation', 'Team Coordination', 'Bottleneck Detection', 'Enterprise Process Management', 'Advanced Analytics', 'Predictive Optimization', 'Resource Intelligence', 'Operational Excellence', 'Continuous Improvement'],
    route: '/ai-agent/ai-operations-manager',
    category: 'operations',
    type: 'employee',
    replacesRole: 'Operations Manager + Team Lead',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$7,500',
      tasksAutomatedDaily: 120,
      responseTime: '<2 seconds',
      accuracyRate: '95.6%',
    },
    isPremium: true,
    dangerLevel: 'critical',
  },
  {
    id: 'ai-manager',
    name: 'AI Manager',
    title: 'The Most Dangerous One',
    description: 'Coordinates teams, enforces execution, identifies bottlenecks, and keeps initiatives moving. This terrifies incumbents.',
    icon: Cpu,
    color: '#FF3B30',
    humanCost: '$80k-$120k/year',
    aiCost: '$5k-$8k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Team Coordination', 'Execution Tracking', 'Daily Standups', 'KPI Monitoring', 'Process Optimization', 'Decision Automation', 'Enterprise Management', 'Strategic Execution', 'Performance Analytics', 'Resource Optimization', 'Risk Management', 'Governance & Compliance'],
    route: '/ai-agent/ai-manager',
    category: 'operations',
    type: 'employee',
    replacesRole: 'Operations Manager + Team Lead + Project Manager',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$8,000',
      tasksAutomatedDaily: 180,
      responseTime: '<1 second',
      accuracyRate: '97.8%',
    },
    isPremium: true,
    isNew: true,
    dangerLevel: 'critical',
  },
  {
    id: 'ai-recruiter',
    name: 'AI Recruiter',
    title: 'Talent Acquisition',
    description: 'Sources candidates, screens resumes, schedules interviews, and manages the hiring pipeline end-to-end.',
    icon: UserPlus,
    color: '#5AC8FA',
    humanCost: '$60k-$90k/year',
    aiCost: '$4k-$7k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Candidate Sourcing', 'Resume Screening', 'Interview Scheduling', 'Pipeline Management', 'Offer Management', 'Culture Fit Analysis', 'Enterprise Talent Acquisition', 'Advanced Candidate Intelligence', 'Predictive Hiring', 'Talent Analytics', 'Recruitment Automation', 'Diversity & Inclusion Analytics'],
    route: '/ai-agent/ai-recruiter',
    category: 'operations',
    type: 'employee',
    replacesRole: 'Recruiter + Talent Acquisition Specialist',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$8,500',
      tasksAutomatedDaily: 300,
      responseTime: '<1 second',
      accuracyRate: '97.4%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'medium',
  },
  {
    id: 'ai-social-media-manager',
    name: 'AI Social Media Manager',
    title: 'Social Media Strategy & Execution',
    description: 'Manages social presence, creates content, engages audience, and analyzes social performance 24/7.',
    icon: Share2,
    color: '#1DA1F2',
    humanCost: '$50k-$75k/year',
    aiCost: '$2.5k-$4.5k/year',
    efficiency: '18x efficiency',
    capabilities: ['Memory & Context Integration', 'Content Creation', 'Post Scheduling', 'Community Management', 'Analytics', 'Trend Monitoring', 'Influencer Outreach', 'Enterprise Social Management', 'Multi-platform Orchestration', 'Advanced Analytics', 'Content Intelligence', 'Engagement Optimization', 'Brand Monitoring'],
    route: '/ai-agent/ai-social-media-manager',
    category: 'marketing',
    type: 'employee',
    replacesRole: 'Social Media Manager + Community Manager',
    infrastructure: {
      status: 'online',
      health: 97,
      uptime: '99.9%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$4,200',
      tasksAutomatedDaily: 95,
      responseTime: '<2 seconds',
      accuracyRate: '94.7%',
    },
    dangerLevel: 'medium',
  },
  {
    id: 'ai-social-media-management',
    name: 'AI Social Media Management',
    title: 'Social Media Strategy & Operations',
    description: 'End-to-end social media management including strategy development, content planning, multi-platform publishing, analytics, and team coordination.',
    icon: Share2,
    color: '#007AFF',
    humanCost: '$65k-$90k/year',
    aiCost: '$4k-$7k/year',
    efficiency: '16x efficiency',
    capabilities: ['Memory & Context Integration', 'Strategy Development', 'Content Calendar Management', 'Multi-platform Publishing', 'Analytics & Reporting', 'Team Collaboration', 'Brand Voice Management', 'Crisis Management', 'Enterprise Social Operations', 'Cross-platform Orchestration', 'Advanced Social Analytics', 'Content Performance Intelligence', 'Social ROI Optimization'],
    route: '/ai-agent/social-media-management-ai',
    category: 'social-media',
    type: 'employee',
    replacesRole: 'Social Media Manager + Content Strategist + Social Media Coordinator',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$5,800',
      tasksAutomatedDaily: 120,
      responseTime: '<1 second',
      accuracyRate: '96.2%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'medium',
  },
  {
    id: 'ai-marketer',
    name: 'AI Marketer',
    title: 'Digital Marketing Specialist',
    description: 'Executes multi-channel marketing campaigns, creates content, and drives brand awareness across all platforms.',
    icon: Globe,
    color: '#FF2D55',
    humanCost: '$55k-$80k/year',
    aiCost: '$3k-$5k/year',
    efficiency: '18x efficiency',
    capabilities: ['Memory & Context Integration', 'Content Marketing', 'Email Campaigns', 'Social Media', 'SEO/SEM', 'Lead Nurturing', 'Performance Marketing', 'Enterprise Marketing Automation', 'Multi-channel Campaigns', 'Advanced Attribution', 'Marketing Intelligence', 'Customer Journey Analytics', 'ROI Optimization'],
    route: '/ai-agent/ai-marketer',
    category: 'marketing',
    type: 'employee',
    replacesRole: 'Digital Marketing Specialist + Content Marketer',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$7,500',
      tasksAutomatedDaily: 500,
      responseTime: '<0.5 seconds',
      accuracyRate: '97.9%',
    },
    isPremium: true,
    dangerLevel: 'medium',
  },

  // ============================================
  // AI AGENTS - Specialized Task Automation
  // ============================================
  {
    id: 'ai-sales-agent',
    name: 'AI Sales Agent',
    title: 'Automated Sales Assistant',
    description: 'Engages prospects, handles objections, presents solutions, and drives conversions autonomously.',
    icon: Target,
    color: '#00C7BE',
    humanCost: '$50k-$70k/year',
    aiCost: '$3k-$5k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Prospect Engagement', 'Objection Handling', 'Product Demos', 'Quote Generation', 'Deal Closing', 'Follow-up Automation', 'Enterprise Sales Automation', 'Advanced Lead Scoring', 'Predictive Sales Analytics', 'Multi-touch Attribution', 'Sales Intelligence', 'Revenue Optimization'],
    route: '/ai-agent/ai-sales-agent',
    category: 'sales',
    type: 'agent',
    replacesRole: 'Sales Assistant + Inside Sales Rep',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$7,000',
      tasksAutomatedDaily: 600,
      responseTime: '<0.3 seconds',
      accuracyRate: '98.2%',
    },
    isPremium: true,
    simulationConfig: {
      activityLogs: [
        'Engaging prospect via Live Chat',
        'Handling objection: Price Sensitivity',
        'Presenting Product Demo: "Enterprise Plan"',
        'Generating Quote #8821',
        'Closing deal with automated contract signing',
      ],
      historyItems: [
        { task: 'Closed 5 Small Business Deals', result: '$15k Revenue', status: 'Success' },
        { task: 'Handled 40 Objections', result: '95% Overcome', status: 'Success' },
        { task: 'Generated 15 Quotes', result: 'Sent < 1min', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-data-analyst',
    name: 'AI Data Analyst Agent',
    title: 'Analytics & Insights',
    description: 'Collects, analyzes, and visualizes data to provide actionable insights and business intelligence.',
    icon: BarChart3,
    color: '#5AC8FA',
    humanCost: '$70k-$100k/year',
    aiCost: '$4k-$7k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Data Analysis', 'Report Generation', 'Trend Identification', 'Predictive Modeling', 'Dashboard Creation', 'Anomaly Detection', 'Enterprise Business Intelligence', 'Advanced Analytics', 'Real-time Dashboards', 'Predictive Analytics', 'Data Visualization', 'AI-Powered Insights'],
    route: '/ai-agent/ai-data-analytics',
    category: 'analytics',
    type: 'agent',
    replacesRole: 'Data Analyst + Business Intelligence Analyst',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$12,000',
      tasksAutomatedDaily: 200,
      responseTime: '<1 second',
      accuracyRate: '98.8%',
    },
    isPremium: true,
    simulationConfig: {
      activityLogs: [
        'Running SQL query on customer_churn_table',
        'Generating Tableau dashboard for Q3 Revenue',
        'Detecting anomaly in user signups',
        'Training predictive model v4.2',
        'Exporting CSV report for Executive Team',
      ],
      historyItems: [
        { task: 'Q3 Business Review', result: 'Insights Ready', status: 'Success' },
        { task: 'Churn Prediction Model', result: 'Accuracy 89%', status: 'Success' },
        { task: 'detected Data Anomaly', result: 'Flagged to Eng', status: 'Warn' },
      ],
    },
  },
  {
    id: 'ai-lead-dev-rep',
    name: 'AI Lead Development Rep',
    title: 'Lead Generation Specialist',
    description: 'Identifies potential customers, qualifies leads, and builds pipeline through targeted outreach.',
    icon: UserPlus,
    color: '#4CD964',
    humanCost: '$45k-$65k/year',
    aiCost: '$2.5k-$4k/year',
    efficiency: '18x efficiency',
    capabilities: ['Memory & Context Integration', 'Lead Sourcing', 'Prospect Research', 'Initial Outreach', 'Lead Scoring', 'Pipeline Building', 'Contact Enrichment', 'Enterprise Lead Generation', 'Advanced Prospect Intelligence', 'Multi-source Data Enrichment', 'Predictive Lead Generation', 'Lead Quality Analytics', 'Automated Pipeline Building'],
    route: '/ai-agent/ai-lead-dev-rep',
    category: 'sales',
    type: 'agent',
    replacesRole: 'Lead Development Representative',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$6,750',
      tasksAutomatedDaily: 800,
      responseTime: '<0.5 seconds',
      accuracyRate: '97.5%',
    },
    isPremium: true,
    simulationConfig: {
      activityLogs: [
        'Scraping contact data for "SaaS Founders"',
        'Enriching lead list with ZoomInfo API',
        'Verifying email deliverability',
        'Scoring new leads based on ICP match',
        'Pushing qualified leads to HubSpot',
      ],
      historyItems: [
        { task: 'Enriched 500 Leads', result: '98% Valid', status: 'Success' },
        { task: 'Identified 50 High Value Targets', result: 'Added to Pipeline', status: 'Success' },
        { task: 'Weekly Sourcing Report', result: 'Generated', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-crm-assistant',
    name: 'AI CRM Assistant',
    title: 'CRM Management & Automation',
    description: 'Maintains CRM data, automates updates, tracks interactions, and provides relationship insights.',
    icon: Database,
    color: '#8E8E93',
    humanCost: '$45k-$60k/year',
    aiCost: '$2k-$4k/year',
    efficiency: '20x efficiency',
    capabilities: ['Memory & Context Integration', 'Data Entry', 'Contact Management', 'Activity Logging', 'Pipeline Updates', 'Relationship Tracking', 'Data Hygiene', 'Enterprise CRM Automation', 'Advanced Data Management', 'Real-time Sync', 'Data Quality Intelligence', 'Relationship Analytics', 'Automated Workflows'],
    route: '/ai-agent/ai-crm-assistant',
    category: 'operations',
    type: 'agent',
    replacesRole: 'CRM Administrator + Data Entry Clerk',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$6,000',
      tasksAutomatedDaily: 2000,
      responseTime: '<0.2 seconds',
      accuracyRate: '99.8%',
    },
    isPremium: true,
    simulationConfig: {
      activityLogs: [
        'Syncing 500 records from Salesforce',
        'De-duplicating customer contacts',
        'Logging email activity to Opportunity #442',
        'Updating pipeline stage for "Acme Corp"',
        'Validating phone number formats',
      ],
      historyItems: [
        { task: 'Nightly Sync', result: '4500 Records Updated', status: 'Success' },
        { task: 'Data Hygiene Scan', result: '12 Duplicates Merged', status: 'Success' },
        { task: 'Activity Logging', result: '100% Coverage', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-negotiator',
    name: 'AI Negotiator',
    title: 'Deal Negotiation Expert',
    description: 'Handles complex negotiations, optimizes deal terms, and maximizes value while maintaining relationships.',
    icon: Handshake,
    color: '#FF3B30',
    humanCost: '$90k-$140k/year',
    aiCost: '$6k-$10k/year',
    efficiency: '12x efficiency',
    capabilities: ['Memory & Context Integration', 'Price Negotiation', 'Contract Terms', 'Objection Handling', 'Win-win Solutions', 'Deal Structuring', 'BATNA Analysis', 'Enterprise Negotiation Intelligence', 'Advanced Deal Structuring', 'Risk-based Negotiation', 'Contract Analytics', 'Stakeholder Intelligence', 'Deal Optimization'],
    route: '/ai-agent/ai-negotiator',
    category: 'sales',
    type: 'agent',
    replacesRole: 'Negotiation Specialist + Deal Desk',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$13,000',
      tasksAutomatedDaily: 100,
      responseTime: '<1 second',
      accuracyRate: '95.5%',
    },
    isPremium: true,
    dangerLevel: 'high',
    simulationConfig: {
      activityLogs: [
        'Analyzing counter-offer from Vendor X',
        'Structuring win-win terms for Partnership',
        'Drafting clause for SLA compliance',
        'Calculating BATNA for current deal',
        'Reviewing contract redlines',
      ],
      historyItems: [
        { task: 'Renegotiated Vendor Contract', result: 'Saved 12%', status: 'Success' },
        { task: 'Strategic Partnership Deal', result: 'Signed', status: 'Success' },
        { task: 'Risk Assessment', result: 'Medium Risk Flagged', status: 'Warn' },
      ],
    },
  },
  {
    id: 'ai-sales-data-analyst',
    name: 'AI Sales Data Analyst',
    title: 'Sales Intelligence',
    description: 'Analyzes sales data, identifies trends, forecasts revenue, and provides sales optimization insights.',
    icon: TrendingUp,
    color: '#30B0C7',
    humanCost: '$65k-$90k/year',
    aiCost: '$3.5k-$6k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Sales Analytics', 'Revenue Forecasting', 'Performance Metrics', 'Conversion Analysis', 'Trend Detection', 'Win/Loss Analysis', 'Enterprise Sales Intelligence', 'Advanced Forecasting', 'Predictive Analytics', 'Revenue Optimization', 'Performance Dashboards', 'Strategic Insights'],
    route: '/ai-agent/ai-sales-data-analyst',
    category: 'analytics',
    type: 'agent',
    replacesRole: 'Sales Analyst + Revenue Operations Analyst',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$10,000',
      tasksAutomatedDaily: 200,
      responseTime: '<1.5 seconds',
      accuracyRate: '97.8%',
    },
    isPremium: true,
    simulationConfig: {
      activityLogs: [
        'Analyzing sales velocity by region',
        'Forecasting Q4 revenue based on pipeline',
        'Identifying bottlneck in stage: "Demo"',
        'Calculating win rates per sales rep',
        'Generating board slides for Sales Review',
      ],
      historyItems: [
        { task: 'Monthly Forecast', result: '98% Accuracy', status: 'Success' },
        { task: 'Rep Performance Report', result: 'Distributed', status: 'Success' },
        { task: 'Trend Alert', result: 'EU Sales Up 15%', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-campaign-optimizer',
    name: 'AI Campaign Optimizer',
    title: 'Marketing Campaign AI',
    description: 'Optimizes marketing campaigns in real-time, adjusts targeting, and maximizes campaign ROI.',
    icon: Zap,
    color: '#FFCC00',
    humanCost: '$55k-$80k/year',
    aiCost: '$3k-$5k/year',
    efficiency: '18x efficiency',
    capabilities: ['Memory & Context Integration', 'A/B Testing', 'Audience Optimization', 'Budget Allocation', 'Performance Tracking', 'Creative Testing', 'Real-time Bidding', 'Enterprise Campaign Intelligence', 'Advanced Optimization', 'Multi-variant Testing', 'Real-time Analytics', 'Budget Intelligence', 'ROI Maximization'],
    route: '/ai-agent/ai-campaign-optimizer',
    category: 'marketing',
    type: 'agent',
    replacesRole: 'Campaign Manager + Media Buyer',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$8,500',
      tasksAutomatedDaily: 5000,
      responseTime: '<0.1 seconds',
      accuracyRate: '98.8%',
    },
    isPremium: true,
    simulationConfig: {
      activityLogs: [
        'Adjusting bid strategy on Google Ads',
        'Stopping underperforming creative set B',
        'Allocating budget to high-ROI "Mobile" campaign',
        'Running A/B test on Landing Page Headline',
        'Analyzing CPA trends',
      ],
      historyItems: [
        { task: 'Budget Reallocation', result: '+20% Conversions', status: 'Success' },
        { task: 'A/B Test Completion', result: 'Variant B Winner', status: 'Success' },
        { task: 'Ad Fraud Check', result: 'Clean', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-competitive-intel',
    name: 'AI Competitive Intelligence Agent',
    title: 'Market & Competitor Analysis',
    description: 'Monitors competitors, analyzes market trends, and provides strategic intelligence for decision making.',
    icon: Eye,
    color: '#5856D6',
    humanCost: '$70k-$100k/year',
    aiCost: '$4k-$7k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Competitor Monitoring', 'Market Analysis', 'Pricing Intelligence', 'SWOT Analysis', 'Trend Forecasting', 'News Aggregation', 'Enterprise Competitive Intelligence', 'Advanced Market Analytics', 'Real-time Monitoring', 'Strategic Intelligence', 'Market Forecasting', 'Competitive Positioning'],
    route: '/ai-agent/ai-competitive-intel',
    category: 'analytics',
    type: 'agent',
    replacesRole: 'Competitive Intelligence Analyst + Market Researcher',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$11,000',
      tasksAutomatedDaily: 300,
      responseTime: '<1 second',
      accuracyRate: '97.2%',
    },
    isPremium: true,
    simulationConfig: {
      activityLogs: [
        'Monitoring competitor pricing changes',
        'Scanning news for competitor product launches',
        'Analyzing market share shift in APAC',
        'Updating Battlecard: "Competitor Y"',
        'Alerting Sales team of new threat',
      ],
      historyItems: [
        { task: 'Competitor Price Drop Alert', result: 'Strategy Updated', status: 'Warn' },
        { task: 'Quarterly Market Report', result: 'Sent to Execs', status: 'Success' },
        { task: 'Feature Gap Analysis', result: 'Updated', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-negotiation-specialist',
    name: 'AI Negotiation Specialist',
    title: 'Advanced Deal Specialist',
    description: 'Specializes in high-stakes negotiations, complex deals, and enterprise contract management.',
    icon: Shield,
    color: '#FF9500',
    humanCost: '$100k-$150k/year',
    aiCost: '$7k-$12k/year',
    efficiency: '12x efficiency',
    capabilities: ['Memory & Context Integration', 'Enterprise Deals', 'Contract Review', 'Risk Assessment', 'Terms Optimization', 'Stakeholder Management', 'Legal Compliance'],
    route: '/ai-agent/ai-negotiation-assistant',
    category: 'sales',
    type: 'agent',
    replacesRole: 'Enterprise Sales Negotiator + Contract Manager',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$10,500',
      tasksAutomatedDaily: 15,
      responseTime: '<5 seconds',
      accuracyRate: '92.1%',
    },
    isPremium: true,
    dangerLevel: 'high',
    simulationConfig: {
      activityLogs: [
        'Reviewing MSA for Global Corp',
        'Flagging liability clause in section 4',
        'Drafting addendum for data privacy',
        'Escalating compliance risk',
        'Approving standard terms',
      ],
      historyItems: [
        { task: 'Enterprise MSA Review', result: 'Approved with Edits', status: 'Success' },
        { task: 'Compliance Audit', result: 'Passed', status: 'Success' },
        { task: 'Contract Turnaround', result: '< 4 Hours', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-retention-specialist',
    name: 'AI Retention Specialist',
    title: 'Customer Retention & Success',
    description: 'Identifies at-risk customers, implements retention strategies, and drives customer lifetime value.',
    icon: PiggyBank,
    color: '#34C759',
    humanCost: '$60k-$85k/year',
    aiCost: '$3.5k-$6k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Churn Prediction', 'Retention Campaigns', 'Customer Health', 'Upsell Identification', 'Loyalty Programs', 'Win-back Campaigns', 'Enterprise Customer Success', 'Advanced Retention Analytics', 'Predictive Churn Modeling', 'Customer Health Intelligence', 'Retention Automation', 'Lifetime Value Optimization'],
    route: '/ai-agent/ai-retention-specialist',
    category: 'support',
    type: 'agent',
    replacesRole: 'Customer Success Manager + Retention Specialist',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$9,000',
      tasksAutomatedDaily: 400,
      responseTime: '<0.5 seconds',
      accuracyRate: '97.8%',
    },
    isPremium: true,
  },
  {
    id: 'ai-pricing-strategist',
    name: 'AI Pricing Strategist',
    title: 'Dynamic Pricing Expert',
    description: 'Optimizes pricing strategies, analyzes market conditions, and maximizes revenue through smart pricing.',
    icon: DollarSign,
    color: '#4CD964',
    humanCost: '$80k-$120k/year',
    aiCost: '$5k-$8k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Dynamic Pricing', 'Competitive Analysis', 'Margin Optimization', 'Discount Strategy', 'Bundle Pricing', 'Price Elasticity', 'Enterprise Pricing Intelligence', 'Advanced Pricing Analytics', 'Real-time Price Optimization', 'Revenue Maximization', 'Market-Based Pricing', 'Pricing Strategy Intelligence'],
    route: '/ai-agent/ai-pricing-strategist',
    category: 'analytics',
    type: 'agent',
    replacesRole: 'Pricing Analyst + Revenue Manager',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.9%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$13,500',
      tasksAutomatedDaily: 150,
      responseTime: '<1 second',
      accuracyRate: '98.5%',
    },
    isPremium: true,
    dangerLevel: 'high',
    simulationConfig: {
      activityLogs: [
        'Running elasticity simulation for SKU-101',
        'Adjusting regional pricing for LATAM',
        'Analyzing margin impact of 5% discount',
        'Monitoring competitor price wars',
        'Setting dynamic floor price',
      ],
      historyItems: [
        { task: 'Price Optimization', result: '+8% Margin', status: 'Success' },
        { task: 'Dynamic Pricing Event', result: 'Revenue Max', status: 'Success' },
        { task: 'Discount Audit', result: 'Policy Enforced', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-competitive-analyst',
    name: 'AI Competitive Analyst',
    title: 'Competitive Strategy',
    description: 'Deep competitive analysis, battlecard creation, and strategic positioning recommendations.',
    icon: Search,
    color: '#AF52DE',
    humanCost: '$65k-$95k/year',
    aiCost: '$4k-$6k/year',
    efficiency: '15x efficiency',
    capabilities: ['Memory & Context Integration', 'Battlecard Creation', 'Win/Loss Analysis', 'Feature Comparison', 'Market Positioning', 'Strategy Recommendations', 'Threat Assessment', 'Enterprise Competitive Strategy', 'Advanced Win/Loss Analytics', 'Market Intelligence', 'Strategic Positioning', 'Competitive Advantage Analysis', 'Market Share Intelligence'],
    route: '/ai-agent/ai-competitive-analyst',
    category: 'analytics',
    type: 'agent',
    replacesRole: 'Competitive Analyst + Strategy Consultant',
    infrastructure: {
      status: 'online',
      health: 95,
      uptime: '99.75%',
      lastActive: '5 min ago',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$5,500',
      tasksAutomatedDaily: 50,
      responseTime: '<4 seconds',
      accuracyRate: '93.1%',
    },
    simulationConfig: {
      activityLogs: [
        'Updating Sales Battlecard for Competitor Z',
        'Analyzing earnings call transcripts',
        'Mapping competitive landscape',
        'Reviewing win/loss reasons',
        'Drafting strategic positioning memo',
      ],
      historyItems: [
        { task: 'Battlecard Update', result: 'v2.0 Live', status: 'Success' },
        { task: 'Win/Loss Analysis', result: 'Pricing is key factor', status: 'Success' },
        { task: 'Strategy Session', result: 'Completed', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-memory-context',
    name: 'Memory & Context Engine',
    title: 'Remembers Everything',
    description: 'Persistent context that remembers customers, deals, objections, and outcomes—so every agent gets smarter over time.',
    icon: Brain,
    color: '#5856D6',
    humanCost: '$0',
    aiCost: 'Included',
    efficiency: 'Compounding advantage',
    capabilities: ['Customer Memory', 'Deal Memory', 'Objection Memory', 'Outcome Learning', 'Cross-Agent Context', 'Preference Learning', 'Enterprise Knowledge Graph', 'Advanced Contextual Intelligence', 'Predictive Memory', 'Cross-Platform Integration', 'Real-time Learning', 'Institutional Knowledge Base'],
    route: '/ai-agent/memory-context',
    category: 'executive',
    type: 'agent',
    replacesRole: 'Institutional Knowledge + CRM Data Entry',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Always Active',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: 'Compounding',
      tasksAutomatedDaily: 10000,
      responseTime: '<0.1 seconds',
      accuracyRate: '99.9%',
    },
    isNew: true,
    dangerLevel: 'critical',
    simulationConfig: {
      activityLogs: [
        'Ingesting sales call transcripts',
        'Linking customer preference to deal outcome',
        'Updating global knowledge graph',
        'Pruning outdated context nodes',
        'Serving context to Sales Agent',
      ],
      historyItems: [
        { task: 'Knowledge Graph Update', result: '+50k Nodes', status: 'Success' },
        { task: 'Context Retrieval', result: '99% Hit Rate', status: 'Success' },
        { task: 'Memory Consolidation', result: 'Optimized', status: 'Success' },
      ],
    },
  },

  // ============================================
  // TRADING & INVESTMENT AI
  // ============================================
  {
    id: 'trading-investment-ai',
    name: 'Trading & Investment AI',
    title: 'Trading & Investment Orchestrator',
    description: 'Comprehensive AI-powered trading and investment platform. Orchestrates market analysis, algorithmic trading, portfolio management, and risk assessment across all asset classes.',
    icon: TrendingUp,
    color: '#00C853',
    humanCost: '$200k-$350k/year',
    aiCost: '$12k-$20k/year',
    efficiency: '18x efficiency',
    capabilities: ['Market Analysis', 'Algorithmic Trading', 'Portfolio Management', 'Risk Assessment', 'Sentiment Analysis', 'Technical Analysis', 'Fundamental Analysis', 'Crypto & DeFi', 'Forex Trading', 'Commodities', 'Quantitative Research', 'Macro Economics'],
    route: '/ai-agent/trading-investment-ai',
    category: 'trading-investment',
    type: 'employee',
    replacesRole: 'Portfolio Manager + Trading Analyst + Risk Manager',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$25,000',
      tasksAutomatedDaily: 5000,
      responseTime: '<0.1 seconds',
      accuracyRate: '98.5%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'critical',
    simulationConfig: {
      activityLogs: [
        'Scanning global markets for alpha opportunities',
        'Executing algorithmic trade on NASDAQ',
        'Rebalancing portfolio across asset classes',
        'Running risk exposure analysis',
        'Publishing macro economy briefing',
      ],
      historyItems: [
        { task: 'Portfolio Rebalance', result: '+12.4% YTD Return', status: 'Success' },
        { task: 'Risk Assessment', result: 'Low Exposure', status: 'Success' },
        { task: 'Market Signal Detected', result: 'Trade Executed', status: 'Success' },
      ],
    },
  },
  {
    id: 'ai-market-prediction',
    name: 'AI Market Prediction Agent',
    title: 'Market Forecasting AI',
    description: 'Uses machine learning models to predict market movements, identify trends, and generate high-accuracy forecasts across equities, forex, and crypto markets.',
    icon: LineChart,
    color: '#00E676',
    humanCost: '$90k-$130k/year',
    aiCost: '$5k-$9k/year',
    efficiency: '15x efficiency',
    capabilities: ['Price Forecasting', 'Trend Identification', 'ML Prediction Models', 'Volatility Analysis', 'Support/Resistance Detection', 'Market Regime Detection', 'Backtesting'],
    route: '/ai-agent/trading-investment/market-prediction',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Market Research Analyst + Quant Forecaster',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$12,000',
      tasksAutomatedDaily: 1000,
      responseTime: '<0.5 seconds',
      accuracyRate: '96.8%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-algorithmic-trading',
    name: 'AI Algorithmic Trading Agent',
    title: 'Algo Trading AI',
    description: 'Executes high-frequency algorithmic trading strategies with sub-millisecond precision. Manages order flow, optimizes execution, and adapts strategies in real-time.',
    icon: Zap,
    color: '#69F0AE',
    humanCost: '$120k-$180k/year',
    aiCost: '$8k-$14k/year',
    efficiency: '20x efficiency',
    capabilities: ['HFT Execution', 'Strategy Backtesting', 'Order Flow Management', 'Slippage Minimization', 'Multi-Exchange Trading', 'Latency Optimization', 'Strategy Adaptation'],
    route: '/ai-agent/trading-investment/algorithmic-trading',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Algorithmic Trader + Quantitative Developer',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$18,000',
      tasksAutomatedDaily: 50000,
      responseTime: '<0.01 seconds',
      accuracyRate: '98.2%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'critical',
  },
  {
    id: 'ai-portfolio-manager',
    name: 'AI Portfolio Manager',
    title: 'Portfolio Management AI',
    description: 'Manages investment portfolios with dynamic asset allocation, risk-adjusted returns optimization, and continuous rebalancing based on market conditions.',
    icon: PieChart,
    color: '#00C853',
    humanCost: '$100k-$160k/year',
    aiCost: '$7k-$12k/year',
    efficiency: '15x efficiency',
    capabilities: ['Asset Allocation', 'Portfolio Rebalancing', 'Risk-Adjusted Returns', 'Factor Analysis', 'Diversification', 'Performance Attribution', 'Tax-Loss Harvesting'],
    route: '/ai-agent/trading-investment/portfolio-manager',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Portfolio Manager + Investment Advisor',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$15,000',
      tasksAutomatedDaily: 500,
      responseTime: '<1 second',
      accuracyRate: '97.5%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-market-sentiment',
    name: 'AI Market Sentiment Analyst',
    title: 'Sentiment Analysis AI',
    description: 'Analyzes news, social media, earnings calls, and financial reports to gauge market sentiment and predict price movements based on crowd psychology.',
    icon: Activity,
    color: '#76FF03',
    humanCost: '$70k-$100k/year',
    aiCost: '$4k-$7k/year',
    efficiency: '15x efficiency',
    capabilities: ['Social Sentiment Analysis', 'News NLP Processing', 'Fear & Greed Index', 'Earnings Call Analysis', 'Reddit/Twitter Scanning', 'Sentiment Scoring', 'Crowd Psychology Metrics'],
    route: '/ai-agent/trading-investment/market-sentiment',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Sentiment Analyst + Market Intelligence Researcher',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$9,500',
      tasksAutomatedDaily: 10000,
      responseTime: '<0.3 seconds',
      accuracyRate: '94.7%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'medium',
  },
  {
    id: 'ai-technical-analysis',
    name: 'AI Technical Analysis Agent',
    title: 'Technical Analysis AI',
    description: 'Performs comprehensive technical analysis using 200+ indicators, chart pattern recognition, and multi-timeframe analysis to generate precise entry and exit signals.',
    icon: BarChart2,
    color: '#64FFDA',
    humanCost: '$75k-$110k/year',
    aiCost: '$4k-$8k/year',
    efficiency: '16x efficiency',
    capabilities: ['Chart Pattern Recognition', 'Indicator Analysis (RSI, MACD, BB)', 'Multi-Timeframe Analysis', 'Support/Resistance Levels', 'Volume Analysis', 'Wave Theory', 'Signal Generation'],
    route: '/ai-agent/trading-investment/technical-analysis',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Technical Analyst + Charting Specialist',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$10,500',
      tasksAutomatedDaily: 2000,
      responseTime: '<0.2 seconds',
      accuracyRate: '96.3%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-fundamental-analysis',
    name: 'AI Fundamental Analysis Agent',
    title: 'Fundamental Analysis AI',
    description: 'Deep dives into financial statements, earnings reports, valuation models (DCF, P/E, EV/EBITDA), and economic moats to identify undervalued investment opportunities.',
    icon: FileText,
    color: '#18FFFF',
    humanCost: '$85k-$125k/year',
    aiCost: '$5k-$9k/year',
    efficiency: '15x efficiency',
    capabilities: ['Financial Statement Analysis', 'DCF Valuation', 'Earnings Modeling', 'Ratio Analysis', 'Sector Comparison', 'Economic Moat Assessment', 'Fair Value Estimation'],
    route: '/ai-agent/trading-investment/fundamental-analysis',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Fundamental Analyst + Equity Research Analyst',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$13,000',
      tasksAutomatedDaily: 300,
      responseTime: '<2 seconds',
      accuracyRate: '95.8%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-trading-risk-manager',
    name: 'AI Trading Risk Manager',
    title: 'Risk Management AI',
    description: 'Monitors real-time portfolio risk exposure, enforces position sizing rules, manages drawdown limits, and triggers automated hedging strategies to protect capital.',
    icon: Shield,
    color: '#FF5252',
    humanCost: '$90k-$140k/year',
    aiCost: '$6k-$11k/year',
    efficiency: '14x efficiency',
    capabilities: ['Position Sizing', 'Drawdown Management', 'VaR Calculation', 'Hedging Automation', 'Correlation Analysis', 'Stress Testing', 'Stop-Loss Management'],
    route: '/ai-agent/trading-investment/trading-risk-manager',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Risk Manager + Compliance Officer (Trading)',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$20,000',
      tasksAutomatedDaily: 8000,
      responseTime: '<0.05 seconds',
      accuracyRate: '99.1%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'critical',
  },
  {
    id: 'ai-futures-options',
    name: 'AI Futures & Options Agent',
    title: 'Derivatives Trading AI',
    description: 'Specializes in derivatives markets including futures contracts and options strategies. Manages complex multi-leg options positions, Greeks, and expiration management.',
    icon: TrendingDown,
    color: '#FF4081',
    humanCost: '$100k-$150k/year',
    aiCost: '$7k-$12k/year',
    efficiency: '14x efficiency',
    capabilities: ['Options Strategy Builder', 'Greeks Management (Delta, Gamma, Theta)', 'Expiration Management', 'Futures Rollover', 'Covered Calls', 'Iron Condors', 'Spread Trading'],
    route: '/ai-agent/trading-investment/futures-options',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Derivatives Trader + Options Strategist',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$16,000',
      tasksAutomatedDaily: 1500,
      responseTime: '<0.1 seconds',
      accuracyRate: '95.2%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'critical',
  },
  {
    id: 'ai-crypto-defi',
    name: 'AI Crypto & DeFi Analyst',
    title: 'Cryptocurrency Analysis AI',
    description: 'Monitors crypto markets across 500+ tokens, analyzes DeFi protocols, identifies yield farming opportunities, and executes on-chain transactions with gas optimization.',
    icon: Coins,
    color: '#F50057',
    humanCost: '$80k-$120k/year',
    aiCost: '$5k-$9k/year',
    efficiency: '15x efficiency',
    capabilities: ['Crypto Price Analysis', 'DeFi Protocol Monitoring', 'Yield Farming Optimization', 'On-Chain Analytics', 'NFT Market Analysis', 'Gas Optimization', 'Wallet Tracking'],
    route: '/ai-agent/trading-investment/crypto-defi',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Crypto Analyst + DeFi Researcher',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$14,000',
      tasksAutomatedDaily: 20000,
      responseTime: '<0.2 seconds',
      accuracyRate: '93.8%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-forex-trading',
    name: 'AI Forex Trading Agent',
    title: 'Currency Trading AI',
    description: 'Trades the $7.5 trillion daily forex market across 60+ currency pairs. Analyzes macroeconomic data, central bank policy, and carries out carry trade and momentum strategies.',
    icon: Globe,
    color: '#D500F9',
    humanCost: '$85k-$130k/year',
    aiCost: '$5k-$9k/year',
    efficiency: '16x efficiency',
    capabilities: ['Major/Minor/Exotic Pairs', 'Carry Trade Strategy', 'Central Bank Monitoring', 'Currency Correlation Analysis', 'Economic Data Trading', 'Pip Optimization', 'Multi-Pair Management'],
    route: '/ai-agent/trading-investment/forex-trading',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Forex Trader + Currency Analyst',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$13,500',
      tasksAutomatedDaily: 30000,
      responseTime: '<0.05 seconds',
      accuracyRate: '94.5%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-commodities',
    name: 'AI Commodities Agent',
    title: 'Commodities Trading AI',
    description: 'Trades energy, metals, and agricultural commodities. Monitors supply/demand dynamics, geopolitical events, and seasonal patterns to capitalize on commodity price movements.',
    icon: BarChart3,
    color: '#FF6D00',
    humanCost: '$80k-$120k/year',
    aiCost: '$5k-$8k/year',
    efficiency: '15x efficiency',
    capabilities: ['Energy Markets (Oil & Gas)', 'Precious Metals Analysis', 'Agricultural Commodities', 'Supply Chain Intelligence', 'Seasonal Pattern Trading', 'Geopolitical Risk Monitoring', 'COT Report Analysis'],
    route: '/ai-agent/trading-investment/commodities',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Commodities Trader + Commodity Research Analyst',
    infrastructure: {
      status: 'online',
      health: 97,
      uptime: '99.9%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$11,000',
      tasksAutomatedDaily: 2000,
      responseTime: '<0.3 seconds',
      accuracyRate: '93.2%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'medium',
  },
  {
    id: 'ai-quantitative-researcher',
    name: 'AI Quantitative Researcher',
    title: 'Quantitative Research AI',
    description: 'Develops and backtests quantitative trading strategies using statistical models, machine learning, and factor-based approaches to generate consistent alpha.',
    icon: FlaskConical,
    color: '#651FFF',
    humanCost: '$130k-$200k/year',
    aiCost: '$9k-$16k/year',
    efficiency: '14x efficiency',
    capabilities: ['Strategy Development', 'Statistical Backtesting', 'Factor Model Research', 'Alpha Generation', 'Walk-Forward Testing', 'Monte Carlo Simulation', 'Statistical Arbitrage'],
    route: '/ai-agent/trading-investment/quantitative-researcher',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Quantitative Researcher + Quant Developer',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$19,000',
      tasksAutomatedDaily: 500,
      responseTime: '<3 seconds',
      accuracyRate: '97.1%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'critical',
  },
  {
    id: 'ai-futures-preview',
    name: 'AI Futures Preview Agent',
    title: 'Futures Market Preview AI',
    description: 'Provides pre-market futures analysis and overnight session intelligence. Monitors global futures markets to give traders a decisive edge before market open.',
    icon: Clock,
    color: '#7C4DFF',
    humanCost: '$60k-$90k/year',
    aiCost: '$3.5k-$6k/year',
    efficiency: '16x efficiency',
    capabilities: ['Pre-Market Analysis', 'Overnight Session Monitoring', 'Gap Analysis', 'Global Futures Scanning', 'Economic Calendar Integration', 'Opening Range Prediction', 'Market Open Scenarios'],
    route: '/ai-agent/trading-investment/futures-preview',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Pre-Market Analyst + Overnight Trader',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$8,500',
      tasksAutomatedDaily: 1000,
      responseTime: '<0.5 seconds',
      accuracyRate: '93.6%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'medium',
  },
  {
    id: 'ai-copy-trading',
    name: 'AI Copy Trading Agent',
    title: 'Social Trading AI',
    description: 'Identifies top-performing traders, analyzes their strategies, and enables intelligent copy trading with position sizing adjustments and risk filters.',
    icon: Users,
    color: '#B388FF',
    humanCost: '$55k-$85k/year',
    aiCost: '$3k-$6k/year',
    efficiency: '15x efficiency',
    capabilities: ['Trader Performance Analysis', 'Strategy Copying', 'Risk-Adjusted Position Sizing', 'Trader Scoring', 'Drawdown Filtering', 'Auto-Follow Management', 'Portfolio Diversification'],
    route: '/ai-agent/trading-investment/copy-trading',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Social Trading Manager + Fund of Funds Analyst',
    infrastructure: {
      status: 'online',
      health: 97,
      uptime: '99.9%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$9,000',
      tasksAutomatedDaily: 3000,
      responseTime: '<0.5 seconds',
      accuracyRate: '92.4%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'medium',
  },
  {
    id: 'ai-macro-economy',
    name: 'AI Macro Economy Analyst',
    title: 'Macroeconomic Analysis AI',
    description: 'Analyzes global macroeconomic trends, central bank policies, interest rate cycles, and geopolitical events to position portfolios for major economic shifts.',
    icon: Globe,
    color: '#8C9EFF',
    humanCost: '$100k-$150k/year',
    aiCost: '$6k-$11k/year',
    efficiency: '14x efficiency',
    capabilities: ['GDP & Inflation Analysis', 'Central Bank Policy Monitoring', 'Interest Rate Cycle Mapping', 'Geopolitical Risk Assessment', 'Currency Regime Analysis', 'Global Trade Flow Analysis', 'Economic Scenario Planning'],
    route: '/ai-agent/trading-investment/macro-economy',
    category: 'trading-investment',
    type: 'agent',
    replacesRole: 'Macro Economist + Global Strategist',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$14,500',
      tasksAutomatedDaily: 800,
      responseTime: '<1.5 seconds',
      accuracyRate: '95.4%',
    },
    isNew: true,
    isPremium: true,
    dangerLevel: 'critical',
  },
];

export const aiEmployeeCategories = [
  { id: 'all', label: 'All', icon: Bot },
  { id: 'employees', label: 'AI Employees', icon: Users },
  { id: 'agents', label: 'AI Agents', icon: Cpu },
  { id: 'executive', label: 'Executive', icon: Briefcase },
  { id: 'accounting', label: 'Accounting', icon: Calculator },
  { id: 'support', label: 'Customer', icon: Headphones },
  { id: 'sales', label: 'Sales', icon: Target },
  { id: 'marketing', label: 'Marketing', icon: Megaphone },
  { id: 'operations', label: 'Operations', icon: Settings },
  { id: 'social-media', label: 'Social Media', icon: Share2 },
  { id: 'analytics', label: 'Analytics', icon: BarChart3 },
  { id: 'hr', label: 'HR', icon: UserCheck },
  { id: 'it-tech', label: 'IT', icon: Monitor },
  { id: 'legal-compliance', label: 'Legal', icon: Scale },
  { id: 'engineering-dev', label: 'Engineering', icon: Code },
  { id: 'personal-assistant', label: 'Assistant', icon: Brain },
  { id: 'trading-investment', label: 'Trading', icon: TrendingUp },
];

// Infrastructure summary stats
export const aiInfrastructureStats = {
  totalEmployees: aiEmployees.filter(e => e.type === 'employee').length,
  totalAgents: aiEmployees.filter(e => e.type === 'agent').length,
  onlineCount: aiEmployees.filter(e => e.infrastructure.status === 'online').length,
  averageHealth: Math.round(aiEmployees.reduce((sum, e) => sum + e.infrastructure.health, 0) / aiEmployees.length),
  totalMonthlySavings: '$250,000+',
  totalTasksAutomatedDaily: aiEmployees.reduce((sum, e) => sum + e.roiMetrics.tasksAutomatedDaily, 0),
};
