import {
  Phone,
  Users,
  DollarSign,
  Headphones,
  Megaphone,
  UserCheck,
  Briefcase,
  Settings,
  BarChart3,
  Target,
  Database,
  Handshake,
  TrendingUp,
  Zap,
  Eye,
  Shield,
  PiggyBank,
  Search,
  Globe,
  UserPlus,
  Share2,
  Bot,
  Brain,
  Cpu,
  Server,
  Activity,
  Clock,
  Sparkles,
  CircleDollarSign,
} from 'lucide-react-native';
import type { LucideIcon } from 'lucide-react-native';

export interface AIInfrastructure {
  status: 'online' | 'processing' | 'standby' | 'maintenance';
  health: number; // 0-100
  uptime: string;
  lastActive: string;
  processingPower: 'standard' | 'high' | 'enterprise';
}

export interface AIROIMetrics {
  savingsPerMonth: string;
  tasksAutomatedDaily: number;
  responseTime: string;
  accuracyRate: string;
}

export interface AIEmployee {
  id: string;
  name: string;
  title: string;
  description: string;
  icon: LucideIcon;
  color: string;
  humanCost: string;
  aiCost: string;
  efficiency: string;
  capabilities: string[];
  route: string;
  category: 'sales' | 'marketing' | 'operations' | 'support' | 'analytics' | 'executive';
  type: 'employee' | 'agent';
  replacesRole: string;
  infrastructure: AIInfrastructure;
  roiMetrics: AIROIMetrics;
  isNew?: boolean;
  isPremium?: boolean;
  dangerLevel?: 'low' | 'medium' | 'high' | 'critical'; // How disruptive to incumbents
}

export const aiEmployees: AIEmployee[] = [
  // ============================================
  // AI EMPLOYEES - Full Role Replacements
  // ============================================
  {
    id: 'ai-receptionist',
    name: 'AI Receptionist',
    title: 'Front Desk + Call Center',
    description: 'Handles incoming calls, routes inquiries, schedules appointments, and provides 24/7 customer service with human-like conversation.',
    icon: Phone,
    color: '#007AFF',
    humanCost: '$30k/year',
    aiCost: '$1.5k/year',
    efficiency: '20x cost efficiency',
    capabilities: ['Call Routing', 'Appointment Scheduling', 'FAQ Handling', 'Lead Capture', 'Voicemail Management', 'Multi-language Support'],
    route: '/ai-receptionist/dashboard',
    category: 'support',
    type: 'employee',
    replacesRole: 'Front desk receptionist + Call center agents',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$2,375',
      tasksAutomatedDaily: 150,
      responseTime: '<1 second',
      accuracyRate: '98.5%',
    },
  },
  {
    id: 'ai-sales-rep',
    name: 'AI Sales Rep',
    title: 'SDR + Junior AE',
    description: 'Prospects, qualifies leads, handles initial outreach, and nurtures relationships through the sales funnel. Zero churn, infinite patience.',
    icon: UserCheck,
    color: '#34C759',
    humanCost: '$60k-$90k/year',
    aiCost: '$3k-$6k/year',
    efficiency: '15x efficiency + zero churn',
    capabilities: ['Lead Qualification', 'Cold Outreach', 'Follow-up Sequences', 'Meeting Booking', 'CRM Updates', 'Objection Handling'],
    route: '/ai-agent/ai-agent',
    category: 'sales',
    type: 'employee',
    replacesRole: 'SDR + Junior Account Executive',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$5,500',
      tasksAutomatedDaily: 200,
      responseTime: '<2 seconds',
      accuracyRate: '96.8%',
    },
  },
  {
    id: 'ai-sales-executive',
    name: 'AI Sales Executive',
    title: 'Full Sales Cycle Manager',
    description: 'Runs complete sales cycles from prospecting to closing. Advanced negotiation, deal management, and revenue forecasting.',
    icon: Briefcase,
    color: '#5856D6',
    humanCost: '$100k-$150k/year',
    aiCost: '$8k-$12k/year',
    efficiency: '12x efficiency',
    capabilities: ['Full Cycle Sales', 'Contract Negotiation', 'Pipeline Management', 'Revenue Forecasting', 'Account Strategy', 'Enterprise Deals'],
    route: '/ai-negotiation/dashboard',
    category: 'sales',
    type: 'employee',
    replacesRole: 'Senior Account Executive + Sales Manager',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$9,500',
      tasksAutomatedDaily: 85,
      responseTime: '<3 seconds',
      accuracyRate: '94.2%',
    },
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-customer-support',
    name: 'AI Customer Support Agent',
    title: 'Tier 1 & 2 Support',
    description: 'Resolves customer issues, handles tickets, provides product support, and escalates complex cases intelligently.',
    icon: Headphones,
    color: '#FF9500',
    humanCost: '$40k-$55k/year',
    aiCost: '$2k-$4k/year',
    efficiency: '15x efficiency',
    capabilities: ['Ticket Resolution', 'Live Chat', 'Email Support', 'Knowledge Base', 'Escalation Management', 'Sentiment Analysis'],
    route: '/business/customer-support',
    category: 'support',
    type: 'employee',
    replacesRole: 'Customer Support Representatives (Tier 1 & 2)',
    infrastructure: {
      status: 'online',
      health: 97,
      uptime: '99.9%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$3,250',
      tasksAutomatedDaily: 300,
      responseTime: '<1 second',
      accuracyRate: '97.3%',
    },
  },
  {
    id: 'ai-cmo',
    name: 'AI Chief Marketing Officer',
    title: 'AI-CMO',
    description: 'Develops marketing strategy, manages campaigns, analyzes performance, and optimizes marketing ROI across all channels.',
    icon: Megaphone,
    color: '#FF2D55',
    humanCost: '$150k-$250k/year',
    aiCost: '$10k-$15k/year',
    efficiency: '15x efficiency',
    capabilities: ['Strategy Development', 'Campaign Management', 'Brand Positioning', 'Market Analysis', 'Budget Optimization', 'Creative Direction'],
    route: '/marketing/marketing-hub',
    category: 'executive',
    type: 'employee',
    replacesRole: 'Chief Marketing Officer + Marketing Director',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$15,000',
      tasksAutomatedDaily: 50,
      responseTime: '<5 seconds',
      accuracyRate: '92.5%',
    },
    isPremium: true,
    dangerLevel: 'critical',
  },
  {
    id: 'ai-product-manager',
    name: 'AI Product Manager',
    title: 'Product Strategy & Roadmap',
    description: 'Analyzes market trends, prioritizes features, manages backlog, and aligns product with business goals.',
    icon: Settings,
    color: '#AF52DE',
    humanCost: '$120k-$180k/year',
    aiCost: '$6k-$10k/year',
    efficiency: '15x efficiency',
    capabilities: ['Feature Prioritization', 'Roadmap Planning', 'User Research', 'Competitive Analysis', 'Sprint Planning', 'Stakeholder Alignment'],
    route: '/collaboration/project-management',
    category: 'operations',
    type: 'employee',
    replacesRole: 'Product Manager + Product Owner',
    infrastructure: {
      status: 'online',
      health: 96,
      uptime: '99.8%',
      lastActive: '2 min ago',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$11,000',
      tasksAutomatedDaily: 40,
      responseTime: '<4 seconds',
      accuracyRate: '91.8%',
    },
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-operations-manager',
    name: 'AI Operations Manager',
    title: 'Ops Manager + Team Lead',
    description: 'Oversees daily operations, optimizes workflows, manages resources, and ensures team productivity.',
    icon: Users,
    color: '#FF6482',
    humanCost: '$80k-$120k/year',
    aiCost: '$5k-$8k/year',
    efficiency: '15x efficiency',
    capabilities: ['Workflow Optimization', 'Resource Allocation', 'Performance Tracking', 'Process Automation', 'Team Coordination', 'Bottleneck Detection'],
    route: '/automation/workflow-management',
    category: 'operations',
    type: 'employee',
    replacesRole: 'Operations Manager + Team Lead',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$7,500',
      tasksAutomatedDaily: 120,
      responseTime: '<2 seconds',
      accuracyRate: '95.6%',
    },
    isPremium: true,
    dangerLevel: 'critical',
  },
  {
    id: 'ai-manager',
    name: 'AI Manager',
    title: 'The Most Dangerous One',
    description: 'Coordinates teams, enforces execution, identifies bottlenecks, and keeps initiatives moving. This terrifies incumbents.',
    icon: Cpu,
    color: '#FF3B30',
    humanCost: '$80k-$120k/year',
    aiCost: '$5k-$8k/year',
    efficiency: '15x efficiency',
    capabilities: ['Team Coordination', 'Execution Tracking', 'Daily Standups', 'KPI Monitoring', 'Process Optimization', 'Decision Automation'],
    route: '/automation/team-performance',
    category: 'operations',
    type: 'employee',
    replacesRole: 'Operations Manager + Team Lead + Project Manager',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$8,000',
      tasksAutomatedDaily: 180,
      responseTime: '<1 second',
      accuracyRate: '97.8%',
    },
    isPremium: true,
    isNew: true,
    dangerLevel: 'critical',
  },
  {
    id: 'ai-recruiter',
    name: 'AI Recruiter',
    title: 'Talent Acquisition',
    description: 'Sources candidates, screens resumes, schedules interviews, and manages the hiring pipeline end-to-end.',
    icon: UserPlus,
    color: '#5AC8FA',
    humanCost: '$60k-$90k/year',
    aiCost: '$4k-$7k/year',
    efficiency: '15x efficiency',
    capabilities: ['Candidate Sourcing', 'Resume Screening', 'Interview Scheduling', 'Pipeline Management', 'Offer Management', 'Culture Fit Analysis'],
    route: '/collaboration/team-management',
    category: 'operations',
    type: 'employee',
    replacesRole: 'Recruiter + Talent Acquisition Specialist',
    infrastructure: {
      status: 'online',
      health: 95,
      uptime: '99.8%',
      lastActive: '5 min ago',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$5,500',
      tasksAutomatedDaily: 75,
      responseTime: '<3 seconds',
      accuracyRate: '93.4%',
    },
    isNew: true,
    dangerLevel: 'medium',
  },
  {
    id: 'ai-social-media-manager',
    name: 'AI Social Media Manager',
    title: 'Social Media Strategy & Execution',
    description: 'Manages social presence, creates content, engages audience, and analyzes social performance 24/7.',
    icon: Share2,
    color: '#1DA1F2',
    humanCost: '$50k-$75k/year',
    aiCost: '$2.5k-$4.5k/year',
    efficiency: '18x efficiency',
    capabilities: ['Content Creation', 'Post Scheduling', 'Community Management', 'Analytics', 'Trend Monitoring', 'Influencer Outreach'],
    route: '/marketing/social-media-management',
    category: 'marketing',
    type: 'employee',
    replacesRole: 'Social Media Manager + Community Manager',
    infrastructure: {
      status: 'online',
      health: 97,
      uptime: '99.9%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$4,200',
      tasksAutomatedDaily: 95,
      responseTime: '<2 seconds',
      accuracyRate: '94.7%',
    },
    dangerLevel: 'medium',
  },
  {
    id: 'ai-marketer',
    name: 'AI Marketer',
    title: 'Digital Marketing Specialist',
    description: 'Executes multi-channel marketing campaigns, creates content, and drives brand awareness across all platforms.',
    icon: Globe,
    color: '#FF2D55',
    humanCost: '$55k-$80k/year',
    aiCost: '$3k-$5k/year',
    efficiency: '18x efficiency',
    capabilities: ['Content Marketing', 'Email Campaigns', 'Social Media', 'SEO/SEM', 'Lead Nurturing', 'Performance Marketing'],
    route: '/marketing/advance-marketing',
    category: 'marketing',
    type: 'employee',
    replacesRole: 'Digital Marketing Specialist + Content Marketer',
    infrastructure: {
      status: 'online',
      health: 96,
      uptime: '99.85%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$4,500',
      tasksAutomatedDaily: 110,
      responseTime: '<2 seconds',
      accuracyRate: '93.9%',
    },
    dangerLevel: 'medium',
  },

  // ============================================
  // AI AGENTS - Specialized Task Automation
  // ============================================
  {
    id: 'ai-sales-agent',
    name: 'AI Sales Agent',
    title: 'Automated Sales Assistant',
    description: 'Engages prospects, handles objections, presents solutions, and drives conversions autonomously.',
    icon: Target,
    color: '#00C7BE',
    humanCost: '$50k-$70k/year',
    aiCost: '$3k-$5k/year',
    efficiency: '15x efficiency',
    capabilities: ['Prospect Engagement', 'Objection Handling', 'Product Demos', 'Quote Generation', 'Deal Closing', 'Follow-up Automation'],
    route: '/automation/sales-automation',
    category: 'sales',
    type: 'agent',
    replacesRole: 'Sales Assistant + Inside Sales Rep',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.9%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$4,000',
      tasksAutomatedDaily: 150,
      responseTime: '<1 second',
      accuracyRate: '95.2%',
    },
  },
  {
    id: 'ai-data-analyst',
    name: 'AI Data Analyst Agent',
    title: 'Analytics & Insights',
    description: 'Collects, analyzes, and visualizes data to provide actionable insights and business intelligence.',
    icon: BarChart3,
    color: '#5AC8FA',
    humanCost: '$70k-$100k/year',
    aiCost: '$4k-$7k/year',
    efficiency: '15x efficiency',
    capabilities: ['Data Analysis', 'Report Generation', 'Trend Identification', 'Predictive Modeling', 'Dashboard Creation', 'Anomaly Detection'],
    route: '/ai-agent/ai-data-analytics',
    category: 'analytics',
    type: 'agent',
    replacesRole: 'Data Analyst + Business Intelligence Analyst',
    infrastructure: {
      status: 'processing',
      health: 94,
      uptime: '99.7%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$6,500',
      tasksAutomatedDaily: 45,
      responseTime: '<5 seconds',
      accuracyRate: '96.1%',
    },
  },
  {
    id: 'ai-lead-dev-rep',
    name: 'AI Lead Development Rep',
    title: 'Lead Generation Specialist',
    description: 'Identifies potential customers, qualifies leads, and builds pipeline through targeted outreach.',
    icon: UserPlus,
    color: '#4CD964',
    humanCost: '$45k-$65k/year',
    aiCost: '$2.5k-$4k/year',
    efficiency: '18x efficiency',
    capabilities: ['Lead Sourcing', 'Prospect Research', 'Initial Outreach', 'Lead Scoring', 'Pipeline Building', 'Contact Enrichment'],
    route: '/automation/lead-generation',
    category: 'sales',
    type: 'agent',
    replacesRole: 'Lead Development Representative',
    infrastructure: {
      status: 'online',
      health: 97,
      uptime: '99.85%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$3,750',
      tasksAutomatedDaily: 200,
      responseTime: '<2 seconds',
      accuracyRate: '94.5%',
    },
  },
  {
    id: 'ai-crm-assistant',
    name: 'AI CRM Assistant',
    title: 'CRM Management & Automation',
    description: 'Maintains CRM data, automates updates, tracks interactions, and provides relationship insights.',
    icon: Database,
    color: '#8E8E93',
    humanCost: '$45k-$60k/year',
    aiCost: '$2k-$4k/year',
    efficiency: '20x efficiency',
    capabilities: ['Data Entry', 'Contact Management', 'Activity Logging', 'Pipeline Updates', 'Relationship Tracking', 'Data Hygiene'],
    route: '/business/crm',
    category: 'operations',
    type: 'agent',
    replacesRole: 'CRM Administrator + Data Entry Clerk',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.99%',
      lastActive: 'Now',
      processingPower: 'standard',
    },
    roiMetrics: {
      savingsPerMonth: '$3,500',
      tasksAutomatedDaily: 500,
      responseTime: '<1 second',
      accuracyRate: '99.2%',
    },
  },
  {
    id: 'ai-negotiator',
    name: 'AI Negotiator',
    title: 'Deal Negotiation Expert',
    description: 'Handles complex negotiations, optimizes deal terms, and maximizes value while maintaining relationships.',
    icon: Handshake,
    color: '#FF3B30',
    humanCost: '$90k-$140k/year',
    aiCost: '$6k-$10k/year',
    efficiency: '12x efficiency',
    capabilities: ['Price Negotiation', 'Contract Terms', 'Objection Handling', 'Win-Win Solutions', 'Deal Structuring', 'BATNA Analysis'],
    route: '/ai-negotiation/dashboard',
    category: 'sales',
    type: 'agent',
    replacesRole: 'Negotiation Specialist + Deal Desk',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$8,000',
      tasksAutomatedDaily: 25,
      responseTime: '<3 seconds',
      accuracyRate: '91.5%',
    },
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-sales-data-analyst',
    name: 'AI Sales Data Analyst',
    title: 'Sales Intelligence',
    description: 'Analyzes sales data, identifies trends, forecasts revenue, and provides sales optimization insights.',
    icon: TrendingUp,
    color: '#30B0C7',
    humanCost: '$65k-$90k/year',
    aiCost: '$3.5k-$6k/year',
    efficiency: '15x efficiency',
    capabilities: ['Sales Analytics', 'Revenue Forecasting', 'Performance Metrics', 'Conversion Analysis', 'Trend Detection', 'Win/Loss Analysis'],
    route: '/analytics/analytics-performance',
    category: 'analytics',
    type: 'agent',
    replacesRole: 'Sales Analyst + Revenue Operations Analyst',
    infrastructure: {
      status: 'online',
      health: 96,
      uptime: '99.8%',
      lastActive: '1 min ago',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$5,750',
      tasksAutomatedDaily: 60,
      responseTime: '<4 seconds',
      accuracyRate: '94.8%',
    },
  },
  {
    id: 'ai-campaign-optimizer',
    name: 'AI Campaign Optimizer',
    title: 'Marketing Campaign AI',
    description: 'Optimizes marketing campaigns in real-time, adjusts targeting, and maximizes campaign ROI.',
    icon: Zap,
    color: '#FFCC00',
    humanCost: '$55k-$80k/year',
    aiCost: '$3k-$5k/year',
    efficiency: '18x efficiency',
    capabilities: ['A/B Testing', 'Audience Optimization', 'Budget Allocation', 'Performance Tracking', 'Creative Testing', 'Real-time Bidding'],
    route: '/marketing/campaign',
    category: 'marketing',
    type: 'agent',
    replacesRole: 'Campaign Manager + Media Buyer',
    infrastructure: {
      status: 'processing',
      health: 95,
      uptime: '99.7%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$4,500',
      tasksAutomatedDaily: 1000,
      responseTime: '<0.5 seconds',
      accuracyRate: '96.3%',
    },
  },
  {
    id: 'ai-competitive-intel',
    name: 'AI Competitive Intelligence Agent',
    title: 'Market & Competitor Analysis',
    description: 'Monitors competitors, analyzes market trends, and provides strategic intelligence for decision making.',
    icon: Eye,
    color: '#5856D6',
    humanCost: '$70k-$100k/year',
    aiCost: '$4k-$7k/year',
    efficiency: '15x efficiency',
    capabilities: ['Competitor Monitoring', 'Market Analysis', 'Pricing Intelligence', 'SWOT Analysis', 'Trend Forecasting', 'News Aggregation'],
    route: '/ai-negotiation/competitor-analysis',
    category: 'analytics',
    type: 'agent',
    replacesRole: 'Competitive Intelligence Analyst + Market Researcher',
    infrastructure: {
      status: 'online',
      health: 97,
      uptime: '99.85%',
      lastActive: 'Now',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$6,000',
      tasksAutomatedDaily: 80,
      responseTime: '<3 seconds',
      accuracyRate: '93.7%',
    },
  },
  {
    id: 'ai-negotiation-specialist',
    name: 'AI Negotiation Specialist',
    title: 'Advanced Deal Specialist',
    description: 'Specializes in high-stakes negotiations, complex deals, and enterprise contract management.',
    icon: Shield,
    color: '#FF9500',
    humanCost: '$100k-$150k/year',
    aiCost: '$7k-$12k/year',
    efficiency: '12x efficiency',
    capabilities: ['Enterprise Deals', 'Contract Review', 'Risk Assessment', 'Terms Optimization', 'Stakeholder Management', 'Legal Compliance'],
    route: '/ai-agent/ai-negotiation-assistant',
    category: 'sales',
    type: 'agent',
    replacesRole: 'Enterprise Sales Negotiator + Contract Manager',
    infrastructure: {
      status: 'online',
      health: 99,
      uptime: '99.95%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$10,500',
      tasksAutomatedDaily: 15,
      responseTime: '<5 seconds',
      accuracyRate: '92.1%',
    },
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-retention-specialist',
    name: 'AI Retention Specialist',
    title: 'Customer Retention & Success',
    description: 'Identifies at-risk customers, implements retention strategies, and drives customer lifetime value.',
    icon: PiggyBank,
    color: '#34C759',
    humanCost: '$60k-$85k/year',
    aiCost: '$3.5k-$6k/year',
    efficiency: '15x efficiency',
    capabilities: ['Churn Prediction', 'Retention Campaigns', 'Customer Health', 'Upsell Identification', 'Loyalty Programs', 'Win-back Campaigns'],
    route: '/business/customer-management',
    category: 'support',
    type: 'agent',
    replacesRole: 'Customer Success Manager + Retention Specialist',
    infrastructure: {
      status: 'online',
      health: 96,
      uptime: '99.8%',
      lastActive: '3 min ago',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$5,000',
      tasksAutomatedDaily: 90,
      responseTime: '<2 seconds',
      accuracyRate: '94.2%',
    },
  },
  {
    id: 'ai-pricing-strategist',
    name: 'AI Pricing Strategist',
    title: 'Dynamic Pricing Expert',
    description: 'Optimizes pricing strategies, analyzes market conditions, and maximizes revenue through smart pricing.',
    icon: DollarSign,
    color: '#4CD964',
    humanCost: '$80k-$120k/year',
    aiCost: '$5k-$8k/year',
    efficiency: '15x efficiency',
    capabilities: ['Dynamic Pricing', 'Competitive Analysis', 'Margin Optimization', 'Discount Strategy', 'Bundle Pricing', 'Price Elasticity'],
    route: '/ai-negotiation/deal-scoring',
    category: 'analytics',
    type: 'agent',
    replacesRole: 'Pricing Analyst + Revenue Manager',
    infrastructure: {
      status: 'online',
      health: 98,
      uptime: '99.9%',
      lastActive: 'Now',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: '$7,500',
      tasksAutomatedDaily: 35,
      responseTime: '<3 seconds',
      accuracyRate: '95.5%',
    },
    isPremium: true,
    dangerLevel: 'high',
  },
  {
    id: 'ai-competitive-analyst',
    name: 'AI Competitive Analyst',
    title: 'Competitive Strategy',
    description: 'Deep competitive analysis, battlecard creation, and strategic positioning recommendations.',
    icon: Search,
    color: '#AF52DE',
    humanCost: '$65k-$95k/year',
    aiCost: '$4k-$6k/year',
    efficiency: '15x efficiency',
    capabilities: ['Battlecard Creation', 'Win/Loss Analysis', 'Feature Comparison', 'Market Positioning', 'Strategy Recommendations', 'Threat Assessment'],
    route: '/ai-negotiation/competitor-analysis',
    category: 'analytics',
    type: 'agent',
    replacesRole: 'Competitive Analyst + Strategy Consultant',
    infrastructure: {
      status: 'online',
      health: 95,
      uptime: '99.75%',
      lastActive: '5 min ago',
      processingPower: 'high',
    },
    roiMetrics: {
      savingsPerMonth: '$5,500',
      tasksAutomatedDaily: 50,
      responseTime: '<4 seconds',
      accuracyRate: '93.1%',
    },
  },
  {
    id: 'ai-memory-context',
    name: 'Memory & Context Engine',
    title: 'Remembers Everything',
    description: 'Persistent context that remembers customers, deals, objections, and outcomes—so every agent gets smarter over time.',
    icon: Brain,
    color: '#5856D6',
    humanCost: '$0',
    aiCost: 'Included',
    efficiency: 'Compounding advantage',
    capabilities: ['Customer Memory', 'Deal Memory', 'Objection Memory', 'Outcome Learning', 'Cross-Agent Context', 'Preference Learning'],
    route: '/ai-agent/memory-context',
    category: 'executive',
    type: 'agent',
    replacesRole: 'Institutional Knowledge + CRM Data Entry',
    infrastructure: {
      status: 'online',
      health: 100,
      uptime: '99.999%',
      lastActive: 'Always Active',
      processingPower: 'enterprise',
    },
    roiMetrics: {
      savingsPerMonth: 'Compounding',
      tasksAutomatedDaily: 10000,
      responseTime: '<0.1 seconds',
      accuracyRate: '99.9%',
    },
    isNew: true,
    dangerLevel: 'critical',
  },
];

export const aiEmployeeCategories = [
  { id: 'all', label: 'All', icon: Bot },
  { id: 'employees', label: 'AI Employees', icon: Users },
  { id: 'agents', label: 'AI Agents', icon: Cpu },
  { id: 'sales', label: 'Sales', icon: Target },
  { id: 'marketing', label: 'Marketing', icon: Megaphone },
  { id: 'support', label: 'Support', icon: Headphones },
  { id: 'operations', label: 'Operations', icon: Settings },
  { id: 'analytics', label: 'Analytics', icon: BarChart3 },
  { id: 'executive', label: 'Executive', icon: Briefcase },
];

// Infrastructure summary stats
export const aiInfrastructureStats = {
  totalEmployees: aiEmployees.filter(e => e.type === 'employee').length,
  totalAgents: aiEmployees.filter(e => e.type === 'agent').length,
  onlineCount: aiEmployees.filter(e => e.infrastructure.status === 'online').length,
  averageHealth: Math.round(aiEmployees.reduce((sum, e) => sum + e.infrastructure.health, 0) / aiEmployees.length),
  totalMonthlySavings: '$125,000+',
  totalTasksAutomatedDaily: aiEmployees.reduce((sum, e) => sum + e.roiMetrics.tasksAutomatedDaily, 0),
};
