export type DepartmentDashboard = {
  id: string;
  number: number;
  name: string;
  shortName: string;
  category: string;
  route: string;
  color: string;
  accent: string;
  agents: number;
  employees: number;
  automation: number;
  efficiency: number;
  risk: number;
  headlineMetric: string;
  headlineLabel: string;
  secondaryMetric: string;
  secondaryLabel: string;
  movement: number;
  chart: number[];
  pipeline: string[];
  allocation: Array<{ label: string; value: number }>;
  signals: Array<{ label: string; value: string; tone: 'up' | 'down' | 'flat' }>;
  watchlist: string[];
};

const buildChart = (seed: number) =>
  Array.from({ length: 12 }, (_, index) => {
    const wave = ((seed * 11 + index * 17) % 42) + 38;
    const lift = index > 7 ? 8 : index > 3 ? 4 : 0;
    return Math.min(96, wave + lift);
  });

const departments: Array<Omit<DepartmentDashboard, 'chart'>> = [
  {
    id: 'executive-strategy',
    number: 1,
    name: 'Executive Strategy',
    shortName: 'Executive',
    category: 'Leadership',
    route: '/ai-agent/executive',
    color: '#f8c14a',
    accent: '#38bdf8',
    agents: 242,
    employees: 36,
    automation: 87,
    efficiency: 94,
    risk: 18,
    headlineMetric: '96.4',
    headlineLabel: 'Strategy score',
    secondaryMetric: '42',
    secondaryLabel: 'Board actions',
    movement: 5.8,
    pipeline: ['Scan', 'Model', 'Align', 'Approve', 'Execute', 'Review'],
    allocation: [
      { label: 'Strategy', value: 32 },
      { label: 'Finance', value: 24 },
      { label: 'Governance', value: 22 },
      { label: 'Ops', value: 22 },
    ],
    signals: [
      { label: 'OKR alignment', value: '94%', tone: 'up' },
      { label: 'Decision latency', value: '1.8h', tone: 'down' },
      { label: 'Risk review', value: 'clear', tone: 'flat' },
    ],
    watchlist: ['Capital allocation', 'Board packet readiness', 'Cross-department escalations'],
  },
  {
    id: 'customer-experience',
    number: 2,
    name: 'Customer Experience',
    shortName: 'CX',
    category: 'Revenue',
    route: '/ai-agent/customer-support',
    color: '#22d3ee',
    accent: '#10b981',
    agents: 176,
    employees: 52,
    automation: 82,
    efficiency: 91,
    risk: 24,
    headlineMetric: '98.1',
    headlineLabel: 'CSAT index',
    secondaryMetric: '12.8k',
    secondaryLabel: 'Cases closed',
    movement: 3.4,
    pipeline: ['Listen', 'Classify', 'Route', 'Resolve', 'Survey', 'Learn'],
    allocation: [
      { label: 'Support', value: 38 },
      { label: 'Success', value: 26 },
      { label: 'Retention', value: 20 },
      { label: 'Insights', value: 16 },
    ],
    signals: [
      { label: 'Churn risk', value: '-9%', tone: 'up' },
      { label: 'Avg handle', value: '2.4m', tone: 'down' },
      { label: 'Escalations', value: '31', tone: 'flat' },
    ],
    watchlist: ['VIP tickets', 'At-risk accounts', 'Sentiment dips'],
  },
  {
    id: 'sales-revenue',
    number: 3,
    name: 'Sales & Revenue',
    shortName: 'Sales',
    category: 'Revenue',
    route: '/ai-agent/sales',
    color: '#34d399',
    accent: '#f59e0b',
    agents: 182,
    employees: 48,
    automation: 79,
    efficiency: 89,
    risk: 28,
    headlineMetric: '$8.7m',
    headlineLabel: 'Pipeline value',
    secondaryMetric: '64%',
    secondaryLabel: 'Win probability',
    movement: 6.2,
    pipeline: ['Prospect', 'Qualify', 'Demo', 'Price', 'Negotiate', 'Close'],
    allocation: [
      { label: 'Pipeline', value: 31 },
      { label: 'Outbound', value: 25 },
      { label: 'RevOps', value: 22 },
      { label: 'Enablement', value: 22 },
    ],
    signals: [
      { label: 'Forecast', value: '+12%', tone: 'up' },
      { label: 'Cycle time', value: '18d', tone: 'down' },
      { label: 'Hot deals', value: '47', tone: 'up' },
    ],
    watchlist: ['Late-stage deals', 'Discount approvals', 'Renewal expansion'],
  },
  {
    id: 'marketing-growth',
    number: 4,
    name: 'Marketing & Growth',
    shortName: 'Marketing',
    category: 'Revenue',
    route: '/ai-agent/marketing',
    color: '#fb7185',
    accent: '#a78bfa',
    agents: 180,
    employees: 44,
    automation: 84,
    efficiency: 90,
    risk: 26,
    headlineMetric: '41.2k',
    headlineLabel: 'Qualified demand',
    secondaryMetric: '7.6x',
    secondaryLabel: 'ROAS',
    movement: 4.1,
    pipeline: ['Research', 'Segment', 'Launch', 'Optimize', 'Attribute', 'Scale'],
    allocation: [
      { label: 'Campaigns', value: 34 },
      { label: 'Content', value: 24 },
      { label: 'Growth', value: 23 },
      { label: 'Brand', value: 19 },
    ],
    signals: [
      { label: 'CAC', value: '-8%', tone: 'up' },
      { label: 'MQL rate', value: '31%', tone: 'up' },
      { label: 'Brand lift', value: '6.4', tone: 'flat' },
    ],
    watchlist: ['Campaign fatigue', 'Channel spend', 'Audience overlap'],
  },
  {
    id: 'operations-management',
    number: 5,
    name: 'Operations Management',
    shortName: 'Operations',
    category: 'Operations',
    route: '/ai-agent/operations-management',
    color: '#94a3b8',
    accent: '#22c55e',
    agents: 156,
    employees: 58,
    automation: 86,
    efficiency: 92,
    risk: 22,
    headlineMetric: '93.8',
    headlineLabel: 'Ops health',
    secondaryMetric: '1.2k',
    secondaryLabel: 'Tasks automated',
    movement: 2.7,
    pipeline: ['Capture', 'Prioritize', 'Assign', 'Automate', 'Verify', 'Report'],
    allocation: [
      { label: 'Workflow', value: 34 },
      { label: 'Quality', value: 23 },
      { label: 'Planning', value: 22 },
      { label: 'Exceptions', value: 21 },
    ],
    signals: [
      { label: 'SLA hit', value: '97%', tone: 'up' },
      { label: 'Backlog', value: '-14%', tone: 'up' },
      { label: 'Blockers', value: '8', tone: 'down' },
    ],
    watchlist: ['Workflow bottlenecks', 'SLA exceptions', 'Automation drift'],
  },
  {
    id: 'finance-accounting',
    number: 6,
    name: 'Finance & Accounting',
    shortName: 'Finance',
    category: 'Finance',
    route: '/ai-agent/accounting',
    color: '#2dd4bf',
    accent: '#38bdf8',
    agents: 209,
    employees: 46,
    automation: 88,
    efficiency: 93,
    risk: 20,
    headlineMetric: '$42.8m',
    headlineLabel: 'Cash visibility',
    secondaryMetric: '99.2%',
    secondaryLabel: 'Close accuracy',
    movement: 3.9,
    pipeline: ['Ingest', 'Match', 'Reconcile', 'Forecast', 'Approve', 'Close'],
    allocation: [
      { label: 'Accounting', value: 30 },
      { label: 'FP&A', value: 26 },
      { label: 'Treasury', value: 22 },
      { label: 'Audit', value: 22 },
    ],
    signals: [
      { label: 'Variance', value: '-3.1%', tone: 'up' },
      { label: 'AP aging', value: '11d', tone: 'down' },
      { label: 'Controls', value: 'pass', tone: 'flat' },
    ],
    watchlist: ['Month-end close', 'Cash runway', 'Budget variance'],
  },
  {
    id: 'technology-engineering',
    number: 7,
    name: 'Technology & Engineering',
    shortName: 'Technology',
    category: 'Technology',
    route: '/ai-agent/ai-and-technology',
    color: '#60a5fa',
    accent: '#22d3ee',
    agents: 362,
    employees: 76,
    automation: 81,
    efficiency: 88,
    risk: 31,
    headlineMetric: '99.95',
    headlineLabel: 'Platform uptime',
    secondaryMetric: '418',
    secondaryLabel: 'Deploys',
    movement: 2.2,
    pipeline: ['Plan', 'Build', 'Test', 'Secure', 'Deploy', 'Observe'],
    allocation: [
      { label: 'Build', value: 35 },
      { label: 'Infra', value: 24 },
      { label: 'QA', value: 21 },
      { label: 'DevOps', value: 20 },
    ],
    signals: [
      { label: 'Incidents', value: '-18%', tone: 'up' },
      { label: 'Lead time', value: '2.1d', tone: 'down' },
      { label: 'Coverage', value: '84%', tone: 'up' },
    ],
    watchlist: ['Reliability budget', 'Security patches', 'Release train'],
  },
  {
    id: 'human-resources',
    number: 8,
    name: 'Human Resources',
    shortName: 'HR',
    category: 'People',
    route: '/ai-agent/human-resources',
    color: '#c084fc',
    accent: '#fb7185',
    agents: 143,
    employees: 38,
    automation: 78,
    efficiency: 86,
    risk: 25,
    headlineMetric: '91.7',
    headlineLabel: 'Workforce health',
    secondaryMetric: '248',
    secondaryLabel: 'Hiring actions',
    movement: 3.1,
    pipeline: ['Plan', 'Source', 'Screen', 'Interview', 'Onboard', 'Retain'],
    allocation: [
      { label: 'Talent', value: 34 },
      { label: 'People Ops', value: 25 },
      { label: 'Comp', value: 21 },
      { label: 'Culture', value: 20 },
    ],
    signals: [
      { label: 'Time to hire', value: '19d', tone: 'down' },
      { label: 'Engagement', value: '+7%', tone: 'up' },
      { label: 'Attrition', value: '-4%', tone: 'up' },
    ],
    watchlist: ['Open requisitions', 'Pay equity', 'Onboarding quality'],
  },
  {
    id: 'legal-compliance',
    number: 9,
    name: 'Legal & Compliance',
    shortName: 'Legal',
    category: 'Governance',
    route: '/ai-agent/legal',
    color: '#818cf8',
    accent: '#f8c14a',
    agents: 120,
    employees: 34,
    automation: 76,
    efficiency: 85,
    risk: 34,
    headlineMetric: '99.0',
    headlineLabel: 'Compliance score',
    secondaryMetric: '316',
    secondaryLabel: 'Contracts reviewed',
    movement: 1.8,
    pipeline: ['Request', 'Review', 'Redline', 'Approve', 'File', 'Monitor'],
    allocation: [
      { label: 'Contracts', value: 33 },
      { label: 'Policy', value: 23 },
      { label: 'Risk', value: 22 },
      { label: 'Privacy', value: 22 },
    ],
    signals: [
      { label: 'Policy gaps', value: '5', tone: 'down' },
      { label: 'Cycle time', value: '3.6d', tone: 'down' },
      { label: 'Audit ready', value: '96%', tone: 'up' },
    ],
    watchlist: ['Contract exceptions', 'Regulatory changes', 'Privacy requests'],
  },
  {
    id: 'data-intelligence',
    number: 10,
    name: 'Data & Intelligence',
    shortName: 'Data',
    category: 'Technology',
    route: '/ai-agent/data',
    color: '#a78bfa',
    accent: '#22d3ee',
    agents: 156,
    employees: 42,
    automation: 83,
    efficiency: 90,
    risk: 23,
    headlineMetric: '12.4b',
    headlineLabel: 'Signals processed',
    secondaryMetric: '94%',
    secondaryLabel: 'Model confidence',
    movement: 4.6,
    pipeline: ['Collect', 'Clean', 'Model', 'Explain', 'Publish', 'Monitor'],
    allocation: [
      { label: 'BI', value: 27 },
      { label: 'ML', value: 29 },
      { label: 'Data Ops', value: 24 },
      { label: 'Insight', value: 20 },
    ],
    signals: [
      { label: 'Freshness', value: '99%', tone: 'up' },
      { label: 'Drift', value: 'low', tone: 'flat' },
      { label: 'Requests', value: '+16%', tone: 'up' },
    ],
    watchlist: ['Model drift', 'Data quality', 'Executive insights'],
  },
  {
    id: 'product-management',
    number: 11,
    name: 'Product Management',
    shortName: 'Product',
    category: 'Product',
    route: '/ai-agent/product-management',
    color: '#fb923c',
    accent: '#38bdf8',
    agents: 240,
    employees: 51,
    automation: 80,
    efficiency: 87,
    risk: 29,
    headlineMetric: '84.5',
    headlineLabel: 'Roadmap score',
    secondaryMetric: '73',
    secondaryLabel: 'Features shipped',
    movement: 3.3,
    pipeline: ['Discover', 'Prioritize', 'Design', 'Build', 'Launch', 'Measure'],
    allocation: [
      { label: 'Strategy', value: 27 },
      { label: 'Discovery', value: 24 },
      { label: 'Delivery', value: 30 },
      { label: 'Research', value: 19 },
    ],
    signals: [
      { label: 'Adoption', value: '+11%', tone: 'up' },
      { label: 'Defects', value: '-6%', tone: 'up' },
      { label: 'NPS', value: '61', tone: 'flat' },
    ],
    watchlist: ['Roadmap risk', 'Feature adoption', 'User feedback'],
  },
  {
    id: 'security-risk',
    number: 12,
    name: 'Security & Risk',
    shortName: 'Security',
    category: 'Governance',
    route: '/ai-agent/security',
    color: '#f87171',
    accent: '#fbbf24',
    agents: 190,
    employees: 45,
    automation: 85,
    efficiency: 92,
    risk: 39,
    headlineMetric: '0',
    headlineLabel: 'Critical incidents',
    secondaryMetric: '1.4m',
    secondaryLabel: 'Events scanned',
    movement: 2.9,
    pipeline: ['Detect', 'Triage', 'Contain', 'Remediate', 'Verify', 'Report'],
    allocation: [
      { label: 'SOC', value: 35 },
      { label: 'GRC', value: 22 },
      { label: 'AppSec', value: 22 },
      { label: 'IR', value: 21 },
    ],
    signals: [
      { label: 'MTTR', value: '21m', tone: 'down' },
      { label: 'Threats', value: '-12%', tone: 'up' },
      { label: 'Patch SLA', value: '93%', tone: 'up' },
    ],
    watchlist: ['Privileged access', 'Vendor risk', 'Threat campaigns'],
  },
  {
    id: 'research-development',
    number: 13,
    name: 'Research & Development',
    shortName: 'R&D',
    category: 'Innovation',
    route: '/ai-agent/research-development',
    color: '#a3e635',
    accent: '#60a5fa',
    agents: 288,
    employees: 54,
    automation: 74,
    efficiency: 84,
    risk: 33,
    headlineMetric: '128',
    headlineLabel: 'Experiments',
    secondaryMetric: '21',
    secondaryLabel: 'Patents tracked',
    movement: 4.9,
    pipeline: ['Explore', 'Hypothesize', 'Prototype', 'Test', 'Validate', 'Transfer'],
    allocation: [
      { label: 'Research', value: 34 },
      { label: 'Prototype', value: 27 },
      { label: 'Testing', value: 21 },
      { label: 'IP', value: 18 },
    ],
    signals: [
      { label: 'Success rate', value: '31%', tone: 'up' },
      { label: 'Cycle time', value: '14d', tone: 'down' },
      { label: 'Novelty', value: 'high', tone: 'flat' },
    ],
    watchlist: ['Experiment quality', 'IP filings', 'Prototype handoffs'],
  },
  {
    id: 'administrative',
    number: 14,
    name: 'Administrative',
    shortName: 'Admin',
    category: 'Operations',
    route: '/ai-agent/administrative',
    color: '#cbd5e1',
    accent: '#34d399',
    agents: 108,
    employees: 36,
    automation: 82,
    efficiency: 88,
    risk: 19,
    headlineMetric: '7.2k',
    headlineLabel: 'Requests handled',
    secondaryMetric: '98%',
    secondaryLabel: 'SLA compliance',
    movement: 2.4,
    pipeline: ['Intake', 'Schedule', 'Route', 'Execute', 'Confirm', 'Archive'],
    allocation: [
      { label: 'Scheduling', value: 28 },
      { label: 'Records', value: 25 },
      { label: 'Office', value: 24 },
      { label: 'Support', value: 23 },
    ],
    signals: [
      { label: 'Queue', value: '-10%', tone: 'up' },
      { label: 'Errors', value: '0.8%', tone: 'down' },
      { label: 'Coverage', value: '24/7', tone: 'flat' },
    ],
    watchlist: ['Executive scheduling', 'Document routing', 'Policy updates'],
  },
  {
    id: 'trading-investments',
    number: 15,
    name: 'Trading & Investments',
    shortName: 'Trading',
    category: 'Finance',
    route: '/ai-agent/trading-investment',
    color: '#10b981',
    accent: '#ef4444',
    agents: 296,
    employees: 64,
    automation: 91,
    efficiency: 96,
    risk: 42,
    headlineMetric: '$581.568',
    headlineLabel: 'Realized PnL live',
    secondaryMetric: '47',
    secondaryLabel: 'Risk stream',
    movement: 8.8,
    pipeline: ['Scan', 'Predict', 'Validate', 'Size', 'Fill', 'Settle'],
    allocation: [
      { label: 'Execution', value: 31 },
      { label: 'Risk', value: 24 },
      { label: 'Quant', value: 25 },
      { label: 'Ops', value: 20 },
    ],
    signals: [
      { label: 'Win rate', value: '68%', tone: 'up' },
      { label: 'VaR', value: '2.8%', tone: 'down' },
      { label: 'Open risk', value: '$76k', tone: 'flat' },
    ],
    watchlist: ['Spot feed volatility', '6-cycle execution pipeline', 'Settlement breaks'],
  },
];

type DepartmentTuple = [
  string,
  number,
  string,
  string,
  string,
  string,
  string,
  string,
  number,
  number,
  number,
  number,
  number,
  string,
  string,
  string,
  string,
  number,
  string[],
  string[],
  string[],
];

const remainingTuples: DepartmentTuple[] = [
  ['real-estate-property', 16, 'Real Estate & Property', 'Property', 'Assets', '/ai-agent/real-estate', '#8b5cf6', '#22c55e', 168, 42, 77, 86, 31, '$2.4b', 'Portfolio value', '93%', 'Occupancy', 3.6, ['Source', 'Value', 'Inspect', 'Lease', 'Operate', 'Renew'], ['Portfolio', 'Leasing', 'Facilities', 'Valuation'], ['Lease renewals', 'Capex plan', 'Occupancy shifts']],
  ['insurance-risk', 17, 'Insurance & Risk', 'Insurance', 'Finance', '/ai-agent/insurance', '#ec4899', '#f59e0b', 192, 43, 81, 89, 36, '98.7', 'Risk score', '$18.2m', 'Claims reviewed', 2.8, ['Intake', 'Assess', 'Price', 'Approve', 'Claim', 'Recover'], ['Underwriting', 'Claims', 'Actuary', 'Fraud'], ['Loss ratio', 'High-risk claims', 'Policy exceptions']],
  ['healthcare-medical', 18, 'Healthcare & Medical', 'Healthcare', 'Services', '/ai-agent/healthcare-medical', '#ef4444', '#22d3ee', 240, 78, 73, 84, 35, '99.1', 'Care quality', '4.8k', 'Cases triaged', 2.1, ['Triage', 'Diagnose', 'Schedule', 'Treat', 'Follow up', 'Report'], ['Clinical', 'Scheduling', 'Billing', 'Quality'], ['Patient risk', 'Care gaps', 'Credentialing']],
  ['manufacturing-production', 19, 'Manufacturing & Production', 'Manufacturing', 'Operations', '/ai-agent/manufacturing', '#f97316', '#22c55e', 224, 84, 88, 91, 30, '97.4', 'Line uptime', '14.2k', 'Units optimized', 4.4, ['Plan', 'Source', 'Produce', 'Inspect', 'Pack', 'Ship'], ['Production', 'Quality', 'Maintenance', 'Planning'], ['Downtime', 'Yield loss', 'Supplier delays']],
  ['transportation-logistics', 20, 'Transportation & Logistics', 'Transport', 'Operations', '/ai-agent/transportation', '#06b6d4', '#34d399', 210, 66, 83, 88, 32, '94.8', 'Fleet health', '18.6k', 'Routes optimized', 3.7, ['Book', 'Route', 'Dispatch', 'Track', 'Deliver', 'Invoice'], ['Fleet', 'Dispatch', 'Routing', 'Compliance'], ['Late loads', 'Fuel variance', 'Route exceptions']],
  ['government-public-sector', 21, 'Government & Public Sector', 'Public', 'Public Sector', '/ai-agent/public-sector', '#2563eb', '#f8c14a', 260, 72, 70, 82, 29, '91.2', 'Citizen service', '6.3k', 'Cases processed', 1.9, ['Request', 'Validate', 'Route', 'Approve', 'Notify', 'Audit'], ['Services', 'Policy', 'Grants', 'Compliance'], ['Grant deadlines', 'FOIA requests', 'Public sentiment']],
  ['supply-chain-logistics', 22, 'Supply Chain & Logistics', 'Supply Chain', 'Operations', '/ai-agent/supply-chain', '#14b8a6', '#f97316', 180, 58, 86, 90, 34, '96.3', 'Flow index', '$3.7m', 'Savings found', 4.2, ['Forecast', 'Source', 'Order', 'Move', 'Receive', 'Replenish'], ['Planning', 'Procurement', 'Inventory', 'Suppliers'], ['Stockouts', 'Supplier risk', 'Demand spikes']],
  ['ai-management-governance', 23, 'AI Management & Governance', 'AI Gov', 'Governance', '/ai-agent/ai-management-governance', '#8b5cf6', '#38bdf8', 124, 28, 93, 95, 21, '99.4', 'Model control', '1.1k', 'Policy checks', 5.5, ['Register', 'Evaluate', 'Approve', 'Monitor', 'Audit', 'Retire'], ['Governance', 'Safety', 'Model Ops', 'Policy'], ['Model drift', 'Tool permissions', 'Audit findings']],
  ['professional-services', 24, 'Professional Services', 'Services', 'Services', '/ai-agent/professional-services/professional-services-command-center', '#0f766e', '#60a5fa', 360, 92, 75, 86, 27, '$12.1m', 'Delivery value', '88%', 'Utilization', 3.3, ['Scope', 'Staff', 'Deliver', 'Review', 'Invoice', 'Expand'], ['Delivery', 'Advisory', 'PMO', 'Quality'], ['Project margin', 'Resource gaps', 'Client health']],
  ['media-entertainment', 25, 'Media & Entertainment', 'Media', 'Creative', '/ai-agent/media-entertainment', '#f43f5e', '#a78bfa', 168, 48, 72, 84, 26, '14.8m', 'Audience reach', '61%', 'Engagement', 5.1, ['Ideate', 'Produce', 'Edit', 'Publish', 'Amplify', 'Measure'], ['Content', 'Production', 'Audience', 'Rights'], ['Rights clearance', 'Audience drop', 'Release calendar']],
  ['education-training', 26, 'Education & Training', 'Education', 'People', '/ai-agent/education', '#22c55e', '#38bdf8', 160, 55, 76, 85, 22, '92.6', 'Learning score', '8.9k', 'Learners guided', 3.8, ['Assess', 'Plan', 'Teach', 'Coach', 'Test', 'Certify'], ['Curriculum', 'Coaching', 'Assessment', 'Ops'], ['Skill gaps', 'Completion risk', 'Certification queue']],
  ['retail-stores', 27, 'Retail Stores', 'Retail', 'Commerce', '/ai-agent/retail-stores', '#f59e0b', '#10b981', 176, 82, 80, 87, 33, '$4.9m', 'Store revenue', '98%', 'Shelf availability', 4.7, ['Forecast', 'Stock', 'Price', 'Sell', 'Serve', 'Reorder'], ['Store Ops', 'Inventory', 'Pricing', 'CX'], ['Stockouts', 'Shrink risk', 'Promo lift']],
  ['e-commerce', 28, 'E-Commerce', 'E-Com', 'Commerce', '/ai-agent/e-commerce', '#38bdf8', '#f59e0b', 188, 52, 89, 92, 30, '$7.8m', 'GMV live', '4.3%', 'Conversion', 6.4, ['Attract', 'Personalize', 'Cart', 'Pay', 'Fulfill', 'Retain'], ['Growth', 'Merch', 'Fulfillment', 'Support'], ['Cart drop', 'Payment failures', 'SKU velocity']],
  ['banking-finance', 29, 'Banking & Finance', 'Banking', 'Finance', '/ai-agent/banking-finance', '#2563eb', '#10b981', 214, 66, 84, 90, 37, '$91.6m', 'Managed book', '99.7%', 'Control pass', 3.9, ['Onboard', 'Verify', 'Advise', 'Transact', 'Monitor', 'Report'], ['Banking', 'Credit', 'Fraud', 'Reporting'], ['KYC queue', 'Credit risk', 'Fraud spikes']],
  ['energy-utilities', 30, 'Energy & Utilities', 'Energy', 'Infrastructure', '/ai-agent/energy-utilities', '#84cc16', '#22d3ee', 174, 70, 82, 88, 35, '98.8', 'Grid health', '12.2gw', 'Load balanced', 2.6, ['Forecast', 'Generate', 'Route', 'Monitor', 'Repair', 'Settle'], ['Grid', 'Field', 'Trading', 'Customer'], ['Outage risk', 'Demand peaks', 'Maintenance']],
  ['agriculture', 31, 'Agriculture', 'Agri', 'Industry', '/ai-agent/agriculture', '#65a30d', '#f59e0b', 132, 48, 74, 82, 28, '87.9', 'Yield index', '42k', 'Acres monitored', 3.1, ['Sense', 'Plan', 'Plant', 'Treat', 'Harvest', 'Sell'], ['Crop', 'Supply', 'Equipment', 'Market'], ['Weather risk', 'Input costs', 'Yield variance']],
  ['construction-infrastructure', 32, 'Construction & Infrastructure', 'Construction', 'Industry', '/ai-agent/architecture-design', '#f97316', '#64748b', 152, 74, 71, 81, 41, '$1.8b', 'Project value', '86%', 'Schedule health', 2.4, ['Bid', 'Design', 'Procure', 'Build', 'Inspect', 'Handover'], ['Projects', 'Safety', 'Procurement', 'Design'], ['Safety incidents', 'Permit delays', 'Cost overruns']],
  ['travel-tourism', 33, 'Travel & Tourism', 'Travel', 'Services', '/ai-agent/travel-tourism', '#0ea5e9', '#f43f5e', 128, 46, 79, 86, 27, '94.1', 'Booking health', '31k', 'Trips supported', 4.8, ['Search', 'Package', 'Book', 'Service', 'Recover', 'Retain'], ['Bookings', 'CX', 'Pricing', 'Partners'], ['Cancellations', 'Demand shifts', 'Partner SLA']],
  ['restaurants-hospitality', 34, 'Restaurants & Hospitality', 'Hospitality', 'Services', '/ai-agent/restaurants', '#fb7185', '#f59e0b', 136, 64, 78, 85, 31, '92.3', 'Guest score', '18.4k', 'Covers optimized', 3.5, ['Reserve', 'Prep', 'Serve', 'Upsell', 'Recover', 'Review'], ['Front desk', 'Kitchen', 'Revenue', 'Guest'], ['Table turns', 'Waste', 'Review sentiment']],
  ['fashion-luxury', 35, 'Fashion & Luxury', 'Fashion', 'Commerce', '/ai-agent/fashion-luxury', '#d946ef', '#f8c14a', 118, 39, 73, 83, 26, '71%', 'Sell-through', '$2.2m', 'Collection value', 4.0, ['Trend', 'Design', 'Source', 'Launch', 'Sell', 'Retain'], ['Design', 'Merch', 'VIP', 'Supply'], ['Trend shifts', 'VIP demand', 'Inventory aging']],
  ['gaming-esports', 36, 'Gaming & Esports', 'Gaming', 'Entertainment', '/ai-agent/gaming-esports', '#7c3aed', '#22c55e', 146, 42, 81, 89, 24, '2.8m', 'Active players', '43%', 'Session lift', 7.1, ['Match', 'Moderate', 'Engage', 'Monetize', 'Analyze', 'Retain'], ['Live Ops', 'Community', 'Monetization', 'Esports'], ['Toxicity spikes', 'Churn cohorts', 'Tournament ops']],
  ['accounting', 37, 'Accounting', 'Accounting', 'Finance', '/ai-agent/accounting', '#0f766e', '#f8c14a', 187, 34, 86, 91, 29, '99.1', 'Filing accuracy', '$6.4m', 'Tax exposure', 2.2, ['Collect', 'Classify', 'Calculate', 'Review', 'File', 'Defend'], ['Compliance', 'Planning', 'Audit', 'Reporting'], ['Filing calendar', 'Jurisdiction changes', 'Audit exposure']],
  ['event-management', 38, 'Event Management', 'Events', 'Services', '/ai-agent/event-management', '#22c55e', '#fb923c', 117, 36, 84, 90, 25, '$3.1m', 'Cost savings', '96%', 'Margin visibility', 4.5, ['Capture', 'Allocate', 'Analyze', 'Optimize', 'Approve', 'Track'], ['Costing', 'Margin', 'Pricing', 'Controls'], ['Cost leakage', 'Margin compression', 'Budget drift']],
];

const remaining: Array<Omit<DepartmentDashboard, 'chart'>> = remainingTuples.map(([id, number, name, shortName, category, route, color, accent, agents, employees, automation, efficiency, risk, headlineMetric, headlineLabel, secondaryMetric, secondaryLabel, movement, pipeline, allocationLabels, watchlist]) => ({
  id,
  number,
  name,
  shortName,
  category,
  route,
  color,
  accent,
  agents,
  employees,
  automation,
  efficiency,
  risk,
  headlineMetric,
  headlineLabel,
  secondaryMetric,
  secondaryLabel,
  movement,
  pipeline,
  allocation: allocationLabels.map((label, index) => ({ label, value: [32, 25, 23, 20][index] })),
  signals: [
    { label: 'Automation', value: `${automation}%`, tone: 'up' as const },
    { label: 'Risk', value: `${risk}`, tone: risk > 35 ? 'down' as const : 'flat' as const },
    { label: 'Efficiency', value: `${efficiency}%`, tone: 'up' as const },
  ],
  watchlist,
}));

export const departmentDashboards: DepartmentDashboard[] = [...departments, ...remaining].map((department) => ({
  ...department,
  chart: buildChart(department.number),
}));

export const departmentDashboardSummary = {
  departmentCount: departmentDashboards.length,
  agentCount: departmentDashboards.reduce((total, department) => total + department.agents, 0),
  employeeCount: departmentDashboards.reduce((total, department) => total + department.employees, 0),
  averageAutomation: Math.round(
    departmentDashboards.reduce((total, department) => total + department.automation, 0) / departmentDashboards.length,
  ),
  averageEfficiency: Math.round(
    departmentDashboards.reduce((total, department) => total + department.efficiency, 0) / departmentDashboards.length,
  ),
};

export const getDepartmentDashboard = (id: string) =>
  departmentDashboards.find((department) => department.id === id) ?? departmentDashboards[14];
