import { aiEmployees } from '@/constants/aiEmployees';

export interface Industry {
  id: string;
  name: string;
  tagline: string;
  description: string;
  primaryUseCases: string[];
  recommendedRoleIds: string[];
}

const allRoleIds = aiEmployees.map(r => r.id);

export const industries: Industry[] = [
  {
    id: 'financial-services',
    name: 'Financial services',
    tagline: 'Handle ID checks, card issues, land claims — securely and at scale.',
    description: 'Modernize support and back-office operations with secure automation, fast resolution, and consistent compliance workflows.',
    primaryUseCases: [
      'KYC intake and identity verification routing',
      'Card issues and dispute intake',
      'Claims triage and status updates',
      'Outbound collections and payment reminders',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-customer-support',
      'ai-crm-assistant',
      'ai-data-analyst',
      'ai-sales-data-analyst',
      'ai-competitive-intel',
      'ai-negotiator',
      'ai-negotiation-specialist',
      'ai-memory-context',
    ],
  },
  {
    id: 'finance-banking',
    name: 'Finance and banking',
    tagline: 'Secure account support, onboarding, and high-volume service requests.',
    description: 'Scale account servicing and onboarding while keeping response times low and controls high.',
    primaryUseCases: [
      'Account onboarding assistance and document collection',
      'Fraud inquiry routing and escalation',
      'Loan application triage and follow-ups',
      'Customer support across chat, email, and phone',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-customer-support',
      'ai-sales-executive',
      'ai-negotiator',
      'ai-pricing-strategist',
      'ai-data-analyst',
      'ai-crm-assistant',
      'ai-retention-specialist',
      'ai-memory-context',
    ],
  },
  {
    id: 'utilities',
    name: 'Utilities',
    tagline: 'Automate high-volume outages and billing questions, without the wait times.',
    description: 'Reduce call-center load during peak events and improve customer satisfaction with instant, accurate answers.',
    primaryUseCases: [
      'Outage reporting and proactive updates',
      'Billing and payment plan support',
      'Move-in / move-out automation',
      'Field service scheduling and status updates',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-customer-support',
      'ai-operations-manager',
      'ai-manager',
      'ai-data-analyst',
      'ai-workflow',
      'ai-smart-task-automation',
      'ai-memory-context',
    ].filter(id => allRoleIds.includes(id)),
  },
  {
    id: 'ecommerce-retail',
    name: 'eCommerce & retail',
    tagline: 'Manage orders, returns, and product questions quickly and effortlessly.',
    description: 'Deliver faster support, better product discovery, and higher conversion with always-on automation.',
    primaryUseCases: [
      'Order status and shipping updates',
      'Returns and refunds automation',
      'Product Q&A and sizing guidance',
      'Cart recovery and post-purchase follow-ups',
    ],
    recommendedRoleIds: [
      'ai-customer-support',
      'ai-retention-specialist',
      'ai-marketer',
      'ai-social-media-manager',
      'ai-campaign-optimizer',
      'ai-sales-agent',
      'ai-sales-rep',
      'ai-crm-assistant',
      'ai-data-analyst',
      'ai-memory-context',
    ],
  },
  {
    id: 'ecommerce',
    name: 'ecommerce',
    tagline: 'Sell more with automated support, outreach, and retention.',
    description: 'A streamlined version of the eCommerce stack focused on conversion and customer success.',
    primaryUseCases: [
      'Product questions and guided selling',
      'Support triage and deflection',
      'Abandoned cart recovery',
      'Loyalty and win-back campaigns',
    ],
    recommendedRoleIds: [
      'ai-sales-agent',
      'ai-sales-rep',
      'ai-customer-support',
      'ai-retention-specialist',
      'ai-campaign-optimizer',
      'ai-crm-assistant',
      'ai-memory-context',
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    tagline: 'Streamline bookings, refills, and patient support.',
    description: 'Improve patient experience with fast scheduling, clear updates, and consistent triage workflows.',
    primaryUseCases: [
      'Appointment scheduling and reminders',
      'Prescription refill intake and routing',
      'Patient FAQs and status checks',
      'Billing and insurance questions triage',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-customer-support',
      'ai-operations-manager',
      'ai-data-analyst',
      'ai-crm-assistant',
      'ai-memory-context',
    ],
  },
  {
    id: 'airline',
    name: 'Airline',
    tagline: 'Automate bookings, changes, and high-volume disruption support.',
    description: 'Reduce pressure during delays and cancellations with automated updates, rebooking flows, and fast support.',
    primaryUseCases: [
      'Flight status updates and disruption comms',
      'Rebooking and change requests routing',
      'Baggage claim status and intake',
      'Loyalty support and retention',
    ],
    recommendedRoleIds: [
      'ai-customer-support',
      'ai-receptionist',
      'ai-operations-manager',
      'ai-data-analyst',
      'ai-retention-specialist',
      'ai-memory-context',
    ],
  },
  {
    id: 'media-entertainment',
    name: 'Media & entertainment',
    tagline: 'Keep fans engaged across multiple support channels.',
    description: 'Boost engagement and reduce churn with fast help, community responses, and always-on marketing execution.',
    primaryUseCases: [
      'Subscription and account support',
      'Content discovery and recommendations',
      'Community moderation and replies',
      'Campaign and social execution',
    ],
    recommendedRoleIds: [
      'ai-customer-support',
      'ai-social-media-manager',
      'ai-marketer',
      'ai-campaign-optimizer',
      'ai-data-analyst',
      'ai-retention-specialist',
      'ai-memory-context',
    ],
  },
  {
    id: 'insurance',
    name: 'Insurance',
    tagline: 'Automate claim intake, status updates, and customer service.',
    description: 'Reduce cycle times with structured intake, better routing, and proactive communication.',
    primaryUseCases: [
      'Claims intake and document collection',
      'Policy questions and endorsements',
      'Renewal reminders and retention plays',
      'Fraud signals routing and escalation',
    ],
    recommendedRoleIds: [
      'ai-customer-support',
      'ai-retention-specialist',
      'ai-data-analyst',
      'ai-crm-assistant',
      'ai-competitive-intel',
      'ai-memory-context',
    ],
  },
  {
    id: 'telecommunications',
    name: 'Telecommunications',
    tagline: 'Scale service requests, network issues, and billing support.',
    description: 'Handle large volumes of device, plan, billing, and outage-related questions without queues.',
    primaryUseCases: [
      'Plan changes and billing questions',
      'Service outages and incident comms',
      'Device troubleshooting and replacements',
      'Retention and win-back',
    ],
    recommendedRoleIds: [
      'ai-customer-support',
      'ai-receptionist',
      'ai-retention-specialist',
      'ai-data-analyst',
      'ai-operations-manager',
      'ai-memory-context',
    ],
  },
  {
    id: 'information-technology',
    name: 'Information technology',
    tagline: 'Resolve tickets, reset passwords, and support users 24/7.',
    description: 'Reduce time-to-resolution with automated triage, instant password resets, and proactive ops insights.',
    primaryUseCases: [
      'Ticket intake and routing',
      'Password resets and access requests',
      'Knowledge-base answers and troubleshooting',
      'On-call escalation and status updates',
    ],
    recommendedRoleIds: [
      'ai-customer-support',
      'ai-operations-manager',
      'ai-manager',
      'ai-data-analyst',
      'ai-workflow',
      'ai-smart-task-automation',
      'ai-memory-context',
    ].filter(id => allRoleIds.includes(id)),
  },
  {
    id: 'retail-ecommerce',
    name: 'retail and ecommcerce',
    tagline: 'Unify in-store + online support with fast, consistent automation.',
    description: 'Handle omnichannel service, returns, and product support with shared context and consistent outcomes.',
    primaryUseCases: [
      'Omnichannel customer support',
      'Returns/exchanges and order changes',
      'Product Q&A and store information',
      'Loyalty and retention automation',
    ],
    recommendedRoleIds: [
      'ai-customer-support',
      'ai-retention-specialist',
      'ai-crm-assistant',
      'ai-sales-agent',
      'ai-marketer',
      'ai-social-media-manager',
      'ai-memory-context',
    ],
  },
  {
    id: 'banking',
    name: 'Banking',
    tagline: 'Secure account management, loan processing, and high-volume customer service.',
    description: 'Automate account operations, loan applications, fraud detection, and customer inquiries with enterprise-grade security.',
    primaryUseCases: [
      'Account opening and KYC verification',
      'Loan application processing and follow-ups',
      'Fraud detection and alert routing',
      'Transaction inquiries and dispute resolution',
      'Investment advisory and portfolio updates',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-customer-support',
      'ai-sales-executive',
      'ai-negotiator',
      'ai-pricing-strategist',
      'ai-data-analyst',
      'ai-crm-assistant',
      'ai-retention-specialist',
      'ai-memory-context',
    ],
  },
  {
    id: 'travel-hospitality',
    name: 'Travel and hospitality',
    tagline: 'Automate bookings, cancellations, and guest support 24/7.',
    description: 'Handle reservations, changes, special requests, and guest inquiries across hotels, airlines, and travel services.',
    primaryUseCases: [
      'Reservation management and modifications',
      'Check-in/check-out automation',
      'Special requests and concierge services',
      'Cancellation and refund processing',
      'Loyalty program support',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-customer-support',
      'ai-sales-agent',
      'ai-retention-specialist',
      'ai-crm-assistant',
      'ai-operations-manager',
      'ai-data-analyst',
      'ai-memory-context',
    ],
  },
  {
    id: 'government-public-sector',
    name: 'Government and public sector',
    tagline: 'Streamline citizen services, applications, and public inquiries.',
    description: 'Automate citizen services, permit applications, benefit claims, and public information requests with compliance and transparency.',
    primaryUseCases: [
      'Citizen service requests and applications',
      'Permit and license processing',
      'Benefit claims and status updates',
      'Public information and FAQ handling',
      'Compliance and document verification',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-customer-support',
      'ai-operations-manager',
      'ai-data-analyst',
      'ai-crm-assistant',
      'ai-memory-context',
    ],
  },
  {
    id: 'technology',
    name: 'Technology',
    tagline: 'Scale support, onboarding, and technical assistance for SaaS and tech companies.',
    description: 'Automate technical support, product onboarding, API documentation, and developer relations with intelligent routing.',
    primaryUseCases: [
      'Technical support and troubleshooting',
      'Product onboarding and setup assistance',
      'API documentation and developer support',
      'Feature requests and product feedback',
      'Account management and billing',
    ],
    recommendedRoleIds: [
      'ai-customer-support',
      'ai-product-manager',
      'ai-operations-manager',
      'ai-data-analyst',
      'ai-sales-rep',
      'ai-retention-specialist',
      'ai-memory-context',
    ],
  },
  {
    id: 'education-training',
    name: 'Education and training',
    tagline: 'Automate enrollment, student support, and course management.',
    description: 'Handle student inquiries, enrollment processes, course scheduling, and educational support with personalized assistance.',
    primaryUseCases: [
      'Student enrollment and registration',
      'Course scheduling and availability',
      'Academic support and tutoring coordination',
      'Financial aid and payment processing',
      'Alumni relations and career services',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-customer-support',
      'ai-recruiter',
      'ai-operations-manager',
      'ai-crm-assistant',
      'ai-data-analyst',
      'ai-memory-context',
    ],
  },
  {
    id: 'real-estate',
    name: 'Real estate',
    tagline: 'Automate property inquiries, showings, and transaction support.',
    description: 'Handle property listings, viewing requests, application processing, and client communication with intelligent scheduling.',
    primaryUseCases: [
      'Property inquiries and listing information',
      'Viewing scheduling and confirmation',
      'Application processing and screening',
      'Lease and contract management',
      'Maintenance requests and coordination',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-sales-agent',
      'ai-sales-rep',
      'ai-customer-support',
      'ai-crm-assistant',
      'ai-data-analyst',
      'ai-memory-context',
    ],
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    tagline: 'Streamline supply chain, order management, and customer service.',
    description: 'Automate order processing, inventory inquiries, shipping updates, and B2B customer support with real-time tracking.',
    primaryUseCases: [
      'Order processing and status updates',
      'Inventory inquiries and availability',
      'Shipping and logistics coordination',
      'Quality control and returns processing',
      'B2B account management',
    ],
    recommendedRoleIds: [
      'ai-customer-support',
      'ai-operations-manager',
      'ai-sales-executive',
      'ai-crm-assistant',
      'ai-data-analyst',
      'ai-memory-context',
    ],
  },
  {
    id: 'legal-services',
    name: 'Legal services',
    tagline: 'Automate intake, scheduling, and client communication.',
    description: 'Handle client inquiries, appointment scheduling, document collection, and case status updates with confidentiality.',
    primaryUseCases: [
      'Client intake and consultation scheduling',
      'Document collection and verification',
      'Case status updates and communication',
      'Billing inquiries and payment processing',
      'Compliance and deadline management',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-customer-support',
      'ai-operations-manager',
      'ai-crm-assistant',
      'ai-data-analyst',
      'ai-memory-context',
    ],
  },
  {
    id: 'professional-services',
    name: 'Professional services',
    tagline: 'Automate client onboarding, project management, and service delivery.',
    description: 'Streamline client communication, project updates, billing, and service delivery with intelligent coordination.',
    primaryUseCases: [
      'Client onboarding and intake',
      'Project updates and milestone communication',
      'Billing and invoice inquiries',
      'Service delivery coordination',
      'Client retention and upselling',
    ],
    recommendedRoleIds: [
      'ai-receptionist',
      'ai-customer-support',
      'ai-sales-executive',
      'ai-operations-manager',
      'ai-crm-assistant',
      'ai-retention-specialist',
      'ai-memory-context',
    ],
  },
];

export const getIndustryById = (id: string) => industries.find(i => i.id === id);
