/**
 * =============================================================================
 * KAYTX PHONE AGENT PHONE NUMBERS
 * =============================================================================
 * Assigns deterministic mock/placeholder phone numbers to the ~72 phone/caller
 * agents routed from `app/(tabs)/home.tsx` to `/ai-agent/phone`
 * (e.g. `2-cx-phone-receptionist`, `2-sales-phone-negotiator`).
 *
 * These agents are NOT part of the master `agentRegistry` (they are route-map
 * keys without per-agent data objects), so their numbers live here instead.
 * Values are generated by the same helper used for the registry, keeping the
 * format consistent across the app. No real PII is introduced.
 */

import { generateAgentPhoneNumber } from './aiAgentRegistry';

/** Stable list of phone/caller agent route ids from home.tsx. */
export const PHONE_AGENT_IDS: string[] = [
  '2-cx-phone-receptionist',
  '2-cx-call-center',
  '2-cx-telephone-support',
  '2-sales-cold-caller',
  '2-sales-phone-negotiator',
  '2-sales-deal-closer',
  '2-sales-appointment-setter',
  '2-sales-follow-up',
  '2-sales-receptionist',
  '2-mkt-telemarketer',
  '2-mkt-event-caller',
  '2-mkt-survey-caller',
  '2-mkt-pr-caller',
  '2-mkt-lead-qualifier',
  '2-mkt-partnership-caller',
  '2-ops-receptionist',
  '2-ops-dispatch-caller',
  '2-ops-coordination-caller',
  '2-fin-collections-caller',
  '2-fin-vendor-payment-caller',
  '2-fin-investor-relations-caller',
  '2-tech-it-support-hotline',
  '2-tech-help-desk-caller',
  '2-tech-incident-response-caller',
  '2-hr-receptionist',
  '2-hr-recruiting-caller',
  '2-hr-interview-scheduler',
  '2-legal-receptionist',
  '2-legal-client-intake-caller',
  '2-legal-compliance-caller',
  '2-data-research-caller',
  '2-data-analytics-caller',
  '2-data-report-caller',
  '2-prod-user-research-caller',
  '2-prod-feedback-caller',
  '2-prod-beta-caller',
  '2-sec-incident-response-caller',
  '2-sec-threat-hunting-caller',
  '2-sec-alert-response-caller',
  '2-rnd-research-caller',
  '2-rnd-partner-caller',
  '2-rnd-collab-caller',
  '2-admin-receptionist',
  '2-admin-exec-assistant-caller',
  '2-admin-switchboard',
  '2-trading-client-relations-caller',
  '2-trading-trade-confirmation-caller',
  '2-trading-investor-relations-caller',
  '2-re-property-receptionist',
  '2-re-leasing-negotiator',
  '2-re-tenant-inquiry-caller',
  '2-ins-claims-hotline',
  '2-ins-underwriting-caller',
  '2-ins-policy-caller',
  '2-healthcare-patient-scheduler',
  '2-healthcare-medical-receptionist',
  '2-healthcare-telehealth-caller',
  '2-mfg-floor-ops-caller',
  '2-mfg-shift-supervisor-caller',
  '2-mfg-emergency-response-caller',
  '2-logistics-dispatch-receptionist',
  '2-logistics-driver-hotline',
  '2-logistics-fleet-caller',
  '2-gov-public-inquiry-line',
  '2-gov-permit-hotline',
  '2-gov-citizen-services-caller',
  '2-sc-supplier-coordination-caller',
  '2-sc-logistics-phone-agent',
  '2-sc-order-status-caller',
  '2-ai-mgmt-phone-support',
  '2-ai-mgmt-escalation-caller',
  '2-ai-mgmt-system-alert-caller',
];

// Base offset keeps these numbers distinct from the registry's 1..1135 seq range.
const PHONE_AGENT_SEQ_OFFSET = 5000;

/** Map of phone-agent route id -> assigned mock phone number. */
export const PHONE_AGENT_NUMBERS: Record<string, string> = PHONE_AGENT_IDS.reduce(
  (acc, id, idx) => {
    acc[id] = generateAgentPhoneNumber(PHONE_AGENT_SEQ_OFFSET + idx);
    return acc;
  },
  {} as Record<string, string>
);

/** Returns the assigned phone number for a phone-agent route id, or null. */
export function getPhoneAgentNumber(id: string): string | null {
  return PHONE_AGENT_NUMBERS[id] ?? null;
}
