 
import {
    MessageSquare,
    Smartphone,
    Shield,
    Mail,
    Phone,
    Cloud,
    Globe,
    Facebook,
    Linkedin,
    Twitter,
    Hash,
    MessageCircle,
    Briefcase,
    Users,
} from 'lucide-react-native';

export interface Platform {
    id: string;
    name: string;
    service: string;
    isConnected: boolean;
    isEnabled: boolean;
    accountName: string;
    avatar: string;
    messageCount: number;
    lastSync: string;
    category: 'messaging' | 'social' | 'business' | 'other';
    description: string;
    features: string[];
    popularity: number;
    isVerified: boolean;
    connectionType: 'qr-code' | 'oauth' | 'credentials' | 'google-account' | 'phone-verify';
    connectionMethod: 'on-device' | 'cloud';
    status: 'active' | 'syncing' | 'error' | 'pending';
    monthlyMessages: number;
    responseTime: string;
    websiteUrl: string;
    apiDocUrl: string;
    appStoreUrl?: string;
    playStoreUrl?: string;
}

export const PLATFORMS_DATA: Platform[] = [
    {
        id: '1',
        name: 'WhatsApp',
        service: 'whatsapp',
        isConnected: false,
        isEnabled: false,
        accountName: 'Not connected',
        avatar: '',
        messageCount: 0,
        lastSync: 'Never',
        category: 'messaging',
        description: 'End-to-end encrypted messaging with enhanced QR linking, business API, multi-device sync, and automated responses',
        features: ['QR Code', 'On-device', 'E2E encrypted', 'Multi-device', 'Business API'],
        popularity: 98,
        isVerified: true,
        connectionType: 'qr-code',
        connectionMethod: 'on-device',
        status: 'active',
        monthlyMessages: 0,
        responseTime: 'N/A',
        websiteUrl: 'https://www.whatsapp.com',
        apiDocUrl: 'https://developers.facebook.com/docs/whatsapp',
        appStoreUrl: 'https://apps.apple.com/app/whatsapp-messenger/id310633997',
        playStoreUrl: 'https://play.google.com/store/apps/details?id=com.whatsapp',
    },
    {
        id: '2',
        name: 'Signal',
        service: 'signal',
        isConnected: false,
        isEnabled: false,
        accountName: 'Not connected',
        avatar: '',
        messageCount: 0,
        lastSync: 'Never',
        category: 'messaging',
        description: 'Privacy-focused messaging with QR code pairing',
        features: ['QR Code', 'On-device', 'Privacy-first'],
        popularity: 85,
        isVerified: true,
        connectionType: 'qr-code',
        connectionMethod: 'on-device',
        status: 'active',
        monthlyMessages: 0,
        responseTime: 'N/A',
        websiteUrl: 'https://signal.org',
        apiDocUrl: 'https://signal.org/docs/',
        appStoreUrl: 'https://apps.apple.com/app/signal-private-messenger/id874139669',
        playStoreUrl: 'https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms',
    },
    {
        id: '3',
        name: 'Instagram',
        service: 'instagram',
        isConnected: false,
        isEnabled: false,
        accountName: 'Not connected',
        avatar: '',
        messageCount: 0,
        lastSync: 'Never',
        category: 'social',
        description: 'Direct messages via cloud bridge with 2FA support',
        features: ['Username/Password', 'Cloud', '2FA'],
        popularity: 96,
        isVerified: true,
        connectionType: 'credentials',
        connectionMethod: 'cloud',
        status: 'active',
        monthlyMessages: 0,
        responseTime: 'N/A',
        websiteUrl: 'https://www.instagram.com',
        apiDocUrl: 'https://developers.facebook.com/docs/instagram',
        appStoreUrl: 'https://apps.apple.com/app/instagram/id389801252',
        playStoreUrl: 'https://play.google.com/store/apps/details?id=com.instagram.android',
    },
    {
        id: '4',
        name: 'Telegram',
        service: 'telegram',
        isConnected: false,
        isEnabled: false,
        accountName: 'Not connected',
        avatar: '',
        messageCount: 0,
        lastSync: 'Never',
        category: 'messaging',
        description: 'Fast, secure messaging with bot capabilities',
        features: ['QR Code', 'Cloud', 'Bots'],
        popularity: 92,
        isVerified: true,
        connectionType: 'qr-code',
        connectionMethod: 'cloud',
        status: 'active',
        monthlyMessages: 0,
        responseTime: 'N/A',
        websiteUrl: 'https://telegram.org',
        apiDocUrl: 'https://core.telegram.org/api',
        appStoreUrl: 'https://apps.apple.com/app/telegram-messenger/id686449807',
        playStoreUrl: 'https://play.google.com/store/apps/details?id=org.telegram.messenger',
    },
    {
        id: '7',
        name: 'Facebook Messenger',
        service: 'messenger',
        isConnected: false,
        isEnabled: false,
        accountName: 'Not connected',
        avatar: '',
        messageCount: 0,
        lastSync: 'Never',
        category: 'social',
        description: 'Facebook messaging via OAuth',
        features: ['OAuth', 'Cloud', 'Rich media'],
        popularity: 94,
        isVerified: true,
        connectionType: 'oauth',
        connectionMethod: 'cloud',
        status: 'active',
        monthlyMessages: 0,
        responseTime: 'N/A',
        websiteUrl: 'https://www.messenger.com',
        apiDocUrl: 'https://developers.facebook.com/docs/messenger-platform',
        appStoreUrl: 'https://apps.apple.com/app/messenger/id454638411',
        playStoreUrl: 'https://play.google.com/store/apps/details?id=com.facebook.orca',
    },
    {
        id: '9',
        name: 'Slack',
        service: 'slack',
        isConnected: false,
        isEnabled: false,
        accountName: 'Not connected',
        avatar: '',
        messageCount: 0,
        lastSync: 'Never',
        category: 'business',
        description: 'Team collaboration via OAuth',
        features: ['OAuth', 'Cloud', 'Channels'],
        popularity: 91,
        isVerified: true,
        connectionType: 'oauth',
        connectionMethod: 'cloud',
        status: 'active',
        monthlyMessages: 0,
        responseTime: 'N/A',
        websiteUrl: 'https://slack.com',
        apiDocUrl: 'https://api.slack.com',
        appStoreUrl: 'https://apps.apple.com/app/slack/id618783545',
        playStoreUrl: 'https://play.google.com/store/apps/details?id=com.Slack',
    },
    {
        id: '10',
        name: 'LinkedIn',
        service: 'linkedin',
        isConnected: false,
        isEnabled: false,
        accountName: 'Not connected',
        avatar: '',
        messageCount: 0,
        lastSync: 'Never',
        category: 'business',
        description: 'Professional networking with OAuth and 2FA support',
        features: ['OAuth', 'Cloud', '2FA', 'InMail'],
        popularity: 89,
        isVerified: true,
        connectionType: 'oauth',
        connectionMethod: 'cloud',
        status: 'active',
        monthlyMessages: 0,
        responseTime: 'N/A',
        websiteUrl: 'https://www.linkedin.com',
        apiDocUrl: 'https://docs.microsoft.com/en-us/linkedin/',
        appStoreUrl: 'https://apps.apple.com/app/linkedin/id288429040',
        playStoreUrl: 'https://play.google.com/store/apps/details?id=com.linkedin.android',
    },
    {
        id: '11',
        name: 'Twitter / X',
        service: 'twitter',
        isConnected: false,
        isEnabled: false,
        accountName: 'Not connected',
        avatar: '',
        messageCount: 0,
        lastSync: 'Never',
        category: 'social',
        description: 'Direct messages and mentions via OAuth',
        features: ['OAuth', 'Cloud', 'API v2', 'DMs'],
        popularity: 88,
        isVerified: true,
        connectionType: 'oauth',
        connectionMethod: 'cloud',
        status: 'active',
        monthlyMessages: 0,
        responseTime: 'N/A',
        websiteUrl: 'https://x.com',
        apiDocUrl: 'https://developer.twitter.com/en/docs',
        appStoreUrl: 'https://apps.apple.com/app/twitter/id333903271',
        playStoreUrl: 'https://play.google.com/store/apps/details?id=com.twitter.android',
    },
    {
        id: '12',
        name: 'Discord',
        service: 'discord',
        isConnected: false,
        isEnabled: false,
        accountName: 'Not connected',
        avatar: '',
        messageCount: 0,
        lastSync: 'Never',
        category: 'social',
        description: 'Community messaging with bot integration',
        features: ['OAuth', 'Cloud', 'Bots', 'Webhooks'],
        popularity: 90,
        isVerified: true,
        connectionType: 'oauth',
        connectionMethod: 'cloud',
        status: 'active',
        monthlyMessages: 0,
        responseTime: 'N/A',
        websiteUrl: 'https://discord.com',
        apiDocUrl: 'https://discord.com/developers/docs',
        appStoreUrl: 'https://apps.apple.com/app/discord/id985746746',
        playStoreUrl: 'https://play.google.com/store/apps/details?id=com.discord',
    },
];
