 
import {
  MessageCircle,
  Send,
  Camera,
  Hash,
  Briefcase,
  Twitter,
  Linkedin,
  MessageSquare,
  Shield,
  Facebook,
  Users,
  Phone,
  Mail,
  Video,
  Globe,
} from 'lucide-react-native';
import { Service } from '@/types/messaging';

export const SUPPORTED_SERVICES: Service[] = [
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    icon: MessageCircle,
    color: '#25D366',
    description: 'Connect your WhatsApp account',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    icon: Send,
    color: '#0088CC',
    description: 'Sync Telegram messages',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    icon: Camera,
    color: '#E4405F',
    description: 'Instagram Direct Messages',
  },
  {
    id: 'discord',
    name: 'Discord',
    icon: Hash,
    color: '#5865F2',
    description: 'Discord servers and DMs',
  },
  {
    id: 'slack',
    name: 'Slack',
    icon: Briefcase,
    color: '#4A154B',
    description: 'Slack workspaces',
  },
  {
    id: 'twitter',
    name: 'Twitter',
    icon: Twitter,
    color: '#1DA1F2',
    description: 'Twitter DMs',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: Linkedin,
    color: '#0077B5',
    description: 'LinkedIn messages',
  },
  {
    id: 'sms',
    name: 'SMS',
    icon: MessageSquare,
    color: '#34C759',
    description: 'Text messages',
  },
  {
    id: 'imessage',
    name: 'iMessage',
    icon: MessageSquare,
    color: '#007AFF',
    description: 'Apple iMessage',
  },
  {
    id: 'signal',
    name: 'Signal',
    icon: Shield,
    color: '#3A76F0',
    description: 'Secure Signal messages',
  },
  {
    id: 'messenger',
    name: 'Messenger',
    icon: Facebook,
    color: '#0084FF',
    description: 'Facebook Messenger',
  },
  {
    id: 'teams',
    name: 'Teams',
    icon: Users,
    color: '#6264A7',
    description: 'Microsoft Teams',
  },
];