import React from 'react';
import DepartmentDashboardView from '@/components/ai-agent/dashboard/DepartmentDashboardView';

const agents = [
  { id: 'ai-chief-operating-officer', uid: 'ktx-04-chief-operating-officer', title: 'AI Chief Operating Officer', route: '/ai-agent/operations/chief-operating-officer', color: '#607D8B', level: 'c_level', efficiency: '77%' },
  { id: 'ai-vp-operations', uid: 'ktx-04-vp-operations', title: 'AI VP Operations', route: '/ai-agent/operations/vp-operations', color: '#607D8B', level: 'vp_director', efficiency: '87%' },
  { id: 'ai-vp-supply-chain', uid: 'ktx-04-vp-supply-chain', title: 'AI VP Supply Chain', route: '/ai-agent/operations/vp-supply-chain', color: '#607D8B', level: 'vp_director', efficiency: '81%' },
  { id: 'ai-vp-quality', uid: 'ktx-04-vp-quality', title: 'AI VP Quality', route: '/ai-agent/operations/vp-quality', color: '#607D8B', level: 'vp_director', efficiency: '86%' },
  { id: 'ai-vp-facilities', uid: 'ktx-04-vp-facilities', title: 'AI VP Facilities', route: '/ai-agent/operations/vp-facilities', color: '#607D8B', level: 'vp_director', efficiency: '87%' },
  { id: 'ai-vp-project-management', uid: 'ktx-04-vp-project-management', title: 'AI VP Project Management', route: '/ai-agent/operations/vp-project-management', color: '#607D8B', level: 'vp_director', efficiency: '83%' },
  { id: 'ai-vp-continuous-improvement', uid: 'ktx-04-vp-continuous-improvement', title: 'AI VP Continuous Improvement', route: '/ai-agent/operations/vp-continuous-improvement', color: '#607D8B', level: 'vp_director', efficiency: '84%' },
  { id: 'ai-vp-risk-management-operations', uid: 'ktx-04-vp-risk-management-operations', title: 'AI VP Risk Management Operations', route: '/ai-agent/operations/vp-risk-management-operations', color: '#607D8B', level: 'vp_director', efficiency: '82%' },
  { id: 'ai-vp-change-management', uid: 'ktx-04-vp-change-management', title: 'AI VP Change Management', route: '/ai-agent/operations/vp-change-management', color: '#607D8B', level: 'vp_director', efficiency: '85%' },
  { id: 'ai-operations-director', uid: 'ktx-04-operations-director', title: 'AI Operations Director', route: '/ai-agent/operations/operations-director', color: '#607D8B', level: 'vp_director', efficiency: '86%' },
  { id: 'ai-operations-manager', uid: 'ktx-04-operations-manager', title: 'AI Operations Manager', route: '/ai-agent/operations/operations-manager', color: '#607D8B', level: 'manager', efficiency: '82%' },
  { id: 'ai-operations-manager-sub', uid: 'ktx-04-operations-manager-sub', title: 'AI Operations Manager (sub)', route: '/ai-agent/operations/operations-manager-sub', color: '#607D8B', level: 'manager', efficiency: '84%' },
  { id: 'ai-process-improvement-manager', uid: 'ktx-04-process-improvement-manager', title: 'AI Process Improvement Manager', route: '/ai-agent/operations/process-improvement-manager', color: '#607D8B', level: 'manager', efficiency: '83%' },
  { id: 'ai-quality-manager', uid: 'ktx-04-quality-manager', title: 'AI Quality Manager', route: '/ai-agent/operations/quality-manager', color: '#607D8B', level: 'manager', efficiency: '85%' },
  { id: 'ai-facilities-manager', uid: 'ktx-04-facilities-manager', title: 'AI Facilities Manager', route: '/ai-agent/operations/facilities-manager', color: '#607D8B', level: 'manager', efficiency: '84%' },
  { id: 'ai-project-management-office', uid: 'ktx-04-project-management-office', title: 'AI Project Management Office', route: '/ai-agent/operations/project-management-office', color: '#607D8B', level: 'manager', efficiency: '82%' },
  { id: 'ai-change-management-lead', uid: 'ktx-04-change-management-lead', title: 'AI Change Management Lead', route: '/ai-agent/operations/change-management-lead', color: '#607D8B', level: 'manager', efficiency: '83%' },
  { id: 'ai-workflow-automation-agent', uid: 'ktx-04-workflow-automation-agent', title: 'AI Workflow Automation Agent', route: '/ai-agent/operations/workflow-automation-agent', color: '#607D8B', level: 'team_lead', efficiency: '91%' },
  { id: 'ai-business-process-automation-specialist', uid: 'ktx-04-business-process-automation-specialist', title: 'AI Business Process Automation Specialist', route: '/ai-agent/operations/business-process-automation-specialist', color: '#607D8B', level: 'team_lead', efficiency: '89%' },
  { id: 'ai-rpa-developer', uid: 'ktx-04-rpa-developer', title: 'AI RPA Developer', route: '/ai-agent/operations/rpa-developer', color: '#607D8B', level: 'team_lead', efficiency: '87%' },
  { id: 'ai-task-coordinator', uid: 'ktx-04-task-coordinator', title: 'AI Task Coordinator', route: '/ai-agent/operations/task-coordinator', color: '#607D8B', level: 'c_level', efficiency: '88%' },
  { id: 'ai-workflow-orchestrator', uid: 'ktx-04-workflow-orchestrator', title: 'AI Workflow Orchestrator', route: '/ai-agent/operations/workflow-orchestrator', color: '#607D8B', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-scheduler', uid: 'ktx-04-scheduler', title: 'AI Scheduler', route: '/ai-agent/operations/scheduler', color: '#607D8B', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-resource-allocator', uid: 'ktx-04-resource-allocator', title: 'AI Resource Allocator', route: '/ai-agent/operations/resource-allocator', color: '#607D8B', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-process-optimization-agent', uid: 'ktx-04-process-optimization-agent', title: 'AI Process Optimization Agent', route: '/ai-agent/operations/process-optimization-agent', color: '#607D8B', level: 'team_lead', efficiency: '78%' },
  { id: 'ai-lean-manufacturing-specialist', uid: 'ktx-04-lean-manufacturing-specialist', title: 'AI Lean Manufacturing Specialist', route: '/ai-agent/operations/lean-manufacturing-specialist', color: '#607D8B', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-six-sigma-specialist', uid: 'ktx-04-six-sigma-specialist', title: 'AI Six Sigma Specialist', route: '/ai-agent/operations/six-sigma-specialist', color: '#607D8B', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-continuous-improvement-specialist', uid: 'ktx-04-continuous-improvement-specialist', title: 'AI Continuous Improvement Specialist', route: '/ai-agent/operations/continuous-improvement-specialist', color: '#607D8B', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-resource-planner', uid: 'ktx-04-resource-planner', title: 'AI Resource Planner', route: '/ai-agent/operations/resource-planner', color: '#607D8B', level: 'team_lead', efficiency: '88%' },
  { id: 'ai-capacity-planner', uid: 'ktx-04-capacity-planner', title: 'AI Capacity Planner', route: '/ai-agent/operations/capacity-planner', color: '#607D8B', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-demand-planner-ops', uid: 'ktx-04-demand-planner-ops', title: 'AI Demand Planner (Ops)', route: '/ai-agent/operations/demand-planner-ops', color: '#607D8B', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-inventory-optimizer', uid: 'ktx-04-inventory-optimizer', title: 'AI Inventory Optimizer', route: '/ai-agent/operations/inventory-optimizer', color: '#607D8B', level: 'team_lead', efficiency: '87%' },
  { id: 'ai-quality-assurance-agent', uid: 'ktx-04-quality-assurance-agent', title: 'AI Quality Assurance Agent', route: '/ai-agent/operations/quality-assurance-agent', color: '#607D8B', level: 'team_lead', efficiency: '77%' },
  { id: 'ai-quality-control-inspector', uid: 'ktx-04-quality-control-inspector', title: 'AI Quality Control Inspector', route: '/ai-agent/operations/quality-control-inspector', color: '#607D8B', level: 'team_lead', efficiency: '80%' },
  { id: 'ai-iso-compliance-specialist', uid: 'ktx-04-iso-compliance-specialist', title: 'AI ISO Compliance Specialist', route: '/ai-agent/operations/iso-compliance-specialist', color: '#607D8B', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-audit-specialist', uid: 'ktx-04-audit-specialist', title: 'AI Audit Specialist', route: '/ai-agent/operations/audit-specialist', color: '#607D8B', level: 'team_lead', efficiency: '81%' },
  { id: 'ai-facilities-coordinator', uid: 'ktx-04-facilities-coordinator', title: 'AI Facilities Coordinator', route: '/ai-agent/operations/facilities-coordinator', color: '#607D8B', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-maintenance-coordinator', uid: 'ktx-04-maintenance-coordinator', title: 'AI Maintenance Coordinator', route: '/ai-agent/operations/maintenance-coordinator', color: '#607D8B', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-space-planner', uid: 'ktx-04-space-planner', title: 'AI Space Planner', route: '/ai-agent/operations/space-planner', color: '#607D8B', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-utilities-manager', uid: 'ktx-04-utilities-manager', title: 'AI Utilities Manager', route: '/ai-agent/operations/utilities-manager', color: '#607D8B', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-project-manager-ops', uid: 'ktx-04-project-manager-ops', title: 'AI Project Manager (Ops)', route: '/ai-agent/operations/project-manager-ops', color: '#607D8B', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-scrum-master', uid: 'ktx-04-scrum-master', title: 'AI Scrum Master', route: '/ai-agent/operations/scrum-master', color: '#607D8B', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-agile-coach', uid: 'ktx-04-agile-coach', title: 'AI Agile Coach', route: '/ai-agent/operations/agile-coach', color: '#607D8B', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-program-manager', uid: 'ktx-04-program-manager', title: 'AI Program Manager', route: '/ai-agent/operations/program-manager', color: '#607D8B', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-portfolio-manager-ops', uid: 'ktx-04-portfolio-manager-ops', title: 'AI Portfolio Manager (Ops)', route: '/ai-agent/operations/portfolio-manager-ops', color: '#607D8B', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-change-management-specialist', uid: 'ktx-04-change-management-specialist', title: 'AI Change Management Specialist', route: '/ai-agent/operations/change-management-specialist', color: '#607D8B', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-communication-specialist', uid: 'ktx-04-communication-specialist', title: 'AI Communication Specialist', route: '/ai-agent/operations/communication-specialist', color: '#607D8B', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-stakeholder-manager', uid: 'ktx-04-stakeholder-manager', title: 'AI Stakeholder Manager', route: '/ai-agent/operations/stakeholder-manager', color: '#607D8B', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-training-coordinator-ops', uid: 'ktx-04-training-coordinator-ops', title: 'AI Training Coordinator (Ops)', route: '/ai-agent/operations/training-coordinator-ops', color: '#607D8B', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-documentation-specialist', uid: 'ktx-04-documentation-specialist', title: 'AI Documentation Specialist', route: '/ai-agent/operations/documentation-specialist', color: '#607D8B', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-policy-developer', uid: 'ktx-04-policy-developer', title: 'AI Policy Developer', route: '/ai-agent/operations/policy-developer', color: '#607D8B', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-compliance-officer-ops', uid: 'ktx-04-compliance-officer-ops', title: 'AI Compliance Officer (Ops)', route: '/ai-agent/operations/compliance-officer-ops', color: '#607D8B', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-risk-assessment-specialist', uid: 'ktx-04-risk-assessment-specialist', title: 'AI Risk Assessment Specialist', route: '/ai-agent/operations/risk-assessment-specialist', color: '#607D8B', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-business-continuity-planner', uid: 'ktx-04-business-continuity-planner', title: 'AI Business Continuity Planner', route: '/ai-agent/operations/business-continuity-planner', color: '#607D8B', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-disaster-recovery-specialist', uid: 'ktx-04-disaster-recovery-specialist', title: 'AI Disaster Recovery Specialist', route: '/ai-agent/operations/disaster-recovery-specialist', color: '#607D8B', level: 'team_lead', efficiency: '81%' },
  { id: 'ai-operations-analyst', uid: 'ktx-04-operations-analyst', title: 'AI Operations Analyst', route: '/ai-agent/operations/operations-analyst', color: '#607D8B', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-performance-analyst', uid: 'ktx-04-performance-analyst', title: 'AI Performance Analyst', route: '/ai-agent/operations/performance-analyst', color: '#607D8B', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-kpi-manager', uid: 'ktx-04-kpi-manager', title: 'AI KPI Manager', route: '/ai-agent/operations/kpi-manager', color: '#607D8B', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-benchmarking-specialist', uid: 'ktx-04-benchmarking-specialist', title: 'AI Benchmarking Specialist', route: '/ai-agent/operations/benchmarking-specialist', color: '#607D8B', level: 'team_lead', efficiency: '83%' },
];
export default function DepartmentIndex() {
  return (
    <DepartmentDashboardView
      departmentId="operations-management"
      agents={agents}
    />
  );
}
