/**
 * KAYTX AI WORKFORCE - Compact Agent Database
 * 22 Departments, 277 Main Agents, 831 Sub-Agents
 */
module.exports = {
  departments: [
    { id:1, slug:'customer', name:'Customer Experience', icon:'Headphones', color:'#007AFF', grad:['#007AFF','#5856D6'], desc:'Delivers 24/7 support through AI-powered agents handling onboarding to loyalty management.' },
    { id:2, slug:'sales', name:'Sales & Revenue', icon:'TrendingUp', color:'#FF9500', grad:['#FF9500','#FF6B00'], desc:'Drives growth through AI-powered selling, pipeline management, and revenue optimization.' },
    { id:3, slug:'marketing', name:'Marketing & Growth', icon:'Megaphone', color:'#AF52DE', grad:['#AF52DE','#8944AB'], desc:'Drives brand awareness, lead generation, and growth through AI-powered marketing automation.' },
    { id:4, slug:'operations', name:'Operations & Management', icon:'Settings', color:'#34C759', grad:['#34C759','#28A745'], desc:'Ensures organizational efficiency through process optimization and workflow automation.' },
    { id:5, slug:'finance', name:'Finance & Accounting', icon:'DollarSign', color:'#5856D6', grad:['#5856D6','#4A4AB5'], desc:'Manages financial operations, reporting, compliance, and strategic financial planning.' },
    { id:6, slug:'tech', name:'Technology & Engineering', icon:'Cpu', color:'#007AFF', grad:['#007AFF','#0051D5'], desc:'Drives innovation, builds and maintains systems, and ensures technical excellence.' },
    { id:7, slug:'hr', name:'Human Resources', icon:'Users', color:'#FF2D55', grad:['#FF2D55','#D4234A'], desc:'Manages talent acquisition, employee development, compensation, and HR operations.' },
    { id:8, slug:'legal', name:'Legal & Compliance', icon:'Scale', color:'#8E8E93', grad:['#8E8E93','#636366'], desc:'Ensures compliance, manages legal risks, handles contracts, and protects IP.' },
    { id:9, slug:'data', name:'Data & Intelligence', icon:'Database', color:'#06B6D4', grad:['#06B6D4','#0891B2'], desc:'Manages data strategy, analytics, BI, and machine learning operations.' },
    { id:10, slug:'product', name:'Product Management', icon:'Package', color:'#FF9500', grad:['#FF9500','#E08600'], desc:'Drives product strategy, development, and market success through AI lifecycle management.' },
    { id:11, slug:'security', name:'Security & Risk', icon:'Shield', color:'#FF3B30', grad:['#FF3B30','#D63028'], desc:'Protects assets, manages cybersecurity threats, ensures compliance, and mitigates risk.' },
    { id:12, slug:'research', name:'Research & Development', icon:'Microscope', color:'#7C3AED', grad:['#7C3AED','#6D28D9'], desc:'Drives innovation, conducts research, develops prototypes, and manages IP pipeline.' },
    { id:13, slug:'admin', name:'Administrative', icon:'Building2', color:'#64748B', grad:['#64748B','#475569'], desc:'Manages office operations, facilities, travel, documentation, and admin support.' },
    { id:14, slug:'trading', name:'Trading & Investments', icon:'TrendingUp', color:'#059669', grad:['#059669','#047857'], desc:'Manages investment portfolios, executes trades, monitors risk, and ensures compliance.' },
    { id:15, slug:'realestate', name:'Real Estate & Property', icon:'Building', color:'#B45309', grad:['#B45309','#92400E'], desc:'Manages property portfolios, leasing, maintenance, acquisitions, and development.' },
    { id:16, slug:'insurance', name:'Insurance & Risk', icon:'ShieldAlert', color:'#DC2626', grad:['#DC2626','#B91C1C'], desc:'Manages underwriting, claims, actuarial analysis, fraud detection, and risk modeling.' },
    { id:17, slug:'healthcare', name:'Healthcare & Medical', icon:'Heart', color:'#EF4444', grad:['#EF4444','#DC2626'], desc:'Manages patient services, medical billing, scheduling, compliance, and quality improvement.' },
    { id:18, slug:'manufacturing', name:'Manufacturing & Production', icon:'Factory', color:'#F59E0B', grad:['#F59E0B','#D97706'], desc:'Manages production lines, quality control, safety, maintenance, and supply chain coordination.' },
    { id:19, slug:'transportation', name:'Transportation & Logistics', icon:'Truck', color:'#2563EB', grad:['#2563EB','#1D4ED8'], desc:'Manages fleet operations, warehousing, distribution, route optimization, and customs.' },
    { id:20, slug:'government', name:'Government & Public Sector', icon:'Landmark', color:'#1E40AF', grad:['#1E40AF','#1E3A8A'], desc:'Manages public policy, regulatory affairs, grants, compliance, and transparency.' },
    { id:21, slug:'supply-chain', name:'Supply Chain & Logistics', icon:'Package', color:'#0891B2', grad:['#0891B2','#0E7490'], desc:'Manages procurement, warehousing, demand planning, supplier relations, and fulfillment.' },
    { id:22, slug:'ai-mgmt', name:'AI Management & Governance', icon:'Bot', color:'#8B5CF6', grad:['#8B5CF6','#7C3AED'], desc:'Manages automation strategy, RPA operations, process excellence, and workflow optimization.' },
  ],
  agents: {
    1: [ // Customer Experience - 14 main
      { n:'AI Chief Customer Officer', s:'chief-customer-officer', sn:'CCO', i:'Crown', l:'C-Suite', t:'enterprise', c:['Customer Strategy','Experience Design','Journey Mapping','Retention Programs','Voice Analytics','Sentiment Analysis','NPS Tracking','Success Frameworks'], r:['Customer Experience Strategy & Vision','Customer Satisfaction Monitoring & Reporting','Support Operations Oversight & Optimization','Customer Retention & Loyalty Programs','Journey Mapping & Touchpoint Analysis','Voice of Customer & Feedback Systems'], sub:[
        { n:'AI CX Strategy Analyst', s:'cx-strategy-analyst', i:'Target', c:['CX Strategy Analysis','AI-Powered','Real-time','Analytics','Integration','Automation'] },
        { n:'AI Customer Journey Mapper', s:'customer-journey-mapper', i:'MapPin', c:['Journey Mapping','Touchpoint Analysis','Path Optimization','Visualization','Integration','Automation'] },
        { n:'AI CX Metrics Tracker', s:'cx-metrics-tracker', i:'ChartBar', c:['Metrics Tracking','KPI Monitoring','NPS Analysis','CSAT Reporting','Trend Analysis','Dashboard Building'] },
      ]},
      { n:'AI VP Customer Success', s:'vp-customer-success', sn:'VP CS', i:'Users', l:'VP', t:'enterprise', c:['Onboarding Management','Account Health Monitoring','Success Planning','Renewal Strategy','Expansion Revenue','Customer Advocacy'], r:['Customer Onboarding & Implementation','Account Health Monitoring & Risk Detection','Success Plan Development & Execution','Renewal & Expansion Strategy','Customer Advocacy Programs','Cross-functional Success Alignment'], sub:[
        { n:'AI Onboarding Specialist', s:'onboarding-specialist', i:'UserPlus', c:['Onboarding Automation','Setup Guidance','Training Coordination','Milestone Tracking','Integration Setup','Success Validation'] },
        { n:'AI Account Health Monitor', s:'account-health-monitor', i:'Activity', c:['Health Scoring','Risk Detection','Usage Analytics','Engagement Tracking','Alert Generation','Trend Analysis'] },
        { n:'AI Success Plan Coordinator', s:'success-plan-coordinator', i:'ClipboardList', c:['Plan Creation','Goal Tracking','Milestone Management','Stakeholder Alignment','Progress Reporting','Outcome Measurement'] },
      ]},
      { n:'AI VP Support', s:'vp-support', sn:'VP Support', i:'Headphones', l:'VP', t:'enterprise', c:['Support Operations','Escalation Management','Knowledge Management','Quality Assurance','SLA Management','Team Optimization'], r:['Support Operations Strategy & Execution','Escalation Management & Resolution','Knowledge Base Development & Curation','Support Quality Assurance Programs','SLA Management & Compliance','Support Team Performance & Optimization'], sub:[
        { n:'AI Escalation Manager', s:'escalation-manager', i:'AlertTriangle', c:['Escalation Routing','Priority Assessment','SLA Tracking','Resolution Coordination','Stakeholder Notification','Post-mortem Analysis'] },
        { n:'AI Knowledge Base Curator', s:'knowledge-base-curator', i:'BookOpen', c:['Content Curation','Article Management','Gap Analysis','Version Control','Search Optimization','Usage Analytics'] },
        { n:'AI Support Quality Auditor', s:'support-quality-auditor', i:'ShieldCheck', c:['Quality Scoring','Compliance Checking','Performance Review','Standard Enforcement','Training Recommendations','Report Generation'] },
      ]},
      { n:'AI VP Experience', s:'vp-experience', sn:'VP CX', i:'Sparkles', l:'VP', t:'enterprise', c:['UX Optimization','Personalization','Experience Benchmarking','Feedback Analysis','Design Thinking','Omnichannel Strategy'], r:['User Experience Strategy & Optimization','Personalization Engine Management','Experience Benchmarking & Comparison','Customer Feedback Analysis & Action','Design Thinking Facilitation','Omnichannel Experience Strategy'], sub:[
        { n:'AI UX Feedback Analyst', s:'ux-feedback-analyst', i:'MessageSquare', c:['Feedback Collection','Sentiment Analysis','Pattern Detection','Priority Ranking','Action Recommendations','Trend Reporting'] },
        { n:'AI Experience Benchmark Analyst', s:'experience-benchmark-analyst', i:'BarChart3', c:['Benchmark Analysis','Competitive Comparison','Industry Standards','Gap Identification','Improvement Planning','Score Tracking'] },
        { n:'AI Personalization Engine', s:'personalization-engine', i:'Fingerprint', c:['User Profiling','Content Personalization','Behavior Prediction','A/B Testing','Recommendation Engine','Preference Learning'] },
      ]},
      { n:'AI VP Retention', s:'vp-retention', sn:'VP Retention', i:'Shield', l:'VP', t:'enterprise', c:['Churn Prevention','Win-back Strategy','Retention Analytics','Customer Lifecycle','Risk Scoring','Proactive Engagement'], r:['Customer Retention Strategy & Programs','Churn Prediction & Prevention','Win-back Campaign Management','Retention Analytics & Reporting','Customer Lifecycle Management','Proactive Engagement Programs'], sub:[
        { n:'AI Churn Predictor', s:'churn-predictor', i:'TrendingDown', c:['Churn Prediction','Risk Scoring','Behavior Analysis','Early Warning','Intervention Triggers','Model Training'] },
        { n:'AI Win-back Campaign Specialist', s:'win-back-campaign-specialist', i:'RotateCcw', c:['Campaign Design','Target Selection','Offer Optimization','Channel Strategy','Performance Tracking','ROI Analysis'] },
        { n:'AI Retention Metrics Analyst', s:'retention-metrics-analyst', i:'PieChart', c:['Metrics Analysis','Cohort Tracking','Retention Curves','Churn Analysis','LTV Calculation','Reporting Automation'] },
      ]},
      { n:'AI VP Loyalty', s:'vp-loyalty', sn:'VP Loyalty', i:'Award', l:'VP', t:'enterprise', c:['Loyalty Programs','Rewards Strategy','Tier Management','Engagement Scoring','Program Design','Member Analytics'], r:['Loyalty Program Strategy & Design','Rewards Program Management','Tier System Management','Engagement Scoring & Optimization','Loyalty Program Analytics','Member Experience Optimization'], sub:[
        { n:'AI Rewards Program Designer', s:'rewards-program-designer', i:'Gift', c:['Program Design','Reward Structuring','Tier Planning','Engagement Mechanics','ROI Modeling','Competitive Analysis'] },
        { n:'AI Loyalty Tier Analyst', s:'loyalty-tier-analyst', i:'Layers', c:['Tier Analysis','Progression Modeling','Threshold Optimization','Member Segmentation','Benefit Planning','Upgrade Triggers'] },
        { n:'AI Engagement Scoring Agent', s:'engagement-scoring-agent', i:'Gauge', c:['Engagement Scoring','Activity Tracking','Behavior Analysis','Score Calibration','Segment Classification','Intervention Triggers'] },
      ]},
      { n:'AI Receptionist', s:'receptionist', sn:'Receptionist', i:'Phone', l:'Specialist', t:'premium', c:['Call Handling','Appointment Scheduling','FAQ Response','Multi-language Support','Call Routing','Voicemail Management'], r:['Incoming Call Management & Routing','Appointment Scheduling & Reminders','FAQ Response & Information Provision','Visitor Management & Logging','Multi-language Support','Voicemail Management & Follow-up'], sub:[
        { n:'AI Call Router', s:'call-router', i:'PhoneCall', c:['Intelligent Routing','Priority Assessment','Skill-based Routing','Queue Management','Transfer Protocols','Analytics Tracking'] },
        { n:'AI Visitor Logger', s:'visitor-logger', i:'ClipboardList', c:['Visitor Registration','Check-in Management','Badge Generation','Visit Logging','Host Notification','Security Integration'] },
        { n:'AI Appointment Scheduler', s:'appointment-scheduler', i:'Calendar', c:['Scheduling Automation','Calendar Sync','Conflict Resolution','Reminder System','Rescheduling Logic','Availability Management'] },
      ]},
      { n:'AI Customer Support Agent', s:'customer-support', sn:'Support', i:'MessageCircle', l:'Specialist', t:'premium', c:['Ticket Resolution','Live Chat','Email Support','Knowledge Base','Escalation Management','SLA Tracking'], r:['Customer Issue Resolution','Live Chat Support','Email Support Management','Knowledge Base Utilization','Escalation Management','SLA Compliance'], sub:[
        { n:'AI FAQ Responder', s:'faq-responder', i:'HelpCircle', c:['FAQ Matching','Instant Response','Context Awareness','Learning System','Multi-channel','Feedback Loop'] },
        { n:'AI Troubleshooting Guide', s:'troubleshooting-guide', i:'Wrench', c:['Step-by-step Guides','Diagnostic Trees','Solution Matching','Visual Aids','Progress Tracking','Resolution Verification'] },
        { n:'AI Live Chat Handler', s:'live-chat-handler', i:'MessagesSquare', c:['Real-time Chat','Multi-conversation','Context Memory','Escalation Triggers','Sentiment Detection','Response Suggestions'] },
      ]},
      { n:'AI Ticket Resolution Agent', s:'ticket-resolution', sn:'Tickets', i:'Ticket', l:'Specialist', t:'premium', c:['Auto-Resolution','Intelligent Escalation','SLA Tracking','Priority Management','Pattern Recognition','Root Cause Analysis'], r:['Automated Ticket Resolution','Intelligent Escalation Management','SLA Tracking & Compliance','Priority Management & Routing','Pattern Recognition & Learning','Root Cause Analysis'], sub:[
        { n:'AI Ticket Classifier', s:'ticket-classifier', i:'Tag', c:['Auto-classification','Priority Scoring','Category Assignment','Sentiment Tagging','Routing Logic','Trend Detection'] },
        { n:'AI Solution Matcher', s:'solution-matcher', i:'Puzzle', c:['Solution Matching','Knowledge Retrieval','Similarity Analysis','Success Rate Tracking','Learning Engine','Recommendation Ranking'] },
        { n:'AI Escalation Router', s:'escalation-router', i:'ArrowUpCircle', c:['Escalation Routing','Skill Matching','Workload Balancing','SLA Compliance','Notification Chain','Tracking Dashboard'] },
      ]},
      { n:'AI Complaint Handling Agent', s:'complaint-handling', sn:'Complaints', i:'AlertCircle', l:'Specialist', t:'enterprise', c:['Complaint Analysis','Resolution Suggestions','Follow-up Automation','Sentiment Detection','Escalation Protocols','Compensation Management'], r:['Complaint Intake & Analysis','Resolution Strategy & Execution','Follow-up Automation','Sentiment Detection & Monitoring','Escalation Protocol Management','Compensation & Recovery Management'], sub:[
        { n:'AI Complaint Categorizer', s:'complaint-categorizer', i:'FolderTree', c:['Auto-categorization','Severity Assessment','Root Cause Tagging','Trend Analysis','Priority Assignment','Pattern Detection'] },
        { n:'AI Resolution Tracker', s:'resolution-tracker', i:'CheckCircle2', c:['Resolution Tracking','Timeline Management','Status Updates','SLA Monitoring','Outcome Recording','Satisfaction Verification'] },
        { n:'AI Sentiment Analyzer', s:'sentiment-analyzer', i:'Heart', c:['Sentiment Analysis','Emotion Detection','Tone Assessment','Trend Monitoring','Alert Generation','Report Building'] },
      ]},
      { n:'AI Retention Specialist', s:'retention-specialist', sn:'Retention', i:'Heart', l:'Specialist', t:'enterprise', c:['Churn Prediction','Win-back Campaigns','Loyalty Offers','Journey Optimization','Risk Scoring','Personalized Outreach'], r:['Churn Risk Identification & Prevention','Win-back Campaign Execution','Loyalty Offer Management','Customer Journey Optimization','Risk Scoring & Monitoring','Personalized Outreach Programs'], sub:[
        { n:'AI At-Risk Identifier', s:'at-risk-identifier', i:'AlertTriangle', c:['Risk Identification','Behavior Monitoring','Churn Signals','Early Warning','Segmentation','Intervention Timing'] },
        { n:'AI Offer Optimizer', s:'offer-optimizer', i:'Percent', c:['Offer Optimization','A/B Testing','ROI Maximization','Personalization','Discount Strategy','Conversion Tracking'] },
        { n:'AI Follow-up Scheduler', s:'follow-up-scheduler', i:'Clock', c:['Follow-up Scheduling','Timing Optimization','Channel Selection','Message Personalization','Response Tracking','Escalation Logic'] },
      ]},
      { n:'AI Loyalty & Engagement Agent', s:'loyalty-engagement', sn:'Loyalty', i:'Gift', l:'Specialist', t:'premium', c:['Rewards Management','Engagement Tracking','Program Optimization','Gamification','Points Management','Tier Progression'], r:['Rewards Program Management','Engagement Tracking & Optimization','Program Performance Optimization','Gamification Strategy','Points System Management','Tier Progression Management'], sub:[
        { n:'AI Points Calculator', s:'points-calculator', i:'Calculator', c:['Points Calculation','Balance Tracking','Earning Rules','Redemption Logic','Expiry Management','Audit Trail'] },
        { n:'AI Reward Recommender', s:'reward-recommender', i:'Star', c:['Reward Recommendations','Preference Learning','Catalog Management','Personalization','Inventory Tracking','Satisfaction Prediction'] },
        { n:'AI Engagement Tracker', s:'engagement-tracker', i:'BarChart', c:['Engagement Tracking','Activity Logging','Score Calculation','Trend Analysis','Segment Reporting','Intervention Triggers'] },
      ]},
      { n:'AI Feedback & Survey Agent', s:'feedback-survey', sn:'Feedback', i:'MessageSquare', l:'Specialist', t:'premium', c:['Survey Design','Response Analysis','Insight Generation','NPS Management','Feedback Collection','Action Planning'], r:['Survey Design & Distribution','Response Analysis & Interpretation','Insight Generation & Reporting','NPS Program Management','Feedback Collection Optimization','Action Planning from Feedback'], sub:[
        { n:'AI Survey Designer', s:'survey-designer', i:'FileEdit', c:['Survey Design','Question Optimization','Logic Branching','Distribution Planning','Response Prediction','Template Management'] },
        { n:'AI Response Analyzer', s:'response-analyzer', i:'BarChart3', c:['Response Analysis','Statistical Processing','Sentiment Extraction','Pattern Detection','Correlation Finding','Visualization'] },
        { n:'AI Insight Reporter', s:'insight-reporter', i:'FileText', c:['Insight Synthesis','Report Generation','Action Recommendations','Trend Highlighting','Stakeholder Summaries','Priority Ranking'] },
      ]},
      { n:'AI Billing Support Agent', s:'billing-support', sn:'Billing', i:'CreditCard', l:'Specialist', t:'premium', c:['Payment Processing','Invoice Management','Dispute Resolution','Billing Inquiries','Payment Plans','Refund Management'], r:['Payment Processing & Management','Invoice Explanation & Management','Billing Dispute Resolution','Payment Plan Administration','Refund Processing & Management','Billing Inquiry Response'], sub:[
        { n:'AI Payment Processor', s:'payment-processor', i:'Wallet', c:['Payment Processing','Transaction Validation','Multi-method Support','Receipt Generation','Reconciliation','Error Handling'] },
        { n:'AI Invoice Explainer', s:'invoice-explainer', i:'Receipt', c:['Invoice Breakdown','Charge Explanation','Tax Details','Payment History','Discrepancy Detection','Self-service Portal'] },
        { n:'AI Dispute Resolver', s:'dispute-resolver', i:'Scale', c:['Dispute Intake','Investigation Logic','Resolution Paths','Escalation Criteria','Compensation Rules','Satisfaction Tracking'] },
      ]},
    ],
  }
};

// Helper to generate remaining department agents programmatically
function makeAgent(num, name, slug, shortName, icon, level, tier, caps, resps, subs) {
  return { n:name, s:slug, sn:shortName, i:icon, l:level, t:tier, c:caps, r:resps, sub:subs };
}
function makeSub(name, slug, icon, caps) {
  return { n:name, s:slug, i:icon, c:caps };
}

// Dept 2: Sales
module.exports.agents[2] = [
  makeAgent(15,'AI VP Sales','vp-sales','VP Sales','TrendingUp','VP','enterprise',['Pipeline Management','Quota Tracking','Territory Planning','Sales Strategy','Team Performance','Revenue Forecasting'],['Sales Strategy & Execution','Pipeline Management & Optimization','Quota Tracking & Achievement','Territory Planning & Assignment','Sales Team Performance Management','Revenue Forecasting & Reporting'],[makeSub('AI Pipeline Analyst','pipeline-analyst','GitBranch',['Pipeline Analysis','Stage Tracking','Velocity Metrics','Bottleneck Detection','Forecast Accuracy','Conversion Optimization']),makeSub('AI Quota Tracker','quota-tracker','Target',['Quota Tracking','Progress Monitoring','Attainment Prediction','Gap Analysis','Incentive Calculation','Team Rankings']),makeSub('AI Territory Planner','territory-planner','Map',['Territory Design','Account Assignment','Balance Optimization','Potential Scoring','Coverage Analysis','Redistricting'])]),
  makeAgent(16,'AI VP Revenue','vp-revenue','VP Revenue','DollarSign','VP','enterprise',['Revenue Modeling','Pricing Strategy','Forecast Validation','Growth Planning','Revenue Operations','Margin Optimization'],['Revenue Strategy & Modeling','Pricing Strategy & Optimization','Forecast Validation & Accuracy','Growth Planning & Execution','Revenue Operations Management','Margin Optimization & Analysis'],[makeSub('AI Revenue Modeler','revenue-modeler','BarChart3',['Revenue Modeling','Scenario Planning','Growth Projection','Cohort Analysis','Unit Economics','Sensitivity Analysis']),makeSub('AI Pricing Optimizer','pricing-optimizer','DollarSign',['Price Optimization','Dynamic Pricing','Elasticity Analysis','Competitor Pricing','Margin Targeting','A/B Testing']),makeSub('AI Forecast Validator','forecast-validator','CheckCircle2',['Forecast Validation','Accuracy Tracking','Bias Detection','Confidence Scoring','Historical Comparison','Adjustment Recommendations'])]),
  makeAgent(17,'AI VP Business Development','vp-business-development','VP BizDev','Briefcase','VP','enterprise',['Partnership Development','Market Expansion','Strategic Alliances','New Markets','Business Planning','Opportunity Assessment'],['Partnership Development & Management','Market Expansion Strategy','Strategic Alliance Building','New Market Identification','Business Planning & Execution','Opportunity Assessment & Prioritization'],[makeSub('AI Partnership Scout','partnership-scout','Search',['Partner Discovery','Fit Assessment','Due Diligence','Outreach Strategy','Relationship Mapping','Opportunity Scoring']),makeSub('AI Market Expander','market-expander','Globe',['Market Analysis','Entry Strategy','Localization','Regulatory Assessment','Competitive Mapping','Growth Planning']),makeSub('AI Alliance Coordinator','alliance-coordinator','Handshake',['Alliance Management','Joint Planning','Resource Coordination','Performance Tracking','Conflict Resolution','Value Measurement'])]),
  makeAgent(18,'AI VP Channel Partners','vp-channel-partners','VP Channel','Network','VP','enterprise',['Channel Strategy','Partner Management','Co-marketing','Channel Performance','Partner Enablement','Revenue Sharing'],['Channel Strategy & Development','Partner Management & Enablement','Co-marketing Program Management','Channel Performance Monitoring','Partner Onboarding & Training','Revenue Sharing & Incentive Programs'],[makeSub('AI Partner Onboarding Agent','partner-onboarding-agent','UserPlus',['Onboarding Automation','Training Coordination','Certification Tracking','Resource Provisioning','Progress Monitoring','Success Validation']),makeSub('AI Channel Performance Tracker','channel-performance-tracker','Activity',['Performance Tracking','Revenue Attribution','Pipeline Monitoring','Engagement Scoring','Tier Management','Incentive Calculation']),makeSub('AI Co-marketing Coordinator','co-marketing-coordinator','Share2',['Campaign Coordination','Budget Sharing','Asset Management','Lead Distribution','Performance Tracking','ROI Reporting'])]),
  makeAgent(19,'AI Sales Operations Manager','sales-ops-manager','Sales Ops','Settings','Manager','enterprise',['CRM Management','Sales Process','Reporting Automation','Data Quality','Sales Tools','Process Optimization'],['CRM System Management & Optimization','Sales Process Design & Enforcement','Reporting & Analytics Automation','Data Quality Management','Sales Tool Administration','Process Optimization & Improvement'],[makeSub('AI CRM Data Cleaner','crm-data-cleaner','Database',['Data Deduplication','Field Standardization','Record Enrichment','Merge Resolution','Quality Scoring','Cleanup Automation']),makeSub('AI Sales Process Auditor','sales-process-auditor','ClipboardCheck',['Process Auditing','Compliance Checking','Stage Validation','Bottleneck Detection','Best Practice Enforcement','Improvement Recommendations']),makeSub('AI Reporting Automator','reporting-automator','FileSpreadsheet',['Report Automation','Dashboard Creation','Schedule Management','Distribution Logic','Format Standardization','Alert Configuration'])]),
  makeAgent(20,'AI Lead Development Rep (SDR)','sdr','SDR','PhoneCall','Specialist','premium',['Prospecting','Outreach Sequences','Lead Scoring','Qualification','Cold Calling','Email Campaigns'],['Prospecting & Lead Generation','Outreach Sequence Management','Lead Scoring & Qualification','Cold Calling & Email Campaigns','Meeting Scheduling','Pipeline Contribution'],[makeSub('AI Prospect Researcher','prospect-researcher','Search',['Company Research','Contact Discovery','Intent Data','Social Selling','Technographic Analysis','Buyer Persona Matching']),makeSub('AI Outreach Sequencer','outreach-sequencer','Mail',['Sequence Design','Multi-channel Outreach','Timing Optimization','Personalization','Response Tracking','A/B Testing']),makeSub('AI Lead Scorer','lead-scorer','Star',['Lead Scoring','Behavior Tracking','Fit Assessment','Intent Analysis','Priority Ranking','Handoff Automation'])]),
  makeAgent(21,'AI Sales Rep','sales-rep','Sales Rep','UserCheck','Specialist','premium',['Discovery','Demo Coordination','Objection Handling','Relationship Building','Proposal Development','Closing'],['Discovery & Needs Assessment','Demo Coordination & Delivery','Objection Handling & Mitigation','Relationship Building & Management','Proposal Development','Deal Closing & Negotiation'],[makeSub('AI Discovery Questioner','discovery-questioner','HelpCircle',['Question Frameworks','Needs Assessment','Pain Point Identification','Stakeholder Mapping','Priority Discovery','Opportunity Sizing']),makeSub('AI Demo Coordinator','demo-coordinator','Monitor',['Demo Scheduling','Environment Setup','Script Preparation','Follow-up Automation','Feedback Collection','Success Tracking']),makeSub('AI Objection Handler','objection-handler','Shield',['Objection Classification','Response Frameworks','Proof Points','Case Study Matching','Risk Mitigation','Confidence Building'])]),
  makeAgent(22,'AI Sales Executive','sales-executive','Sales Exec','Briefcase','Specialist','enterprise',['Deal Structuring','Stakeholder Management','Closing Strategy','Enterprise Sales','Contract Negotiation','Revenue Optimization'],['Deal Structuring & Strategy','Stakeholder Mapping & Management','Closing Strategy & Execution','Enterprise Sales Process Management','Contract Negotiation & Terms','Revenue Optimization & Expansion'],[makeSub('AI Deal Structurer','deal-structurer','FileText',['Deal Architecture','Pricing Models','Term Structuring','Risk Assessment','Value Proposition','Approval Workflow']),makeSub('AI Stakeholder Mapper','stakeholder-mapper','Users',['Stakeholder Identification','Influence Mapping','Decision Tree','Champion Development','Objection Anticipation','Engagement Strategy']),makeSub('AI Closing Strategist','closing-strategist','CheckCircle2',['Close Planning','Urgency Creation','Negotiation Tactics','Mutual Action Plans','Timeline Management','Win Strategy'])]),
  makeAgent(23,'AI CRM Assistant','crm-assistant','CRM','Database','Specialist','premium',['Contact Management','Activity Logging','Pipeline Organization','Data Entry','Follow-up Tracking','Reporting'],['Contact Management & Updates','Activity Logging & Tracking','Pipeline Organization & Management','Data Entry & Maintenance','Follow-up Task Management','CRM Reporting & Analytics'],[makeSub('AI Contact Updater','contact-updater','UserCheck',['Contact Updates','Enrichment Automation','Change Detection','Duplicate Prevention','Sync Management','Quality Assurance']),makeSub('AI Activity Logger','activity-logger','Clock',['Activity Logging','Auto-capture','Timeline Building','Category Tagging','Duration Tracking','Compliance Recording']),makeSub('AI Pipeline Organizer','pipeline-organizer','GitBranch',['Pipeline Organization','Stage Management','Deal Tracking','Probability Scoring','Close Date Prediction','Forecast Contribution'])]),
  makeAgent(24,'AI Proposal Generator','proposal-generator','Proposals','FileText','Specialist','premium',['Template Management','Pricing Calculation','Proposal Review','Customization','Approval Workflow','Version Control'],['Proposal Template Management','Pricing Calculation & Configuration','Proposal Review & Quality Assurance','Customization & Personalization','Approval Workflow Management','Version Control & Tracking'],[makeSub('AI Template Selector','template-selector','Layout',['Template Matching','Industry Selection','Customization Points','Branding Application','Compliance Checking','Version Management']),makeSub('AI Pricing Calculator','pricing-calculator','Calculator',['Price Calculation','Discount Logic','Bundle Pricing','Margin Analysis','Approval Triggers','Historical Comparison']),makeSub('AI Proposal Reviewer','proposal-reviewer','Eye',['Quality Review','Consistency Check','Compliance Verification','Win Probability','Improvement Suggestions','Approval Routing'])]),
  makeAgent(25,'AI Negotiator','negotiator','Negotiator','Scale','Specialist','enterprise',['Term Analysis','Concession Tracking','BATNA Calculation','Strategy Planning','Value Creation','Agreement Drafting'],['Negotiation Strategy & Planning','Term Analysis & Optimization','Concession Tracking & Management','BATNA Development & Calculation','Value Creation & Distribution','Agreement Drafting & Finalization'],[makeSub('AI Term Analyzer','term-analyzer','FileSearch',['Term Analysis','Risk Assessment','Market Benchmarking','Impact Modeling','Alternative Generation','Negotiation Leverage']),makeSub('AI Concession Tracker','concession-tracker','ArrowLeftRight',['Concession Tracking','Value Accounting','Trade-off Analysis','Pattern Detection','Reciprocity Logic','Boundary Enforcement']),makeSub('AI BATNA Calculator','batna-calculator','Calculator',['BATNA Calculation','Alternative Valuation','Walk-away Point','Leverage Assessment','Scenario Modeling','Decision Framework'])]),
  makeAgent(26,'AI Pricing Analyst','pricing-analyst','Pricing','DollarSign','Specialist','premium',['Competitor Pricing','Margin Calculation','Discount Management','Price Optimization','Market Analysis','Revenue Impact'],['Competitor Price Monitoring & Analysis','Margin Calculation & Optimization','Discount Policy Management','Price Optimization & Testing','Market Price Analysis','Revenue Impact Assessment'],[makeSub('AI Competitor Price Tracker','competitor-price-tracker','ScanSearch',['Price Monitoring','Change Detection','Trend Analysis','Competitive Positioning','Alert Generation','Historical Tracking']),makeSub('AI Margin Calculator','margin-calculator','Percent',['Margin Calculation','Cost Analysis','Break-even Analysis','Profitability Modeling','Scenario Planning','Sensitivity Testing']),makeSub('AI Discount Approver','discount-approver','CheckCircle2',['Discount Validation','Policy Enforcement','Approval Routing','Impact Assessment','Threshold Management','Audit Trail'])]),
  makeAgent(27,'AI Sales Forecasting Agent','sales-forecasting','Forecasting','BarChart3','Specialist','premium',['Trend Analysis','Seasonality Adjustment','Pipeline Weighting','Forecast Modeling','Accuracy Tracking','Scenario Planning'],['Sales Trend Analysis & Reporting','Seasonality Adjustment & Planning','Pipeline Weighting & Scoring','Forecast Model Development','Accuracy Tracking & Improvement','Scenario Planning & Sensitivity'],[makeSub('AI Trend Analyzer','trend-analyzer','TrendingUp',['Trend Detection','Pattern Recognition','Cycle Analysis','Growth Rate Calculation','Anomaly Detection','Prediction Modeling']),makeSub('AI Seasonality Adjuster','seasonality-adjuster','Calendar',['Seasonal Adjustment','Holiday Impact','Quarterly Patterns','Cyclical Analysis','Baseline Calculation','Forecast Correction']),makeSub('AI Pipeline Weighter','pipeline-weighter','Scale',['Pipeline Weighting','Close Probability','Stage Multipliers','Historical Calibration','Risk Adjustment','Confidence Scoring'])]),
  makeAgent(28,'AI Sales Enablement Agent','sales-enablement','Enablement','Zap','Specialist','premium',['Content Recommendation','Training Scheduling','Playbook Management','Onboarding','Skill Development','Knowledge Management'],['Content Recommendation & Management','Training Program Scheduling & Delivery','Playbook Development & Updates','Sales Onboarding Programs','Skill Development Planning','Knowledge Management & Distribution'],[makeSub('AI Content Recommender','content-recommender','BookOpen',['Content Matching','Context Awareness','Usage Analytics','Effectiveness Scoring','Gap Identification','Recommendation Engine']),makeSub('AI Training Scheduler','training-scheduler','Calendar',['Training Scheduling','Curriculum Mapping','Progress Tracking','Certification Management','Reminder System','Completion Reporting']),makeSub('AI Playbook Updater','playbook-updater','RefreshCw',['Playbook Updates','Best Practice Integration','Win/Loss Analysis','Competitive Intelligence','Process Improvement','Version Management'])]),
];

// Dept 3: Marketing
module.exports.agents[3] = [
  makeAgent(29,'AI Chief Marketing Officer','cmo','CMO','Crown','C-Suite','enterprise',['Marketing Strategy','Budget Allocation','Campaign ROI','Brand Management','Growth Planning','Market Intelligence'],['Marketing Strategy & Vision','Budget Allocation & Optimization','Campaign ROI Evaluation','Brand Management & Positioning','Growth Planning & Execution','Market Intelligence & Analysis'],[makeSub('AI Marketing Strategy Analyst','marketing-strategy-analyst','Target',['Strategy Analysis','Market Research','Competitive Intelligence','Opportunity Identification','Channel Strategy','ROI Forecasting']),makeSub('AI Budget Allocator','budget-allocator','PieChart',['Budget Allocation','Channel Optimization','Spend Analysis','ROI Maximization','Forecast Modeling','Reallocation Logic']),makeSub('AI Campaign ROI Evaluator','campaign-roi-evaluator','TrendingUp',['ROI Calculation','Attribution Modeling','Cost Analysis','Performance Benchmarking','Optimization Recommendations','Reporting Automation'])]),
  makeAgent(30,'AI VP Marketing','vp-marketing','VP Marketing','Megaphone','VP','enterprise',['Channel Planning','Calendar Management','Campaign Coordination','Team Leadership','Marketing Operations','Performance Management'],['Channel Planning & Optimization','Marketing Calendar Management','Campaign Coordination & Execution','Marketing Team Leadership','Marketing Operations Management','Performance Management & Reporting'],[makeSub('AI Channel Planner','channel-planner','Layout',['Channel Strategy','Mix Optimization','Budget Distribution','Audience Matching','Performance Prediction','Cross-channel Coordination']),makeSub('AI Marketing Calendar Manager','marketing-calendar-manager','Calendar',['Calendar Management','Campaign Scheduling','Content Planning','Deadline Tracking','Conflict Resolution','Resource Allocation']),makeSub('AI Campaign Coordinator','campaign-coordinator','Zap',['Campaign Coordination','Cross-team Alignment','Timeline Management','Asset Tracking','Launch Execution','Performance Monitoring'])]),
  makeAgent(31,'AI VP Brand','vp-brand','VP Brand','Palette','VP','enterprise',['Brand Strategy','Perception Monitoring','Guidelines Enforcement','Visual Identity','Brand Equity','Reputation Management'],['Brand Strategy & Development','Brand Perception Monitoring','Brand Guidelines Enforcement','Visual Identity Management','Brand Equity Building','Reputation Management'],[makeSub('AI Brand Perception Monitor','brand-perception-monitor','Eye',['Perception Tracking','Sentiment Analysis','Social Listening','Competitor Comparison','Trend Detection','Alert Generation']),makeSub('AI Brand Guidelines Enforcer','brand-guidelines-enforcer','ShieldCheck',['Guideline Enforcement','Consistency Checking','Asset Validation','Template Management','Compliance Scoring','Violation Detection']),makeSub('AI Visual Identity Auditor','visual-identity-auditor','Image',['Visual Auditing','Color Compliance','Typography Checking','Logo Usage','Asset Management','Template Validation'])]),
  makeAgent(32,'AI VP Growth','vp-growth','VP Growth','Rocket','VP','enterprise',['Growth Experiments','Funnel Analysis','A/B Testing','Acquisition Strategy','Retention Optimization','Product-led Growth'],['Growth Experiment Design & Execution','Funnel Analysis & Optimization','A/B Testing Program Management','Acquisition Strategy & Execution','Retention Optimization','Product-led Growth Initiatives'],[makeSub('AI Experiment Designer','experiment-designer','FlaskConical',['Experiment Design','Hypothesis Formation','Sample Sizing','Variable Control','Statistical Planning','Success Criteria']),makeSub('AI Funnel Analyzer','funnel-analyzer','Filter',['Funnel Analysis','Drop-off Detection','Conversion Optimization','Stage Metrics','Bottleneck Identification','Improvement Recommendations']),makeSub('AI A/B Test Coordinator','ab-test-coordinator','GitCompare',['Test Coordination','Variant Management','Traffic Splitting','Statistical Significance','Result Analysis','Implementation Planning'])]),
  makeAgent(33,'AI VP Content','vp-content','VP Content','PenTool','VP','enterprise',['Content Strategy','Editorial Planning','Quality Assurance','Repurposing','Content Operations','Distribution Strategy'],['Content Strategy & Planning','Editorial Calendar Management','Content Quality Assurance','Content Repurposing Strategy','Content Operations Management','Distribution Strategy & Execution'],[makeSub('AI Editorial Calendar Planner','editorial-calendar-planner','Calendar',['Calendar Planning','Content Scheduling','Theme Development','Deadline Management','Resource Allocation','Publication Workflow']),makeSub('AI Content Quality Reviewer','content-quality-reviewer','CheckCircle2',['Quality Review','Style Guide Compliance','Grammar Checking','Readability Scoring','Brand Voice Validation','Improvement Suggestions']),makeSub('AI Repurposing Strategist','repurposing-strategist','Repeat',['Content Repurposing','Format Transformation','Channel Optimization','Lifecycle Extension','Audience Adaptation','Performance Prediction'])]),
  makeAgent(34,'AI VP Digital','vp-digital','VP Digital','Monitor','VP','enterprise',['Digital Optimization','Web Performance','Conversion Optimization','Digital Strategy','Technology Stack','Analytics Integration'],['Digital Channel Optimization','Web Performance Management','Conversion Rate Optimization','Digital Strategy Development','Technology Stack Management','Analytics Integration & Reporting'],[makeSub('AI Digital Channel Optimizer','digital-channel-optimizer','Zap',['Channel Optimization','Performance Tuning','Budget Reallocation','Audience Targeting','Cross-channel Synergy','Automation Rules']),makeSub('AI Web Performance Tracker','web-performance-tracker','Gauge',['Performance Tracking','Core Web Vitals','Load Time Monitoring','Error Detection','User Experience Metrics','Improvement Recommendations']),makeSub('AI Conversion Analyst','conversion-analyst','Target',['Conversion Analysis','Funnel Optimization','Landing Page Testing','User Behavior','Attribution Modeling','Revenue Impact'])]),
  makeAgent(35,'AI Marketing Manager','marketing-manager','Mktg Mgr','Users','Manager','enterprise',['Task Management','Deadline Tracking','Spend Monitoring','Team Coordination','Campaign Execution','Performance Reporting'],['Marketing Task Assignment & Management','Deadline Tracking & Enforcement','Marketing Spend Monitoring','Team Coordination & Communication','Campaign Execution Oversight','Performance Reporting & Analysis'],[makeSub('AI Task Assigner','task-assigner','ClipboardList',['Task Assignment','Workload Balancing','Skill Matching','Priority Setting','Progress Tracking','Completion Validation']),makeSub('AI Deadline Tracker','deadline-tracker','Clock',['Deadline Tracking','Milestone Management','Escalation Triggers','Reminder System','Dependency Mapping','Status Reporting']),makeSub('AI Marketing Spend Monitor','marketing-spend-monitor','DollarSign',['Spend Monitoring','Budget Tracking','Overspend Alerts','ROI Calculation','Channel Attribution','Forecast Adjustment'])]),
  makeAgent(36,'AI Content Marketing Agent','content-marketing','Content','FileText','Specialist','premium',['Blog Writing','Copy Editing','Content Distribution','SEO Content','Social Content','Email Content'],['Blog Content Creation & Management','Copy Editing & Quality Assurance','Content Distribution & Promotion','SEO Content Optimization','Social Media Content Creation','Email Content Development'],[makeSub('AI Blog Writer','blog-writer','PenTool',['Blog Writing','Topic Research','SEO Optimization','Audience Targeting','Content Structuring','Publication Ready']),makeSub('AI Copy Editor','copy-editor','CheckSquare',['Copy Editing','Grammar Correction','Style Consistency','Brand Voice','Fact Checking','Readability Optimization']),makeSub('AI Content Distributor','content-distributor','Share2',['Content Distribution','Channel Optimization','Timing Strategy','Audience Targeting','Performance Tracking','Repurposing'])]),
  makeAgent(37,'AI SEO Specialist','seo-specialist','SEO','Search','Specialist','premium',['Keyword Research','On-page Optimization','Backlink Analysis','Technical SEO','Content Strategy','Rank Tracking'],['Keyword Research & Strategy','On-page SEO Optimization','Backlink Profile Management','Technical SEO Auditing','SEO Content Strategy','Rank Tracking & Reporting'],[makeSub('AI Keyword Researcher','keyword-researcher','Search',['Keyword Discovery','Volume Analysis','Difficulty Scoring','Trend Identification','Gap Analysis','Opportunity Ranking']),makeSub('AI On-page Optimizer','on-page-optimizer','FileCode',['On-page Optimization','Meta Tag Management','Schema Markup','Internal Linking','Content Structure','Mobile Optimization']),makeSub('AI Backlink Analyzer','backlink-analyzer','Link',['Backlink Analysis','Quality Scoring','Anchor Text Review','Competitor Links','Opportunity Finding','Disavow Management'])]),
  makeAgent(38,'AI Social Media Manager','social-media-manager','Social','Share2','Specialist','premium',['Post Scheduling','Engagement Management','Trend Monitoring','Content Calendar','Analytics','Community Management'],['Social Media Post Scheduling','Engagement Response Management','Trend Monitoring & Reporting','Content Calendar Management','Social Analytics & Reporting','Community Management'],[makeSub('AI Post Scheduler','post-scheduler','Calendar',['Post Scheduling','Optimal Timing','Multi-platform','Queue Management','Content Calendar','Automation Rules']),makeSub('AI Engagement Responder','engagement-responder','MessageCircle',['Response Generation','Sentiment Detection','Priority Assessment','Escalation Logic','Brand Voice','Response Time Optimization']),makeSub('AI Trend Monitor','trend-monitor','TrendingUp',['Trend Detection','Hashtag Monitoring','Viral Identification','Competitor Tracking','Opportunity Alerting','Content Suggestion'])]),
  makeAgent(39,'AI Email Marketing Agent','email-marketing','Email','Mail','Specialist','premium',['List Segmentation','Template Design','Deliverability','A/B Testing','Automation','Analytics'],['Email List Segmentation & Management','Email Template Design & Testing','Deliverability Monitoring & Optimization','A/B Testing & Optimization','Email Automation & Workflows','Email Analytics & Reporting'],[makeSub('AI List Segmenter','list-segmenter','Users',['List Segmentation','Behavioral Segments','Demographic Split','Engagement Tiers','Dynamic Segments','Size Optimization']),makeSub('AI Template Designer','template-designer','Layout',['Template Design','Responsive Layout','Brand Compliance','Component Library','Personalization Tags','Preview Testing']),makeSub('AI Deliverability Monitor','deliverability-monitor','ShieldCheck',['Deliverability Monitoring','Spam Score Checking','Bounce Management','Authentication Setup','Reputation Tracking','Inbox Placement'])]),
  makeAgent(40,'AI Ad Campaign Manager','ad-campaign-manager','Ads','Target','Specialist','enterprise',['Bid Optimization','Creative Testing','Audience Targeting','Budget Management','Performance Tracking','Multi-platform'],['Ad Bid Optimization & Management','Creative Testing & Optimization','Audience Targeting & Segmentation','Budget Management & Allocation','Performance Tracking & Reporting','Multi-platform Campaign Management'],[makeSub('AI Bid Optimizer','bid-optimizer','DollarSign',['Bid Optimization','ROAS Targeting','Budget Pacing','Competition Analysis','Dayparting','Automated Rules']),makeSub('AI Creative Tester','creative-tester','Image',['Creative Testing','A/B Variants','Performance Comparison','Element Analysis','Winner Selection','Iteration Planning']),makeSub('AI Audience Targeter','audience-targeter','Crosshair',['Audience Targeting','Lookalike Building','Interest Stacking','Exclusion Logic','Custom Audiences','Segment Optimization'])]),
  makeAgent(41,'AI Marketing Analytics Agent','marketing-analytics','Analytics','BarChart3','Specialist','premium',['Attribution Modeling','KPI Dashboards','Insight Summarization','Data Visualization','Trend Analysis','Reporting'],['Marketing Attribution Modeling','KPI Dashboard Building & Management','Insight Summarization & Reporting','Data Visualization & Storytelling','Trend Analysis & Forecasting','Marketing Performance Reporting'],[makeSub('AI Attribution Modeler','attribution-modeler','GitMerge',['Attribution Modeling','Multi-touch Analysis','Channel Valuation','Conversion Path','Model Comparison','Budget Optimization']),makeSub('AI KPI Dashboard Builder','kpi-dashboard-builder','LayoutDashboard',['Dashboard Design','KPI Selection','Visualization Choice','Real-time Updates','Drill-down Capability','Sharing & Export']),makeSub('AI Insight Summarizer','insight-summarizer','FileText',['Insight Extraction','Pattern Recognition','Anomaly Detection','Priority Ranking','Action Recommendations','Executive Summaries'])]),
  makeAgent(42,'AI Brand Manager','brand-manager','Brand','Award','Specialist','premium',['Competitor Tracking','Brand Health','Messaging Alignment','Brand Strategy','Market Position','Brand Equity'],['Competitor Brand Tracking & Analysis','Brand Health Surveying & Monitoring','Messaging Alignment & Consistency','Brand Strategy Development','Market Position Management','Brand Equity Measurement'],[makeSub('AI Competitor Brand Tracker','competitor-brand-tracker','ScanSearch',['Competitor Tracking','Brand Comparison','Market Share','Campaign Monitoring','Positioning Analysis','Alert Generation']),makeSub('AI Brand Health Surveyor','brand-health-surveyor','Heart',['Brand Health Surveying','Awareness Tracking','Perception Mapping','Loyalty Measurement','NPS Correlation','Trend Analysis']),makeSub('AI Messaging Aligner','messaging-aligner','AlignCenter',['Message Alignment','Consistency Checking','Channel Adaptation','Audience Tailoring','Tone Calibration','Compliance Verification'])]),
  makeAgent(43,'AI Growth Hacker','growth-hacker','Growth','Rocket','Specialist','enterprise',['Viral Loops','Referral Programs','Acquisition Testing','Growth Experiments','Product Hacking','Rapid Iteration'],['Viral Loop Design & Implementation','Referral Program Building','Acquisition Channel Testing','Growth Experiment Execution','Product Hacking & Optimization','Rapid Iteration & Learning'],[makeSub('AI Viral Loop Designer','viral-loop-designer','Share2',['Viral Loop Design','K-factor Optimization','Incentive Structuring','Friction Reduction','Share Mechanics','Analytics Integration']),makeSub('AI Referral Program Builder','referral-program-builder','Gift',['Referral Program Design','Reward Structuring','Tracking Implementation','Fraud Prevention','Optimization Logic','Performance Analytics']),makeSub('AI Acquisition Channel Tester','acquisition-channel-tester','FlaskConical',['Channel Testing','Cost Analysis','Quality Assessment','Scale Potential','Experiment Design','Rapid Validation'])]),
];
