import { z } from "zod";
import { permissionProcedure } from '../../../create-context';
import { Permission } from '../../../../lib/rbac';
import { db as pgDb } from '../../../../db/connection';
import { platformConnections } from '../../../../db/drizzle-schema';
import { eq } from 'drizzle-orm';

export const getAllPlatformsProcedure = permissionProcedure(Permission.PLATFORM_READ)
  .input(z.object({}).optional())
  .query(async ({ ctx, input }) => {
  console.log('Fetching all platforms for org:', ctx.user.organizationId);

  // 1. Fetch real connections from DB
  let userConnections: any[] = [];
  try {
    userConnections = await pgDb
      .select()
      .from(platformConnections)
      .where(eq(platformConnections.organizationId, ctx.user.organizationId as string));
  } catch (e) {
    console.warn('[PLATFORMS] Failed to fetch DB connections, using static list only');
  }

  const staticPlatforms = [
    {
      id: '1',
      name: 'WhatsApp',
      service: 'whatsapp',
      isConnected: false,
      isEnabled: false,
      accountName: 'Not connected',
      avatar: '',
      messageCount: 0,
      lastSync: 'Never',
      category: 'messaging',
      description: 'End-to-end encrypted messaging with QR code linking',
      features: ['QR Code', 'On-device', 'E2E encrypted'],
      popularity: 98,
      isVerified: true,
      connectionType: 'qr-code',
      connectionMethod: 'on-device',
      status: 'active',
      monthlyMessages: 0,
      responseTime: 'N/A',
    },
    {
      id: '2',
      name: 'Signal',
      service: 'signal',
      isConnected: false,
      isEnabled: false,
      accountName: 'Not connected',
      avatar: '',
      messageCount: 0,
      lastSync: 'Never',
      category: 'messaging',
      description: 'Privacy-focused messaging with QR code pairing',
      features: ['QR Code', 'On-device', 'Privacy-first'],
      popularity: 85,
      isVerified: true,
      connectionType: 'qr-code',
      connectionMethod: 'on-device',
      status: 'active',
      monthlyMessages: 0,
      responseTime: 'N/A',
    },
    {
      id: '3',
      name: 'Instagram',
      service: 'instagram',
      isConnected: false,
      isEnabled: false,
      accountName: 'Not connected',
      avatar: '',
      messageCount: 0,
      lastSync: 'Never',
      category: 'social',
      description: 'Direct messages via cloud bridge with 2FA support',
      features: ['Username/Password', 'Cloud', '2FA'],
      popularity: 96,
      isVerified: true,
      connectionType: 'credentials',
      connectionMethod: 'cloud',
      status: 'active',
      monthlyMessages: 0,
      responseTime: 'N/A',
    },
    {
      id: '4',
      name: 'X (Twitter)',
      service: 'twitter',
      isConnected: false,
      isEnabled: false,
      accountName: 'Not connected',
      avatar: '',
      messageCount: 0,
      lastSync: 'Never',
      category: 'social',
      description: 'Direct messaging via cloud bridge',
      features: ['Username/Password', 'Cloud', '2FA'],
      popularity: 78,
      isVerified: true,
      connectionType: 'credentials',
      connectionMethod: 'cloud',
      status: 'active',
      monthlyMessages: 0,
      responseTime: 'N/A',
    },
    {
      id: '5',
      name: 'Gmail',
      service: 'email',
      isConnected: false,
      isEnabled: false,
      accountName: 'Not connected',
      avatar: '',
      messageCount: 0,
      lastSync: 'Never',
      category: 'email',
      description: 'Email via OAuth authentication',
      features: ['OAuth', 'Cloud', 'Smart compose'],
      popularity: 97,
      isVerified: true,
      connectionType: 'oauth',
      connectionMethod: 'cloud',
      status: 'active',
      monthlyMessages: 0,
      responseTime: 'N/A',
    },
    {
      id: '6',
      name: 'Slack',
      service: 'slack',
      isConnected: false,
      isEnabled: false,
      accountName: 'Not connected',
      avatar: '',
      messageCount: 0,
      lastSync: 'Never',
      category: 'business',
      description: 'Team collaboration via OAuth',
      features: ['OAuth', 'Cloud', 'Channels'],
      popularity: 91,
      isVerified: true,
      connectionType: 'oauth',
      connectionMethod: 'cloud',
      status: 'active',
      monthlyMessages: 0,
      responseTime: 'N/A',
    },
    {
      id: '7',
      name: 'Telegram',
      service: 'telegram',
      isConnected: false,
      isEnabled: false,
      accountName: 'Not connected',
      avatar: '',
      messageCount: 0,
      lastSync: 'Never',
      category: 'messaging',
      description: 'Fast, secure messaging with bot capabilities',
      features: ['QR Code', 'Cloud', 'Bots'],
      popularity: 92,
      isVerified: true,
      connectionType: 'qr-code',
      connectionMethod: 'cloud',
      status: 'active',
      monthlyMessages: 0,
      responseTime: 'N/A',
    },
    {
      id: '8',
      name: 'Discord',
      service: 'discord',
      isConnected: false,
      isEnabled: false,
      accountName: 'Not connected',
      avatar: '',
      messageCount: 0,
      lastSync: 'Never',
      category: 'business',
      description: 'Voice, video, and text communication',
      features: ['OAuth', 'Cloud', 'Voice channels'],
      popularity: 87,
      isVerified: true,
      connectionType: 'oauth',
      connectionMethod: 'cloud',
      status: 'active',
      monthlyMessages: 0,
      responseTime: 'N/A',
    },
    {
      id: '9',
      name: 'Microsoft Teams',
      service: 'teams',
      isConnected: false,
      isEnabled: false,
      accountName: 'Not connected',
      avatar: '',
      messageCount: 0,
      lastSync: 'Never',
      category: 'business',
      description: 'Enterprise collaboration and video conferencing',
      features: ['OAuth', 'Cloud', 'SSO'],
      popularity: 94,
      isVerified: true,
      connectionType: 'oauth',
      connectionMethod: 'cloud',
      status: 'active',
      monthlyMessages: 0,
      responseTime: 'N/A',
    },
    {
      id: '10',
      name: 'Twilio',
      service: 'voice',
      isConnected: false,
      isEnabled: false,
      accountName: 'Not connected',
      avatar: '',
      messageCount: 0,
      lastSync: 'Never',
      category: 'voice',
      description: 'Programmable voice and SMS for enterprise',
      features: ['API Key', 'Webhook', 'High-volume'],
      popularity: 99,
      isVerified: true,
      connectionType: 'credentials',
      connectionMethod: 'cloud',
      status: 'active',
      monthlyMessages: 0,
      responseTime: 'N/A',
    }
  ];

  // 2. Merge status
  const platforms = staticPlatforms.map(p => {
    const conn = userConnections.find(c => c.platform === p.service);
    if (conn) {
      return {
        ...p,
        isConnected: conn.isActive,
        isEnabled: conn.isActive,
        accountName: conn.metadata?.accountName || 'Active Connection',
        lastSync: conn.lastSyncAt ? new Date(conn.lastSyncAt).toLocaleString() : 'Just now',
      };
    }
    return p;
  });

  return { platforms };
});
