import React from 'react';
import { Calculator, FileText, PiggyBank, Search, ClipboardList, CreditCard, DollarSign } from 'lucide-react-native';
import { DepartmentAIPage, DeptSubAgent } from '@/components/DepartmentAIPage';

const subAgents: DeptSubAgent[] = [
  { id: 'af-1', name: 'AI Bookkeeper', description: 'Automated transaction recording, reconciliation, and ledger management', icon: FileText, enabled: true, status: 'active', tasksCompleted: 4520, successRate: 99, lastActive: '1 min ago', capabilities: ['Transaction Recording', 'Bank Reconciliation', 'Ledger Management', 'Journal Entries', 'Account Categorization', 'Error Detection'], tier: 'enterprise', learningProgress: 96, efficiency: 99, todayTasks: 234, avgResponseTime: '0.3s', trend: 'up', recentActions: ['Reconciled 150 transactions', 'Categorized 89 expenses', 'Generated trial balance'], healthScore: 99, weeklyGrowth: 8 },
  { id: 'af-2', name: 'AI Tax Analyst', description: 'Tax planning, compliance monitoring, and filing preparation', icon: Calculator, enabled: true, status: 'active', tasksCompleted: 1890, successRate: 97, lastActive: '5 min ago', capabilities: ['Tax Planning', 'Compliance Monitoring', 'Deduction Optimization', 'Filing Prep', 'Multi-jurisdiction', 'Audit Support'], tier: 'enterprise', learningProgress: 92, efficiency: 96, todayTasks: 45, avgResponseTime: '2.1s', trend: 'up', recentActions: ['Reviewed Q3 tax provisions', 'Identified tax savings opportunity', 'Updated compliance checklist'], healthScore: 97, weeklyGrowth: 12 },
  { id: 'af-3', name: 'AI Financial Planner', description: 'Budget forecasting, scenario modeling, and financial strategy', icon: PiggyBank, enabled: true, status: 'active', tasksCompleted: 1240, successRate: 94, lastActive: '8 min ago', capabilities: ['Budget Forecasting', 'Scenario Modeling', 'Cash Flow Planning', 'Investment Analysis', 'Risk Assessment', 'Financial Strategy'], tier: 'premium', learningProgress: 89, efficiency: 93, todayTasks: 34, avgResponseTime: '2.5s', trend: 'up', recentActions: ['Updated annual budget forecast', 'Modeled 3 growth scenarios', 'Analyzed investment returns'], healthScore: 94, weeklyGrowth: 15 },
  { id: 'af-4', name: 'AI Auditor', description: 'Internal audit, compliance checks, and risk assessment', icon: Search, enabled: true, status: 'training', tasksCompleted: 780, successRate: 96, lastActive: '15 min ago', capabilities: ['Internal Audit', 'Compliance Checks', 'Risk Assessment', 'Control Testing', 'Fraud Detection', 'Audit Reports'], tier: 'enterprise', learningProgress: 82, efficiency: 91, todayTasks: 18, avgResponseTime: '3.2s', trend: 'up', recentActions: ['Completed SOX compliance review', 'Tested internal controls', 'Flagged anomaly in expenses'], healthScore: 88, weeklyGrowth: 20 },
  { id: 'af-5', name: 'AI Expense Manager', description: 'Expense tracking, policy enforcement, and reimbursement automation', icon: CreditCard, enabled: true, status: 'active', tasksCompleted: 3450, successRate: 98, lastActive: '2 min ago', capabilities: ['Receipt Scanning', 'Policy Enforcement', 'Approval Workflows', 'Reimbursement', 'Budget Tracking', 'Spend Analytics'], tier: 'standard', learningProgress: 94, efficiency: 97, todayTasks: 156, avgResponseTime: '0.5s', trend: 'stable', recentActions: ['Processed 45 expense reports', 'Flagged 3 policy violations', 'Generated spend report'], healthScore: 98, weeklyGrowth: 5 },
  { id: 'af-6', name: 'AI Invoice Processor', description: 'Invoice capture, validation, matching, and payment scheduling', icon: ClipboardList, enabled: true, status: 'active', tasksCompleted: 5670, successRate: 97, lastActive: '3 min ago', capabilities: ['OCR Capture', 'PO Matching', 'Validation Rules', 'Payment Scheduling', 'Vendor Management', 'Dispute Resolution'], tier: 'premium', learningProgress: 93, efficiency: 98, todayTasks: 189, avgResponseTime: '0.8s', trend: 'up', recentActions: ['Processed 67 invoices', 'Matched 45 POs', 'Scheduled 12 payments'], healthScore: 97, weeklyGrowth: 10 },
  { id: 'af-7', name: 'AI Payroll Manager', description: 'Payroll processing, tax withholding, and benefits administration', icon: DollarSign, enabled: false, status: 'inactive', tasksCompleted: 890, successRate: 99, lastActive: '1 hour ago', capabilities: ['Payroll Processing', 'Tax Withholding', 'Benefits Admin', 'Time Tracking', 'Compliance', 'Reporting'], tier: 'enterprise', learningProgress: 88, efficiency: 99, todayTasks: 0, avgResponseTime: '-', trend: 'stable', recentActions: ['Paused - awaiting activation'], healthScore: 72, weeklyGrowth: 0 },
];

export default function AccountingFinanceAIScreen() {
  return <DepartmentAIPage config={{ title: 'Accounting & Finance AI', subtitle: 'Precision → Compliance → Growth', accentColor: '#10B981', gradientColors: ['#10B981', '#059669'], mainIcon: Calculator, mainAgentId: 'main-af', category: 'accounting-finance', statLabels: ['Transactions', 'Accuracy', 'Sub-Agents'], subAgents }} />;
}
