import React from 'react';
import { Scale, FileText, Shield, Search, BookOpen, CircleAlert } from 'lucide-react-native';
import { DepartmentAIPage, DeptSubAgent } from '@/components/DepartmentAIPage';

const subAgents: DeptSubAgent[] = [
  { id: 'lc-1', name: 'AI Contract Reviewer', description: 'Automated contract analysis, clause detection, and risk identification', icon: FileText, enabled: true, status: 'active', tasksCompleted: 2340, successRate: 96, lastActive: '3 min ago', capabilities: ['Clause Analysis', 'Risk Detection', 'Redline Suggestions', 'Template Generation', 'Version Comparison', 'Obligation Tracking'], tier: 'enterprise', learningProgress: 93, efficiency: 97, todayTasks: 45, avgResponseTime: '2.5s', trend: 'up', recentActions: ['Reviewed 8 vendor contracts', 'Flagged 3 risky clauses', 'Generated contract summary'], healthScore: 97, weeklyGrowth: 14 },
  { id: 'lc-2', name: 'AI Compliance Monitor', description: 'Regulatory compliance tracking, policy enforcement, and audit prep', icon: Shield, enabled: true, status: 'active', tasksCompleted: 3890, successRate: 99, lastActive: '1 min ago', capabilities: ['Regulatory Tracking', 'Policy Enforcement', 'Audit Prep', 'Gap Analysis', 'Risk Rating', 'Compliance Dashboards'], tier: 'enterprise', learningProgress: 96, efficiency: 99, todayTasks: 156, avgResponseTime: '0.5s', trend: 'up', recentActions: ['Updated GDPR compliance status', 'Monitored 23 regulatory changes', 'Prepared audit documentation'], healthScore: 99, weeklyGrowth: 8 },
  { id: 'lc-3', name: 'AI Risk Assessor', description: 'Enterprise risk identification, quantification, and mitigation planning', icon: CircleAlert, enabled: true, status: 'active', tasksCompleted: 1890, successRate: 94, lastActive: '8 min ago', capabilities: ['Risk Identification', 'Impact Analysis', 'Mitigation Plans', 'Risk Registers', 'Heat Maps', 'Scenario Planning'], tier: 'enterprise', learningProgress: 91, efficiency: 95, todayTasks: 34, avgResponseTime: '2.0s', trend: 'up', recentActions: ['Updated risk register', 'Assessed vendor risk scores', 'Created mitigation plans'], healthScore: 95, weeklyGrowth: 12 },
  { id: 'lc-4', name: 'AI Policy Analyst', description: 'Policy creation, review, distribution, and acknowledgment tracking', icon: BookOpen, enabled: true, status: 'active', tasksCompleted: 1120, successRate: 95, lastActive: '12 min ago', capabilities: ['Policy Drafting', 'Review Workflows', 'Distribution Management', 'Acknowledgment Tracking', 'Version Control', 'Impact Assessment'], tier: 'premium', learningProgress: 88, efficiency: 93, todayTasks: 23, avgResponseTime: '2.2s', trend: 'stable', recentActions: ['Drafted privacy policy update', 'Distributed 5 policy changes', 'Tracked acknowledgments'], healthScore: 93, weeklyGrowth: 10 },
  { id: 'lc-5', name: 'AI Legal Researcher', description: 'Legal research, case analysis, and precedent identification', icon: Search, enabled: true, status: 'training', tasksCompleted: 670, successRate: 92, lastActive: '20 min ago', capabilities: ['Case Research', 'Precedent Analysis', 'Statute Review', 'Legal Briefs', 'Citation Management', 'Litigation Support'], tier: 'premium', learningProgress: 80, efficiency: 89, todayTasks: 12, avgResponseTime: '4.0s', trend: 'up', recentActions: ['Researched 3 case precedents', 'Summarized statute changes', 'Prepared legal brief'], healthScore: 86, weeklyGrowth: 18 },
  { id: 'lc-6', name: 'AI Regulatory Agent', description: 'Regulatory filing, deadline tracking, and submission management', icon: Scale, enabled: false, status: 'inactive', tasksCompleted: 340, successRate: 98, lastActive: '1 hour ago', capabilities: ['Filing Management', 'Deadline Tracking', 'Submission Automation', 'Regulatory Calendar', 'Cross-jurisdiction', 'Change Alerts'], tier: 'enterprise', learningProgress: 76, efficiency: 95, todayTasks: 0, avgResponseTime: '-', trend: 'stable', recentActions: ['Paused - awaiting activation'], healthScore: 72, weeklyGrowth: 0 },
];

export default function LegalComplianceAIScreen() {
  return <DepartmentAIPage config={{ title: 'Legal & Compliance AI', subtitle: 'Risk → Compliance → Protection', accentColor: '#F59E0B', gradientColors: ['#F59E0B', '#D97706'], mainIcon: Scale, mainAgentId: 'main-lc', category: 'legal-compliance', statLabels: ['Reviews', 'Compliance', 'Sub-Agents'], subAgents }} />;
}
