import React from 'react';
import { Lightbulb, Settings, Search, Target, Layers, TestTube } from 'lucide-react-native';
import { DepartmentAIPage, DeptSubAgent } from '@/components/DepartmentAIPage';

const subAgents: DeptSubAgent[] = [
  { id: 'pr-1', name: 'AI Product Manager', description: 'Feature prioritization, roadmap planning, and user research synthesis', icon: Settings, enabled: true, status: 'active', tasksCompleted: 2340, successRate: 94, lastActive: '3 min ago', capabilities: ['Feature Prioritization', 'Roadmap Planning', 'User Research', 'Sprint Planning', 'Stakeholder Alignment', 'PRD Generation'], tier: 'enterprise', learningProgress: 92, efficiency: 95, todayTasks: 56, avgResponseTime: '1.8s', trend: 'up', recentActions: ['Prioritized Q4 features', 'Generated PRD for v3.0', 'Analyzed user feedback'], healthScore: 96, weeklyGrowth: 14 },
  { id: 'pr-2', name: 'AI UX Researcher', description: 'User behavior analysis, usability testing, and experience optimization', icon: Search, enabled: true, status: 'active', tasksCompleted: 1560, successRate: 91, lastActive: '8 min ago', capabilities: ['User Interviews', 'Usability Testing', 'Behavior Analytics', 'Persona Creation', 'Journey Mapping', 'A/B Testing'], tier: 'premium', learningProgress: 88, efficiency: 92, todayTasks: 34, avgResponseTime: '2.5s', trend: 'up', recentActions: ['Analyzed 500 session recordings', 'Created user personas', 'Mapped conversion funnel'], healthScore: 93, weeklyGrowth: 18 },
  { id: 'pr-3', name: 'AI Feature Analyst', description: 'Competitive feature analysis and market gap identification', icon: Target, enabled: true, status: 'active', tasksCompleted: 890, successRate: 93, lastActive: '12 min ago', capabilities: ['Feature Comparison', 'Gap Analysis', 'Market Research', 'Impact Assessment', 'ROI Prediction', 'Trend Analysis'], tier: 'premium', learningProgress: 86, efficiency: 91, todayTasks: 23, avgResponseTime: '3.0s', trend: 'stable', recentActions: ['Completed competitive feature matrix', 'Identified 3 market gaps', 'Updated feature impact scores'], healthScore: 91, weeklyGrowth: 10 },
  { id: 'pr-4', name: 'AI Roadmap Planner', description: 'Strategic roadmap management with dependency tracking', icon: Layers, enabled: true, status: 'active', tasksCompleted: 670, successRate: 95, lastActive: '5 min ago', capabilities: ['Roadmap Creation', 'Dependency Tracking', 'Release Planning', 'Risk Assessment', 'Resource Allocation', 'Timeline Optimization'], tier: 'enterprise', learningProgress: 90, efficiency: 94, todayTasks: 18, avgResponseTime: '2.2s', trend: 'up', recentActions: ['Updated product roadmap', 'Resolved dependency conflict', 'Planned Q1 releases'], healthScore: 95, weeklyGrowth: 12 },
  { id: 'pr-5', name: 'AI Prototype Builder', description: 'Rapid prototyping and design concept generation', icon: Lightbulb, enabled: true, status: 'training', tasksCompleted: 340, successRate: 88, lastActive: '20 min ago', capabilities: ['Wireframing', 'Mockup Generation', 'Interactive Prototypes', 'Design Systems', 'Component Library', 'Visual Testing'], tier: 'premium', learningProgress: 75, efficiency: 85, todayTasks: 8, avgResponseTime: '4.5s', trend: 'up', recentActions: ['Generated 5 wireframe concepts', 'Built interactive prototype', 'Updated design system'], healthScore: 82, weeklyGrowth: 25 },
  { id: 'pr-6', name: 'AI A/B Test Agent', description: 'Experiment design, statistical analysis, and optimization', icon: TestTube, enabled: false, status: 'inactive', tasksCompleted: 450, successRate: 96, lastActive: '1 hour ago', capabilities: ['Experiment Design', 'Statistical Analysis', 'Variant Creation', 'Significance Testing', 'Multi-variate Tests', 'Rollout Strategy'], tier: 'enterprise', learningProgress: 84, efficiency: 93, todayTasks: 0, avgResponseTime: '-', trend: 'stable', recentActions: ['Paused - awaiting activation'], healthScore: 70, weeklyGrowth: 0 },
];

export default function ProductRndAIScreen() {
  return <DepartmentAIPage config={{ title: 'Product & R&D AI', subtitle: 'Innovation → Research → Launch', accentColor: '#8B5CF6', gradientColors: ['#8B5CF6', '#7C3AED'], mainIcon: Lightbulb, mainAgentId: 'main-pr', category: 'product-rnd', statLabels: ['Features', 'Success', 'Sub-Agents'], subAgents }} />;
}
