import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { useTheme } from '@/providers/ThemeProvider';
import { Layers, Activity, Star, Users, CircleCheckBig, Clock, ArrowRight, Zap, Package, FileText, GitBranch, ArrowUpDown } from 'lucide-react-native';
import AgentFeatures from '@/components/ai-agent/AgentFeatures';
import { useRouter } from 'expo-router';
export default function AgentPage(){const{theme}=useTheme();const router=useRouter();const stats=[{label:'Specs',value:'3,450',icon:CircleCheckBig,color:'#34C759'},{label:'Uptime',value:'99.9%',icon:Activity,color:'#007AFF'},{label:'Response',value:'1.5s',icon:Clock,color:'#FF9500'},{label:'Accuracy',value:'97.9%',icon:Package,color:'#6A1B9A'}];const capabilities=['Feature Specification','User Story Mapping','Priority Adjustment','Requirement Analysis','Stakeholder Management','Sprint Coordination','Product Analytics','Market Alignment'];const responsibilities=['Write detailed feature specifications for engineering teams','Create and maintain user story maps for product epics','Adjust priorities based on market feedback and analytics','Analyze requirements and identify dependencies','Manage stakeholder expectations and communications','Coordinate sprint activities across product teams','Analyze product usage data to inform decisions','Ensure product alignment with market needs'];const activities=[{time:'2 min ago',text:'Completed feature spec for AI dashboard'},{time:'12 min ago',text:'Updated user story map for Q3 epic'},{time:'30 min ago',text:'Adjusted priority of 5 features based on feedback'},{time:'2 hours ago',text:'Analyzed product usage data for v2.4'}];const subAgents=[{name:'AI Feature Spec Writer',route:'/ai-agent/product/sub-agents/feature-spec-writer',desc:'Feature specification & documentation'},{name:'AI User Story Mapper',route:'/ai-agent/product/sub-agents/user-story-mapper',desc:'User story mapping & epic management'},{name:'AI Priority Adjuster',route:'/ai-agent/product/sub-agents/priority-adjuster',desc:'Priority adjustment & trade-off analysis'}];
return(<ScrollView style={[styles.container,{backgroundColor:theme.colors.background}]}><View style={[styles.hero,{borderBottomColor:theme.colors.border||'#E5E5EA'}]}><View style={[styles.heroIconWrap,{backgroundColor:'#6A1B9A20'}]}><Layers size={48} color="#6A1B9A"/></View><Text style={[styles.heroTitle,{color:theme.colors.text}]}>AI Product Manager (Sub)</Text><Text style={[styles.heroSubtitle,{color:theme.colors.textSecondary}]}>Product Management Department</Text><View style={styles.badgesRow}><View style={[styles.badge,{backgroundColor:'#34C75922'}]}><Activity size={12}color="#34C759"/><Text style={[styles.badgeText,{color:'#34C759'}]}>Active</Text></View><View style={[styles.badge,{backgroundColor:'#6A1B9A22'}]}><Star size={12}color="#6A1B9A"/><Text style={[styles.badgeText,{color:'#6A1B9A'}]}>Manager</Text></View><View style={[styles.badge,{backgroundColor:'#FF950022'}]}><Users size={12}color="#FF9500"/><Text style={[styles.badgeText,{color:'#FF9500'}]}>{subAgents.length} Sub-Agents</Text></View></View></View>
<View style={styles.statsContainer}>{stats.map((s,i)=>(<View key={i}style={[styles.statCard,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><s.icon size={22}color={s.color}/><Text style={[styles.statValue,{color:theme.colors.text}]}>{s.value}</Text><Text style={[styles.statLabel,{color:theme.colors.textSecondary}]}>{s.label}</Text></View>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Overview</Text><Text style={[styles.description,{color:theme.colors.textSecondary}]}>The AI Product Manager (Sub) specializes in feature specifications, user story mapping, and priority management. It oversees 3 specialized sub-agents for comprehensive product management support.</Text></View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Capabilities</Text><View style={styles.tagsContainer}>{capabilities.map((cap,i)=>(<View key={i}style={[styles.tag,{backgroundColor:'#6A1B9A18'}]}><Text style={[styles.tagText,{color:'#6A1B9A'}]}>{cap}</Text></View>))}</View></View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Key Responsibilities</Text>{responsibilities.map((r,i)=>(<View key={i}style={styles.responsibilityRow}><ArrowRight size={14}color="#6A1B9A"/><Text style={[styles.responsibilityText,{color:theme.colors.textSecondary}]}>{r}</Text></View>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>A2A Endpoints</Text>{['/consult/ai-product-manager-sub','/product-mgr-sub/execute','/product-mgr-sub/analyze','/product-mgr-sub/specs'].map((e,i)=>(<View key={i}style={styles.endpointRow}><Zap size={14}color="#6A1B9A"/><Text style={[styles.endpointText,{color:theme.colors.textSecondary}]}>{e}</Text></View>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Sub-Agents</Text>{subAgents.map((sub,i)=>(<TouchableOpacity key={i}onPress={()=>router.push(sub.route as any)}style={[styles.subAgentCard,{backgroundColor:theme.colors.background||'#F2F2F7',marginTop:i>0?8:0}]}><Package size={24}color="#6A1B9A"/><View style={styles.subAgentInfo}><Text style={[styles.subAgentName,{color:theme.colors.text}]}>{sub.name}</Text><Text style={[styles.subAgentDesc,{color:theme.colors.textSecondary}]}>{sub.desc}</Text></View><ArrowRight size={20}color={theme.colors.textSecondary}/></TouchableOpacity>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Recent Activity</Text>{activities.map((a,i)=>(<View key={i}style={styles.activityRow}><View style={[styles.activityIcon,{backgroundColor:'#6A1B9A15'}]}><Package size={14}color="#6A1B9A"/></View><View style={styles.activityContent}><Text style={[styles.activityText,{color:theme.colors.text}]}>{a.text}</Text><Text style={[styles.activityTime,{color:theme.colors.textSecondary}]}>{a.time}</Text></View></View>))}</View>
<AgentFeatures agentId="ai-product-manager-sub" agentName="AI Product Manager (Sub)"/><View style={{height:40}}/></ScrollView>);}
const styles=StyleSheet.create({container:{flex:1},hero:{alignItems:'center',paddingVertical:32,paddingHorizontal:20,borderBottomWidth:1},heroIconWrap:{width:88,height:88,borderRadius:44,justifyContent:'center',alignItems:'center',marginBottom:16},heroTitle:{fontSize:26,fontWeight:'bold'},heroSubtitle:{fontSize:15,marginTop:4,fontWeight:'500'},badgesRow:{flexDirection:'row',gap:10,marginTop:16},badge:{flexDirection:'row',alignItems:'center',paddingHorizontal:10,paddingVertical:5,borderRadius:20,gap:4},badgeText:{fontSize:12,fontWeight:'600'},statsContainer:{flexDirection:'row',flexWrap:'wrap',padding:16,gap:12},statCard:{flex:1,minWidth:'22%',alignItems:'center',padding:14,borderRadius:12},statValue:{fontSize:18,fontWeight:'bold',marginTop:8},statLabel:{fontSize:11,marginTop:4},section:{marginHorizontal:16,marginBottom:16,padding:20,borderRadius:16},sectionTitle:{fontSize:18,fontWeight:'700',marginBottom:14},description:{fontSize:14,lineHeight:22},tagsContainer:{flexDirection:'row',flexWrap:'wrap',gap:8},tag:{paddingHorizontal:12,paddingVertical:6,borderRadius:20},tagText:{fontSize:12,fontWeight:'600'},responsibilityRow:{flexDirection:'row',alignItems:'center',marginBottom:10,gap:8},responsibilityText:{fontSize:14,flex:1,lineHeight:20},endpointRow:{flexDirection:'row',alignItems:'center',marginBottom:8,gap:8},endpointText:{fontSize:13,fontFamily:'monospace'},subAgentCard:{flexDirection:'row',alignItems:'center',padding:16,borderRadius:12,gap:12},subAgentInfo:{flex:1},subAgentName:{fontSize:16,fontWeight:'600'},subAgentDesc:{fontSize:12,marginTop:2},activityRow:{flexDirection:'row',alignItems:'center',marginBottom:12,gap:12},activityIcon:{width:32,height:32,borderRadius:16,justifyContent:'center',alignItems:'center'},activityContent:{flex:1},activityText:{fontSize:14,fontWeight:'500'},activityTime:{fontSize:12,marginTop:2}});