import React from 'react';
import { View, StyleSheet, Text, ScrollView } from 'react-native';
import { useTheme } from '@/providers/ThemeProvider';

interface Insight {
  id: string;
  type: 'warning' | 'opportunity' | 'info' | 'success' | 'risk' | 'recommendation' | 'alert';
  title: string;
  description: string;
  impact: 'high' | 'medium' | 'low';
  actionable: boolean;
  confidence?: number;
}

interface ProductInsightsEngineProps {
  insights: Insight[];
}

export default function ProductInsightsEngine({ insights }: ProductInsightsEngineProps) {
  const { theme } = useTheme();

  const getInsightColor = (type: string) => {
    switch (type) {
      case 'warning': return '#F59E0B';
      case 'opportunity': return '#22C55E';
      case 'info': return '#3B82F6';
      case 'success': return '#10B981';
      case 'risk': return '#EF4444';
      case 'recommendation': return '#8B5CF6';
      case 'alert': return '#EC4899';
      default: return '#6B7280';
    }
  };

  const getInsightIcon = (type: string) => {
    switch (type) {
      case 'warning': return '⚠️';
      case 'opportunity': return '🚀';
      case 'info': return 'ℹ️';
      case 'success': return '✅';
      case 'risk': return '⚡';
      case 'recommendation': return '💡';
      case 'alert': return '🔔';
      default: return '📌';
    }
  };

  const getImpactColor = (impact: string) => {
    switch (impact) {
      case 'high': return '#EF4444';
      case 'medium': return '#F59E0B';
      case 'low': return '#22C55E';
      default: return '#6B7280';
    }
  };

  const groupedInsights = {
    high: insights.filter(i => i.impact === 'high'),
    medium: insights.filter(i => i.impact === 'medium'),
    low: insights.filter(i => i.impact === 'low'),
  };

  return (
    <View style={[styles.container, { backgroundColor: theme.colors.card }]}>
      <Text style={[styles.title, { color: theme.colors.text }]}>
        Product Insights Engine
      </Text>

      <ScrollView 
        style={styles.scrollContainer}
        showsVerticalScrollIndicator={false}
      >
        {/* AI Summary */}
        <View style={[styles.summaryCard, { backgroundColor: theme.colors.background }]}>
          <View style={styles.summaryHeader}>
            <Text style={styles.summaryIcon}>🧠</Text>
            <View style={styles.summaryContent}>
              <Text style={[styles.summaryTitle, { color: theme.colors.text }]}>
                AI Intelligence Summary
              </Text>
              <Text style={[styles.summarySubtitle, { color: theme.colors.textSecondary }]}>
                {insights.length} active insights generated by product agents
              </Text>
            </View>
          </View>
          <View style={styles.summaryMetrics}>
            <View style={styles.summaryMetric}>
              <Text style={[styles.metricCount, { color: '#EF4444' }]}>
                {groupedInsights.high.length}
              </Text>
              <Text style={[styles.metricLabel, { color: theme.colors.textSecondary }]}>
                High Impact
              </Text>
            </View>
            <View style={styles.summaryMetric}>
              <Text style={[styles.metricCount, { color: '#F59E0B' }]}>
                {groupedInsights.medium.length}
              </Text>
              <Text style={[styles.metricLabel, { color: theme.colors.textSecondary }]}>
                Medium Impact
              </Text>
            </View>
            <View style={styles.summaryMetric}>
              <Text style={[styles.metricCount, { color: '#22C55E' }]}>
                {groupedInsights.low.length}
              </Text>
              <Text style={[styles.metricLabel, { color: theme.colors.textSecondary }]}>
                Low Impact
              </Text>
            </View>
          </View>
        </View>

        {/* High Impact Insights */}
        {groupedInsights.high.length > 0 && (
          <View style={styles.insightSection}>
            <Text style={[styles.sectionTitle, { color: theme.colors.text }]}>
              High Impact Insights
            </Text>
            {groupedInsights.high.map((insight) => (
              <View 
                key={insight.id}
                style={[styles.insightCard, { 
                  backgroundColor: theme.colors.background,
                  borderColor: getInsightColor(insight.type),
                  borderLeftWidth: 4
                }]}
              >
                <View style={styles.insightHeader}>
                  <View style={styles.insightMeta}>
                    <Text style={styles.insightIcon}>{getInsightIcon(insight.type)}</Text>
                    <Text style={[styles.insightType, { color: getInsightColor(insight.type) }]}>
                      {insight.type}
                    </Text>
                  </View>
                  <View style={[styles.impactBadge, { backgroundColor: `${getImpactColor(insight.impact)}20` }]}>
                    <Text style={[styles.impactText, { color: getImpactColor(insight.impact) }]}>
                      {insight.impact} impact
                    </Text>
                  </View>
                </View>

                <Text style={[styles.insightTitle, { color: theme.colors.text }]}>
                  {insight.title}
                </Text>
                <Text style={[styles.insightDescription, { color: theme.colors.textSecondary }]}>
                  {insight.description}
                </Text>

                <View style={styles.insightFooter}>
                  {insight.confidence && (
                    <View style={styles.confidenceItem}>
                      <Text style={[styles.confidenceLabel, { color: theme.colors.textSecondary }]}>
                        AI Confidence
                      </Text>
                      <View style={styles.confidenceBar}>
                        <View 
                          style={[
                            styles.confidenceFill, 
                            { 
                              width: `${insight.confidence}%`,
                              backgroundColor: insight.confidence > 80 ? '#22C55E' : insight.confidence > 60 ? '#F59E0B' : '#EF4444'
                            }
                          ]} 
                        />
                      </View>
                      <Text style={[styles.confidenceValue, { color: theme.colors.text }]}>
                        {insight.confidence}%
                      </Text>
                    </View>
                  )}
                  {insight.actionable && (
                    <View style={styles.actionableBadge}>
                      <Text style={[styles.actionableText, { color: '#22C55E' }]}>
                        ✓ Actionable
                      </Text>
                    </View>
                  )}
                </View>
              </View>
            ))}
          </View>
        )}

        {/* Medium Impact Insights */}
        {groupedInsights.medium.length > 0 && (
          <View style={styles.insightSection}>
            <Text style={[styles.sectionTitle, { color: theme.colors.text }]}>
              Medium Impact Insights
            </Text>
            {groupedInsights.medium.map((insight) => (
              <View 
                key={insight.id}
                style={[styles.insightCard, { 
                  backgroundColor: theme.colors.background,
                  borderColor: theme.colors.border,
                  borderLeftWidth: 2,
                  borderLeftColor: getInsightColor(insight.type)
                }]}
              >
                <View style={styles.insightHeader}>
                  <View style={styles.insightMeta}>
                    <Text style={styles.insightIcon}>{getInsightIcon(insight.type)}</Text>
                    <Text style={[styles.insightType, { color: getInsightColor(insight.type) }]}>
                      {insight.type}
                    </Text>
                  </View>
                  <View style={[styles.impactBadge, { backgroundColor: `${getImpactColor(insight.impact)}20` }]}>
                    <Text style={[styles.impactText, { color: getImpactColor(insight.impact) }]}>
                      {insight.impact} impact
                    </Text>
                  </View>
                </View>

                <Text style={[styles.insightTitle, { color: theme.colors.text }]}>
                  {insight.title}
                </Text>
                <Text style={[styles.insightDescription, { color: theme.colors.textSecondary }]}>
                  {insight.description}
                </Text>
              </View>
            ))}
          </View>
        )}

        {/* Low Impact Insights */}
        {groupedInsights.low.length > 0 && (
          <View style={styles.insightSection}>
            <Text style={[styles.sectionTitle, { color: theme.colors.text }]}>
              Low Impact Insights
            </Text>
            {groupedInsights.low.map((insight) => (
              <View 
                key={insight.id}
                style={[styles.insightCard, { 
                  backgroundColor: theme.colors.background,
                  borderColor: theme.colors.border,
                  opacity: 0.8
                }]}
              >
                <View style={styles.insightHeader}>
                  <View style={styles.insightMeta}>
                    <Text style={styles.insightIcon}>{getInsightIcon(insight.type)}</Text>
                    <Text style={[styles.insightType, { color: getInsightColor(insight.type) }]}>
                      {insight.type}
                    </Text>
                  </View>
                </View>

                <Text style={[styles.insightTitle, { color: theme.colors.text }]}>
                  {insight.title}
                </Text>
                <Text style={[styles.insightDescription, { color: theme.colors.textSecondary }]}>
                  {insight.description}
                </Text>
              </View>
            ))}
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 16,
  },
  scrollContainer: {
    maxHeight: 700,
  },
  summaryCard: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  summaryIcon: {
    fontSize: 32,
    marginRight: 12,
  },
  summaryContent: {
    flex: 1,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  summarySubtitle: {
    fontSize: 12,
  },
  summaryMetrics: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  summaryMetric: {
    alignItems: 'center',
  },
  metricCount: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 4,
  },
  metricLabel: {
    fontSize: 11,
  },
  insightSection: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
  },
  insightCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  insightHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  insightMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  insightIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  insightType: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  impactBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  impactText: {
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  insightTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 6,
  },
  insightDescription: {
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 12,
  },
  insightFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  confidenceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  confidenceLabel: {
    fontSize: 10,
    marginRight: 8,
  },
  confidenceBar: {
    width: 60,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 2,
    marginRight: 8,
  },
  confidenceFill: {
    height: '100%',
    borderRadius: 2,
  },
  confidenceValue: {
    fontSize: 11,
    fontWeight: '600',
  },
  actionableBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: 'rgba(34, 197, 94, 0.1)',
    borderRadius: 6,
  },
  actionableText: {
    fontSize: 10,
    fontWeight: '600',
  },
});
