import React from 'react';
import DepartmentDashboardView from '@/components/ai-agent/dashboard/DepartmentDashboardView';

const agents = [
  { id: 'ai-chief-risk-officer', uid: 'ktx-16-chief-risk-officer', title: 'AI Chief Risk Officer', route: '/ai-agent/insurance/chief-risk-officer', color: '#FF7043', level: 'c_level', efficiency: '82%' },
  { id: 'ai-vp-underwriting', uid: 'ktx-16-vp-underwriting', title: 'AI VP Underwriting', route: '/ai-agent/insurance/vp-underwriting', color: '#FF7043', level: 'vp_director', efficiency: '81%' },
  { id: 'ai-vp-claims', uid: 'ktx-16-vp-claims', title: 'AI VP Claims', route: '/ai-agent/insurance/vp-claims', color: '#FF7043', level: 'vp_director', efficiency: '79%' },
  { id: 'ai-vp-risk-assessment', uid: 'ktx-16-vp-risk-assessment', title: 'AI VP Risk Assessment', route: '/ai-agent/insurance/vp-risk-assessment', color: '#FF7043', level: 'vp_director', efficiency: '82%' },
  { id: 'ai-vp-actuarial', uid: 'ktx-16-vp-actuarial', title: 'AI VP Actuarial', route: '/ai-agent/insurance/vp-actuarial', color: '#FF7043', level: 'vp_director', efficiency: '84%' },
  { id: 'ai-vp-reinsurance', uid: 'ktx-16-vp-reinsurance', title: 'AI VP Reinsurance', route: '/ai-agent/insurance/vp-reinsurance', color: '#FF7043', level: 'vp_director', efficiency: '83%' },
  { id: 'ai-vp-compliance-insurance', uid: 'ktx-16-vp-compliance-insurance', title: 'AI VP Compliance (Insurance)', route: '/ai-agent/insurance/vp-compliance-insurance', color: '#FF7043', level: 'vp_director', efficiency: '85%' },
  { id: 'ai-vp-insurance-operations', uid: 'ktx-16-vp-insurance-operations', title: 'AI VP Insurance Operations', route: '/ai-agent/insurance/vp-insurance-operations', color: '#FF7043', level: 'vp_director', efficiency: '82%' },
  { id: 'ai-underwriting-manager', uid: 'ktx-16-underwriting-manager', title: 'AI Underwriting Manager', route: '/ai-agent/insurance/underwriting-manager', color: '#FF7043', level: 'manager', efficiency: '76%' },
  { id: 'ai-claims-manager', uid: 'ktx-16-claims-manager', title: 'AI Claims Manager', route: '/ai-agent/insurance/claims-manager', color: '#FF7043', level: 'manager', efficiency: '94%' },
  { id: 'ai-policy-manager', uid: 'ktx-16-policy-manager', title: 'AI Policy Manager', route: '/ai-agent/insurance/policy-manager', color: '#FF7043', level: 'manager', efficiency: '94%' },
  { id: 'ai-actuarial-manager', uid: 'ktx-16-actuarial-manager', title: 'AI Actuarial Manager', route: '/ai-agent/insurance/actuarial-manager', color: '#FF7043', level: 'manager', efficiency: '87%' },
  { id: 'ai-risk-management-manager', uid: 'ktx-16-risk-management-manager', title: 'AI Risk Management Manager', route: '/ai-agent/insurance/risk-management-manager', color: '#FF7043', level: 'manager', efficiency: '85%' },
  { id: 'ai-underwriter', uid: 'ktx-16-underwriter', title: 'AI Underwriter', route: '/ai-agent/insurance/underwriter', color: '#FF7043', level: 'team_lead', efficiency: '93%' },
  { id: 'ai-senior-underwriter', uid: 'ktx-16-senior-underwriter', title: 'AI Senior Underwriter', route: '/ai-agent/insurance/senior-underwriter', color: '#FF7043', level: 'team_lead', efficiency: '91%' },
  { id: 'ai-life-underwriter', uid: 'ktx-16-life-underwriter', title: 'AI Life Underwriter', route: '/ai-agent/insurance/life-underwriter', color: '#FF7043', level: 'team_lead', efficiency: '88%' },
  { id: 'ai-property-underwriter', uid: 'ktx-16-property-underwriter', title: 'AI Property Underwriter', route: '/ai-agent/insurance/property-underwriter', color: '#FF7043', level: 'team_lead', efficiency: '89%' },
  { id: 'ai-casualty-underwriter', uid: 'ktx-16-casualty-underwriter', title: 'AI Casualty Underwriter', route: '/ai-agent/insurance/casualty-underwriter', color: '#FF7043', level: 'team_lead', efficiency: '87%' },
  { id: 'ai-health-underwriter', uid: 'ktx-16-health-underwriter', title: 'AI Health Underwriter', route: '/ai-agent/insurance/health-underwriter', color: '#FF7043', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-auto-underwriter', uid: 'ktx-16-auto-underwriter', title: 'AI Auto Underwriter', route: '/ai-agent/insurance/auto-underwriter', color: '#FF7043', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-claims-adjuster', uid: 'ktx-16-claims-adjuster', title: 'AI Claims Adjuster', route: '/ai-agent/insurance/claims-adjuster', color: '#FF7043', level: 'team_lead', efficiency: '81%' },
  { id: 'ai-senior-claims-adjuster', uid: 'ktx-16-senior-claims-adjuster', title: 'AI Senior Claims Adjuster', route: '/ai-agent/insurance/senior-claims-adjuster', color: '#FF7043', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-field-adjuster', uid: 'ktx-16-field-adjuster', title: 'AI Field Adjuster', route: '/ai-agent/insurance/field-adjuster', color: '#FF7043', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-desk-adjuster', uid: 'ktx-16-desk-adjuster', title: 'AI Desk Adjuster', route: '/ai-agent/insurance/desk-adjuster', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-catastrophe-adjuster', uid: 'ktx-16-catastrophe-adjuster', title: 'AI Catastrophe Adjuster', route: '/ai-agent/insurance/catastrophe-adjuster', color: '#FF7043', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-fraud-detection-agent', uid: 'ktx-16-fraud-detection-agent', title: 'AI Fraud Detection Agent', route: '/ai-agent/insurance/fraud-detection-agent', color: '#FF7043', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-siu-investigator', uid: 'ktx-16-siu-investigator', title: 'AI SIU Investigator', route: '/ai-agent/insurance/siu-investigator', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-claims-analyst', uid: 'ktx-16-claims-analyst', title: 'AI Claims Analyst', route: '/ai-agent/insurance/claims-analyst', color: '#FF7043', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-actuary-analyst', uid: 'ktx-16-actuary-analyst', title: 'AI Actuary Analyst', route: '/ai-agent/insurance/actuary-analyst', color: '#FF7043', level: 'team_lead', efficiency: '81%' },
  { id: 'ai-actuary', uid: 'ktx-16-actuary', title: 'AI Actuary', route: '/ai-agent/insurance/actuary', color: '#FF7043', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-pricing-actuary', uid: 'ktx-16-pricing-actuary', title: 'AI Pricing Actuary', route: '/ai-agent/insurance/pricing-actuary', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-reserving-actuary', uid: 'ktx-16-reserving-actuary', title: 'AI Reserving Actuary', route: '/ai-agent/insurance/reserving-actuary', color: '#FF7043', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-valuation-actuary', uid: 'ktx-16-valuation-actuary', title: 'AI Valuation Actuary', route: '/ai-agent/insurance/valuation-actuary', color: '#FF7043', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-risk-modeler', uid: 'ktx-16-risk-modeler', title: 'AI Risk Modeler', route: '/ai-agent/insurance/risk-modeler', color: '#FF7043', level: 'team_lead', efficiency: '80%' },
  { id: 'ai-quantitative-analyst-insurance', uid: 'ktx-16-quantitative-analyst-insurance', title: 'AI Quantitative Analyst (Insurance)', route: '/ai-agent/insurance/quantitative-analyst-insurance', color: '#FF7043', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-data-scientist-insurance', uid: 'ktx-16-data-scientist-insurance', title: 'AI Data Scientist (Insurance)', route: '/ai-agent/insurance/data-scientist-insurance', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-policy-administrator', uid: 'ktx-16-policy-administrator', title: 'AI Policy Administrator', route: '/ai-agent/insurance/policy-administrator', color: '#FF7043', level: 'team_lead', efficiency: '76%' },
  { id: 'ai-policy-processor', uid: 'ktx-16-policy-processor', title: 'AI Policy Processor', route: '/ai-agent/insurance/policy-processor', color: '#FF7043', level: 'team_lead', efficiency: '78%' },
  { id: 'ai-billing-specialist-insurance', uid: 'ktx-16-billing-specialist-insurance', title: 'AI Billing Specialist (Insurance)', route: '/ai-agent/insurance/billing-specialist-insurance', color: '#FF7043', level: 'team_lead', efficiency: '79%' },
  { id: 'ai-collections-specialist-insurance', uid: 'ktx-16-collections-specialist-insurance', title: 'AI Collections Specialist (Insurance)', route: '/ai-agent/insurance/collections-specialist-insurance', color: '#FF7043', level: 'team_lead', efficiency: '77%' },
  { id: 'ai-customer-risk-analyst', uid: 'ktx-16-customer-risk-analyst', title: 'AI Customer Risk Analyst', route: '/ai-agent/insurance/customer-risk-analyst', color: '#FF7043', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-catastrophe-modeler', uid: 'ktx-16-catastrophe-modeler', title: 'AI Catastrophe Modeler', route: '/ai-agent/insurance/catastrophe-modeler', color: '#FF7043', level: 'team_lead', efficiency: '89%' },
  { id: 'ai-disaster-recovery-specialist', uid: 'ktx-16-disaster-recovery-specialist', title: 'AI Disaster Recovery Specialist', route: '/ai-agent/insurance/disaster-recovery-specialist', color: '#FF7043', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-emergency-response-coordinator', uid: 'ktx-16-emergency-response-coordinator', title: 'AI Emergency Response Coordinator', route: '/ai-agent/insurance/emergency-response-coordinator', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-reinsurance-specialist', uid: 'ktx-16-reinsurance-specialist', title: 'AI Reinsurance Specialist', route: '/ai-agent/insurance/reinsurance-specialist', color: '#FF7043', level: 'team_lead', efficiency: '90%' },
  { id: 'ai-reinsurance-underwriter', uid: 'ktx-16-reinsurance-underwriter', title: 'AI Reinsurance Underwriter', route: '/ai-agent/insurance/reinsurance-underwriter', color: '#FF7043', level: 'team_lead', efficiency: '88%' },
  { id: 'ai-reinsurance-broker', uid: 'ktx-16-reinsurance-broker', title: 'AI Reinsurance Broker', route: '/ai-agent/insurance/reinsurance-broker', color: '#FF7043', level: 'team_lead', efficiency: '87%' },
  { id: 'ai-cedent-relationship-manager', uid: 'ktx-16-cedent-relationship-manager', title: 'AI Cedent Relationship Manager', route: '/ai-agent/insurance/cedent-relationship-manager', color: '#FF7043', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-compliance-specialist-insurance', uid: 'ktx-16-compliance-specialist-insurance', title: 'AI Compliance Specialist (Insurance)', route: '/ai-agent/insurance/compliance-specialist-insurance', color: '#FF7043', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-regulatory-affairs-insurance', uid: 'ktx-16-regulatory-affairs-insurance', title: 'AI Regulatory Affairs (Insurance)', route: '/ai-agent/insurance/regulatory-affairs-insurance', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-licensing-specialist-insurance', uid: 'ktx-16-licensing-specialist-insurance', title: 'AI Licensing Specialist (Insurance)', route: '/ai-agent/insurance/licensing-specialist-insurance', color: '#FF7043', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-audit-specialist-insurance', uid: 'ktx-16-audit-specialist-insurance', title: 'AI Audit Specialist (Insurance)', route: '/ai-agent/insurance/audit-specialist-insurance', color: '#FF7043', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-claims-operations-manager', uid: 'ktx-16-claims-operations-manager', title: 'AI Claims Operations Manager', route: '/ai-agent/insurance/claims-operations-manager', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-first-notice-of-loss-specialist', uid: 'ktx-16-first-notice-of-loss-specialist', title: 'AI First Notice of Loss Specialist', route: '/ai-agent/insurance/first-notice-of-loss-specialist', color: '#FF7043', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-claims-service-representative', uid: 'ktx-16-claims-service-representative', title: 'AI Claims Service Representative', route: '/ai-agent/insurance/claims-service-representative', color: '#FF7043', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-legal-counsel-insurance', uid: 'ktx-16-legal-counsel-insurance', title: 'AI Legal Counsel (Insurance)', route: '/ai-agent/insurance/legal-counsel-insurance', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-settlement-specialist', uid: 'ktx-16-settlement-specialist', title: 'AI Settlement Specialist', route: '/ai-agent/insurance/settlement-specialist', color: '#FF7043', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-subrogation-specialist', uid: 'ktx-16-subrogation-specialist', title: 'AI Subrogation Specialist', route: '/ai-agent/insurance/subrogation-specialist', color: '#FF7043', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-medical-reviewer', uid: 'ktx-16-medical-reviewer', title: 'AI Medical Reviewer', route: '/ai-agent/insurance/medical-reviewer', color: '#FF7043', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-nurse-case-manager', uid: 'ktx-16-nurse-case-manager', title: 'AI Nurse Case Manager', route: '/ai-agent/insurance/nurse-case-manager', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-rehabilitation-specialist', uid: 'ktx-16-rehabilitation-specialist', title: 'AI Rehabilitation Specialist', route: '/ai-agent/insurance/rehabilitation-specialist', color: '#FF7043', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-disability-specialist', uid: 'ktx-16-disability-specialist', title: 'AI Disability Specialist', route: '/ai-agent/insurance/disability-specialist', color: '#FF7043', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-workers-comp-specialist', uid: 'ktx-16-workers-comp-specialist', title: 'AI Workers Comp Specialist', route: '/ai-agent/insurance/workers-comp-specialist', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-benefits-administrator', uid: 'ktx-16-benefits-administrator', title: 'AI Benefits Administrator', route: '/ai-agent/insurance/benefits-administrator', color: '#FF7043', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-customer-service-insurance', uid: 'ktx-16-customer-service-insurance', title: 'AI Customer Service (Insurance)', route: '/ai-agent/insurance/customer-service-insurance', color: '#FF7043', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-sales-support-insurance', uid: 'ktx-16-sales-support-insurance', title: 'AI Sales Support (Insurance)', route: '/ai-agent/insurance/sales-support-insurance', color: '#FF7043', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-agent-support', uid: 'ktx-16-agent-support', title: 'AI Agent Support', route: '/ai-agent/insurance/agent-support', color: '#FF7043', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-broker-support', uid: 'ktx-16-broker-support', title: 'AI Broker Support', route: '/ai-agent/insurance/broker-support', color: '#FF7043', level: 'team_lead', efficiency: '83%' },
];

export default function DepartmentIndex() {
  return (
    <DepartmentDashboardView
      departmentId="insurance-risk"
      agents={agents}
    />
  );
}
