import type {
  NegotiationCall,
  CallLog,
  PhoneNumber,
  CallTranscript,
  CallerInsight,
  NegotiationAppointment,
  CallScript,
  NegotiationContact,
  Deal,
  NegotiationTemplate,
  Integration,
  NegotiationNotification,
} from '@/types/negotiation';

export const mockNegotiationCalls: NegotiationCall[] = [
  {
    id: '1',
    customerName: 'John Anderson',
    customerCompany: 'TechCorp Solutions',
    customerPhone: '+1 (555) 123-4567',
    status: 'active',
    startTime: '2024-01-15T10:30:00',
    dealValue: 75000,
    priority: 'high',
    assignedTo: 'Sarah Miller',
    tags: ['enterprise', 'urgent'],
  },
  {
    id: '2',
    customerName: 'Emily Davis',
    customerCompany: 'Global Innovations',
    customerPhone: '+1 (555) 234-5678',
    status: 'completed',
    startTime: '2024-01-15T09:00:00',
    duration: '24:15',
    dealValue: 125000,
    discountOffered: 10,
    outcome: 'won',
    priority: 'high',
    assignedTo: 'Mike Johnson',
    tags: ['enterprise', 'closed'],
  },
  {
    id: '3',
    customerName: 'Robert Chen',
    customerCompany: 'Startup Hub',
    customerPhone: '+1 (555) 345-6789',
    status: 'scheduled',
    startTime: '2024-01-16T14:00:00',
    dealValue: 35000,
    priority: 'medium',
    assignedTo: 'Sarah Miller',
    tags: ['startup', 'follow-up'],
  },
  {
    id: '4',
    customerName: 'Lisa Brown',
    customerCompany: 'Enterprise Systems',
    customerPhone: '+1 (555) 456-7890',
    status: 'completed',
    startTime: '2024-01-14T15:30:00',
    duration: '45:20',
    dealValue: 180000,
    discountOffered: 15,
    outcome: 'lost',
    priority: 'high',
    assignedTo: 'Mike Johnson',
    notes: 'Customer chose competitor',
    tags: ['enterprise', 'lost'],
  },
];

export const mockCallLogs: CallLog[] = [
  {
    id: '1',
    callId: 'call-001',
    customerName: 'John Anderson',
    customerPhone: '+1 (555) 123-4567',
    callType: 'incoming',
    duration: '18:45',
    timestamp: '2024-01-15T10:30:00',
    status: 'answered',
    summary: 'Discussed enterprise plan pricing. Customer interested in 20% discount. Scheduled follow-up.',
    dealValue: 75000,
    outcome: 'ongoing',
  },
  {
    id: '2',
    callId: 'call-002',
    customerName: 'Emily Davis',
    customerPhone: '+1 (555) 234-5678',
    callType: 'outgoing',
    duration: '24:15',
    timestamp: '2024-01-15T09:00:00',
    status: 'answered',
    summary: 'Successfully closed deal with 10% discount. Customer happy with terms.',
    dealValue: 125000,
    outcome: 'won',
  },
  {
    id: '3',
    callId: 'call-003',
    customerName: 'Michael Wilson',
    customerPhone: '+1 (555) 567-8901',
    callType: 'incoming',
    duration: '0:00',
    timestamp: '2024-01-15T08:15:00',
    status: 'missed',
  },
  {
    id: '4',
    callId: 'call-004',
    customerName: 'Lisa Brown',
    customerPhone: '+1 (555) 456-7890',
    callType: 'outgoing',
    duration: '45:20',
    timestamp: '2024-01-14T15:30:00',
    status: 'answered',
    summary: 'Customer declined offer despite 15% discount. Chose competitor.',
    dealValue: 180000,
    outcome: 'lost',
  },
];

export const mockPhoneNumbers: PhoneNumber[] = [
  {
    id: '1',
    number: '+1 (800) 555-0001',
    label: 'Main Sales Line',
    type: 'toll-free',
    isActive: true,
    callsHandled: 1247,
    successRate: 68,
    assignedAgents: ['Sarah Miller', 'Mike Johnson'],
  },
  {
    id: '2',
    number: '+1 (555) 100-2000',
    label: 'Enterprise Deals',
    type: 'local',
    isActive: true,
    callsHandled: 456,
    successRate: 82,
    assignedAgents: ['Mike Johnson'],
  },
  {
    id: '3',
    number: '+44 20 7946 0958',
    label: 'UK Sales',
    type: 'international',
    isActive: true,
    callsHandled: 234,
    successRate: 71,
    assignedAgents: ['Sarah Miller'],
  },
];

export const mockCallTranscripts: CallTranscript[] = [
  {
    id: '1',
    callId: 'call-001',
    customerName: 'John Anderson',
    timestamp: '2024-01-15T10:30:00',
    duration: '18:45',
    transcript: 'Agent: Good morning, this is Sarah from our sales team. How can I help you today?\nCustomer: Hi Sarah, I\'m interested in your enterprise plan but the pricing seems high.\nAgent: I understand your concern. What specific features are you most interested in?\nCustomer: We need the advanced analytics and API access for our team of 50 users.\nAgent: Perfect! For 50 users with those features, I can offer you a competitive package. What\'s your budget range?\nCustomer: We were hoping to stay around $60,000 annually.\nAgent: I appreciate your transparency. Our standard pricing is $75,000, but I can discuss a 20% discount if you commit to a 2-year contract. That would bring it to $60,000.\nCustomer: That sounds interesting. Can I have some time to discuss with my team?\nAgent: Absolutely! I\'ll send you a detailed proposal. When would be a good time for a follow-up call?',
    summary: 'Customer interested in enterprise plan. Negotiating 20% discount for 2-year commitment. Follow-up scheduled.',
    sentiment: 'positive',
    keyPoints: [
      'Budget constraint: $60,000',
      'Team size: 50 users',
      'Interested in: Advanced analytics and API',
      'Willing to consider 2-year contract',
    ],
    actionItems: [
      'Send detailed proposal',
      'Schedule follow-up call',
      'Prepare contract for 2-year commitment',
    ],
  },
  {
    id: '2',
    callId: 'call-002',
    customerName: 'Emily Davis',
    timestamp: '2024-01-15T09:00:00',
    duration: '24:15',
    transcript: 'Agent: Hi Emily, thanks for taking my call. I wanted to follow up on the proposal I sent last week.\nCustomer: Yes, we\'ve reviewed it thoroughly. The team is impressed with the features.\nAgent: That\'s great to hear! Do you have any questions or concerns?\nCustomer: The pricing is at the top of our budget. Is there any flexibility?\nAgent: I understand. Given your company\'s size and potential for growth, I can offer a 10% discount if you sign this quarter.\nCustomer: That would work for us. When can we get started?\nAgent: I can have the contracts ready by end of day. You could start onboarding next week.\nCustomer: Perfect. Let\'s do it.\nAgent: Excellent! I\'ll send over the paperwork right away.',
    summary: 'Deal closed successfully with 10% discount. Customer satisfied and ready to proceed.',
    sentiment: 'positive',
    keyPoints: [
      'Team impressed with features',
      'Pricing at top of budget',
      'Accepted 10% discount',
      'Ready to sign immediately',
    ],
    actionItems: [
      'Send contracts immediately',
      'Schedule onboarding for next week',
      'Assign customer success manager',
    ],
  },
];

export const mockCallerInsights: CallerInsight[] = [
  {
    id: '1',
    customerName: 'John Anderson',
    customerCompany: 'TechCorp Solutions',
    totalCalls: 5,
    totalDeals: 2,
    avgDealValue: 65000,
    avgDiscount: 12,
    winRate: 40,
    lastContact: '2024-01-15T10:30:00',
    preferredTime: 'Morning (9-11 AM)',
    behaviorPattern: 'Decision-maker, budget-conscious, prefers detailed proposals',
    sentiment: 'positive',
    demographics: {
      industry: 'Technology',
      companySize: '50-100 employees',
      location: 'San Francisco, CA',
    },
  },
  {
    id: '2',
    customerName: 'Emily Davis',
    customerCompany: 'Global Innovations',
    totalCalls: 8,
    totalDeals: 5,
    avgDealValue: 120000,
    avgDiscount: 8,
    winRate: 62.5,
    lastContact: '2024-01-15T09:00:00',
    preferredTime: 'Early Morning (8-10 AM)',
    behaviorPattern: 'Quick decision maker, values quality over price',
    sentiment: 'positive',
    demographics: {
      industry: 'Manufacturing',
      companySize: '200-500 employees',
      location: 'New York, NY',
    },
  },
];

export const mockNegotiationAppointments: NegotiationAppointment[] = [
  {
    id: '1',
    title: 'Enterprise Plan Discussion',
    customerName: 'John Anderson',
    customerPhone: '+1 (555) 123-4567',
    date: '2024-01-16',
    time: '10:00 AM',
    duration: '30 min',
    type: 'phone',
    status: 'scheduled',
    dealValue: 75000,
    notes: 'Follow-up on proposal. Prepare contract for review.',
    reminders: true,
  },
  {
    id: '2',
    title: 'Contract Signing',
    customerName: 'Emily Davis',
    customerPhone: '+1 (555) 234-5678',
    date: '2024-01-16',
    time: '2:00 PM',
    duration: '45 min',
    type: 'video',
    status: 'scheduled',
    dealValue: 125000,
    notes: 'Final contract review and signing. Have legal team on standby.',
    reminders: true,
  },
  {
    id: '3',
    title: 'Product Demo',
    customerName: 'Robert Chen',
    customerPhone: '+1 (555) 345-6789',
    date: '2024-01-17',
    time: '11:00 AM',
    duration: '60 min',
    type: 'video',
    status: 'scheduled',
    dealValue: 35000,
    reminders: true,
  },
];

export const mockCallScripts: CallScript[] = [
  {
    id: '1',
    title: 'Warm Opening Script',
    category: 'opening',
    script: 'Good [morning/afternoon], this is [Your Name] from [Company]. I hope I\'m catching you at a good time. I\'m calling because [reason for call]. Do you have a few minutes to discuss how we can help [their company] achieve [specific goal]?',
    tags: ['professional', 'friendly', 'permission-based'],
    successRate: 78,
    timesUsed: 145,
    lastUsed: '2024-01-15',
  },
  {
    id: '2',
    title: 'Price Objection Handler',
    category: 'objection-handling',
    script: 'I understand budget is a concern. Let me ask - what specific value are you looking for? [Listen] Based on that, let me show you how our solution will actually save you money in the long run by [specific benefits]. Would a [discount %] discount if you commit to [term] help fit your budget?',
    tags: ['pricing', 'value-focused', 'solution-oriented'],
    successRate: 65,
    timesUsed: 89,
    lastUsed: '2024-01-14',
  },
  {
    id: '3',
    title: 'Closing the Deal',
    category: 'closing',
    script: 'Based on our discussion, it sounds like our [product/service] is exactly what you need. I can get you started with [offer details] and have you up and running by [timeline]. Can I send over the agreement today so you can start seeing results this [week/month]?',
    tags: ['action-oriented', 'benefit-focused', 'urgency'],
    successRate: 71,
    timesUsed: 67,
    lastUsed: '2024-01-15',
  },
];

export const mockNegotiationContacts: NegotiationContact[] = [
  {
    id: '1',
    name: 'John Anderson',
    company: 'TechCorp Solutions',
    email: 'john.anderson@techcorp.com',
    phone: '+1 (555) 123-4567',
    role: 'CTO',
    status: 'prospect',
    dealValue: 75000,
    dealStage: 'negotiation',
    lastContact: '2024-01-15',
    nextFollowUp: '2024-01-16',
    tags: ['enterprise', 'tech', 'decision-maker'],
    notes: 'Interested in enterprise plan. Budget conscious. Prefers 2-year contracts.',
  },
  {
    id: '2',
    name: 'Emily Davis',
    company: 'Global Innovations',
    email: 'emily.davis@globalinnovations.com',
    phone: '+1 (555) 234-5678',
    role: 'VP of Operations',
    status: 'customer',
    dealValue: 125000,
    dealStage: 'won',
    lastContact: '2024-01-15',
    tags: ['enterprise', 'manufacturing', 'closed'],
    notes: 'Recently closed. Quick decision maker. Values quality.',
  },
  {
    id: '3',
    name: 'Robert Chen',
    company: 'Startup Hub',
    email: 'robert.chen@startuphub.io',
    phone: '+1 (555) 345-6789',
    role: 'CEO',
    status: 'lead',
    dealValue: 35000,
    dealStage: 'discovery',
    lastContact: '2024-01-14',
    nextFollowUp: '2024-01-17',
    tags: ['startup', 'tech', 'early-stage'],
    notes: 'New startup. Looking for scalable solution. Price sensitive.',
  },
];

export const mockDeals: Deal[] = [
  {
    id: '1',
    title: 'TechCorp Enterprise Package',
    customerName: 'John Anderson',
    customerCompany: 'TechCorp Solutions',
    value: 75000,
    stage: 'negotiation',
    probability: 70,
    expectedCloseDate: '2024-01-20',
    owner: 'Sarah Miller',
    product: 'Enterprise Plan - 50 users',
    discountOffered: 20,
    notes: 'Negotiating 2-year contract with 20% discount',
    lastActivity: '2024-01-15',
  },
  {
    id: '2',
    title: 'Global Innovations Contract',
    customerName: 'Emily Davis',
    customerCompany: 'Global Innovations',
    value: 125000,
    stage: 'won',
    probability: 100,
    expectedCloseDate: '2024-01-15',
    owner: 'Mike Johnson',
    product: 'Enterprise Plan - 100 users',
    discountOffered: 10,
    notes: 'Deal closed successfully',
    lastActivity: '2024-01-15',
  },
  {
    id: '3',
    title: 'Startup Hub Growth Plan',
    customerName: 'Robert Chen',
    customerCompany: 'Startup Hub',
    value: 35000,
    stage: 'discovery',
    probability: 40,
    expectedCloseDate: '2024-01-25',
    owner: 'Sarah Miller',
    product: 'Growth Plan - 20 users',
    notes: 'Early stage startup, needs more nurturing',
    lastActivity: '2024-01-14',
  },
];

export const mockNegotiationTemplates: NegotiationTemplate[] = [
  {
    id: '1',
    title: 'Initial Outreach Email',
    type: 'email',
    content: 'Hi {{firstName}},\n\nI hope this email finds you well. I wanted to reach out because {{companyName}} could benefit from our {{productName}}.\n\nWe\'ve helped companies like {{similarCompany}} achieve {{result}}. I\'d love to discuss how we can help {{companyName}} achieve similar results.\n\nAre you available for a quick 15-minute call this week?\n\nBest regards,\n{{senderName}}',
    category: 'prospecting',
    variables: ['firstName', 'companyName', 'productName', 'similarCompany', 'result', 'senderName'],
    successRate: 42,
    timesUsed: 234,
  },
  {
    id: '2',
    title: 'Pricing Proposal',
    type: 'email',
    content: 'Hi {{firstName}},\n\nThank you for your interest in {{productName}}. Based on our discussion, I\'ve prepared a customized proposal for {{companyName}}.\n\nPackage: {{packageName}}\nUsers: {{userCount}}\nPrice: ${{price}}\nDiscount: {{discount}}%\nFinal Price: ${{finalPrice}}\n\nThis offer includes:\n- {{feature1}}\n- {{feature2}}\n- {{feature3}}\n\nThis pricing is valid until {{expiryDate}}. Let me know if you have any questions!\n\nBest regards,\n{{senderName}}',
    category: 'proposal',
    variables: ['firstName', 'productName', 'companyName', 'packageName', 'userCount', 'price', 'discount', 'finalPrice', 'feature1', 'feature2', 'feature3', 'expiryDate', 'senderName'],
    successRate: 68,
    timesUsed: 156,
  },
  {
    id: '3',
    title: 'Follow-up SMS',
    type: 'sms',
    content: 'Hi {{firstName}}, this is {{senderName}} from {{companyName}}. Just following up on our call yesterday. Are you available for a quick chat? Reply YES to schedule.',
    category: 'follow-up',
    variables: ['firstName', 'senderName', 'companyName'],
    successRate: 55,
    timesUsed: 89,
  },
];

export const mockIntegrations: Integration[] = [
  {
    id: '1',
    name: 'Salesforce',
    description: 'Sync contacts and deals with Salesforce CRM',
    icon: 'briefcase',
    isConnected: true,
    lastSync: '2024-01-15T10:30:00',
    category: 'crm',
  },
  {
    id: '2',
    name: 'Google Calendar',
    description: 'Sync appointments and meetings',
    icon: 'calendar',
    isConnected: true,
    lastSync: '2024-01-15T09:00:00',
    category: 'calendar',
  },
  {
    id: '3',
    name: 'Slack',
    description: 'Receive notifications in Slack',
    icon: 'message-circle',
    isConnected: false,
    category: 'communication',
  },
  {
    id: '4',
    name: 'Zoom',
    description: 'Schedule and join video calls',
    icon: 'video',
    isConnected: true,
    lastSync: '2024-01-15T08:00:00',
    category: 'communication',
  },
  {
    id: '5',
    name: 'HubSpot',
    description: 'Connect with HubSpot CRM',
    icon: 'briefcase',
    isConnected: false,
    category: 'crm',
  },
  {
    id: '6',
    name: 'Google Analytics',
    description: 'Track performance metrics',
    icon: 'bar-chart',
    isConnected: false,
    category: 'analytics',
  },
];

export const mockReceptionistPhoneNumbers = [
  {
    id: '1',
    number: '+1 (800) 555-0100',
    label: 'Main Reception Line',
    type: 'toll-free' as const,
    isActive: true,
    callsHandled: 2847,
    successRate: 94,
    assignedAgents: ['AI Receptionist 1', 'AI Receptionist 2'],
  },
  {
    id: '2',
    number: '+1 (555) 200-3000',
    label: 'Customer Service',
    type: 'local' as const,
    isActive: true,
    callsHandled: 1456,
    successRate: 92,
    assignedAgents: ['AI Receptionist 1'],
  },
  {
    id: '3',
    number: '+44 20 7946 0100',
    label: 'UK Reception',
    type: 'international' as const,
    isActive: true,
    callsHandled: 634,
    successRate: 89,
    assignedAgents: ['AI Receptionist 3'],
  },
];

export const mockReceptionistCallLogs = [
  {
    id: '1',
    callId: 'rec-001',
    callerName: 'Jennifer Smith',
    callerPhone: '+1 (555) 123-4567',
    callType: 'incoming' as const,
    duration: '5:34',
    timestamp: '2024-01-15T14:30:00',
    status: 'answered' as const,
    summary: 'Customer inquiry about business hours and services. AI provided information and scheduled callback with sales team.',
    sentiment: 'positive' as const,
    category: 'inquiry',
  },
  {
    id: '2',
    callId: 'rec-002',
    callerName: 'Michael Johnson',
    callerPhone: '+1 (555) 234-5678',
    callType: 'incoming' as const,
    duration: '3:15',
    timestamp: '2024-01-15T13:45:00',
    status: 'answered' as const,
    summary: 'Appointment booking request. Successfully scheduled meeting for Jan 18 at 2PM.',
    sentiment: 'positive' as const,
    category: 'appointment',
  },
  {
    id: '3',
    callId: 'rec-003',
    callerName: 'Unknown',
    callerPhone: '+1 (555) 345-6789',
    callType: 'incoming' as const,
    duration: '0:00',
    timestamp: '2024-01-15T12:20:00',
    status: 'missed' as const,
    category: 'missed',
  },
];

export const mockReceptionistContacts = [
  {
    id: '1',
    name: 'Jennifer Smith',
    company: 'Tech Innovations Inc',
    email: 'jennifer.smith@techinnovations.com',
    phone: '+1 (555) 123-4567',
    role: 'Marketing Director',
    status: 'lead' as const,
    lastContact: '2024-01-15',
    nextFollowUp: '2024-01-18',
    tags: ['inquiry', 'high-priority'],
    notes: 'Interested in enterprise package. Requested callback.',
    callCount: 3,
    totalDuration: '15:45',
  },
  {
    id: '2',
    name: 'Michael Johnson',
    company: 'Global Solutions',
    email: 'michael.j@globalsolutions.com',
    phone: '+1 (555) 234-5678',
    role: 'CEO',
    status: 'customer' as const,
    lastContact: '2024-01-15',
    tags: ['appointment', 'vip'],
    notes: 'Regular customer. Scheduled meeting for product demo.',
    callCount: 12,
    totalDuration: '45:23',
  },
];

export const mockReceptionistAppointments = [
  {
    id: '1',
    title: 'Product Demo',
    callerName: 'Michael Johnson',
    callerPhone: '+1 (555) 234-5678',
    date: '2024-01-18',
    time: '2:00 PM',
    duration: '60 min',
    type: 'video' as const,
    status: 'scheduled' as const,
    notes: 'Requested enterprise plan demo',
    reminders: true,
  },
  {
    id: '2',
    title: 'Sales Consultation',
    callerName: 'Jennifer Smith',
    callerPhone: '+1 (555) 123-4567',
    date: '2024-01-19',
    time: '10:00 AM',
    duration: '30 min',
    type: 'phone' as const,
    status: 'scheduled' as const,
    notes: 'Follow-up on pricing inquiry',
    reminders: true,
  },
];

export const mockNegotiationNotifications: NegotiationNotification[] = [
  {
    id: '1',
    title: 'Upcoming Call',
    message: 'You have a call with John Anderson in 30 minutes',
    type: 'call',
    priority: 'high',
    timestamp: '2024-01-15T09:30:00',
    isRead: false,
    actionUrl: '/ai-negotiation/appointments',
  },
  {
    id: '2',
    title: 'Deal Closed',
    message: 'Emily Davis signed the contract for $125,000',
    type: 'deal',
    priority: 'high',
    timestamp: '2024-01-15T09:15:00',
    isRead: false,
    actionUrl: '/ai-negotiation/deals',
  },
  {
    id: '3',
    title: 'Missed Call',
    message: 'Missed call from Michael Wilson',
    type: 'call',
    priority: 'medium',
    timestamp: '2024-01-15T08:15:00',
    isRead: true,
    actionUrl: '/ai-negotiation/call-logs',
  },
];

export const mockTrainingModules = [
  {
    id: '1',
    title: 'Advanced Negotiation Tactics',
    description: 'Master the art of price negotiation and closing deals',
    category: 'negotiation',
    duration: '45 min',
    difficulty: 'advanced' as const,
    lessons: 12,
    completed: 8,
    progress: 67,
    rating: 4.9,
    students: 1247,
  },
  {
    id: '2',
    title: 'Objection Handling Masterclass',
    description: 'Turn objections into opportunities',
    category: 'sales',
    duration: '30 min',
    difficulty: 'intermediate' as const,
    lessons: 8,
    completed: 0,
    progress: 0,
    rating: 4.8,
    students: 892,
  },
  {
    id: '3',
    title: 'Psychological Pricing Strategies',
    description: 'Learn the psychology behind pricing decisions',
    category: 'pricing',
    duration: '60 min',
    difficulty: 'advanced' as const,
    lessons: 15,
    completed: 15,
    progress: 100,
    rating: 5.0,
    students: 654,
  },
  {
    id: '4',
    title: 'Building Rapport & Trust',
    description: 'Essential techniques for connecting with clients',
    category: 'communication',
    duration: '25 min',
    difficulty: 'beginner' as const,
    lessons: 6,
    completed: 3,
    progress: 50,
    rating: 4.7,
    students: 2134,
  },
];

export const mockAnalyticsData = {
  revenue: {
    current: 5300000,
    previous: 4070000,
    change: 30.2,
    trend: 'up' as const,
    chartData: [
      { month: 'Jul', value: 3200000 },
      { month: 'Aug', value: 3650000 },
      { month: 'Sep', value: 3890000 },
      { month: 'Oct', value: 4070000 },
      { month: 'Nov', value: 4580000 },
      { month: 'Dec', value: 5300000 },
    ],
  },
  deals: {
    current: 342,
    previous: 271,
    change: 26.2,
    trend: 'up' as const,
    chartData: [
      { month: 'Jul', value: 198 },
      { month: 'Aug', value: 215 },
      { month: 'Sep', value: 234 },
      { month: 'Oct', value: 271 },
      { month: 'Nov', value: 298 },
      { month: 'Dec', value: 342 },
    ],
  },
  winRate: {
    current: 70,
    previous: 65,
    change: 7.7,
    trend: 'up' as const,
    chartData: [
      { month: 'Jul', value: 62 },
      { month: 'Aug', value: 63 },
      { month: 'Sep', value: 64 },
      { month: 'Oct', value: 65 },
      { month: 'Nov', value: 68 },
      { month: 'Dec', value: 70 },
    ],
  },
  callVolume: {
    current: 2847,
    previous: 2456,
    change: 15.9,
    trend: 'up' as const,
    byHour: [
      { hour: '8 AM', calls: 142 },
      { hour: '9 AM', calls: 234 },
      { hour: '10 AM', calls: 312 },
      { hour: '11 AM', calls: 287 },
      { hour: '12 PM', calls: 198 },
      { hour: '1 PM', calls: 176 },
      { hour: '2 PM', calls: 298 },
      { hour: '3 PM', calls: 267 },
      { hour: '4 PM', calls: 234 },
      { hour: '5 PM', calls: 189 },
    ],
  },
  conversionFunnel: [
    { stage: 'Leads', count: 1247, conversion: 100 },
    { stage: 'Qualified', count: 892, conversion: 71.5 },
    { stage: 'Proposal', count: 567, conversion: 63.6 },
    { stage: 'Negotiation', count: 423, conversion: 74.6 },
    { stage: 'Closed Won', count: 342, conversion: 80.9 },
  ],
  topPerformers: [
    { name: 'Sarah Miller', deals: 89, revenue: 1890000, winRate: 78 },
    { name: 'Mike Johnson', deals: 76, revenue: 1650000, winRate: 72 },
    { name: 'Alex Chen', deals: 68, revenue: 1420000, winRate: 69 },
    { name: 'Emma Wilson', deals: 54, revenue: 1180000, winRate: 71 },
  ],
};

export const mockReceptionistTrainingModules = [
  {
    id: '1',
    title: 'Professional Phone Etiquette',
    description: 'Master the fundamentals of professional communication',
    category: 'communication',
    duration: '30 min',
    difficulty: 'beginner' as const,
    lessons: 8,
    completed: 8,
    progress: 100,
    rating: 4.8,
    students: 3245,
  },
  {
    id: '2',
    title: 'Advanced Caller Management',
    description: 'Handle difficult callers with confidence',
    category: 'management',
    duration: '40 min',
    difficulty: 'intermediate' as const,
    lessons: 10,
    completed: 5,
    progress: 50,
    rating: 4.9,
    students: 1876,
  },
  {
    id: '3',
    title: 'Emergency Call Protocols',
    description: 'Learn critical emergency response procedures',
    category: 'emergency',
    duration: '20 min',
    difficulty: 'advanced' as const,
    lessons: 6,
    completed: 0,
    progress: 0,
    rating: 5.0,
    students: 987,
  },
];

export const mockReceptionistCallerInsights = [
  {
    id: '1',
    callerName: 'Jennifer Smith',
    callerCompany: 'Tech Innovations Inc',
    totalCalls: 8,
    totalDuration: '42:35',
    avgDuration: '5:19',
    lastContact: '2024-01-15T14:30:00',
    preferredTime: 'Afternoon (2-4 PM)',
    callPattern: 'Regular caller, prefers quick inquiries',
    sentiment: 'positive' as const,
    satisfaction: 4.9,
    demographics: {
      industry: 'Technology',
      companySize: '50-100 employees',
      location: 'San Francisco, CA',
    },
    topics: ['Pricing', 'Product Features', 'Support'],
  },
  {
    id: '2',
    callerName: 'Michael Johnson',
    callerCompany: 'Global Solutions',
    totalCalls: 15,
    totalDuration: '98:45',
    avgDuration: '6:35',
    lastContact: '2024-01-15T13:45:00',
    preferredTime: 'Morning (9-11 AM)',
    callPattern: 'VIP client, detailed discussions',
    sentiment: 'positive' as const,
    satisfaction: 5.0,
    demographics: {
      industry: 'Consulting',
      companySize: '200-500 employees',
      location: 'New York, NY',
    },
    topics: ['Account Management', 'Technical Support', 'Billing'],
  },
];

export const mockReceptionistAnalytics = {
  totalCalls: {
    current: 2847,
    previous: 2456,
    change: 15.9,
    trend: 'up' as const,
  },
  answeredCalls: {
    current: 2679,
    previous: 2301,
    change: 16.4,
    trend: 'up' as const,
  },
  missedCalls: {
    current: 168,
    previous: 155,
    change: 8.4,
    trend: 'up' as const,
  },
  avgResponseTime: {
    current: '2.3s',
    previous: '2.8s',
    change: -17.9,
    trend: 'down' as const,
  },
  satisfaction: {
    current: 4.8,
    previous: 4.6,
    change: 4.3,
    trend: 'up' as const,
  },
  appointmentsBooked: {
    current: 487,
    previous: 412,
    change: 18.2,
    trend: 'up' as const,
  },
  callsByCategory: [
    { category: 'General Inquiry', count: 1247, percentage: 43.8 },
    { category: 'Appointment', count: 625, percentage: 22.0 },
    { category: 'Support', count: 542, percentage: 19.0 },
    { category: 'Sales', count: 289, percentage: 10.2 },
    { category: 'Other', count: 144, percentage: 5.0 },
  ],
  peakHours: [
    { hour: '9 AM', calls: 324 },
    { hour: '10 AM', calls: 398 },
    { hour: '11 AM', calls: 356 },
    { hour: '2 PM', calls: 412 },
    { hour: '3 PM', calls: 387 },
  ],
};
