import { Task, Meeting, Email, ContextMemory, Workflow, ProductivityInsight, Project, Goal, Document, Contact, VoiceNote } from '@/providers/AIAssistantProvider';

export const mockTasksEnhanced: Task[] = [
  {
    id: '1',
    title: 'Review Q4 Marketing Strategy & ROI Analysis',
    description: 'Comprehensive analysis of Q3 performance metrics, ROI calculations, competitive positioning, and strategic recommendations for Q4. Prepare executive summary with data visualizations. Focus on digital channels showing 34% growth.',
    priority: 'high',
    status: 'in-progress',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '3 hours',
    actualTime: '1.5 hours',
    energyLevel: 'high',
    aiGenerated: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    tags: ['marketing', 'strategy', 'quarterly', 'executive', 'high-impact'],
    assignedTo: 'you',
    projectId: 'proj_1',
    complexity: 'complex',
    aiSuggestions: [
      'Schedule 30min strategy alignment call with CMO',
      'Review last year Q4 performance for benchmarking',
      'Prepare interactive dashboard using latest analytics data'
    ],
    sentiment: 'neutral',
    attachments: ['Q3_Performance_Report.pdf', 'Competitive_Analysis_2024.xlsx', 'ROI_Dashboard.png'],
    subtasks: ['sub_1', 'sub_2', 'sub_3'],
  },
  {
    id: '2',
    title: 'Prepare Client Presentation - Acme Corp Quarterly Review',
    description: 'Create comprehensive slides showcasing deliverables, KPIs achieved, challenges overcome, and roadmap for next quarter. Include case studies and success metrics. Client expects deep-dive into conversion improvements (+23%).',
    priority: 'high',
    status: 'pending',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '4 hours',
    energyLevel: 'high',
    aiGenerated: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    tags: ['presentation', 'client', 'urgent', 'acme-corp', 'quarterly-review'],
    assignedTo: 'you',
    projectId: 'proj_2',
    complexity: 'complex',
    aiSuggestions: [
      'Include before/after metrics visualization',
      'Add client testimonial from John Smith',
      'Prepare backup slides for technical Q&A'
    ],
    sentiment: 'positive',
    attachments: ['Draft_Presentation.pptx', 'Client_Metrics_Dashboard.pdf'],
  },
  {
    id: '3',
    title: 'Update API Documentation & Developer Guide',
    description: 'Document recent v2.5 API changes including new authentication flow, rate limiting updates, and webhook improvements. Update code examples for Python, Node.js, and Java SDKs. Add troubleshooting section.',
    priority: 'medium',
    status: 'pending',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '2.5 hours',
    energyLevel: 'medium',
    aiGenerated: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    tags: ['documentation', 'development', 'api', 'technical-writing'],
    assignedTo: 'you',
    projectId: 'proj_3',
    complexity: 'moderate',
    dependencies: ['task_api_v2_5_release'],
    sentiment: 'neutral',
  },
  {
    id: '4',
    title: 'Conduct User Interview Sessions (5 participants)',
    description: 'Schedule and conduct in-depth user interviews to gather insights on new feature usability, pain points, and improvement suggestions. Focus on power users who utilize advanced features. Record sessions and extract key quotes.',
    priority: 'high',
    status: 'pending',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '6 hours',
    energyLevel: 'high',
    aiGenerated: true,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    tags: ['research', 'user-experience', 'interviews', 'product-development'],
    assignedTo: 'you',
    projectId: 'proj_4',
    complexity: 'complex',
    aiSuggestions: [
      'Prepare interview guide with open-ended questions',
      'Set up Zoom recordings and backup audio',
      'Create synthesis framework for analyzing responses'
    ],
    sentiment: 'positive',
  },
  {
    id: '5',
    title: 'Fix Critical Bug: Payment Processing Timeout',
    description: 'Investigate and resolve timeout issue affecting 3% of payment transactions. Root cause appears to be third-party gateway latency. Implement retry logic and improve error handling. Priority: P0',
    priority: 'high',
    status: 'in-progress',
    dueDate: new Date(Date.now() + 0.5 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '4 hours',
    energyLevel: 'high',
    aiGenerated: false,
    createdAt: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000),
    tags: ['bug', 'critical', 'payment', 'backend', 'urgent'],
    assignedTo: 'you',
    complexity: 'complex',
    sentiment: 'negative',
    aiSuggestions: [
      'Check error logs from last 48 hours',
      'Contact payment gateway support for latency analysis',
      'Implement circuit breaker pattern'
    ],
  },
];

export const mockMeetingsEnhanced: Meeting[] = [
  {
    id: '1',
    title: 'Weekly Team Standup - Engineering',
    description: 'Sprint progress review, blocker discussions, and upcoming priorities. Focus on Q4 release timeline and resource allocation.',
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 2.5 * 60 * 60 * 1000).toISOString(),
    attendees: ['john.doe@company.com', 'sarah.chen@company.com', 'mike.wilson@company.com', 'emma.davis@company.com'],
    location: 'Conference Room A / Zoom Hybrid',
    type: 'in-person',
    aiScheduled: false,
    preparationNeeded: false,
    status: 'scheduled',
    agenda: [
      'Sprint progress updates (10min)',
      'Blocker discussion (15min)',
      'Q4 timeline review (10min)',
      'Action items & next steps (5min)'
    ],
    meetingLink: 'https://zoom.us/j/123456789',
    sentiment: 'neutral',
    productivityScore: 85,
  },
  {
    id: '2',
    title: 'Acme Corp - Q3 Strategy Review & Q4 Planning',
    description: 'Executive strategy session with Acme Corp leadership. Present Q3 achievements (+34% growth), discuss Q4 objectives, address concerns about competitive landscape, and finalize budget allocation.',
    startTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 25.5 * 60 * 60 * 1000).toISOString(),
    attendees: ['john.smith@acmecorp.com', 'lisa.johnson@acmecorp.com', 'manager@company.com', 'you@company.com'],
    meetingLink: 'https://zoom.us/j/987654321',
    type: 'video',
    aiScheduled: true,
    preparationNeeded: true,
    status: 'scheduled',
    agenda: [
      'Q3 Performance Review (20min)',
      'Key Wins & Success Stories (15min)',
      'Challenges & Solutions (15min)',
      'Q4 Strategic Priorities (20min)',
      'Budget Discussion (10min)',
      'Q&A (10min)'
    ],
    notes: 'Prepare slides with data visualizations. Focus on conversion rate improvements. John prefers detailed metrics.',
    sentiment: 'positive',
    productivityScore: 92,
    followUpRequired: true,
    aiSummary: 'Strategic alignment meeting with key client. High importance for relationship building and contract renewal.',
  },
  {
    id: '3',
    title: 'Product Roadmap Planning - H1 2025',
    description: 'Cross-functional planning session for first half of 2025. Align on feature priorities, technical debt, resource allocation, and OKRs.',
    startTime: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
    attendees: [
      'product@company.com',
      'engineering.lead@company.com', 
      'design.head@company.com',
      'marketing.lead@company.com'
    ],
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    type: 'video',
    aiScheduled: true,
    preparationNeeded: true,
    status: 'scheduled',
    agenda: [
      'Review customer feedback & feature requests',
      'Technical debt prioritization',
      'Resource capacity planning',
      'H1 OKR alignment',
      'Risk assessment'
    ],
    sentiment: 'neutral',
    productivityScore: 88,
    aiSummary: 'Critical planning meeting. Requires strategic thinking and cross-team alignment.',
  },
  {
    id: '4',
    title: 'Design System 2.0 - Final Review',
    description: 'Review updated components, accessibility improvements, and implementation guidelines. Sign-off required before engineering handoff.',
    startTime: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 73 * 60 * 60 * 1000).toISOString(),
    attendees: ['design@company.com', 'product@company.com', 'frontend@company.com'],
    meetingLink: 'https://zoom.us/j/555123789',
    type: 'video',
    aiScheduled: true,
    preparationNeeded: false,
    status: 'scheduled',
    sentiment: 'positive',
    productivityScore: 90,
    actionItems: [
      { task: 'Update Figma documentation', assignee: 'design@company.com' },
      { task: 'Create implementation guide', assignee: 'frontend@company.com' }
    ],
  },
];

export const mockEmailsEnhanced: Email[] = [
  {
    id: '1',
    from: 'john.smith@acmecorp.com',
    to: ['you@company.com'],
    cc: ['manager@company.com'],
    subject: 'Q4 Strategy Review - Follow Up & Additional Questions',
    body: `Hi there,\n\nThank you for yesterday's productive strategy session. The metrics you shared were impressive, particularly the 34% growth in digital channels.\n\nI have a few follow-up questions:\n1. Can you provide a breakdown of the conversion improvements by segment?\n2. What's your confidence level in maintaining this growth trajectory in Q4?\n3. Timeline for implementing the personalization features we discussed?\n\nCould you send over the updated timeline and budget breakdown by end of week? Our board meeting is next Monday and I'd like to include these insights.\n\nAlso, Lisa mentioned interest in expanding the partnership scope. Let's schedule a call to discuss.\n\nBest regards,\nJohn Smith\nVP of Marketing, Acme Corp`,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: false,
    aiDrafted: false,
    priority: 'high',
    category: 'work',
    sentiment: 'positive',
    intent: 'followup',
    requiresResponse: true,
    suggestedReplies: [
      'Thank you John. I will have the detailed breakdown to you by Thursday. The data shows strong signals for continued growth.',
      'Great meeting yesterday! I will prepare a comprehensive response addressing all three questions with supporting data.',
      'Thanks for the follow-up. Let me compile the metrics and schedule that call with Lisa for early next week.'
    ],
    labels: ['important', 'client', 'quarterly'],
    relatedTasks: ['1', '2'],
    relatedMeetings: ['2'],
    aiContext: 'High-priority client follow-up requiring detailed response with data. Mentions board meeting deadline. Expansion opportunity mentioned.',
  },
  {
    id: '2',
    from: 'sarah.chen@company.com',
    to: ['team@company.com'],
    cc: ['you@company.com'],
    subject: '🎉 Sprint 47 Completed - 94% Velocity!',
    body: `Team,\n\nAmazing work this sprint! We achieved 94% velocity and completed all P0 items.\n\n✅ Completed:\n- Payment integration improvements\n- Dashboard performance optimization (+40% load time)\n- Mobile responsive fixes\n- 23 bug fixes\n\n🚀 Highlights:\n- Zero production incidents\n- API latency reduced by 25%\n- User satisfaction score up to 4.7/5\n\nNext Sprint Planning: Thursday 2 PM\n\nCelebrating with team lunch on Friday! 🍕\n\nGreat job everyone!\nSarah`,
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    read: true,
    aiDrafted: false,
    priority: 'medium',
    category: 'work',
    sentiment: 'positive',
    intent: 'update',
    requiresResponse: false,
    labels: ['team', 'sprint', 'celebration'],
    aiContext: 'Positive team update celebrating achievements. No action required but shows strong team performance.',
  },
  {
    id: '3',
    from: 'alerts@monitoring.company.com',
    to: ['oncall@company.com', 'you@company.com'],
    subject: '🔴 CRITICAL: Payment Service Latency Spike',
    body: `ALERT: Payment Service Latency\n\nSeverity: P0 - Critical\nService: payment-processor\nMetric: p95 latency > 5000ms\nAffected: 3% of transactions\nStarted: 15 minutes ago\n\nAction Required:\n- Investigate payment gateway performance\n- Check third-party service status\n- Implement fallback if needed\n\nRunbook: https://docs.company.com/runbooks/payment-latency\nDashboard: https://monitor.company.com/payment\n\nIncident #INC-2024-1047`,
    timestamp: new Date(Date.now() - 0.25 * 60 * 60 * 1000),
    read: false,
    aiDrafted: false,
    priority: 'high',
    category: 'urgent',
    sentiment: 'negative',
    intent: 'request',
    requiresResponse: true,
    starred: true,
    labels: ['alert', 'critical', 'incident'],
    relatedTasks: ['5'],
    aiContext: 'Critical production alert requiring immediate attention. Payment processing issue affecting customers.',
  },
  {
    id: '4',
    from: 'newsletter@techinsights.com',
    to: ['you@company.com'],
    subject: 'Weekly Tech Insights - AI Trends 2024 & Enterprise Adoption',
    body: `This week's top stories:\n\n📊 AI in Enterprise: 67% adoption rate\n☁️ Cloud Computing: Multi-cloud strategies surge\n🔒 Cybersecurity: Zero-trust architecture trends\n💡 Developer Tools: AI-powered IDEs gain traction\n\n[Read more...]`,
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000),
    read: false,
    aiDrafted: false,
    priority: 'low',
    category: 'newsletter',
    sentiment: 'neutral',
    intent: 'other',
    requiresResponse: false,
    archived: false,
    aiContext: 'Weekly newsletter. Low priority informational content.',
  },
  {
    id: '5',
    from: 'you@company.com',
    to: ['john.smith@acmecorp.com'],
    cc: ['manager@company.com'],
    subject: 'Re: Q4 Strategy Review - Detailed Response & Analysis',
    body: `Hi John,\n\nThank you for your email. I'm excited to address your questions with detailed insights.\n\n1. Conversion Breakdown by Segment:\n- Enterprise: +41% (highest performing)\n- Mid-Market: +32%\n- SMB: +28%\nDetailed report attached.\n\n2. Q4 Growth Confidence: 85% confidence based on:\n- Strong pipeline momentum\n- Seasonal trends analysis\n- Market positioning improvements\n\n3. Personalization Features Timeline:\n- Phase 1: Mid-November (basic segmentation)\n- Phase 2: December (advanced targeting)\n- Full rollout: Early January\n\nI'll have the complete timeline and budget breakdown to you by Thursday EOD, well ahead of your Monday board meeting.\n\nRegarding the partnership expansion with Lisa, I have availability next Tuesday or Wednesday. Would either work for a 30-minute call?\n\nLooking forward to our continued collaboration.\n\nBest regards,\nYour Name\n\nAttached: Q3_Conversion_Analysis_Detailed.pdf`,
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    read: true,
    aiDrafted: true,
    priority: 'high',
    category: 'work',
    sentiment: 'positive',
    intent: 'followup',
    requiresResponse: false,
    labels: ['sent', 'client', 'important'],
    threadId: 'thread_1',
    aiContext: 'AI-drafted response to client inquiry. Professional tone maintained with detailed answers and proactive scheduling.',
  },
];

export const mockProjectsEnhanced: Project[] = [
  {
    id: 'proj_1',
    name: 'Q4 Marketing Campaign - Digital Transformation',
    description: 'Comprehensive digital marketing initiative targeting enterprise segment with focus on thought leadership and brand positioning',
    status: 'active',
    progress: 68,
    startDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    team: ['you@company.com', 'marketing.lead@company.com', 'content.manager@company.com'],
    priority: 'high',
    tags: ['marketing', 'campaign', 'enterprise', 'q4'],
    budget: 250000,
    spent: 170000,
    aiGenerated: true,
    metrics: [
      { key: 'Lead Generation', value: '+127%' },
      { key: 'Engagement Rate', value: '4.2%' },
      { key: 'Content Views', value: '1.2M' },
    ],
  },
  {
    id: 'proj_2',
    name: 'Mobile App Redesign - v3.0',
    description: 'Complete UX overhaul with focus on user engagement, performance optimization, and modern design system implementation',
    status: 'active',
    progress: 72,
    startDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    team: ['design.lead@company.com', 'mobile.dev@company.com', 'product.manager@company.com'],
    priority: 'high',
    tags: ['mobile', 'design', 'ux', 'product'],
    budget: 180000,
    spent: 129600,
    aiGenerated: false,
    metrics: [
      { key: 'User Testing Score', value: '4.6/5' },
      { key: 'Performance Gain', value: '+35%' },
      { key: 'Screens Completed', value: '47/65' },
    ],
  },
  {
    id: 'proj_3',
    name: 'API Platform Modernization',
    description: 'Migrate to microservices architecture, implement GraphQL, enhance security, and improve developer experience',
    status: 'active',
    progress: 45,
    startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    team: ['backend.lead@company.com', 'devops@company.com', 'security@company.com'],
    priority: 'medium',
    tags: ['api', 'backend', 'infrastructure', 'security'],
    budget: 320000,
    spent: 144000,
    aiGenerated: true,
    metrics: [
      { key: 'API Latency', value: '-42%' },
      { key: 'Test Coverage', value: '87%' },
      { key: 'Services Migrated', value: '12/27' },
    ],
  },
];

export const mockGoalsEnhanced: Goal[] = [
  {
    id: 'goal_1',
    title: 'Increase Revenue by 35%',
    description: 'Achieve 35% year-over-year revenue growth through new customer acquisition, expansion revenue, and improved retention',
    type: 'company',
    progress: 71,
    target: 100,
    unit: '%',
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    milestones: [
      { title: 'Q1: +8% growth', completed: true, date: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString() },
      { title: 'Q2: +12% growth', completed: true, date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString() },
      { title: 'Q3: +15% growth (current)', completed: false },
      { title: 'Q4: Hit 35% annual target', completed: false },
    ],
    priority: 'high',
    aiGenerated: false,
    relatedProjects: ['proj_1'],
  },
  {
    id: 'goal_2',
    title: 'Improve Customer Satisfaction Score',
    description: 'Increase NPS score from 45 to 70 through product improvements, enhanced support, and proactive customer success',
    type: 'team',
    progress: 82,
    target: 70,
    unit: 'NPS',
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    milestones: [
      { title: 'Implement feedback system', completed: true },
      { title: 'Launch support improvements', completed: true },
      { title: 'Achieve NPS 60', completed: true },
      { title: 'Reach NPS 70', completed: false },
    ],
    priority: 'high',
    aiGenerated: true,
  },
  {
    id: 'goal_3',
    title: 'Complete 150 Hours of Professional Development',
    description: 'Invest in skills growth through courses, conferences, and certifications in AI, leadership, and product strategy',
    type: 'personal',
    progress: 64,
    target: 150,
    unit: 'hours',
    deadline: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
    milestones: [
      { title: 'Complete AI/ML certification', completed: true, date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString() },
      { title: 'Attend industry conference', completed: true },
      { title: 'Leadership training program', completed: false },
      { title: 'Advanced product strategy course', completed: false },
    ],
    priority: 'medium',
    aiGenerated: true,
  },
];

export const mockDocumentsEnhanced: Document[] = [
  {
    id: 'doc_1',
    title: 'Q3 Performance Report - Executive Summary',
    type: 'pdf',
    size: 2457600,
    content: 'Executive summary of Q3 performance metrics, achievements, and strategic insights...',
    aiSummary: 'Comprehensive Q3 review showing 34% growth in digital channels, improved customer acquisition costs, and strong market positioning. Key highlights include successful product launches and team expansion.',
    aiTags: ['quarterly', 'performance', 'metrics', 'executive', 'q3-2024'],
    uploadedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    lastModified: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    sharedWith: ['executive@company.com', 'board@company.com'],
    sentiment: 'positive',
    language: 'en',
    extractedData: {
      revenue: '$12.4M',
      growth: '34%',
      customers: '1,247',
      satisfaction: '4.6/5'
    },
  },
  {
    id: 'doc_2',
    title: 'Product Roadmap 2025 H1',
    type: 'doc',
    size: 892800,
    aiSummary: 'Strategic product roadmap outlining major features, technical improvements, and resource allocation for first half of 2025. Focus on AI capabilities, mobile experience, and enterprise features.',
    aiTags: ['roadmap', 'product', '2025', 'planning', 'strategy'],
    uploadedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    lastModified: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    sharedWith: ['product@company.com', 'engineering@company.com'],
    sentiment: 'neutral',
    language: 'en',
  },
  {
    id: 'doc_3',
    title: 'Customer Research Insights - October 2024',
    type: 'sheet',
    size: 1536000,
    aiSummary: 'Detailed analysis of customer interviews and survey data. Key themes: desire for automation features, mobile app improvements, and better integrations. High satisfaction with support team.',
    aiTags: ['research', 'customer-feedback', 'insights', 'ux', 'october-2024'],
    uploadedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    lastModified: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    sentiment: 'positive',
    language: 'en',
    extractedData: {
      participants: 47,
      satisfactionScore: 4.4,
      topRequest: 'Automation features',
      responseRate: '73%'
    },
  },
];

export const mockContactsEnhanced: Contact[] = [
  {
    id: 'contact_1',
    name: 'John Smith',
    email: 'john.smith@acmecorp.com',
    phone: '+1 (555) 123-4567',
    company: 'Acme Corporation',
    role: 'VP of Marketing',
    tags: ['client', 'executive', 'key-account', 'decision-maker'],
    lastContact: new Date(Date.now() - 2 * 60 * 60 * 1000),
    notes: 'Primary contact at Acme Corp. Prefers detailed data and strategic insights. Board meetings typically first Monday of month. Interested in expansion opportunities.',
    aiInsights: [
      'High engagement with quarterly reports',
      'Responds best to data-driven communication',
      'Active on LinkedIn - shares industry content',
      'Strong advocate for our services within his organization'
    ],
    relationshipScore: 92,
    preferredContactMethod: 'email',
    timezone: 'America/New_York',
    socialProfiles: [
      { platform: 'LinkedIn', url: 'https://linkedin.com/in/johnsmith' },
      { platform: 'Twitter', url: 'https://twitter.com/johnsmith' }
    ],
  },
  {
    id: 'contact_2',
    name: 'Sarah Chen',
    email: 'sarah.chen@company.com',
    phone: '+1 (555) 234-5678',
    company: 'Your Company',
    role: 'Engineering Lead',
    tags: ['team', 'engineering', 'leadership', 'mentor'],
    lastContact: new Date(Date.now() - 3 * 60 * 60 * 1000),
    notes: 'Technical lead for backend services. Excellent problem solver. Mentors junior developers. Passionate about code quality and system architecture.',
    aiInsights: [
      'Consistently delivers high-quality work',
      'Strong collaborator across teams',
      'Advocates for technical excellence',
      'Values work-life balance and team culture'
    ],
    relationshipScore: 95,
    preferredContactMethod: 'chat',
    timezone: 'America/Los_Angeles',
  },
  {
    id: 'contact_3',
    name: 'Dr. Lisa Johnson',
    email: 'lisa.johnson@acmecorp.com',
    phone: '+1 (555) 345-6789',
    company: 'Acme Corporation',
    role: 'Chief Technology Officer',
    tags: ['client', 'executive', 'technical', 'strategic-partner'],
    lastContact: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    notes: 'CTO at Acme Corp. PhD in Computer Science. Deeply technical and strategic. Interested in AI/ML capabilities and scalability.',
    aiInsights: [
      'Values technical depth in conversations',
      'Interested in partnership expansion',
      'Influential in tech community',
      'Speaks at major conferences'
    ],
    relationshipScore: 88,
    preferredContactMethod: 'video',
    timezone: 'America/New_York',
    socialProfiles: [
      { platform: 'LinkedIn', url: 'https://linkedin.com/in/drlisajohnson' },
    ],
  },
];

export const mockVoiceNotesEnhanced: VoiceNote[] = [
  {
    id: 'voice_1',
    title: 'Product Ideas from Client Call',
    duration: 180,
    recordedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    transcription: 'Client mentioned they really need better automation for their workflow. Specifically mentioned the need for conditional logic in our automation builder. Also interested in Slack integration for real-time notifications. Should schedule follow-up to discuss technical requirements.',
    aiSummary: 'Client feedback on automation features: conditional logic needed, Slack integration requested. Follow-up meeting required.',
    actionItems: [
      'Schedule technical requirements call',
      'Create spec for conditional logic in automation builder',
      'Evaluate Slack API integration options'
    ],
    tags: ['client-feedback', 'product-ideas', 'automation', 'integration'],
    sentiment: 'positive',
  },
  {
    id: 'voice_2',
    title: 'Team Brainstorming - Marketing Campaign',
    duration: 420,
    recordedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    transcription: 'Team brainstorming session for Q4 marketing campaign. Key themes: thought leadership, case studies, and video content. Sarah suggested partnering with industry influencers. Mike proposed a webinar series. Budget approved for $50K. Timeline: launch mid-November.',
    aiSummary: 'Marketing campaign brainstorm: thought leadership focus, influencer partnerships, webinar series. Budget $50K, launch mid-November.',
    actionItems: [
      'Contact potential influencer partners',
      'Draft webinar topics and schedule',
      'Create content calendar',
      'Assign roles and responsibilities'
    ],
    tags: ['brainstorming', 'marketing', 'campaign', 'team'],
    sentiment: 'positive',
  },
];
