import { Task, Meeting, Email, ContextMemory, Workflow, ProductivityInsight } from '@/providers/AIAssistantProvider';

export { mockTasksEnhanced, mockMeetingsEnhanced, mockEmailsEnhanced, mockProjectsEnhanced, mockGoalsEnhanced, mockDocumentsEnhanced, mockContactsEnhanced, mockVoiceNotesEnhanced } from './mockAIDataEnhanced';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Review Q4 Marketing Strategy',
    description: 'Analyze performance metrics and prepare recommendations for next quarter',
    priority: 'high',
    status: 'in-progress',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '2 hours',
    energyLevel: 'high',
    aiGenerated: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    tags: ['marketing', 'strategy', 'quarterly'],
    assignedTo: 'you',
  },
  {
    id: '2',
    title: 'Prepare Client Presentation',
    description: 'Create slides for the upcoming client meeting on Friday',
    priority: 'high',
    status: 'pending',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '3 hours',
    energyLevel: 'high',
    aiGenerated: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    tags: ['presentation', 'client', 'urgent'],
    assignedTo: 'you',
  },
  {
    id: '3',
    title: 'Update Project Documentation',
    description: 'Document recent changes to the API and update README files',
    priority: 'medium',
    status: 'pending',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '1.5 hours',
    energyLevel: 'medium',
    aiGenerated: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    tags: ['documentation', 'development'],
    assignedTo: 'you',
  },
  {
    id: '4',
    title: 'Schedule Team Building Event',
    description: 'Coordinate with team members to find a suitable date and venue',
    priority: 'low',
    status: 'pending',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '1 hour',
    energyLevel: 'low',
    aiGenerated: true,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    tags: ['team', 'event', 'planning'],
    assignedTo: 'you',
  },
  {
    id: '5',
    title: 'Review Code Pull Requests',
    description: 'Review and approve pending PRs from the development team',
    priority: 'medium',
    status: 'in-progress',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '2 hours',
    energyLevel: 'medium',
    aiGenerated: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    tags: ['development', 'code-review'],
    assignedTo: 'you',
  },
  {
    id: '6',
    title: 'Respond to Customer Feedback',
    description: 'Address recent customer feedback and implement improvements',
    priority: 'high',
    status: 'pending',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '2.5 hours',
    energyLevel: 'high',
    aiGenerated: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    tags: ['customer-service', 'feedback'],
    assignedTo: 'you',
  },
  {
    id: '7',
    title: 'Prepare Monthly Report',
    description: 'Compile data and insights for the monthly performance report',
    priority: 'medium',
    status: 'pending',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '3 hours',
    energyLevel: 'medium',
    aiGenerated: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    tags: ['reporting', 'analytics'],
    assignedTo: 'you',
  },
  {
    id: '8',
    title: 'Update Website Content',
    description: 'Refresh homepage content and update product descriptions',
    priority: 'low',
    status: 'pending',
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '2 hours',
    energyLevel: 'low',
    aiGenerated: false,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    tags: ['website', 'content'],
    assignedTo: 'you',
  },
  {
    id: '9',
    title: 'Conduct User Research',
    description: 'Interview users to gather insights for product improvements',
    priority: 'high',
    status: 'pending',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '4 hours',
    energyLevel: 'high',
    aiGenerated: true,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    tags: ['research', 'user-experience'],
    assignedTo: 'you',
  },
  {
    id: '10',
    title: 'Optimize Database Queries',
    description: 'Identify and optimize slow database queries for better performance',
    priority: 'medium',
    status: 'completed',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedTime: '2 hours',
    energyLevel: 'medium',
    aiGenerated: false,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    tags: ['development', 'performance'],
    assignedTo: 'you',
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: '1',
    title: 'Weekly Team Standup',
    description: 'Discuss progress, blockers, and upcoming tasks',
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 2.5 * 60 * 60 * 1000).toISOString(),
    attendees: ['john@company.com', 'sarah@company.com', 'mike@company.com'],
    location: 'Conference Room A',
    type: 'in-person',
    aiScheduled: false,
    preparationNeeded: false,
    status: 'scheduled',
  },
  {
    id: '2',
    title: 'Client Strategy Session',
    description: 'Review Q4 strategy and discuss next steps with the client',
    startTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 25 * 60 * 60 * 1000).toISOString(),
    attendees: ['client@acmecorp.com', 'manager@company.com'],
    meetingLink: 'https://zoom.us/j/123456789',
    type: 'video',
    aiScheduled: true,
    preparationNeeded: true,
    status: 'scheduled',
    notes: 'Prepare slides on Q4 performance metrics',
  },
  {
    id: '3',
    title: 'Product Roadmap Planning',
    description: 'Plan features and priorities for the next quarter',
    startTime: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
    attendees: ['product@company.com', 'engineering@company.com', 'design@company.com'],
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    type: 'video',
    aiScheduled: true,
    preparationNeeded: true,
    status: 'scheduled',
  },
  {
    id: '4',
    title: '1-on-1 with Manager',
    description: 'Monthly check-in and career development discussion',
    startTime: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 72.5 * 60 * 60 * 1000).toISOString(),
    attendees: ['manager@company.com'],
    type: 'phone',
    aiScheduled: false,
    preparationNeeded: false,
    status: 'scheduled',
  },
  {
    id: '5',
    title: 'Design Review',
    description: 'Review new UI designs for the mobile app',
    startTime: new Date(Date.now() + 96 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 97 * 60 * 60 * 1000).toISOString(),
    attendees: ['design@company.com', 'product@company.com', 'frontend@company.com'],
    meetingLink: 'https://zoom.us/j/987654321',
    type: 'video',
    aiScheduled: true,
    preparationNeeded: false,
    status: 'scheduled',
  },
  {
    id: '6',
    title: 'Sprint Retrospective',
    description: 'Reflect on the past sprint and identify improvements',
    startTime: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    attendees: ['team@company.com'],
    location: 'Conference Room B',
    type: 'in-person',
    aiScheduled: false,
    preparationNeeded: false,
    status: 'completed',
    notes: 'Action items: improve code review process, update documentation',
  },
];

export const mockEmails: Email[] = [
  {
    id: '1',
    from: 'client@acmecorp.com',
    to: ['you@company.com'],
    subject: 'Q4 Strategy Review - Follow Up',
    body: 'Hi,\n\nThank you for the productive meeting yesterday. I wanted to follow up on the action items we discussed. Could you send over the updated timeline by end of week?\n\nBest regards,\nJohn Smith\nAcme Corp',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: false,
    aiDrafted: false,
    priority: 'high',
    category: 'work',
  },
  {
    id: '2',
    from: 'you@company.com',
    to: ['client@acmecorp.com'],
    subject: 'Re: Q4 Strategy Review - Follow Up',
    body: 'Hi John,\n\nThank you for your email. I\'ll have the updated timeline ready by Thursday afternoon. I\'ve also included some additional insights from our analytics team that might be helpful.\n\nLooking forward to our next meeting.\n\nBest regards,\nYour Name',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    read: true,
    aiDrafted: true,
    priority: 'high',
    category: 'work',
  },
  {
    id: '3',
    from: 'hr@company.com',
    to: ['you@company.com', 'team@company.com'],
    subject: 'Team Building Event - Save the Date',
    body: 'Hello Team,\n\nWe\'re excited to announce our upcoming team building event on March 15th. More details to follow soon. Please mark your calendars!\n\nBest,\nHR Team',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    read: true,
    aiDrafted: false,
    priority: 'low',
    category: 'work',
  },
  {
    id: '4',
    from: 'newsletter@techinsights.com',
    to: ['you@company.com'],
    subject: 'Weekly Tech Insights - AI Trends 2024',
    body: 'This week\'s top stories:\n\n1. AI in Enterprise: Latest Trends\n2. Cloud Computing Innovations\n3. Cybersecurity Best Practices\n\nRead more...',
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000),
    read: false,
    aiDrafted: false,
    priority: 'low',
    category: 'promotional',
  },
  {
    id: '5',
    from: 'manager@company.com',
    to: ['you@company.com'],
    subject: '1-on-1 Meeting Agenda',
    body: 'Hi,\n\nLooking forward to our 1-on-1 this week. I\'d like to discuss:\n\n1. Your current projects and progress\n2. Career development goals\n3. Any challenges or support needed\n\nFeel free to add any topics you\'d like to cover.\n\nBest,\nManager',
    timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000),
    read: true,
    aiDrafted: false,
    priority: 'medium',
    category: 'work',
  },
  {
    id: '6',
    from: 'support@vendor.com',
    to: ['you@company.com'],
    subject: 'Your Subscription Renewal',
    body: 'Dear Customer,\n\nYour annual subscription is due for renewal next month. Click here to review your plan and renew.\n\nThank you for being a valued customer.\n\nBest regards,\nVendor Support',
    timestamp: new Date(Date.now() - 96 * 60 * 60 * 1000),
    read: false,
    aiDrafted: false,
    priority: 'medium',
    category: 'promotional',
  },
  {
    id: '7',
    from: 'friend@personal.com',
    to: ['you@company.com'],
    subject: 'Catch up soon?',
    body: 'Hey! It\'s been a while. Want to grab coffee this weekend?\n\nLet me know!\n\nCheers,\nAlex',
    timestamp: new Date(Date.now() - 120 * 60 * 60 * 1000),
    read: true,
    aiDrafted: false,
    priority: 'low',
    category: 'personal',
  },
  {
    id: '8',
    from: 'you@company.com',
    to: ['team@company.com'],
    subject: 'Project Update - Week 12',
    body: 'Hi Team,\n\nHere\'s our weekly project update:\n\n✅ Completed: API integration, UI improvements\n🔄 In Progress: Testing, documentation\n📅 Next Week: Launch preparation\n\nGreat work everyone!\n\nBest,\nYour Name',
    timestamp: new Date(Date.now() - 144 * 60 * 60 * 1000),
    read: true,
    aiDrafted: true,
    priority: 'medium',
    category: 'work',
  },
];

export const mockMemories: ContextMemory[] = [
  {
    id: '1',
    type: 'preference',
    content: 'User prefers morning meetings between 9-11 AM',
    metadata: { category: 'scheduling', confidence: 0.95 },
    timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    importance: 0.9,
    tags: ['scheduling', 'preference', 'meetings'],
  },
  {
    id: '2',
    type: 'habit',
    content: 'User typically responds to emails within 2-3 hours during work hours',
    metadata: { category: 'communication', avgResponseTime: '2.5 hours' },
    timestamp: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    importance: 0.8,
    tags: ['email', 'habit', 'response-time'],
  },
  {
    id: '3',
    type: 'contact',
    content: 'John Smith from Acme Corp - primary client contact, prefers detailed updates',
    metadata: { email: 'john@acmecorp.com', role: 'client', communicationStyle: 'detailed' },
    timestamp: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    importance: 0.95,
    tags: ['contact', 'client', 'communication'],
  },
  {
    id: '4',
    type: 'preference',
    content: 'User prefers video calls over phone calls for client meetings',
    metadata: { category: 'meetings', preference: 'video' },
    timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    importance: 0.7,
    tags: ['meetings', 'preference', 'video'],
  },
  {
    id: '5',
    type: 'habit',
    content: 'User is most productive during morning hours (9 AM - 12 PM)',
    metadata: { category: 'productivity', peakHours: '9-12' },
    timestamp: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    importance: 0.85,
    tags: ['productivity', 'habit', 'peak-hours'],
  },
  {
    id: '6',
    type: 'document',
    content: 'Q4 Strategy Document - contains key metrics and goals for the quarter',
    metadata: { type: 'strategy', quarter: 'Q4', year: 2024 },
    timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    importance: 0.9,
    tags: ['document', 'strategy', 'quarterly'],
  },
  {
    id: '7',
    type: 'conversation',
    content: 'Discussed project timeline extension with manager - approved 2-week extension',
    metadata: { topic: 'timeline', decision: 'approved', extension: '2 weeks' },
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    importance: 0.8,
    tags: ['conversation', 'project', 'timeline'],
  },
  {
    id: '8',
    type: 'preference',
    content: 'User prefers concise email responses, typically 3-4 sentences',
    metadata: { category: 'communication', style: 'concise' },
    timestamp: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000),
    importance: 0.75,
    tags: ['email', 'preference', 'writing-style'],
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: '1',
    name: 'Daily Morning Briefing',
    description: 'Automatically send a summary of today\'s tasks and meetings every morning at 8 AM',
    trigger: {
      type: 'time',
      config: { time: '08:00', timezone: 'America/New_York', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
    },
    actions: [
      { type: 'generate_summary', config: { include: ['tasks', 'meetings', 'emails'] } },
      { type: 'send_notification', config: { channel: 'email', priority: 'normal' } },
    ],
    enabled: true,
    lastRun: new Date(Date.now() - 24 * 60 * 60 * 1000),
    runCount: 45,
  },
  {
    id: '2',
    name: 'Auto-Respond to Low Priority Emails',
    description: 'Automatically draft responses to promotional and newsletter emails',
    trigger: {
      type: 'event',
      config: { event: 'email_received', filter: { category: ['promotional', 'social'] } },
    },
    actions: [
      { type: 'analyze_email', config: { extractIntent: true } },
      { type: 'draft_response', config: { tone: 'polite', length: 'short' } },
      { type: 'save_draft', config: { requireApproval: true } },
    ],
    enabled: true,
    lastRun: new Date(Date.now() - 3 * 60 * 60 * 1000),
    runCount: 128,
  },
  {
    id: '3',
    name: 'Meeting Preparation Reminder',
    description: 'Send a reminder 30 minutes before meetings that require preparation',
    trigger: {
      type: 'condition',
      config: { condition: 'meeting.preparationNeeded === true', checkInterval: '15m' },
    },
    actions: [
      { type: 'gather_context', config: { sources: ['emails', 'documents', 'previous_meetings'] } },
      { type: 'generate_briefing', config: { includeActionItems: true } },
      { type: 'send_notification', config: { channel: 'push', timing: '-30m' } },
    ],
    enabled: true,
    lastRun: new Date(Date.now() - 48 * 60 * 60 * 1000),
    runCount: 23,
  },
  {
    id: '4',
    name: 'Weekly Progress Report',
    description: 'Generate and send a weekly progress report every Friday at 4 PM',
    trigger: {
      type: 'time',
      config: { time: '16:00', timezone: 'America/New_York', days: ['Fri'] },
    },
    actions: [
      { type: 'analyze_week', config: { metrics: ['tasks_completed', 'meetings_attended', 'emails_sent'] } },
      { type: 'generate_report', config: { format: 'summary', includeInsights: true } },
      { type: 'send_email', config: { to: 'manager@company.com', subject: 'Weekly Progress Report' } },
    ],
    enabled: true,
    lastRun: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    runCount: 12,
  },
  {
    id: '5',
    name: 'Task Priority Optimizer',
    description: 'Automatically re-prioritize tasks based on deadlines and dependencies',
    trigger: {
      type: 'event',
      config: { event: 'task_created', immediate: true },
    },
    actions: [
      { type: 'analyze_task', config: { checkDependencies: true, estimateEffort: true } },
      { type: 'calculate_priority', config: { factors: ['deadline', 'importance', 'dependencies'] } },
      { type: 'update_task', config: { fields: ['priority', 'suggestedTime'] } },
    ],
    enabled: true,
    lastRun: new Date(Date.now() - 6 * 60 * 60 * 1000),
    runCount: 67,
  },
];

export const mockInsights: ProductivityInsight[] = [
  {
    id: '1',
    type: 'peak-hours',
    title: 'Peak Productivity Hours',
    value: '9:00 AM - 11:30 AM',
    description: 'You\'re most productive during morning hours. Your task completion rate is 45% higher during this time compared to afternoon.',
    trend: 'stable',
    recommendation: 'Schedule your most important and challenging tasks during these peak hours. Avoid scheduling meetings during this time when possible.',
  },
  {
    id: '2',
    type: 'task-completion',
    title: 'Task Completion Rate',
    value: '87%',
    description: 'Great job! You\'re completing most tasks on time. Your completion rate has improved by 12% over the past month.',
    trend: 'up',
    recommendation: 'Continue using time-blocking techniques. Consider breaking down larger tasks into smaller, manageable pieces.',
  },
  {
    id: '3',
    type: 'meeting-load',
    title: 'Meeting Load',
    value: '12 hours/week',
    description: 'You spend about 30% of your work week in meetings. This is slightly above the recommended 25% for optimal productivity.',
    trend: 'up',
    recommendation: 'Try to batch meetings on specific days (e.g., Tuesday and Thursday) to create longer blocks of focus time on other days.',
  },
  {
    id: '4',
    type: 'response-time',
    title: 'Email Response Time',
    value: 'Average: 2.3 hours',
    description: 'Your email response time has improved by 35% this week. You\'re responding faster while maintaining quality.',
    trend: 'up',
    recommendation: 'Set specific times for checking emails (e.g., 10 AM, 2 PM, 4 PM) to maintain this improvement without constant interruptions.',
  },
  {
    id: '5',
    type: 'focus-time',
    title: 'Deep Focus Time',
    value: '18 hours/week',
    description: 'You\'re getting good blocks of uninterrupted focus time. This represents 45% of your work week, which is excellent for deep work.',
    trend: 'stable',
    recommendation: 'Protect these focus blocks by declining non-essential meetings and using "Do Not Disturb" mode during these times.',
  },
];

export const mockBusinessGoals = [
  {
    id: '1',
    title: 'Increase Revenue by 25%',
    description: 'Achieve 25% revenue growth by end of Q4',
    progress: 68,
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    keyMetrics: ['Monthly Recurring Revenue', 'Customer Acquisition', 'Conversion Rate'],
  },
  {
    id: '2',
    title: 'Launch New Product Line',
    description: 'Successfully launch and market new product offerings',
    progress: 45,
    deadline: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
    keyMetrics: ['Product Development', 'Marketing Campaign', 'Pre-orders'],
  },
  {
    id: '3',
    title: 'Improve Customer Satisfaction',
    description: 'Increase NPS score from 45 to 65',
    progress: 72,
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    keyMetrics: ['NPS Score', 'Support Response Time', 'Customer Retention'],
  },
];

export const mockProjects = [
  {
    id: '1',
    name: 'Mobile App Redesign',
    status: 'in-progress',
    progress: 65,
    team: ['Design', 'Engineering', 'Product'],
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'high',
  },
  {
    id: '2',
    name: 'API v2 Migration',
    status: 'in-progress',
    progress: 40,
    team: ['Engineering', 'DevOps'],
    deadline: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'medium',
  },
  {
    id: '3',
    name: 'Customer Portal Enhancement',
    status: 'planning',
    progress: 15,
    team: ['Product', 'Engineering', 'Customer Success'],
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'medium',
  },
];

export const mockCorrespondencePatterns = {
  emailStyle: {
    tone: 'professional-friendly',
    avgLength: '3-4 sentences',
    commonPhrases: [
      'Thank you for reaching out',
      'I appreciate your patience',
      'Looking forward to',
      'Please let me know if you need anything else',
    ],
    signatureStyle: 'Best regards',
  },
  responsePatterns: {
    clientEmails: {
      avgResponseTime: '2 hours',
      preferredTime: 'morning',
      detailLevel: 'detailed',
    },
    internalEmails: {
      avgResponseTime: '1 hour',
      preferredTime: 'any',
      detailLevel: 'concise',
    },
    newsletters: {
      action: 'archive',
      readRate: '15%',
    },
  },
  meetingPreferences: {
    acceptanceRate: {
      'client-meetings': 95,
      'internal-meetings': 75,
      'social-events': 60,
    },
    preferredDuration: {
      '1-on-1': '30 minutes',
      'team-meetings': '45 minutes',
      'client-calls': '60 minutes',
    },
    preferredTime: 'morning',
    bufferTime: '15 minutes',
  },
};
