import type {
  CallTranscript,
  Deal,
  Integration,
  NegotiationCall,
  NegotiationAppointment,
  NegotiationContact,
  NegotiationNotification,
  NegotiationTemplate,
  PhoneNumber,
} from '@/types/negotiation';

export const mockAnalyticsData = {
  revenue: {
    current: 5300000,
    change: 30.2,
    chartData: [
      { month: 'Jan', value: 3200000 },
      { month: 'Feb', value: 3600000 },
      { month: 'Mar', value: 4100000 },
      { month: 'Apr', value: 4600000 },
      { month: 'May', value: 5000000 },
      { month: 'Jun', value: 5300000 },
    ],
  },
  deals: {
    current: 342,
    change: 26.2,
    chartData: [
      { month: 'Jan', value: 210 },
      { month: 'Feb', value: 235 },
      { month: 'Mar', value: 260 },
      { month: 'Apr', value: 290 },
      { month: 'May', value: 315 },
      { month: 'Jun', value: 342 },
    ],
  },
  winRate: {
    current: 70,
    change: 7.7,
    chartData: [
      { month: 'Jan', value: 58 },
      { month: 'Feb', value: 60 },
      { month: 'Mar', value: 63 },
      { month: 'Apr', value: 66 },
      { month: 'May', value: 68 },
      { month: 'Jun', value: 70 },
    ],
  },
  conversionFunnel: [
    { stage: 'Leads', count: 1200, conversion: 100 },
    { stage: 'Qualified', count: 780, conversion: 65 },
    { stage: 'Negotiations', count: 420, conversion: 35 },
    { stage: 'Closed Won', count: 294, conversion: 24.5 },
  ],
  callVolume: {
    byHour: [
      { hour: '9 AM', calls: 18 },
      { hour: '10 AM', calls: 32 },
      { hour: '11 AM', calls: 40 },
      { hour: '12 PM', calls: 28 },
      { hour: '1 PM', calls: 22 },
      { hour: '2 PM', calls: 34 },
      { hour: '3 PM', calls: 46 },
      { hour: '4 PM', calls: 30 },
    ],
  },
  topPerformers: [
    { name: 'Ava Chen', deals: 48, revenue: 930000, winRate: 76 },
    { name: 'Noah Patel', deals: 41, revenue: 810000, winRate: 72 },
    { name: 'Mia Johnson', deals: 36, revenue: 745000, winRate: 69 },
  ],
} as const;

export const mockNegotiationAppointments: NegotiationAppointment[] = [
  {
    id: 'apt_1',
    title: 'Discovery Call',
    customerName: 'Acme Corp',
    customerPhone: '+1 (555) 010-1001',
    date: new Date().toISOString().split('T')[0],
    time: '10:00 AM',
    duration: '30 min',
    type: 'phone',
    status: 'scheduled',
    dealValue: 4200,
    notes: 'Focus on pricing & onboarding timeline.',
    reminders: true,
  },
  {
    id: 'apt_2',
    title: 'Product Demo',
    customerName: 'StartUp Inc',
    customerPhone: '+1 (555) 010-1002',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    time: '2:30 PM',
    duration: '45 min',
    type: 'video',
    status: 'scheduled',
    dealValue: 1150,
    notes: 'Show analytics dashboard + integrations.',
    reminders: true,
  },
  {
    id: 'apt_3',
    title: 'Negotiation Follow-up',
    customerName: 'Global Ltd',
    customerPhone: '+1 (555) 010-1003',
    date: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    time: '11:15 AM',
    duration: '30 min',
    type: 'in-person',
    status: 'rescheduled',
    dealValue: 8500,
    notes: 'Bring revised proposal and discount options.',
    reminders: false,
  },
] ;

export const mockCallerInsights = [
  {
    id: 'insight_1',
    customerName: 'John Smith',
    customerCompany: 'Acme Corp',
    sentiment: 'positive',
    totalCalls: 12,
    totalDeals: 5,
    winRate: 75,
    avgDealValue: 45000,
    keywords: ['pricing', 'demo', 'timeline'],
    talkRatio: { agent: 45, customer: 55 },
    satisfaction: 4.2,
    summary: 'Interested in enterprise plan, wants demo next week',
    duration: 420,
    timestamp: new Date().toISOString(),
    demographics: {
      industry: 'Technology',
      companySize: '500-1000',
      location: 'San Francisco, CA',
    },
    preferredTime: '10:00 AM - 2:00 PM',
    behaviorPattern: 'Responds well to technical details and ROI data',
    lastContact: new Date().toISOString(),
  },
  {
    id: 'insight_2',
    customerName: 'Sarah Johnson',
    customerCompany: 'TechStart Inc',
    sentiment: 'neutral',
    totalCalls: 8,
    totalDeals: 2,
    winRate: 50,
    avgDealValue: 12000,
    keywords: ['features', 'integration', 'support'],
    talkRatio: { agent: 60, customer: 40 },
    satisfaction: 3.5,
    summary: 'Asking about API capabilities and SLAs',
    duration: 315,
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    demographics: {
      industry: 'Software',
      companySize: '50-200',
      location: 'Austin, TX',
    },
    preferredTime: '2:00 PM - 5:00 PM',
    behaviorPattern: 'Needs detailed documentation before making decisions',
    lastContact: new Date(Date.now() - 86400000).toISOString(),
  },
] as const;

export const mockNegotiationCalls: NegotiationCall[] = [
  {
    id: 'call_1',
    customerName: 'John Smith',
    customerCompany: 'Acme Corp',
    customerPhone: '+1 (555) 010-1001',
    status: 'active',
    startTime: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    duration: '07:00',
    dealValue: 50000,
    outcome: 'ongoing',
    priority: 'high',
    assignedTo: 'Ava Chen',
    notes: 'Strong interest, follow up with pricing',
    tags: ['hot-lead', 'enterprise'],
  },
  {
    id: 'call_2',
    customerName: 'Sarah Johnson',
    customerCompany: 'TechStart Inc',
    customerPhone: '+1 (555) 010-1002',
    status: 'completed',
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    duration: '03:00',
    dealValue: 12000,
    outcome: 'ongoing',
    priority: 'medium',
    assignedTo: 'Noah Patel',
    notes: 'Needs technical documentation',
    tags: ['api-question', 'startup'],
  },
];

export const mockNegotiationContacts: NegotiationContact[] = [
  {
    id: 'contact_1',
    name: 'John Smith',
    company: 'Acme Corp',
    email: 'john.smith@acmecorp.com',
    phone: '+1 (555) 010-1001',
    role: 'CTO',
    status: 'prospect',
    dealValue: 50000,
    dealStage: 'negotiation',
    lastContact: new Date().toISOString(),
    tags: ['decision-maker', 'enterprise'],
  },
  {
    id: 'contact_2',
    name: 'Sarah Johnson',
    company: 'TechStart Inc',
    email: 'sarah.j@techstart.io',
    phone: '+1 (555) 010-1002',
    role: 'Engineering Manager',
    status: 'prospect',
    dealValue: 12000,
    dealStage: 'proposal',
    lastContact: new Date(Date.now() - 86400000).toISOString(),
    tags: ['technical', 'startup'],
  },
] ;

export const mockDeals: Deal[] = [
  {
    id: 'deal_1',
    title: 'Acme Corp Enterprise',
    customerName: 'John Smith',
    customerCompany: 'Acme Corp',
    value: 50000,
    stage: 'negotiation',
    probability: 70,
    expectedCloseDate: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
    owner: 'Ava Chen',
    product: 'Enterprise Plan',
    notes: 'Strong champion, procurement reviewing',
    lastActivity: new Date().toISOString(),
  },
  {
    id: 'deal_2',
    title: 'TechStart API Plan',
    customerName: 'Sarah Johnson',
    customerCompany: 'TechStart Inc',
    value: 12000,
    stage: 'proposal',
    probability: 50,
    expectedCloseDate: new Date(Date.now() + 60 * 86400000).toISOString().split('T')[0],
    owner: 'Noah Patel',
    product: 'API Plan',
    notes: 'Evaluating API limits and pricing',
    lastActivity: new Date(Date.now() - 3600000).toISOString(),
  },
] ;

export const mockIntegrations: Integration[] = [
  {
    id: 'int_1',
    name: 'Salesforce',
    description: 'Sync contacts, accounts, and deals to keep negotiation context up to date.',
    icon: 'database',
    isConnected: true,
    category: 'crm',
    lastSync: new Date().toISOString(),
  },
  {
    id: 'int_2',
    name: 'HubSpot',
    description: 'Pull CRM timelines and deal stages to tailor outreach and follow-ups.',
    icon: 'database',
    isConnected: false,
    category: 'crm',
  },
  {
    id: 'int_3',
    name: 'Slack',
    description: 'Send deal updates, alerts, and approvals to the right channels automatically.',
    icon: 'message-square',
    isConnected: true,
    category: 'communication',
    lastSync: new Date(Date.now() - 3600000).toISOString(),
  },
] ;

export const mockNegotiationNotifications: NegotiationNotification[] = [
  {
    id: 'notif_1',
    title: 'High-priority deal needs approval',
    message: 'Acme Corp requested a 12% discount. Review and approve the counter-offer.',
    type: 'deal',
    priority: 'high',
    timestamp: new Date().toISOString(),
    isRead: false,
    actionUrl: '/ai-negotiation/deals',
  },
  {
    id: 'notif_2',
    title: 'Upcoming appointment',
    message: 'Discovery call with StartUp Inc starts in 30 minutes.',
    type: 'appointment',
    priority: 'medium',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    isRead: false,
    actionUrl: '/ai-negotiation/appointments',
  },
  {
    id: 'notif_3',
    title: 'Missed call follow-up',
    message: 'You missed a call from Sarah Johnson. Tap to call back.',
    type: 'call',
    priority: 'low',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    isRead: true,
    actionUrl: '/ai-negotiation/calls',
  },
] ;

export const mockPhoneNumbers: PhoneNumber[] = [
  {
    id: 'num_1',
    number: '+1 (555) 010-2001',
    label: 'Sales - Main',
    type: 'local',
    isActive: true,
    callsHandled: 1240,
    successRate: 0.74,
    assignedAgents: ['Ava Chen', 'Noah Patel'],
  },
  {
    id: 'num_2',
    number: '+1 (555) 010-2002',
    label: 'Sales - Toll Free',
    type: 'toll-free',
    isActive: true,
    callsHandled: 860,
    successRate: 0.69,
    assignedAgents: ['Mia Johnson'],
  },
  {
    id: 'num_3',
    number: '+44 20 7946 0100',
    label: 'UK - Enterprise',
    type: 'international',
    isActive: false,
    callsHandled: 120,
    successRate: 0.58,
    assignedAgents: ['Noah Patel'],
  },
] ;

export const mockNegotiationTemplates: NegotiationTemplate[] = [
  {
    id: 'tmpl_1',
    title: 'Pricing Follow-up (Email)',
    type: 'email',
    content: 'Hi {{customerName}}, thanks for your time today. Based on what we discussed, the best fit is {{product}} at {{price}}/mo. Would you like me to send a proposal?',
    category: 'follow-up',
    variables: ['customerName', 'product', 'price'],
    successRate: 62,
    timesUsed: 128,
  },
];

export const mockCallTranscripts: CallTranscript[] = [
  {
    id: 'tx_1',
    callId: 'call_1',
    customerName: 'John Smith',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    duration: '07:00',
    transcript: 'Customer asked about enterprise pricing and onboarding timeline. Discussed ROI and next steps.',
    summary: 'Customer is interested in enterprise plan; requested a proposal and implementation timeline.',
    sentiment: 'positive',
    keyPoints: ['Interested in enterprise plan', 'Asked for timeline', 'Wants proposal'],
    actionItems: ['Send proposal', 'Schedule demo with stakeholders'],
  },
];

export const mockReceptionistAppointments: NegotiationAppointment[] = [];
