const fs=require('fs'),p=require('path');
const d=p.join(__dirname,'..','app','ai-agent','marketing','sub-agents');
const S=`const styles=StyleSheet.create({container:{flex:1},hero:{alignItems:'center',paddingVertical:36,paddingHorizontal:20,borderBottomWidth:1,borderBottomColor:'#E5E5EA'},heroIconWrap:{width:100,height:100,borderRadius:50,justifyContent:'center',alignItems:'center',marginBottom:16},heroTitle:{fontSize:22,fontWeight:'bold',textAlign:'center'},heroSubtitle:{fontSize:15,marginTop:6,fontWeight:'500'},badgesRow:{flexDirection:'row',gap:10,marginTop:16,flexWrap:'wrap',justifyContent:'center'},badge:{flexDirection:'row',alignItems:'center',paddingHorizontal:12,paddingVertical:6,borderRadius:20,gap:5},badgeText:{fontSize:12,fontWeight:'600'},statsContainer:{flexDirection:'row',flexWrap:'wrap',padding:16,gap:12},statCard:{flex:1,minWidth:'22%',alignItems:'center',padding:14,borderRadius:12},statValue:{fontSize:14,fontWeight:'bold',marginTop:8},statLabel:{fontSize:11,marginTop:4,textAlign:'center'},section:{marginHorizontal:16,marginBottom:16,padding:20,borderRadius:16},sectionTitle:{fontSize:18,fontWeight:'700',marginBottom:14},description:{fontSize:14,lineHeight:22},tagsContainer:{flexDirection:'row',flexWrap:'wrap',gap:8},tag:{paddingHorizontal:12,paddingVertical:6,borderRadius:20},tagText:{fontSize:12,fontWeight:'600'},responsibilityRow:{flexDirection:'row',alignItems:'center',marginBottom:10,gap:8},responsibilityText:{fontSize:14,flex:1,lineHeight:20},endpointRow:{flexDirection:'row',alignItems:'center',marginBottom:8,gap:8},endpointText:{fontSize:13,fontFamily:'monospace'},parentCard:{flexDirection:'row',alignItems:'center',padding:16,borderRadius:12,gap:12},parentInfo:{flex:1},parentName:{fontSize:16,fontWeight:'600'},parentDesc:{fontSize:12,marginTop:2},quickActionsGrid:{flexDirection:'row',flexWrap:'wrap',gap:12},quickActionButton:{flex:1,minWidth:'45%',alignItems:'center',padding:14,borderRadius:12},quickActionText:{fontSize:12,fontWeight:'600',marginTop:6}});`;

const agents=[
{id:'marketing-strategy-analyst',name:'AI Marketing Strategy Analyst',parent:'AI Chief Marketing Officer',parentId:'cmo',color:'#C62828',icon:'TrendingUp',caps:['Market Analysis','Strategic Planning','Competitive Intelligence','Trend Forecasting','SWOT Analysis','Market Segmentation'],eps:['/consult/marketing-strategy-analyst','/marketing-strategy-analyst/execute','/marketing-strategy-analyst/analyze'],overview:'Provides deep market analysis, competitive intelligence, and strategic planning. Identifies market opportunities, forecasts trends, and delivers actionable insights shaping marketing strategy.',resps:['Conduct comprehensive market and competitor analysis','Identify emerging trends and market opportunities','Develop strategic marketing recommendations','Perform SWOT analysis for marketing initiatives','Segment markets for targeted campaign planning','Forecast market shifts and competitive threats','Align strategy insights with CMO objectives','Deliver weekly strategic intelligence briefings'],acts:[{t:'5 min ago',tx:'Completed Q3 market opportunity analysis',ic:'TrendingUp'},{t:'30 min ago',tx:'Identified 3 emerging competitor threats',ic:'Target'},{t:'1 hour ago',tx:'Delivered SWOT analysis for new product line',ic:'Zap'},{t:'3 hours ago',tx:'Updated market segmentation model',ic:'Activity'}],qas:[{l:'Market Scan',ic:'TrendingUp'},{l:'Competitor Report',ic:'Target'},{l:'SWOT Analysis',ic:'Zap'},{l:'Strategy Brief',ic:'Activity'}]},
{id:'budget-allocator',name:'AI Budget Allocator',parent:'AI Chief Marketing Officer',parentId:'cmo',color:'#C62828',icon:'DollarSign',caps:['Budget Distribution','Spend Optimization','ROI Forecasting','Channel Allocation','Cost Analysis','Financial Planning'],eps:['/consult/budget-allocator','/budget-allocator/execute','/budget-allocator/analyze'],overview:'Optimizes marketing budget distribution across channels, campaigns, and teams. Uses ROI forecasting and historical performance to maximize impact of every marketing dollar.',resps:['Allocate marketing budget across channels and campaigns','Optimize spend based on ROI forecasts','Monitor budget utilization and variance','Rebalance allocations based on performance data','Generate budget reports for CMO review','Forecast quarterly and annual budget needs','Identify cost-saving opportunities','Ensure budget compliance with organizational targets'],acts:[{t:'2 min ago',tx:'Rebalanced $2.4M across 12 channels',ic:'DollarSign'},{t:'20 min ago',tx:'Forecasted Q4 budget requirements',ic:'TrendingUp'},{t:'1 hour ago',tx:'Identified 15% cost-saving opportunity',ic:'Zap'},{t:'2 hours ago',tx:'Generated monthly budget variance report',ic:'Activity'}],qas:[{l:'Allocate Budget',ic:'DollarSign'},{l:'ROI Forecast',ic:'TrendingUp'},{l:'Variance Report',ic:'Zap'},{l:'Cost Analysis',ic:'Activity'}]},
{id:'campaign-roi-evaluator',name:'AI Campaign ROI Evaluator',parent:'AI Chief Marketing Officer',parentId:'cmo',color:'#C62828',icon:'ChartBarBig',caps:['ROI Analysis','Campaign Performance','Attribution Modeling','Revenue Tracking','Cost-per-Acquisition','LTV Analysis'],eps:['/consult/campaign-roi-evaluator','/campaign-roi-evaluator/execute','/campaign-roi-evaluator/analyze'],overview:'Measures and evaluates ROI for every marketing campaign. Provides attribution modeling, tracks revenue impact, and delivers insights to optimize future campaign spending.',resps:['Evaluate campaign ROI across all channels','Build and maintain attribution models','Track revenue impact per campaign','Calculate cost-per-acquisition metrics','Analyze customer lifetime value by campaign','Compare actual vs projected ROI','Generate campaign performance dashboards','Recommend budget adjustments based on ROI data'],acts:[{t:'3 min ago',tx:'Completed ROI analysis for 8 active campaigns',ic:'ChartBarBig'},{t:'15 min ago',tx:'Updated multi-touch attribution model',ic:'Target'},{t:'1 hour ago',tx:'Identified top 3 campaigns by LTV',ic:'TrendingUp'},{t:'4 hours ago',tx:'Generated monthly ROI dashboard',ic:'Activity'}],qas:[{l:'ROI Report',ic:'ChartBarBig'},{l:'Attribution Model',ic:'Target'},{l:'LTV Analysis',ic:'TrendingUp'},{l:'CPA Tracker',ic:'Activity'}]}
];

agents.forEach(a=>{
const fn=a.icon;
fs.writeFileSync(p.join(d,`${a.id}.tsx`),`import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { useTheme } from '@/providers/ThemeProvider';
import { Activity, ${fn}, Clock, Target, Zap, ArrowRight, Briefcase, TrendingUp, DollarSign, ChartBarBig } from 'lucide-react-native';
import AgentFeatures from '@/components/ai-agent/AgentFeatures';
import { useRouter } from 'expo-router';

export default function ${a.id.split('-').map(w=>w[0].toUpperCase()+w.slice(1)).join('')}Page() {
  const { theme } = useTheme();
  const router = useRouter();
  const stats = [
    {label:'Status',value:'Active',icon:Activity,color:'#34C759'},
    {label:'Level',value:'Specialist',icon:Briefcase,color:'${a.color}'},
    {label:'Efficiency',value:'20x',icon:Target,color:'#FF9500'},
    {label:'Parent',value:'${a.parentId}',icon:${fn},color:'#007AFF'}
  ];
  const capabilities = ${JSON.stringify(a.caps)};
  const responsibilities = ${JSON.stringify(a.resps)};
  const activities = ${JSON.stringify(a.acts).replace(/"ic":/g,'icon:').replace(/"tx":/g,'text:').replace(/"t":/g,'time:')};
  const endpoints = ${JSON.stringify(a.eps)};
  const quickActions = ${JSON.stringify(a.qas).replace(/"ic":/g,'icon:').replace(/"l":/g,'label:')};
  return (
    <ScrollView style={[styles.container,{backgroundColor:theme.colors.background}]}>
      <View style={[styles.hero,{backgroundColor:'${a.color}18'}]}>
        <View style={[styles.heroIconWrap,{backgroundColor:'${a.color}25'}]}><${fn} size={56} color="${a.color}"/></View>
        <Text style={[styles.heroTitle,{color:theme.colors.text}]}>${a.name}</Text>
        <Text style={[styles.heroSubtitle,{color:theme.colors.textSecondary}]}>Sub-Agent of ${a.parent}</Text>
        <View style={styles.badgesRow}>
          <View style={[styles.badge,{backgroundColor:'#34C75922'}]}><Activity size={12} color="#34C759"/><Text style={[styles.badgeText,{color:'#34C759'}]}>Active</Text></View>
          <View style={[styles.badge,{backgroundColor:'${a.color}22'}]}><Briefcase size={12} color="${a.color}"/><Text style={[styles.badgeText,{color:'${a.color}'}]}>Specialist</Text></View>
        </View>
      </View>
      <View style={styles.statsContainer}>{stats.map((s,i)=>(<View key={i} style={[styles.statCard,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><s.icon size={22} color={s.color}/><Text style={[styles.statValue,{color:theme.colors.text}]}>{s.value}</Text><Text style={[styles.statLabel,{color:theme.colors.textSecondary}]}>{s.label}</Text></View>))}</View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Overview</Text><Text style={[styles.description,{color:theme.colors.textSecondary}]}>${a.overview}</Text></View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Core Capabilities</Text><View style={styles.tagsContainer}>{capabilities.map((c,i)=>(<View key={i} style={[styles.tag,{backgroundColor:'${a.color}18'}]}><Text style={[styles.tagText,{color:'${a.color}'}]}>{c}</Text></View>))}</View></View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Key Responsibilities</Text>{responsibilities.map((r,i)=>(<View key={i} style={styles.responsibilityRow}><ArrowRight size={14} color="${a.color}"/><Text style={[styles.responsibilityText,{color:theme.colors.textSecondary}]}>{r}</Text></View>))}</View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>A2A Endpoints</Text>{endpoints.map((e,i)=>(<View key={i} style={styles.endpointRow}><Zap size={14} color="#8B5CF6"/><Text style={[styles.endpointText,{color:theme.colors.textSecondary}]}>{e}</Text></View>))}</View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Recent Activity</Text>{activities.map((a2,i)=>(<View key={i} style={{flexDirection:'row',alignItems:'center',marginBottom:12,gap:12}}><View style={{width:32,height:32,borderRadius:16,justifyContent:'center',alignItems:'center',backgroundColor:'${a.color}15'}}><a2.icon size={14} color="${a.color}"/></View><View style={{flex:1}}><Text style={{fontSize:14,fontWeight:'500',color:theme.colors.text}}>{a2.text}</Text><Text style={{fontSize:12,marginTop:2,color:theme.colors.textSecondary}}>{a2.time}</Text></View></View>))}</View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Quick Actions</Text><View style={styles.quickActionsGrid}>{quickActions.map((qa,i)=>(<TouchableOpacity key={i} style={[styles.quickActionButton,{backgroundColor:'${a.color}12'}]}><qa.icon size={22} color="${a.color}"/><Text style={[styles.quickActionText,{color:'${a.color}'}]}>{qa.label}</Text></TouchableOpacity>))}</View></View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Parent Agent</Text><TouchableOpacity onPress={()=>router.push('/ai-agent/marketing/${a.parentId}')} style={[styles.parentCard,{backgroundColor:theme.colors.background||'#F2F2F7'}]}><${fn} size={24} color="${a.color}"/><View style={styles.parentInfo}><Text style={[styles.parentName,{color:theme.colors.text}]}>${a.parent}</Text><Text style={[styles.parentDesc,{color:theme.colors.textSecondary}]}>Main Agent</Text></View><ArrowRight size={20} color={theme.colors.textSecondary}/></TouchableOpacity></View>
      <AgentFeatures agentId="${a.id}" agentName="${a.name}" />
      <View style={{height:40}}/>
    </ScrollView>
  );
}
${S}`);
console.log('Written: '+a.id+'.tsx');
});
console.log('CMO sub-agents done!');
