const fs=require('fs'),p=require('path');
const B='c:\\Users\\shaida\\Desktop\\kaytx-full-app\\app\\ai-agent';
const A=[
{id:'vp-product-strategy',f:'product',n:'AI VP Product Strategy',ic:'Target',c:'#6A1B9A',lv:'VP Level',sub:[{n:'AI Competitive Analyst',i:'Eye',r:'competitive-analyst'},{n:'AI Strategic Opportunity Scout',i:'Compass',r:'strategic-opportunity-scout'},{n:'AI Vision Communicator',i:'Megaphone',r:'vision-communicator'}],caps:'Product Strategy,Competitive Analysis,Strategic Opportunity Identification,Vision Communication,Market Positioning,Portfolio Strategy,Innovation Scouting,Executive Alignment'.split(','),resps:'Define and communicate product vision and strategic direction,Lead competitive analysis and market positioning initiatives,Identify and evaluate strategic opportunities for growth,Align product strategy with business objectives and executive goals,Drive innovation scouting and emerging technology assessment,Coordinate cross-functional strategic planning sessions,Present strategic recommendations to C-suite stakeholders,Monitor competitive landscape and adjust strategy accordingly'.split(','),acts:[{t:'2 min ago',x:'Completed competitive landscape analysis for Q3',i:'Eye'},{t:'15 min ago',x:'Identified 3 new strategic growth opportunities',i:'Compass'},{t:'1 hour ago',x:'Presented product vision to executive team',i:'Megaphone'},{t:'3 hours ago',x:'Updated strategic roadmap with market shifts',i:'Target'}],ep:['/consult/vp-product-strategy','/product-strategy/execute','/product-strategy/analyze']},
{id:'vp-product-operations',f:'product',n:'AI VP Product Operations',ic:'Settings',c:'#6A1B9A',lv:'VP Level',sub:[{n:'AI Process Standardizer',i:'ClipboardList',r:'process-standardizer'},{n:'AI Metric Tracker',i:'BarChart3',r:'metric-tracker'},{n:'AI Cross-functional Coordinator',i:'Users',r:'cross-functional-coordinator'}],caps:'Process Standardization,Metric Tracking,Cross-functional Coordination,Operational Excellence,Workflow Optimization,Quality Assurance,Resource Planning,Performance Monitoring'.split(','),resps:'Standardize product development processes across teams,Track and report on key product metrics and KPIs,Coordinate cross-functional teams for product delivery,Drive operational excellence and continuous improvement,Optimize workflows for maximum efficiency and throughput,Ensure quality standards across all product operations,Plan and allocate resources for product initiatives,Monitor performance dashboards and escalate issues'.split(','),acts:[{t:'5 min ago',x:'Standardized 12 product development processes',i:'ClipboardList'},{t:'20 min ago',x:'Updated product KPI dashboard for Q3',i:'BarChart3'},{t:'1 hour ago',x:'Coordinated sprint planning across 4 teams',i:'Users'},{t:'2 hours ago',x:'Resolved resource allocation conflict',i:'Settings'}],ep:['/consult/vp-product-operations','/product-ops/execute','/product-ops/analyze']},
{id:'ai-product-manager',f:'product',n:'AI Product Manager',ic:'LayoutDashboard',c:'#6A1B9A',lv:'Manager',sub:[{n:'AI Backlog Groomer',i:'ClipboardList',r:'backlog-groomer'},{n:'AI Sprint Planner',i:'Calendar',r:'sprint-planner'},{n:'AI Stakeholder Communicator',i:'MessageSquare',r:'stakeholder-communicator'}],caps:'Backlog Management,Sprint Planning,Stakeholder Communication,Feature Prioritization,Roadmap Execution,User Story Management,Release Coordination,Data-driven Decisions'.split(','),resps:'Groom and prioritize product backlog continuously,Plan and coordinate sprint cycles with engineering teams,Communicate product updates to all stakeholders,Prioritize features based on business value and effort,Execute product roadmap milestones on schedule,Manage user stories and acceptance criteria,Coordinate release schedules across dependent teams,Make data-driven product decisions using analytics'.split(','),acts:[{t:'3 min ago',x:'Groomed 25 backlog items for next sprint',i:'ClipboardList'},{t:'10 min ago',x:'Planned sprint 14 with engineering leads',i:'Calendar'},{t:'45 min ago',x:'Sent stakeholder update on v2.5 progress',i:'MessageSquare'},{t:'2 hours ago',x:'Prioritized 8 features using RICE framework',i:'Target'}],ep:['/consult/ai-product-manager','/product-mgr/execute','/product-mgr/analyze']},
{id:'ai-product-owner',f:'product',n:'AI Product Owner',ic:'Briefcase',c:'#6A1B9A',lv:'Owner',sub:[{n:'AI Story Writer',i:'FileText',r:'story-writer'},{n:'AI Acceptance Criteria Definer',i:'CheckCircle',r:'acceptance-criteria-definer'},{n:'AI Sprint Reviewer',i:'Users',r:'sprint-reviewer'}],caps:'Story Writing,Acceptance Criteria,Sprint Review,Product Vision,Requirement Management,Value Maximization,Team Collaboration,Definition of Done'.split(','),resps:'Write clear and actionable user stories for development teams,Define acceptance criteria for all product features,Conduct sprint reviews and gather stakeholder feedback,Maintain and communicate product vision to the team,Manage and prioritize product requirements effectively,Maximize value delivery through strategic prioritization,Collaborate with development teams on implementation details,Ensure definition of done is met for all deliverables'.split(','),acts:[{t:'4 min ago',x:'Wrote 12 user stories for payment module',i:'FileText'},{t:'18 min ago',x:'Defined acceptance criteria for 6 features',i:'CheckCircle'},{t:'1 hour ago',x:'Conducted sprint 13 review with team',i:'Users'},{t:'3 hours ago',x:'Updated product backlog priorities',i:'Target'}],ep:['/consult/ai-product-owner','/product-owner/execute','/product-owner/analyze']},
{id:'ai-product-manager-sub',f:'product',n:'AI Product Manager (Sub)',ic:'Layers',c:'#6A1B9A',lv:'Manager',sub:[{n:'AI Feature Spec Writer',i:'FileText',r:'feature-spec-writer'},{n:'AI User Story Mapper',i:'GitBranch',r:'user-story-mapper'},{n:'AI Priority Adjuster',i:'ArrowUpDown',r:'priority-adjuster'}],caps:'Feature Specification,User Story Mapping,Priority Adjustment,Requirement Analysis,Stakeholder Management,Sprint Coordination,Product Analytics,Market Alignment'.split(','),resps:'Write detailed feature specifications for engineering teams,Create and maintain user story maps for product epics,Adjust priorities based on market feedback and analytics,Analyze requirements and identify dependencies,Manage stakeholder expectations and communications,Coordinate sprint activities across product teams,Analyze product usage data to inform decisions,Ensure product alignment with market needs'.split(','),acts:[{t:'2 min ago',x:'Completed feature spec for AI dashboard',i:'FileText'},{t:'12 min ago',x:'Updated user story map for Q3 epic',i:'GitBranch'},{t:'30 min ago',x:'Adjusted priority of 5 features based on feedback',i:'ArrowUpDown'},{t:'2 hours ago',x:'Analyzed product usage data for v2.4',i:'BarChart3'}],ep:['/consult/ai-product-manager-sub','/product-mgr-sub/execute','/product-mgr-sub/analyze']},
{id:'ai-product-analyst',f:'product',n:'AI Product Analyst',ic:'Search',c:'#6A1B9A',lv:'Specialist',sub:[{n:'AI Market Researcher',i:'Search',r:'market-researcher'},{n:'AI Feature Usage Tracker',i:'BarChart3',r:'feature-usage-tracker'},{n:'AI Feedback Aggregator',i:'MessageSquare',r:'feedback-aggregator'}],caps:'Market Research,Feature Usage Tracking,Feedback Aggregation,Data Analysis,Competitive Intelligence,User Behavior Analysis,A/B Testing,Product Intelligence'.split(','),resps:'Conduct market research and trend analysis for product decisions,Track feature usage patterns and adoption metrics,Aggregate and analyze user feedback from multiple channels,Perform data analysis to identify product improvement opportunities,Monitor competitive intelligence and market shifts,Analyze user behavior patterns for optimization insights,Design and analyze A/B tests for feature validation,Generate product intelligence reports for stakeholders'.split(','),acts:[{t:'3 min ago',x:'Completed market research for new vertical',i:'Search'},{t:'15 min ago',x:'Tracked feature usage for 8 product areas',i:'BarChart3'},{t:'1 hour ago',x:'Aggregated feedback from 5 user channels',i:'MessageSquare'},{t:'3 hours ago',x:'Analyzed A/B test results for onboarding flow',i:'FlaskConical'}],ep:['/consult/ai-product-analyst','/product-analyst/execute','/product-analyst/analyze']},
{id:'ai-ux-researcher',f:'product',n:'AI UX Researcher',ic:'PenTool',c:'#6A1B9A',lv:'Specialist',sub:[{n:'AI Interview Scheduler',i:'Calendar',r:'interview-scheduler'},{n:'AI Usability Test Designer',i:'PenTool',r:'usability-test-designer'},{n:'AI Insight Synthesizer',i:'Lightbulb',r:'insight-synthesizer'}],caps:'UX Research,Interview Scheduling,Usability Testing,Insight Synthesis,User Personas,Journey Mapping,Heuristic Evaluation,Accessibility Review'.split(','),resps:'Design and conduct UX research studies and interviews,Schedule and coordinate user research interviews,Design usability tests and analyze test results,Synthesize research insights into actionable recommendations,Create and maintain user personas based on research data,Map user journeys to identify pain points and opportunities,Conduct heuristic evaluations of product interfaces,Review and ensure accessibility compliance across products'.split(','),acts:[{t:'5 min ago',x:'Completed 5 user interviews for onboarding',i:'Calendar'},{t:'20 min ago',x:'Designed usability test for checkout flow',i:'PenTool'},{t:'1 hour ago',x:'Synthesized insights from 12 user sessions',i:'Lightbulb'},{t:'3 hours ago',x:'Updated user personas with new research data',i:'Users'}],ep:['/consult/ai-ux-researcher','/ux-research/execute','/ux-research/analyze']},
{id:'ai-product-marketer',f:'product',n:'AI Product Marketer',ic:'Megaphone',c:'#6A1B9A',lv:'Specialist',sub:[{n:'AI Launch Planner',i:'Rocket',r:'launch-planner'},{n:'AI Messaging Crafter',i:'PenTool',r:'messaging-crafter'},{n:'AI Competitive Differentiator',i:'Target',r:'competitive-differentiator'}],caps:'Launch Planning,Messaging Strategy,Competitive Differentiation,Go-to-Market,Product Positioning,Sales Enablement,Market Communication,Brand Alignment'.split(','),resps:'Plan and execute product launch campaigns and strategies,Craft compelling messaging for target audiences,Differentiate product positioning against competitors,Develop and execute go-to-market strategies,Position products effectively in target markets,Enable sales teams with product marketing materials,Communicate product value propositions to market segments,Ensure brand alignment across all product communications'.split(','),acts:[{t:'4 min ago',x:'Launched v3.0 marketing campaign',i:'Rocket'},{t:'15 min ago',x:'Crafted messaging for enterprise segment',i:'PenTool'},{t:'1 hour ago',x:'Analyzed competitive differentiation matrix',i:'Target'},{t:'3 hours ago',x:'Updated sales enablement materials',i:'Megaphone'}],ep:['/consult/ai-product-marketer','/product-marketing/execute','/product-marketing/analyze']},
{id:'ai-release-manager',f:'product',n:'AI Release Manager',ic:'Rocket',c:'#6A1B9A',lv:'Manager',sub:[{n:'AI Release Coordinator',i:'GitBranch',r:'release-coordinator'},{n:'AI Rollback Planner',i:'RotateCcw',r:'rollback-planner'},{n:'AI Change Communicator',i:'MessageSquare',r:'change-communicator'}],caps:'Release Coordination,Rollback Planning,Change Communication,Version Management,Deployment Strategy,Risk Assessment,Release Automation,Compliance Tracking'.split(','),resps:'Coordinate release schedules across all product teams,Plan rollback strategies for failed deployments,Communicate changes to all affected stakeholders,Manage version control and release artifacts,Develop and execute deployment strategies,Assess risks associated with each release,Automate release pipelines for efficiency,Track compliance requirements for each release'.split(','),acts:[{t:'1 min ago',x:'Coordinated v2.5.1 hotfix release',i:'GitBranch'},{t:'10 min ago',x:'Planned rollback strategy for v3.0',i:'RotateCcw'},{t:'30 min ago',x:'Communicated breaking changes to partners',i:'MessageSquare'},{t:'2 hours ago',x:'Automated release pipeline for mobile apps',i:'Zap'}],ep:['/consult/ai-release-manager','/release-mgr/execute','/release-mgr/analyze']},
{id:'ai-ciso',f:'security',n:'AI Chief Information Security Officer',ic:'Shield',c:'#581C84',lv:'C-Suite',sub:[{n:'AI Security Strategy Advisor',i:'Shield',r:'security-strategy-advisor'},{n:'AI Risk Appetite Definer',i:'Gauge',r:'risk-appetite-definer'},{n:'AI Board Reporter',i:'FileBarChart',r:'board-reporter'}],caps:'Security Strategy,Risk Appetite Definition,Board Reporting,Threat Intelligence,Governance,Compliance,Incident Response,Cyber Risk Management'.split(','),resps:'Define enterprise-wide security strategy and direction,Establish organizational risk appetite and tolerance levels,Report security posture and risks to the board of directors,Lead threat intelligence and vulnerability management,Develop and enforce security governance frameworks,Ensure compliance with security regulations and standards,Oversee incident response and crisis management,Manage enterprise cyber risk assessment and mitigation'.split(','),acts:[{t:'2 min ago',x:'Approved new zero-trust architecture',i:'Shield'},{t:'15 min ago',x:'Reviewed quarterly risk appetite assessment',i:'Gauge'},{t:'1 hour ago',x:'Prepared board security report for Q3',i:'FileBarChart'},{t:'3 hours ago',x:'Briefed executive team on threat landscape',i:'Zap'}],ep:['/consult/ai-ciso','/ciso/execute','/ciso/analyze','/ciso/board-report']}
];
const icons=new Set(['Target','Settings','LayoutDashboard','Briefcase','Layers','Search','PenTool','Megaphone','Rocket','Shield','Activity','Star','Users','CircleCheckBig','Clock','ArrowRight','Zap','Eye','Compass','ClipboardList','BarChart3','Calendar','MessageSquare','FileText','CheckCircle','GitBranch','ArrowUpDown','FlaskConical','Lightbulb','RotateCcw','Gauge','FileBarChart','Package']);
A.forEach(a=>{
const fp=p.join(B,a.f,a.id+'.tsx');
const impI=[...new Set([a.ic,...a.acts.map(x=>x.i),...a.sub.map(s=>s.i),...icons])].filter(x=>x).join(', ');
const tpl=`import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { useTheme } from '@/providers/ThemeProvider';
import { ${impI} } from 'lucide-react-native';
import AgentFeatures from '@/components/ai-agent/AgentFeatures';
import { useRouter } from 'expo-router';

export default function AgentPage() {
  const { theme } = useTheme();
  const router = useRouter();
  const stats = [
    { label: 'Tasks', value: '${Math.floor(Math.random()*5000+1000).toLocaleString()}', icon: CircleCheckBig, color: '#34C759' },
    { label: 'Uptime', value: '99.9%', icon: Activity, color: '#007AFF' },
    { label: 'Response', value: '${(Math.random()*2+0.5).toFixed(1)}s', icon: Clock, color: '#FF9500' },
    { label: 'Accuracy', value: '${(Math.random()*3+96).toFixed(1)}%', icon: Target, color: '${a.c}' },
  ];
  const capabilities = ${JSON.stringify(a.caps)};
  const responsibilities = ${JSON.stringify(a.resps)};
  const activities = ${JSON.stringify(a.acts)};
  const subAgents = ${JSON.stringify(a.sub.map(s=>({name:s.n,icon:s.i,route:`/ai-agent/${a.f}/sub-agents/${s.r}`,desc:s.d||''})))};
  return (
    <ScrollView style={[styles.container, { backgroundColor: theme.colors.background }]}>
      <View style={[styles.hero, { borderBottomColor: theme.colors.border || '#E5E5EA' }]}>
        <View style={[styles.heroIconWrap, { backgroundColor: '${a.c}20' }]}><${a.ic} size={48} color="${a.c}" /></View>
        <Text style={[styles.heroTitle, { color: theme.colors.text }]}>${a.n}</Text>
        <Text style={[styles.heroSubtitle, { color: theme.colors.textSecondary }]}>${a.dept||'Product Management Department'}</Text>
        <View style={styles.badgesRow}>
          <View style={[styles.badge, { backgroundColor: '#34C75922' }]}><Activity size={12} color="#34C759" /><Text style={[styles.badgeText, { color: '#34C759' }]}>Active</Text></View>
          <View style={[styles.badge, { backgroundColor: '${a.c}22' }]}><Star size={12} color="${a.c}" /><Text style={[styles.badgeText, { color: '${a.c}' }]}>${a.lv}</Text></View>
          <View style={[styles.badge, { backgroundColor: '#FF950022' }]}><Users size={12} color="#FF9500" /><Text style={[styles.badgeText, { color: '#FF9500' }]}>{subAgents.length} Sub-Agents</Text></View>
        </View>
      </View>
      <View style={styles.statsContainer}>{stats.map((stat,i)=>(<View key={i} style={[styles.statCard,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><stat.icon size={22} color={stat.color}/><Text style={[styles.statValue,{color:theme.colors.text}]}>{stat.value}</Text><Text style={[styles.statLabel,{color:theme.colors.textSecondary}]}>{stat.label}</Text></View>))}</View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Overview</Text><Text style={[styles.description,{color:theme.colors.textSecondary}]}>The ${a.n} leads enterprise-level operations, overseeing ${subAgents.length} specialized sub-agents for comprehensive coverage and maximum efficiency.</Text></View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Capabilities</Text><View style={styles.tagsContainer}>{capabilities.map((cap,i)=>(<View key={i} style={[styles.tag,{backgroundColor:'${a.c}18'}]}><Text style={[styles.tagText,{color:'${a.c}'}]}>{cap}</Text></View>))}</View></View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Key Responsibilities</Text>{responsibilities.map((item,i)=>(<View key={i} style={styles.responsibilityRow}><ArrowRight size={14} color="${a.c}"/><Text style={[styles.responsibilityText,{color:theme.colors.textSecondary}]}>{item}</Text></View>))}</View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>A2A Endpoints</Text>{${JSON.stringify(a.ep)}.map((ep,i)=>(<View key={i} style={styles.endpointRow}><Zap size={14} color="${a.c}"/><Text style={[styles.endpointText,{color:theme.colors.textSecondary}]}>{ep}</Text></View>))}</View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Sub-Agents</Text>{subAgents.map((sub,i)=>(<TouchableOpacity key={i} onPress={()=>router.push(sub.route as any)} style={[styles.subAgentCard,{backgroundColor:theme.colors.background||'#F2F2F7',marginTop:i>0?8:0}]}><Package size={24} color="${a.c}"/><View style={styles.subAgentInfo}><Text style={[styles.subAgentName,{color:theme.colors.text}]}>{sub.name}</Text><Text style={[styles.subAgentDesc,{color:theme.colors.textSecondary}]}>{sub.desc}</Text></View><ArrowRight size={20} color={theme.colors.textSecondary}/></TouchableOpacity>))}</View>
      <View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Recent Activity</Text>{activities.map((act,i)=>(<View key={i} style={styles.activityRow}><View style={[styles.activityIcon,{backgroundColor:'${a.c}15'}]}><Package size={14} color="${a.c}"/></View><View style={styles.activityContent}><Text style={[styles.activityText,{color:theme.colors.text}]}>{act.text}</Text><Text style={[styles.activityTime,{color:theme.colors.textSecondary}]}>{act.time}</Text></View></View>))}</View>
      <AgentFeatures agentId="${a.id}" agentName="${a.n}"/>
      <View style={{height:40}}/>
    </ScrollView>
  );
}

const styles = StyleSheet.create({container:{flex:1},hero:{alignItems:'center',paddingVertical:32,paddingHorizontal:20,borderBottomWidth:1},heroIconWrap:{width:88,height:88,borderRadius:44,justifyContent:'center',alignItems:'center',marginBottom:16},heroTitle:{fontSize:26,fontWeight:'bold'},heroSubtitle:{fontSize:15,marginTop:4,fontWeight:'500'},badgesRow:{flexDirection:'row',gap:10,marginTop:16},badge:{flexDirection:'row',alignItems:'center',paddingHorizontal:10,paddingVertical:5,borderRadius:20,gap:4},badgeText:{fontSize:12,fontWeight:'600'},statsContainer:{flexDirection:'row',flexWrap:'wrap',padding:16,gap:12},statCard:{flex:1,minWidth:'22%',alignItems:'center',padding:14,borderRadius:12},statValue:{fontSize:18,fontWeight:'bold',marginTop:8},statLabel:{fontSize:11,marginTop:4},section:{marginHorizontal:16,marginBottom:16,padding:20,borderRadius:16},sectionTitle:{fontSize:18,fontWeight:'700',marginBottom:14},description:{fontSize:14,lineHeight:22},tagsContainer:{flexDirection:'row',flexWrap:'wrap',gap:8},tag:{paddingHorizontal:12,paddingVertical:6,borderRadius:20},tagText:{fontSize:12,fontWeight:'600'},responsibilityRow:{flexDirection:'row',alignItems:'center',marginBottom:10,gap:8},responsibilityText:{fontSize:14,flex:1,lineHeight:20},endpointRow:{flexDirection:'row',alignItems:'center',marginBottom:8,gap:8},endpointText:{fontSize:13,fontFamily:'monospace'},subAgentCard:{flexDirection:'row',alignItems:'center',padding:16,borderRadius:12,gap:12},subAgentInfo:{flex:1},subAgentName:{fontSize:16,fontWeight:'600'},subAgentDesc:{fontSize:12,marginTop:2},activityRow:{flexDirection:'row',alignItems:'center',marginBottom:12,gap:12},activityIcon:{width:32,height:32,borderRadius:16,justifyContent:'center',alignItems:'center'},activityContent:{flex:1},activityText:{fontSize:14,fontWeight:'500'},activityTime:{fontSize:12,marginTop:2}});
`;
fs.writeFileSync(fp,tpl);
console.log('Created:',fp);
});
