const fs=require('fs'),p=require('path'),B='c:\\Users\\shaida\\Desktop\\kaytx-full-app\\app\\ai-agent';
const SS=`container:{flex:1},hero:{alignItems:'center',paddingVertical:32,paddingHorizontal:20,borderBottomWidth:1},heroIconWrap:{width:88,height:88,borderRadius:44,justifyContent:'center',alignItems:'center',marginBottom:16},heroTitle:{fontSize:26,fontWeight:'bold'},heroSubtitle:{fontSize:15,marginTop:4,fontWeight:'500'},badgesRow:{flexDirection:'row',gap:10,marginTop:16},badge:{flexDirection:'row',alignItems:'center',paddingHorizontal:10,paddingVertical:5,borderRadius:20,gap:4},badgeText:{fontSize:12,fontWeight:'600'},statsContainer:{flexDirection:'row',flexWrap:'wrap',padding:16,gap:12},statCard:{flex:1,minWidth:'22%',alignItems:'center',padding:14,borderRadius:12},statValue:{fontSize:18,fontWeight:'bold',marginTop:8},statLabel:{fontSize:11,marginTop:4},section:{marginHorizontal:16,marginBottom:16,padding:20,borderRadius:16},sectionTitle:{fontSize:18,fontWeight:'700',marginBottom:14},description:{fontSize:14,lineHeight:22},tagsContainer:{flexDirection:'row',flexWrap:'wrap',gap:8},tag:{paddingHorizontal:12,paddingVertical:6,borderRadius:20},tagText:{fontSize:12,fontWeight:'600'},responsibilityRow:{flexDirection:'row',alignItems:'center',marginBottom:10,gap:8},responsibilityText:{fontSize:14,flex:1,lineHeight:20},endpointRow:{flexDirection:'row',alignItems:'center',marginBottom:8,gap:8},endpointText:{fontSize:13,fontFamily:'monospace'},subAgentCard:{flexDirection:'row',alignItems:'center',padding:16,borderRadius:12,gap:12},subAgentInfo:{flex:1},subAgentName:{fontSize:16,fontWeight:'600'},subAgentDesc:{fontSize:12,marginTop:2},activityRow:{flexDirection:'row',alignItems:'center',marginBottom:12,gap:12},activityIcon:{width:32,height:32,borderRadius:16,justifyContent:'center',alignItems:'center'},activityContent:{flex:1},activityText:{fontSize:14,fontWeight:'500'},activityTime:{fontSize:12,marginTop:2}`;
const D=JSON.parse(fs.readFileSync(p.join(__dirname,'gen9-data.json'),'utf8'));
D.forEach(a=>{
const c=a.c,caps=a.caps.map(x=>`'${x}'`).join(','),rsps=a.rsps.map(x=>`'${x}'`).join(','),acts=a.acts.map(x=>`{time:'${x.t}',text:'${x.x}'}`).join(','),eps=a.eps.map(x=>`'${x}'`).join(','),subs=a.subs.map(x=>`{name:'${x.n}',route:'${x.r}',desc:'${x.d}'}`).join(',');
const t=`import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { useTheme } from '@/providers/ThemeProvider';
import { ${a.ic}, Activity, Star, Users, CircleCheckBig, Clock, ArrowRight, Zap, Package${a.i2?', '+a.i2:''} } from 'lucide-react-native';
import AgentFeatures from '@/components/ai-agent/AgentFeatures';
import { useRouter } from 'expo-router';
export default function AgentPage(){const{theme}=useTheme();const router=useRouter();const stats=[{label:'${a.sl}',value:'${a.sv}',icon:CircleCheckBig,color:'#34C759'},{label:'Uptime',value:'99.9%',icon:Activity,color:'#007AFF'},{label:'Response',value:'${a.rt}',icon:Clock,color:'#FF9500'},{label:'Accuracy',value:'${a.acc}',icon:Package,color:'${c}'}];const capabilities=[${caps}];const responsibilities=[${rsps}];const activities=[${acts}];const subAgents=[${subs}];
return(<ScrollView style={[styles.container,{backgroundColor:theme.colors.background}]}><View style={[styles.hero,{borderBottomColor:theme.colors.border||'#E5E5EA'}]}><View style={[styles.heroIconWrap,{backgroundColor:'${c}20'}]}><${a.ic} size={48} color="${c}"/></View><Text style={[styles.heroTitle,{color:theme.colors.text}]}>${a.n}</Text><Text style={[styles.heroSubtitle,{color:theme.colors.textSecondary}]}>${a.dp}</Text><View style={styles.badgesRow}><View style={[styles.badge,{backgroundColor:'#34C75922'}]}><Activity size={12}color="#34C759"/><Text style={[styles.badgeText,{color:'#34C759'}]}>Active</Text></View><View style={[styles.badge,{backgroundColor:'${c}22'}]}><Star size={12}color="${c}"/><Text style={[styles.badgeText,{color:'${c}'}]}>${a.lv}</Text></View><View style={[styles.badge,{backgroundColor:'#FF950022'}]}><Users size={12}color="#FF9500"/><Text style={[styles.badgeText,{color:'#FF9500'}]}>{subAgents.length} Sub-Agents</Text></View></View></View>
<View style={styles.statsContainer}>{stats.map((s,i)=>(<View key={i}style={[styles.statCard,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><s.icon size={22}color={s.color}/><Text style={[styles.statValue,{color:theme.colors.text}]}>{s.value}</Text><Text style={[styles.statLabel,{color:theme.colors.textSecondary}]}>{s.label}</Text></View>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Overview</Text><Text style={[styles.description,{color:theme.colors.textSecondary}]}>${a.ov}</Text></View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Capabilities</Text><View style={styles.tagsContainer}>{capabilities.map((cap,i)=>(<View key={i}style={[styles.tag,{backgroundColor:'${c}18'}]}><Text style={[styles.tagText,{color:'${c}'}]}>{cap}</Text></View>))}</View></View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Key Responsibilities</Text>{responsibilities.map((r,i)=>(<View key={i}style={styles.responsibilityRow}><ArrowRight size={14}color="${c}"/><Text style={[styles.responsibilityText,{color:theme.colors.textSecondary}]}>{r}</Text></View>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>A2A Endpoints</Text>{[${eps}].map((e,i)=>(<View key={i}style={styles.endpointRow}><Zap size={14}color="${c}"/><Text style={[styles.endpointText,{color:theme.colors.textSecondary}]}>{e}</Text></View>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Sub-Agents</Text>{subAgents.map((sub,i)=>(<TouchableOpacity key={i}onPress={()=>router.push(sub.route as any)}style={[styles.subAgentCard,{backgroundColor:theme.colors.background||'#F2F2F7',marginTop:i>0?8:0}]}><Package size={24}color="${c}"/><View style={styles.subAgentInfo}><Text style={[styles.subAgentName,{color:theme.colors.text}]}>{sub.name}</Text><Text style={[styles.subAgentDesc,{color:theme.colors.textSecondary}]}>{sub.desc}</Text></View><ArrowRight size={20}color={theme.colors.textSecondary}/></TouchableOpacity>))}</View>
<View style={[styles.section,{backgroundColor:theme.colors.card||'#F2F2F7'}]}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Recent Activity</Text>{activities.map((a,i)=>(<View key={i}style={styles.activityRow}><View style={[styles.activityIcon,{backgroundColor:'${c}15'}]}><Package size={14}color="${c}"/></View><View style={styles.activityContent}><Text style={[styles.activityText,{color:theme.colors.text}]}>{a.text}</Text><Text style={[styles.activityTime,{color:theme.colors.textSecondary}]}>{a.time}</Text></View></View>))}</View>
<AgentFeatures agentId="${a.id}" agentName="${a.n}"/><View style={{height:40}}/></ScrollView>);}
const styles=StyleSheet.create({${SS}});`;
fs.writeFileSync(p.join(B,a.f,a.id+'.tsx'),t);console.log('Created:',a.id);
});
