$base = "c:\Users\shaida\Desktop\kaytx-full-app\app\ai-agent\realestate\sub-agents"

$subAgents = @(
  @{ id="market-cycle-analyst"; name="AI Market Cycle Analyst"; parent="AI Chief Real Estate Officer"; parentRoute="/ai-agent/realestate/creo"; icon="TrendingUp"; stats="1,956"; resp="0.8s"; acc="97.9"; caps="Cycle Detection","Market Timing","Trend Forecasting","Leading Indicators","Historical Analysis","Scenario Planning"; resps="Real estate market cycle detection & analysis","Market timing & entry/exit strategy","Trend forecasting & projection modeling","Leading economic indicator monitoring","Historical cycle pattern analysis","Scenario planning & stress testing"; acts="Detected early expansion phase in office market","Updated 5-year cycle forecast model","Analyzed 30 years of historical cycle data" },
  @{ id="capital-deployment-planner"; name="AI Capital Deployment Planner"; parent="AI Chief Real Estate Officer"; parentRoute="/ai-agent/realestate/creo"; icon="Calculator"; stats="1,523"; resp="1.0s"; acc="98.7"; caps="Capital Allocation","Investment Planning","Fund Deployment","ROI Projection","Risk Assessment","Draw Scheduling"; resps="Capital allocation & deployment planning","Investment planning & prioritization","Fund deployment & draw scheduling","ROI projection & modeling","Capital risk assessment & mitigation","Draw schedule management & tracking"; acts="Planned $200M capital deployment for Q3","Scheduled 5 investment draws totaling $50M","Projected 18% ROI on new deployments" },
  @{ id="property-performance-monitor"; name="AI Property Performance Monitor"; parent="AI VP Property Management"; parentRoute="/ai-agent/realestate/vp-property-management"; icon="Activity"; stats="3,412"; resp="0.5s"; acc="99.1"; caps="Performance Tracking","KPI Monitoring","Variance Analysis","Benchmarking","Dashboard Reporting","Alert Management"; resps="Property performance tracking & monitoring","KPI monitoring & threshold alerting","Variance analysis & root cause identification","Performance benchmarking across portfolio","Dashboard reporting & visualization","Automated alert management & escalation"; acts="Monitored 200 properties performance metrics","Identified 8 properties below NOI targets","Generated monthly performance dashboard" },
  @{ id="noi-optimizer"; name="AI NOI Optimizer"; parent="AI VP Property Management"; parentRoute="/ai-agent/realestate/vp-property-management"; icon="TrendingUp"; stats="2,156"; resp="0.7s"; acc="98.3"; caps="Revenue Optimization","Expense Reduction","NOI Modeling","Rent Optimization","CAM Recovery","Operating Efficiency"; resps="Net operating income optimization & modeling","Revenue enhancement strategy identification","Expense reduction opportunity analysis","Rent optimization & market adjustment","CAM recovery maximization","Operating efficiency improvement programs"; acts="Increased portfolio NOI by 12% YoY","Identified $2M in expense reduction opportunities","Optimized rent schedules for 50 units" },
  @{ id="tenant-retention-strategist"; name="AI Tenant Retention Strategist"; parent="AI VP Property Management"; parentRoute="/ai-agent/realestate/vp-property-management"; icon="Heart"; stats="1,847"; resp="0.9s"; acc="97.5"; caps="Retention Strategy","Churn Prediction","Renewal Negotiation","Satisfaction Analysis","Loyalty Programs","Engagement Tracking"; resps="Tenant retention strategy development","Churn prediction & early warning systems","Lease renewal negotiation & incentives","Tenant satisfaction analysis & improvement","Loyalty program design & management","Tenant engagement tracking & reporting"; acts="Improved retention rate from 78% to 91%","Predicted 15 at-risk tenants for outreach","Designed loyalty program for top 20 tenants" },
  @{ id="development-pipeline-manager"; name="AI Development Pipeline Manager"; parent="AI VP Real Estate Development"; parentRoute="/ai-agent/realestate/vp-real-estate-development"; icon="GitBranch"; stats="1,289"; resp="1.1s"; acc="97.8"; caps="Pipeline Management","Stage Gate Tracking","Resource Allocation","Priority Ranking","Pipeline Analytics","Deal Flow"; resps="Development pipeline management & tracking","Stage gate process management","Resource allocation & optimization","Project priority ranking & scheduling","Pipeline analytics & reporting","Deal flow management & tracking"; acts="Managed pipeline of 15 development projects","Advanced 3 projects through stage gate review","Allocated resources across $800M pipeline" },
  @{ id="feasibility-analyst"; name="AI Feasibility Analyst"; parent="AI VP Real Estate Development"; parentRoute="/ai-agent/realestate/vp-real-estate-development"; icon="ChartBarBig"; stats="987"; resp="1.3s"; acc="96.9"; caps="Feasibility Studies","Financial Modeling","Site Analysis","Regulatory Review","Risk Assessment","Go/No-Go Analysis"; resps="Development feasibility study execution","Financial modeling & pro forma development","Site analysis & due diligence","Regulatory & zoning review","Development risk assessment","Go/no-go recommendation & analysis"; acts="Completed feasibility study for $100M mixed-use","Analyzed zoning for 5 potential sites","Recommended go decision on 3 of 5 projects" },
  @{ id="permit-tracker"; name="AI Permit Tracker"; parent="AI VP Real Estate Development"; parentRoute="/ai-agent/realestate/vp-real-estate-development"; icon="FileCheck"; stats="2,341"; resp="0.4s"; acc="99.4"; caps="Permit Tracking","Application Management","Compliance Monitoring","Timeline Tracking","Agency Liaison","Document Management"; resps="Permit application management & tracking","Compliance monitoring & requirement tracking","Timeline tracking & milestone management","Regulatory agency liaison & communication","Document management & submission tracking","Permit renewal & expiration management"; acts="Tracked 45 active permit applications","Obtained 8 permits ahead of schedule","Managed 12 agency communications this week" },
  @{ id="rent-collector"; name="AI Rent Collector"; parent="AI Property Manager"; parentRoute="/ai-agent/realestate/property-manager"; icon="DollarSign"; stats="4,567"; resp="0.2s"; acc="99.8"; caps="Rent Collection","Payment Processing","Delinquency Tracking","Late Fee Management","Payment Plans","Collections Reporting"; resps="Rent collection & payment processing","Delinquency tracking & follow-up","Late fee calculation & management","Payment plan administration","Collections reporting & analytics","Automated payment reminders & notifications"; acts="Collected $2.5M in rent this month","Reduced delinquency rate from 5% to 2%","Set up 8 payment plans for struggling tenants" },
  @{ id="maintenance-dispatcher"; name="AI Maintenance Dispatcher"; parent="AI Property Manager"; parentRoute="/ai-agent/realestate/property-manager"; icon="Radio"; stats="3,891"; resp="0.3s"; acc="98.9"; caps="Work Dispatch","Technician Assignment","Emergency Response","SLA Management","Priority Routing","Status Tracking"; resps="Maintenance work order dispatch","Technician assignment & scheduling","Emergency maintenance response coordination","SLA management & compliance tracking","Priority-based work order routing","Real-time status tracking & updates"; acts="Dispatched 120 work orders today","Achieved 95% SLA compliance rate","Resolved 3 emergency calls within 30 minutes" },
  @{ id="lease-enforcer"; name="AI Lease Enforcer"; parent="AI Property Manager"; parentRoute="/ai-agent/realestate/property-manager"; icon="Shield"; stats="1,678"; resp="0.6s"; acc="99.2"; caps="Lease Compliance","Violation Tracking","Enforcement Actions","Cure Notices","Default Management","Policy Enforcement"; resps="Lease compliance monitoring & enforcement","Violation tracking & documentation","Enforcement action management","Cure notice preparation & delivery","Default management & resolution","Policy enforcement & consistency"; acts="Identified 12 lease violations this week","Issued 8 cure notices for non-compliance","Resolved 5 default situations through negotiation" },
  @{ id="vacancy-minimizer"; name="AI Vacancy Minimizer"; parent="AI Leasing Manager"; parentRoute="/ai-agent/realestate/leasing-manager"; icon="TrendingDown"; stats="2,045"; resp="0.8s"; acc="98.1"; caps="Vacancy Reduction","Downtime Minimization","Marketing Acceleration","Tenant Matching","Incentive Optimization","Turnover Analysis"; resps="Vacancy reduction strategy execution","Downtime minimization between tenants","Marketing acceleration for vacant units","Tenant matching & qualification","Incentive optimization for quick lease-up","Turnover analysis & prevention"; acts="Reduced average vacancy from 45 to 18 days","Filled 25 vacant units this quarter","Analyzed turnover patterns across 8 properties" },
  @{ id="lease-negotiator"; name="AI Lease Negotiator"; parent="AI Leasing Manager"; parentRoute="/ai-agent/realestate/leasing-manager"; icon="Handshake"; stats="1,567"; resp="1.0s"; acc="97.6"; caps="Lease Negotiation","Term Optimization","Concession Management","Renewal Negotiation","Counter-Offer Analysis","Deal Structuring"; resps="Lease negotiation & deal structuring","Term optimization & rent escalation","Concession management & analysis","Lease renewal negotiation & strategy","Counter-offer analysis & response","Deal structuring & documentation"; acts="Negotiated 15 new leases this month","Achieved 3% above asking on 8 deals","Structured 5 renewal deals with favorable terms" },
  @{ id="tenant-qualifier"; name="AI Tenant Qualifier"; parent="AI Leasing Manager"; parentRoute="/ai-agent/realestate/leasing-manager"; icon="UserCheck"; stats="3,234"; resp="0.4s"; acc="99.0"; caps="Tenant Screening","Credit Analysis","Background Verification","Income Validation","Risk Scoring","Qualification Criteria"; resps="Tenant screening & qualification","Credit analysis & scoring","Background verification & reference checks","Income validation & employment verification","Risk scoring & assessment","Qualification criteria management"; acts="Screened 150 tenant applications this month","Approved 85% of applicants meeting criteria","Flagged 12 high-risk applications for review" },
  @{ id="building-systems-monitor"; name="AI Building Systems Monitor"; parent="AI Facilities Manager"; parentRoute="/ai-agent/realestate/facilities-manager"; icon="Cpu"; stats="5,678"; resp="0.1s"; acc="99.7"; caps="Systems Monitoring","HVAC Control","Electrical Monitoring","Plumbing Tracking","Fire Safety","IoT Integration"; resps="Building systems monitoring & control","HVAC system monitoring & optimization","Electrical system monitoring & load management","Plumbing system tracking & leak detection","Fire safety system monitoring & compliance","IoT sensor integration & data collection"; acts="Monitored 500+ building sensors in real-time","Detected HVAC anomaly 2 hours before failure","Maintained 99.9% building systems uptime" },
  @{ id="energy-manager"; name="AI Energy Manager"; parent="AI Facilities Manager"; parentRoute="/ai-agent/realestate/facilities-manager"; icon="Zap"; stats="2,345"; resp="0.5s"; acc="98.5"; caps="Energy Optimization","Consumption Tracking","Sustainability","Cost Reduction","Carbon Reporting","Green Certifications"; resps="Energy consumption tracking & optimization","Utility cost reduction & management","Sustainability program management","Carbon footprint reporting & reduction","Green building certification support","Energy efficiency improvement programs"; acts="Reduced energy costs by 15% across portfolio","Tracked consumption for 12 buildings","Prepared LEED certification documentation" },
  @{ id="space-optimizer"; name="AI Space Optimizer"; parent="AI Facilities Manager"; parentRoute="/ai-agent/realestate/facilities-manager"; icon="LayoutGrid"; stats="1,890"; resp="0.7s"; acc="97.8"; caps="Space Planning","Utilization Analysis","Floor Plan Optimization","Density Management","Common Area Planning","Space Allocation"; resps="Space planning & utilization optimization","Space utilization analysis & reporting","Floor plan optimization & redesign","Occupancy density management","Common area planning & management","Space allocation & reallocation"; acts="Optimized space utilization from 72% to 89%","Redesigned floor plans for 3 office buildings","Identified 15,000 sq ft of underutilized space" },
  @{ id="comparable-analyzer"; name="AI Comparable Analyzer"; parent="AI Property Analyst"; parentRoute="/ai-agent/realestate/property-analyst"; icon="BarChart3"; stats="2,456"; resp="0.6s"; acc="98.8"; caps="Comp Analysis","Market Comparison","Adjustment Modeling","Sales Tracking","Rent Comp Analysis","Regression Modeling"; resps="Comparable property analysis & selection","Market comparison & adjustment modeling","Comparable sales tracking & database management","Rent comparable analysis & benchmarking","Statistical regression modeling","Comp selection criteria & methodology"; acts="Analyzed 200 comparable sales this quarter","Built adjustment model for 5 submarkets","Updated comp database with 50 new transactions" },
  @{ id="value-estimator"; name="AI Value Estimator"; parent="AI Property Analyst"; parentRoute="/ai-agent/realestate/property-analyst"; icon="Calculator"; stats="1,789"; resp="0.9s"; acc="97.5"; caps="Property Valuation","Income Approach","Sales Comparison","Cost Approach","DCF Modeling","Value Forecasting"; resps="Property valuation & estimation","Income approach valuation & analysis","Sales comparison approach valuation","Cost approach valuation & depreciation","Discounted cash flow modeling","Property value forecasting & projection"; acts="Valued 30 properties totaling $500M","Built DCF models for 8 investment properties","Forecasted 5-year value appreciation trends" },
  @{ id="market-trend-reporter"; name="AI Market Trend Reporter"; parent="AI Property Analyst"; parentRoute="/ai-agent/realestate/property-analyst"; icon="LineChart"; stats="1,234"; resp="1.1s"; acc="96.8"; caps="Trend Analysis","Market Reporting","Data Visualization","Forecasting","Demographic Analysis","Supply/Demand"; resps="Market trend analysis & identification","Market reporting & publication","Data visualization & dashboard creation","Market forecasting & projection","Demographic analysis & impact assessment","Supply & demand analysis & balance reporting"; acts="Published monthly market trend report","Analyzed demographic shifts in 3 submarkets","Created interactive market dashboard" },
  @{ id="lease-abstractor"; name="AI Lease Abstractor"; parent="AI Lease Administrator"; parentRoute="/ai-agent/realestate/lease-administrator"; icon="FileText"; stats="4,123"; resp="0.3s"; acc="99.5"; caps="Lease Abstraction","Data Extraction","Key Term Summary","Clause Analysis","Database Management","Document Processing"; resps="Lease abstraction & data extraction","Key term summary & documentation","Clause analysis & categorization","Lease database management & maintenance","Document processing & OCR integration","Abstract quality assurance & verification"; acts="Abstracted 75 new leases this month","Extracted key terms from 200-page master lease","Maintained database of 1,500 lease abstracts" },
  @{ id="critical-date-tracker"; name="AI Critical Date Tracker"; parent="AI Lease Administrator"; parentRoute="/ai-agent/realestate/lease-administrator"; icon="Calendar"; stats="3,567"; resp="0.2s"; acc="99.6"; caps="Date Tracking","Expiration Management","Renewal Deadlines","Option Tracking","Automated Alerts","Timeline Management"; resps="Critical date tracking & management","Lease expiration management & notification","Renewal deadline tracking & alerts","Option exercise date tracking","Automated alert system & notifications","Timeline management & milestone tracking"; acts="Tracked 500 critical dates across portfolio","Sent 45 renewal notifications this month","Managed 30 option exercise deadlines" },
  @{ id="rent-escalation-calculator"; name="AI Rent Escalation Calculator"; parent="AI Lease Administrator"; parentRoute="/ai-agent/realestate/lease-administrator"; icon="Calculator"; stats="2,890"; resp="0.4s"; acc="99.3"; caps="Rent Escalation","CPI Adjustments","Fixed Increase","Percentage Rent","Step-Up Calculations","Escalation Modeling"; resps="Rent escalation calculation & management","CPI-based adjustment calculations","Fixed increase schedule management","Percentage rent calculation & reconciliation","Step-up rent calculation & tracking","Escalation modeling & projection"; acts="Calculated CPI adjustments for 200 leases","Projected 5-year rent escalation schedules","Reconciled percentage rent for 25 retail leases" },
  @{ id="issue-resolver"; name="AI Issue Resolver"; parent="AI Tenant Relations Specialist"; parentRoute="/ai-agent/realestate/tenant-relations"; icon="Wrench"; stats="5,234"; resp="0.3s"; acc="98.7"; caps="Issue Resolution","Ticket Management","Escalation Handling","Root Cause Analysis","Resolution Tracking","Prevention Planning"; resps="Tenant issue resolution & management","Ticket management & prioritization","Escalation handling & routing","Root cause analysis & prevention","Resolution tracking & follow-up","Issue prevention planning & programs"; acts="Resolved 150 tenant issues this week","Reduced average resolution time from 48h to 12h","Identified root cause for recurring HVAC complaints" },
  @{ id="communication-coordinator"; name="AI Communication Coordinator"; parent="AI Tenant Relations Specialist"; parentRoute="/ai-agent/realestate/tenant-relations"; icon="MessageSquare"; stats="3,456"; resp="0.5s"; acc="98.2"; caps="Communication Management","Notification Systems","Channel Coordination","Response Tracking","Broadcast Messaging","Feedback Collection"; resps="Tenant communication coordination & management","Notification system management","Multi-channel communication coordination","Response tracking & follow-up","Broadcast messaging & announcements","Tenant feedback collection & analysis"; acts="Coordinated 500 tenant communications this month","Managed 3 property-wide announcements","Collected feedback from 200 tenants on services" },
  @{ id="satisfaction-surveyor"; name="AI Satisfaction Surveyor"; parent="AI Tenant Relations Specialist"; parentRoute="/ai-agent/realestate/tenant-relations"; icon="ClipboardCheck"; stats="1,678"; resp="0.8s"; acc="97.4"; caps="Survey Design","Satisfaction Measurement","NPS Tracking","Sentiment Analysis","Action Planning","Benchmarking"; resps="Tenant satisfaction survey design & execution","Satisfaction measurement & scoring","Net Promoter Score tracking & analysis","Sentiment analysis & trend identification","Action planning based on survey results","Satisfaction benchmarking across portfolio"; acts="Achieved 85% survey response rate this quarter","Measured NPS improvement from 32 to 48","Designed targeted survey for 5 properties" },
  @{ id="work-order-prioritizer"; name="AI Work Order Prioritizer"; parent="AI Maintenance Coordinator"; parentRoute="/ai-agent/realestate/maintenance-coordinator"; icon="ListOrdered"; stats="4,567"; resp="0.2s"; acc="99.1"; caps="Priority Assessment","SLA Compliance","Urgency Classification","Resource Matching","Queue Management","Workload Balancing"; resps="Work order priority assessment & ranking","SLA compliance tracking & management","Urgency classification & routing","Resource matching & assignment optimization","Work order queue management","Technician workload balancing"; acts="Prioritized 300 work orders by urgency","Achieved 97% SLA compliance rate","Balanced workload across 12 technicians" },
  @{ id="vendor-dispatcher"; name="AI Vendor Dispatcher"; parent="AI Maintenance Coordinator"; parentRoute="/ai-agent/realestate/maintenance-coordinator"; icon="Truck"; stats="2,345"; resp="0.5s"; acc="98.6"; caps="Vendor Dispatch","Contractor Matching","Availability Tracking","Performance Rating","Cost Management","Scheduling"; resps="Vendor & contractor dispatch management","Contractor skill matching & selection","Vendor availability tracking & scheduling","Vendor performance rating & tracking","Cost management & quote comparison","Service scheduling & coordination"; acts="Dispatched 80 vendor calls this week","Maintained 95% vendor response rate","Compared quotes from 15 vendors for major project" },
  @{ id="cost-estimator"; name="AI Cost Estimator"; parent="AI Maintenance Coordinator"; parentRoute="/ai-agent/realestate/maintenance-coordinator"; icon="Coins"; stats="1,890"; resp="0.7s"; acc="97.9"; caps="Cost Estimation","Budget Forecasting","Quote Analysis","Material Pricing","Labor Costing","Variance Tracking"; resps="Maintenance cost estimation & quoting","Budget forecasting & planning","Quote analysis & comparison","Material pricing & tracking","Labor costing & rate management","Cost variance tracking & reporting"; acts="Estimated costs for 200 maintenance projects","Forecasted Q3 maintenance budget at $1.2M","Tracked 5% cost variance from estimates" },
  @{ id="deal-screener"; name="AI Deal Screener"; parent="AI Acquisition Analyst"; parentRoute="/ai-agent/realestate/acquisition-analyst"; icon="Filter"; stats="3,456"; resp="0.3s"; acc="99.2"; caps="Deal Screening","Criteria Matching","Quick Assessment","Pipeline Filtering","Market Scanning","Opportunity Identification"; resps="Acquisition deal screening & filtering","Investment criteria matching & scoring","Quick deal assessment & triage","Pipeline filtering & prioritization","Market scanning & opportunity identification","Deal flow management & tracking"; acts="Screened 50 acquisition opportunities this month","Advanced 8 deals to due diligence phase","Filtered out 42 deals not meeting criteria" },
  @{ id="due-diligence-coordinator"; name="AI Due Diligence Coordinator"; parent="AI Acquisition Analyst"; parentRoute="/ai-agent/realestate/acquisition-analyst"; icon="Search"; stats="1,234"; resp="1.2s"; acc="98.4"; caps="Due Diligence","Checklist Management","Team Coordination","Document Review","Risk Identification","Timeline Management"; resps="Due diligence process coordination & management","Checklist management & tracking","Due diligence team coordination","Document review & organization","Risk identification & assessment","Due diligence timeline management"; acts="Coordinated due diligence for 5 acquisitions","Managed 200-item checklist for $50M deal","Identified 3 material risks during DD review" },
  @{ id="underwriting-assistant"; name="AI Underwriting Assistant"; parent="AI Acquisition Analyst"; parentRoute="/ai-agent/realestate/acquisition-analyst"; icon="FileSpreadsheet"; stats="2,567"; resp="0.9s"; acc="98.8"; caps="Underwriting Support","Financial Analysis","Deal Structuring","Lender Coordination","Compliance Review","Documentation"; resps="Underwriting support & analysis","Financial analysis & modeling","Deal structuring & terms negotiation","Lender coordination & package preparation","Compliance review & verification","Underwriting documentation management"; acts="Supported underwriting for 8 deals totaling $200M","Prepared lender packages for 3 acquisitions","Verified compliance for 15 loan applications" },
  @{ id="asset-performance-tracker"; name="AI Asset Performance Tracker"; parent="AI Asset Manager"; parentRoute="/ai-agent/realestate/asset-manager"; icon="Activity"; stats="3,789"; resp="0.4s"; acc="99.0"; caps="Performance Tracking","KPI Monitoring","Benchmarking","Variance Reporting","Trend Analysis","Alert Management"; resps="Asset performance tracking & monitoring","KPI monitoring & threshold management","Performance benchmarking & comparison","Variance reporting & analysis","Performance trend analysis & projection","Automated alert management & notification"; acts="Tracked performance for 25 assets in portfolio","Generated monthly variance reports for board","Alerted on 3 assets below target returns" },
  @{ id="disposition-advisor"; name="AI Disposition Advisor"; parent="AI Asset Manager"; parentRoute="/ai-agent/realestate/asset-manager"; icon="TrendingDown"; stats="1,456"; resp="1.0s"; acc="97.6"; caps="Disposition Strategy","Sale Timing","Market Positioning","Buyer Identification","Exit Planning","Value Maximization"; resps="Asset disposition strategy development","Sale timing optimization & market analysis","Market positioning & marketing strategy","Buyer identification & qualification","Exit planning & execution management","Value maximization & negotiation support"; acts="Advised on disposition of 5 non-core assets","Identified optimal sale window for office portfolio","Positioned 3 assets for competitive bidding" },
  @{ id="return-calculator"; name="AI Return Calculator"; parent="AI Asset Manager"; parentRoute="/ai-agent/realestate/asset-manager"; icon="Percent"; stats="2,123"; resp="0.6s"; acc="99.1"; caps="Return Calculation","IRR Modeling","Equity Multiple","Cash-on-Cash","ROI Analysis","Performance Attribution"; resps="Investment return calculation & modeling","Internal rate of return (IRR) modeling","Equity multiple calculation & projection","Cash-on-cash return analysis","ROI analysis & comparison","Performance attribution & decomposition"; acts="Calculated IRR for 15 assets averaging 18%","Modeled equity multiples for 5-year hold periods","Analyzed performance attribution across portfolio" },
  @{ id="timeline-manager"; name="AI Timeline Manager"; parent="AI Development Coordinator"; parentRoute="/ai-agent/realestate/development-coordinator"; icon="Clock"; stats="2,890"; resp="0.5s"; acc="98.7"; caps="Timeline Management","Milestone Tracking","Gantt Charting","Critical Path","Delay Analysis","Schedule Optimization"; resps="Development timeline management & tracking","Milestone tracking & reporting","Gantt chart management & visualization","Critical path analysis & management","Delay analysis & impact assessment","Schedule optimization & acceleration"; acts="Managed timelines for 8 development projects","Identified critical path delay saving 3 weeks","Updated Gantt charts across $400M pipeline" },
  @{ id="contractor-coordinator"; name="AI Contractor Coordinator"; parent="AI Development Coordinator"; parentRoute="/ai-agent/realestate/development-coordinator"; icon="HardHat"; stats="1,567"; resp="0.8s"; acc="97.5"; caps="Contractor Management","Bid Coordination","Performance Tracking","Payment Management","Compliance Verification","Scheduling"; resps="General contractor coordination & management","Bid coordination & comparison","Contractor performance tracking & rating","Payment management & approval workflow","Compliance verification & insurance tracking","Contractor scheduling & resource planning"; acts="Coordinated 12 contractors across 5 projects","Managed bid process for $50M construction contract","Verified compliance for 8 contractor renewals" },
  @{ id="budget-tracker"; name="AI Budget Tracker"; parent="AI Development Coordinator"; parentRoute="/ai-agent/realestate/development-coordinator"; icon="Wallet"; stats="2,345"; resp="0.6s"; acc="98.9"; caps="Budget Tracking","Cost Control","Variance Analysis","Forecasting","Draw Management","Financial Reporting"; resps="Development budget tracking & management","Cost control & change order management","Budget variance analysis & reporting","Cost forecasting & projection","Draw management & lender reporting","Financial reporting & documentation"; acts="Tracked $200M in development budgets","Identified $5M in cost overruns early","Managed 30 draw requests across 5 projects" },
  @{ id="listing-creator"; name="AI Listing Creator"; parent="AI Property Marketing"; parentRoute="/ai-agent/realestate/property-marketing"; icon="FilePlus"; stats="2,678"; resp="0.4s"; acc="98.5"; caps="Listing Creation","Copy Writing","Photo Management","Platform Distribution","SEO Optimization","Template Management"; resps="Property listing creation & management","Marketing copy writing & optimization","Photo & media management & selection","Multi-platform listing distribution","SEO optimization for property listings","Listing template management & standardization"; acts="Created 45 property listings this month","Distributed listings across 8 platforms","Optimized listing copy improving CTR by 25%" },
  @{ id="virtual-tour-builder"; name="AI Virtual Tour Builder"; parent="AI Property Marketing"; parentRoute="/ai-agent/realestate/property-marketing"; icon="Video"; stats="1,234"; resp="1.5s"; acc="96.2"; caps="Virtual Tours","3D Modeling","Interactive Floor Plans","Video Production","VR Integration","Tour Analytics"; resps="Virtual tour creation & management","3D model generation & integration","Interactive floor plan development","Video tour production & editing","VR experience integration","Tour analytics & engagement tracking"; acts="Built virtual tours for 20 properties","Generated 3D models from floor plans","Tracked 5,000 tour views with 12% conversion" },
  @{ id="lead-qualifier"; name="AI Lead Qualifier"; parent="AI Property Marketing"; parentRoute="/ai-agent/realestate/property-marketing"; icon="UserSearch"; stats="3,890"; resp="0.3s"; acc="99.0"; caps="Lead Qualification","Intent Scoring","Contact Management","Pipeline Tracking","Response Routing","CRM Integration"; resps="Lead qualification & scoring","Intent scoring & behavioral analysis","Contact management & organization","Lead pipeline tracking & management","Response routing & assignment","CRM integration & data synchronization"; acts="Qualified 500 leads this month with 35% conversion","Scored leads using behavioral intent model","Routed 150 hot leads to leasing agents" }
)

foreach ($agent in $subAgents) {
  $filePath = Join-Path $base "$($agent.id).tsx"
  
  $capsStr = ($agent.caps | ForEach-Object { "'$_'" }) -join ','
  $respsStr = ($agent.resps | ForEach-Object { "'$_'" }) -join ','
  $actsData = @()
  for ($i = 0; $i -lt $agent.acts.Count; $i++) {
    $icon = if ($i -eq 0) { "CircleCheckBig" } elseif ($i -eq 1) { "Clock" } else { "Zap" }
    $time = if ($i -eq 0) { "3 min ago" } elseif ($i -eq 1) { "15 min ago" } else { "30 min ago" }
    $actsData += "{time:'$time',text:'$($agent.acts[$i])',icon:$icon}"
  }
  $actsStr = $actsData -join ','

  $content = @"
import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { useTheme } from '@/providers/ThemeProvider';
import { $($agent.icon), Activity, Star, CircleCheckBig, Clock, Target, ArrowRight, Zap } from 'lucide-react-native';
import AgentFeatures from '@/components/ai-agent/AgentFeatures';
import { useRouter } from 'expo-router';

export default function $($agent.id -replace '-','' | %{ ${_}.Substring(0,1).ToUpper() + ${_}.Substring(1) })Page() {
  const { theme } = useTheme();
  const router = useRouter();
  const stats = [{label:'Tasks',value:'$($agent.stats)',icon:CircleCheckBig,color:'#34C759'},{label:'Uptime',value:'99.9%',icon:Activity,color:'#007AFF'},{label:'Response',value:'$($agent.resp)',icon:Clock,color:'#FF9500'},{label:'Accuracy',value:'$($agent.acc)%',icon:Target,color:'#558B2F'}];
  const capabilities = [$capsStr];
  const responsibilities = [$respsStr];
  const activities = [$actsStr];

  return (
    <ScrollView style={[styles.container, { backgroundColor: theme.colors.background }]}>
      <View style={[styles.hero, { borderBottomColor: theme.colors.border || '#E5E5EA' }]}>
        <View style={[styles.heroIconWrap, { backgroundColor: '#558B2F20' }]}><$($agent.icon) size={56} color="#558B2F" /></View>
        <Text style={[styles.heroTitle, { color: theme.colors.text }]}>$($agent.name)</Text>
        <Text style={[styles.heroSubtitle, { color: theme.colors.textSecondary }]}>Sub-Agent of $($agent.parent)</Text>
        <View style={styles.badgesRow}>
          <View style={[styles.badge, { backgroundColor: '#34C75922' }]}><Activity size={12} color="#34C759" /><Text style={[styles.badgeText, { color: '#34C759' }]}>Active</Text></View>
          <View style={[styles.badge, { backgroundColor: '#558B2F22' }]}><Star size={12} color="#558B2F" /><Text style={[styles.badgeText, { color: '#558B2F' }]}>Specialist</Text></View>
        </View>
      </View>
      <View style={styles.statsContainer}>{stats.map((stat,i)=>(<View key={i} style={[styles.statCard, { backgroundColor: theme.colors.card || '#F2F2F7' }]}><stat.icon size={22} color={stat.color} /><Text style={[styles.statValue, { color: theme.colors.text }]}>{stat.value}</Text><Text style={[styles.statLabel, { color: theme.colors.textSecondary }]}>{stat.label}</Text></View>))}</View>
      <View style={[styles.section, { backgroundColor: theme.colors.card || '#F2F2F7' }]}><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Overview</Text><Text style={[styles.description, { color: theme.colors.textSecondary }]}>The $($agent.name) provides specialized capabilities supporting the $($agent.parent) within the Real Estate division, delivering automated analysis, tracking, and optimization.</Text></View>
      <View style={[styles.section, { backgroundColor: theme.colors.card || '#F2F2F7' }]}><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Capabilities</Text><View style={styles.tagsContainer}>{capabilities.map((cap,i)=>(<View key={i} style={[styles.tag, { backgroundColor: '#558B2F18' }]}><Text style={[styles.tagText, { color: '#558B2F' }]}>{cap}</Text></View>))}</View></View>
      <View style={[styles.section, { backgroundColor: theme.colors.card || '#F2F2F7' }]}><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Key Responsibilities</Text>{responsibilities.map((item,i)=>(<View key={i} style={styles.responsibilityRow}><ArrowRight size={14} color="#558B2F" /><Text style={[styles.responsibilityText, { color: theme.colors.textSecondary }]}>{item}</Text></View>))}</View>
      <View style={[styles.section, { backgroundColor: theme.colors.card || '#F2F2F7' }]}><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Recent Activity</Text>{activities.map((act,i)=>(<View key={i} style={styles.activityRow}><View style={[styles.activityIcon, { backgroundColor: '#558B2F15' }]}><act.icon size={14} color="#558B2F" /></View><View style={styles.activityContent}><Text style={[styles.activityText, { color: theme.colors.text }]}>{act.text}</Text><Text style={[styles.activityTime, { color: theme.colors.textSecondary }]}>{act.time}</Text></View></View>))}</View>
      <View style={[styles.section, { backgroundColor: theme.colors.card || '#F2F2F7' }]}><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Parent Agent</Text><TouchableOpacity onPress={() => router.push('$($agent.parentRoute)')} style={[styles.parentCard, { backgroundColor: theme.colors.background || '#F2F2F7' }]}><$($agent.icon) size={24} color="#33691E" /><View style={styles.parentInfo}><Text style={[styles.parentName, { color: theme.colors.text }]}>$($agent.parent)</Text><Text style={[styles.parentDesc, { color: theme.colors.textSecondary }]}>Main Agent</Text></View><ArrowRight size={20} color={theme.colors.textSecondary} /></TouchableOpacity></View>
      <AgentFeatures agentId="$($agent.id)" agentName="$($agent.name)" />
      <View style={{ height: 40 }} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({container:{flex:1},hero:{alignItems:'center',paddingVertical:32,paddingHorizontal:20,borderBottomWidth:1},heroIconWrap:{width:88,height:88,borderRadius:44,justifyContent:'center',alignItems:'center',marginBottom:16},heroTitle:{fontSize:26,fontWeight:'bold'},heroSubtitle:{fontSize:15,marginTop:4,fontWeight:'500'},badgesRow:{flexDirection:'row',gap:10,marginTop:16},badge:{flexDirection:'row',alignItems:'center',paddingHorizontal:10,paddingVertical:5,borderRadius:20,gap:4},badgeText:{fontSize:12,fontWeight:'600'},statsContainer:{flexDirection:'row',flexWrap:'wrap',padding:16,gap:12},statCard:{flex:1,minWidth:'22%',alignItems:'center',padding:14,borderRadius:12},statValue:{fontSize:18,fontWeight:'bold',marginTop:8},statLabel:{fontSize:11,marginTop:4},section:{marginHorizontal:16,marginBottom:16,padding:20,borderRadius:16},sectionTitle:{fontSize:18,fontWeight:'700',marginBottom:14},description:{fontSize:14,lineHeight:22},tagsContainer:{flexDirection:'row',flexWrap:'wrap',gap:8},tag:{paddingHorizontal:12,paddingVertical:6,borderRadius:20},tagText:{fontSize:12,fontWeight:'600'},responsibilityRow:{flexDirection:'row',alignItems:'center',marginBottom:10,gap:8},responsibilityText:{fontSize:14,flex:1,lineHeight:20},activityRow:{flexDirection:'row',alignItems:'center',marginBottom:12,gap:12},activityIcon:{width:32,height:32,borderRadius:16,justifyContent:'center',alignItems:'center'},activityContent:{flex:1},activityText:{fontSize:14,fontWeight:'500'},activityTime:{fontSize:12,marginTop:2},parentCard:{flexDirection:'row',alignItems:'center',padding:16,borderRadius:12,gap:12},parentInfo:{flex:1},parentName:{fontSize:16,fontWeight:'600'},parentDesc:{fontSize:12,marginTop:2}});
"@

  [System.IO.File]::WriteAllText($filePath, $content, [System.Text.Encoding]::UTF8)
  Write-Host "Updated: $($agent.id).tsx"
}

Write-Host "`nDone! Updated $($subAgents.Count) sub-agent pages."
