import React from 'react';
import DepartmentDashboardView from '@/components/ai-agent/dashboard/DepartmentDashboardView';

const agents = [
  { id: 'ai-chief-logistics-officer', uid: 'ktx-19-chief-logistics-officer', title: 'AI Chief Logistics Officer', route: '/ai-agent/transportation/chief-logistics-officer', color: '#26A69A', level: 'c_level', efficiency: '77%' },
  { id: 'ai-vp-transportation', uid: 'ktx-19-vp-transportation', title: 'AI VP Transportation', route: '/ai-agent/transportation/vp-transportation', color: '#26A69A', level: 'vp_director', efficiency: '75%' },
  { id: 'ai-vp-logistics-operations', uid: 'ktx-19-vp-logistics-operations', title: 'AI VP Logistics Operations', route: '/ai-agent/transportation/vp-logistics-operations', color: '#26A69A', level: 'vp_director', efficiency: '77%' },
  { id: 'ai-vp-fleet-operations', uid: 'ktx-19-vp-fleet-operations', title: 'AI VP Fleet Operations', route: '/ai-agent/transportation/vp-fleet-operations', color: '#26A69A', level: 'vp_director', efficiency: '82%' },
  { id: 'ai-vp-warehouse-operations', uid: 'ktx-19-vp-warehouse-operations', title: 'AI VP Warehouse Operations', route: '/ai-agent/transportation/vp-warehouse-operations', color: '#26A69A', level: 'vp_director', efficiency: '80%' },
  { id: 'ai-vp-distribution', uid: 'ktx-19-vp-distribution', title: 'AI VP Distribution', route: '/ai-agent/transportation/vp-distribution', color: '#26A69A', level: 'vp_director', efficiency: '78%' },
  { id: 'ai-vp-freight-operations', uid: 'ktx-19-vp-freight-operations', title: 'AI VP Freight Operations', route: '/ai-agent/transportation/vp-freight-operations', color: '#26A69A', level: 'vp_director', efficiency: '81%' },
  { id: 'ai-vp-supply-chain', uid: 'ktx-19-vp-supply-chain', title: 'AI VP Supply Chain', route: '/ai-agent/transportation/vp-supply-chain', color: '#26A69A', level: 'vp_director', efficiency: '83%' },
  { id: 'ai-vp-last-mile', uid: 'ktx-19-vp-last-mile', title: 'AI VP Last Mile', route: '/ai-agent/transportation/vp-last-mile', color: '#26A69A', level: 'vp_director', efficiency: '84%' },
  { id: 'ai-vp-global-logistics', uid: 'ktx-19-vp-global-logistics', title: 'AI VP Global Logistics', route: '/ai-agent/transportation/vp-global-logistics', color: '#26A69A', level: 'vp_director', efficiency: '79%' },
  { id: 'ai-vp-customs-compliance', uid: 'ktx-19-vp-customs-compliance', title: 'AI VP Customs & Compliance', route: '/ai-agent/transportation/vp-customs-compliance', color: '#26A69A', level: 'vp_director', efficiency: '85%' },
  { id: 'ai-fleet-manager', uid: 'ktx-19-fleet-manager', title: 'AI Fleet Manager', route: '/ai-agent/transportation/fleet-manager', color: '#26A69A', level: 'manager', efficiency: '87%' },
  { id: 'ai-warehouse-manager', uid: 'ktx-19-warehouse-manager', title: 'AI Warehouse Manager', route: '/ai-agent/transportation/warehouse-manager', color: '#26A69A', level: 'manager', efficiency: '75%' },
  { id: 'ai-distribution-manager', uid: 'ktx-19-distribution-manager', title: 'AI Distribution Manager', route: '/ai-agent/transportation/distribution-manager', color: '#26A69A', level: 'manager', efficiency: '76%' },
  { id: 'ai-dispatch-manager', uid: 'ktx-19-dispatch-manager', title: 'AI Dispatch Manager', route: '/ai-agent/transportation/dispatch-manager', color: '#26A69A', level: 'manager', efficiency: '84%' },
  { id: 'ai-freight-manager', uid: 'ktx-19-freight-manager', title: 'AI Freight Manager', route: '/ai-agent/transportation/freight-manager', color: '#26A69A', level: 'manager', efficiency: '82%' },
  { id: 'ai-cross-dock-manager', uid: 'ktx-19-cross-dock-manager', title: 'AI Cross-Dock Manager', route: '/ai-agent/transportation/cross-dock-manager', color: '#26A69A', level: 'manager', efficiency: '83%' },
  { id: 'ai-route-optimizer', uid: 'ktx-19-route-optimizer', title: 'AI Route Optimizer', route: '/ai-agent/transportation/route-optimizer', color: '#26A69A', level: 'team_lead', efficiency: '81%' },
  { id: 'ai-fleet-coordinator', uid: 'ktx-19-fleet-coordinator', title: 'AI Fleet Coordinator', route: '/ai-agent/transportation/fleet-coordinator', color: '#26A69A', level: 'c_level', efficiency: '75%' },
  { id: 'ai-warehouse-operator', uid: 'ktx-19-warehouse-operator', title: 'AI Warehouse Operator', route: '/ai-agent/transportation/warehouse-operator', color: '#26A69A', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-dispatcher', uid: 'ktx-19-dispatcher', title: 'AI Dispatcher', route: '/ai-agent/transportation/dispatcher', color: '#26A69A', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-tracking-specialist', uid: 'ktx-19-tracking-specialist', title: 'AI Tracking Specialist', route: '/ai-agent/transportation/tracking-specialist', color: '#26A69A', level: 'team_lead', efficiency: '89%' },
  { id: 'ai-last-mile-coordinator', uid: 'ktx-19-last-mile-coordinator', title: 'AI Last Mile Coordinator', route: '/ai-agent/transportation/last-mile-coordinator', color: '#26A69A', level: 'c_level', efficiency: '83%' },
  { id: 'ai-freight-broker', uid: 'ktx-19-freight-broker', title: 'AI Freight Broker', route: '/ai-agent/transportation/freight-broker', color: '#26A69A', level: 'team_lead', efficiency: '94%' },
  { id: 'ai-customs-specialist', uid: 'ktx-19-customs-specialist', title: 'AI Customs Specialist', route: '/ai-agent/transportation/customs-specialist', color: '#26A69A', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-load-planner', uid: 'ktx-19-load-planner', title: 'AI Load Planner', route: '/ai-agent/transportation/load-planner', color: '#26A69A', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-route-planner', uid: 'ktx-19-route-planner', title: 'AI Route Planner', route: '/ai-agent/transportation/route-planner', color: '#26A69A', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-delivery-coordinator', uid: 'ktx-19-delivery-coordinator', title: 'AI Delivery Coordinator', route: '/ai-agent/transportation/delivery-coordinator', color: '#26A69A', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-shipment-tracker', uid: 'ktx-19-shipment-tracker', title: 'AI Shipment Tracker', route: '/ai-agent/transportation/shipment-tracker', color: '#26A69A', level: 'team_lead', efficiency: '88%' },
  { id: 'ai-eta-predictor', uid: 'ktx-19-eta-predictor', title: 'AI ETA Predictor', route: '/ai-agent/transportation/eta-predictor', color: '#26A69A', level: 'team_lead', efficiency: '87%' },
  { id: 'ai-exception-handler', uid: 'ktx-19-exception-handler', title: 'AI Exception Handler', route: '/ai-agent/transportation/exception-handler', color: '#26A69A', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-capacity-planner', uid: 'ktx-19-capacity-planner', title: 'AI Capacity Planner', route: '/ai-agent/transportation/capacity-planner', color: '#26A69A', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-carrier-relations-specialist', uid: 'ktx-19-carrier-relations-specialist', title: 'AI Carrier Relations Specialist', route: '/ai-agent/transportation/carrier-relations-specialist', color: '#26A69A', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-rate-analyst', uid: 'ktx-19-rate-analyst', title: 'AI Rate Analyst', route: '/ai-agent/transportation/rate-analyst', color: '#26A69A', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-freight-auditor', uid: 'ktx-19-freight-auditor', title: 'AI Freight Auditor', route: '/ai-agent/transportation/freight-auditor', color: '#26A69A', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-inventory-coordinator', uid: 'ktx-19-inventory-coordinator', title: 'AI Inventory Coordinator', route: '/ai-agent/transportation/inventory-coordinator', color: '#26A69A', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-pick-pack-lead', uid: 'ktx-19-pick-pack-lead', title: 'AI Pick/Pack Lead', route: '/ai-agent/transportation/pick-pack-lead', color: '#26A69A', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-warehouse-supervisor', uid: 'ktx-19-warehouse-supervisor', title: 'AI Warehouse Supervisor', route: '/ai-agent/transportation/warehouse-supervisor', color: '#26A69A', level: 'team_lead', efficiency: '82%' },
  { id: 'ai-forklift-operator', uid: 'ktx-19-forklift-operator', title: 'AI Forklift Operator', route: '/ai-agent/transportation/forklift-operator', color: '#26A69A', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-receiving-clerk', uid: 'ktx-19-receiving-clerk', title: 'AI Receiving Clerk', route: '/ai-agent/transportation/receiving-clerk', color: '#26A69A', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-shipping-clerk', uid: 'ktx-19-shipping-clerk', title: 'AI Shipping Clerk', route: '/ai-agent/transportation/shipping-clerk', color: '#26A69A', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-quality-control-inspector', uid: 'ktx-19-quality-control-inspector', title: 'AI Quality Control Inspector', route: '/ai-agent/transportation/quality-control-inspector', color: '#26A69A', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-fleet-maintenance-coordinator', uid: 'ktx-19-fleet-maintenance-coordinator', title: 'AI Fleet Maintenance Coordinator', route: '/ai-agent/transportation/fleet-maintenance-coordinator', color: '#26A69A', level: 'team_lead', efficiency: '87%' },
  { id: 'ai-vehicle-inspector', uid: 'ktx-19-vehicle-inspector', title: 'AI Vehicle Inspector', route: '/ai-agent/transportation/vehicle-inspector', color: '#26A69A', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-fuel-manager', uid: 'ktx-19-fuel-manager', title: 'AI Fuel Manager', route: '/ai-agent/transportation/fuel-manager', color: '#26A69A', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-driver-coordinator', uid: 'ktx-19-driver-coordinator', title: 'AI Driver Coordinator', route: '/ai-agent/transportation/driver-coordinator', color: '#26A69A', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-driver-scheduler', uid: 'ktx-19-driver-scheduler', title: 'AI Driver Scheduler', route: '/ai-agent/transportation/driver-scheduler', color: '#26A69A', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-compliance-officer', uid: 'ktx-19-compliance-officer', title: 'AI Compliance Officer', route: '/ai-agent/transportation/compliance-officer', color: '#26A69A', level: 'team_lead', efficiency: '88%' },
  { id: 'ai-documents-specialist', uid: 'ktx-19-documents-specialist', title: 'AI Documents Specialist', route: '/ai-agent/transportation/documents-specialist', color: '#26A69A', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-bill-of-lading-specialist', uid: 'ktx-19-bill-of-lading-specialist', title: 'AI Bill of Lading Specialist', route: '/ai-agent/transportation/bill-of-lading-specialist', color: '#26A69A', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-import-export-coordinator', uid: 'ktx-19-import-export-coordinator', title: 'AI Import/Export Coordinator', route: '/ai-agent/transportation/import-export-coordinator', color: '#26A69A', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-trade-compliance-specialist', uid: 'ktx-19-trade-compliance-specialist', title: 'AI Trade Compliance Specialist', route: '/ai-agent/transportation/trade-compliance-specialist', color: '#26A69A', level: 'team_lead', efficiency: '87%' },
  { id: 'ai-cross-border-specialist', uid: 'ktx-19-cross-border-specialist', title: 'AI Cross Border Specialist', route: '/ai-agent/transportation/cross-border-specialist', color: '#26A69A', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-terminal-coordinator', uid: 'ktx-19-terminal-coordinator', title: 'AI Terminal Coordinator', route: '/ai-agent/transportation/terminal-coordinator', color: '#26A69A', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-yard-manager', uid: 'ktx-19-yard-manager', title: 'AI Yard Manager', route: '/ai-agent/transportation/yard-manager', color: '#26A69A', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-appointment-scheduler', uid: 'ktx-19-appointment-scheduler', title: 'AI Appointment Scheduler', route: '/ai-agent/transportation/appointment-scheduler', color: '#26A69A', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-dock-scheduler', uid: 'ktx-19-dock-scheduler', title: 'AI Dock Scheduler', route: '/ai-agent/transportation/dock-scheduler', color: '#26A69A', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-labor-planner', uid: 'ktx-19-labor-planner', title: 'AI Labor Planner', route: '/ai-agent/transportation/labor-planner', color: '#26A69A', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-performance-analyst', uid: 'ktx-19-performance-analyst', title: 'AI Performance Analyst', route: '/ai-agent/transportation/performance-analyst', color: '#26A69A', level: 'team_lead', efficiency: '87%' },
  { id: 'ai-kpi-tracker', uid: 'ktx-19-kpi-tracker', title: 'AI KPI Tracker', route: '/ai-agent/transportation/kpi-tracker', color: '#26A69A', level: 'team_lead', efficiency: '86%' },
  { id: 'ai-cost-analyst', uid: 'ktx-19-cost-analyst', title: 'AI Cost Analyst', route: '/ai-agent/transportation/cost-analyst', color: '#26A69A', level: 'team_lead', efficiency: '85%' },
  { id: 'ai-service-level-analyst', uid: 'ktx-19-service-level-analyst', title: 'AI Service Level Analyst', route: '/ai-agent/transportation/service-level-analyst', color: '#26A69A', level: 'team_lead', efficiency: '84%' },
  { id: 'ai-customer-service-transport', uid: 'ktx-19-customer-service-transport', title: 'AI Customer Service Transport', route: '/ai-agent/transportation/customer-service-transport', color: '#26A69A', level: 'team_lead', efficiency: '88%' },
  { id: 'ai-claims-specialist', uid: 'ktx-19-claims-specialist', title: 'AI Claims Specialist', route: '/ai-agent/transportation/claims-specialist', color: '#26A69A', level: 'team_lead', efficiency: '83%' },
  { id: 'ai-logistics-director-1', uid: 'ktx-19-logistics-director-1', title: 'AI Logistics Director I', route: '/ai-agent/transportation/logistics-director-1', color: '#26A69A', level: 'vp_director', efficiency: '94%' },
  { id: 'ai-logistics-director-2', uid: 'ktx-19-logistics-director-2', title: 'AI Logistics Director II', route: '/ai-agent/transportation/logistics-director-2', color: '#26A69A', level: 'vp_director', efficiency: '95%' },
  { id: 'ai-fleet-director-1', uid: 'ktx-19-fleet-director-1', title: 'AI Fleet Director I', route: '/ai-agent/transportation/fleet-director-1', color: '#26A69A', level: 'vp_director', efficiency: '92%' },
  { id: 'ai-fleet-director-2', uid: 'ktx-19-fleet-director-2', title: 'AI Fleet Director II', route: '/ai-agent/transportation/fleet-director-2', color: '#26A69A', level: 'vp_director', efficiency: '93%' },
  { id: 'ai-route-optimization-manager-1', uid: 'ktx-19-route-optimization-manager-1', title: 'AI Route Optimization Manager I', route: '/ai-agent/transportation/route-optimization-manager-1', color: '#26A69A', level: 'manager', efficiency: '91%' },
  { id: 'ai-route-optimization-manager-2', uid: 'ktx-19-route-optimization-manager-2', title: 'AI Route Optimization Manager II', route: '/ai-agent/transportation/route-optimization-manager-2', color: '#26A69A', level: 'manager', efficiency: '92%' },
  { id: 'ai-transportation-analyst-1', uid: 'ktx-19-transportation-analyst-1', title: 'AI Transportation Analyst I', route: '/ai-agent/transportation/transportation-analyst-1', color: '#26A69A', level: 'team_lead', efficiency: '89%' },
  { id: 'ai-transportation-analyst-2', uid: 'ktx-19-transportation-analyst-2', title: 'AI Transportation Analyst II', route: '/ai-agent/transportation/transportation-analyst-2', color: '#26A69A', level: 'team_lead', efficiency: '90%' },
  { id: 'ai-transportation-analyst-3', uid: 'ktx-19-transportation-analyst-3', title: 'AI Transportation Analyst III', route: '/ai-agent/transportation/transportation-analyst-3', color: '#26A69A', level: 'team_lead', efficiency: '91%' },
  { id: 'ai-compliance-manager-1', uid: 'ktx-19-compliance-manager-1', title: 'AI Compliance Manager I', route: '/ai-agent/transportation/compliance-manager-1', color: '#26A69A', level: 'manager', efficiency: '90%' },
  { id: 'ai-compliance-manager-2', uid: 'ktx-19-compliance-manager-2', title: 'AI Compliance Manager II', route: '/ai-agent/transportation/compliance-manager-2', color: '#26A69A', level: 'manager', efficiency: '91%' },
];

export default function DepartmentIndex() {
  return (
    <DepartmentDashboardView
      departmentId="transportation-logistics"
      agents={agents}
    />
  );
}
