import { z } from "zod";
import { publicProcedure } from "../../../create-context";
import type { MainAgent, SubAgent, AgentCategory } from "../types";

const customerExperienceSubAgents: SubAgent[] = [
  {
    id: 'ce-1',
    name: 'AI Receptionist',
    description: 'First point of contact - handles calls, schedules appointments, answers FAQs',
    category: 'customer-experience',
    enabled: true,
    status: 'active',
    tasksCompleted: 3240,
    successRate: 96,
    lastActive: '2 min ago',
    capabilities: ['Call Handling', 'Appointment Scheduling', 'FAQ Response', 'Multi-language Support', 'Call Routing', 'Voicemail Management'],
    tier: 'premium',
    learningProgress: 92,
    efficiency: 98,
    healthScore: 98,
    weeklyGrowth: 12,
    trend: 'up',
    recentActions: ['Scheduled appointment for John D.', 'Answered billing inquiry', 'Routed call to Sales'],
    metrics: { activeConversations: 8, resolvedToday: 142, avgResponseTime: '1.2s', customerSatisfaction: 4.8 },
  },
  {
    id: 'ce-2',
    name: 'AI Customer Support Agent',
    description: 'Handles support via chat, email, and voice with intelligent routing',
    category: 'customer-experience',
    enabled: true,
    status: 'active',
    tasksCompleted: 4520,
    successRate: 93,
    lastActive: '1 min ago',
    capabilities: ['Ticket Resolution', 'Live Chat', 'Email Support', 'Knowledge Base', 'Escalation Management', 'SLA Tracking'],
    tier: 'enterprise',
    learningProgress: 88,
    efficiency: 95,
    healthScore: 95,
    weeklyGrowth: 8,
    trend: 'up',
    recentActions: ['Resolved ticket #4521', 'Initiated live chat with Sarah M.', 'Sent follow-up email'],
    metrics: { activeConversations: 24, resolvedToday: 198, avgResponseTime: '0.8s', customerSatisfaction: 4.6 },
  },
  {
    id: 'ce-3',
    name: 'AI Ticket Resolution Agent',
    description: 'Auto-resolves tickets using AI analysis and pattern matching',
    category: 'customer-experience',
    enabled: true,
    status: 'active',
    tasksCompleted: 2890,
    successRate: 91,
    lastActive: '5 min ago',
    capabilities: ['Auto-Resolution', 'Intelligent Escalation', 'SLA Tracking', 'Priority Management', 'Pattern Recognition', 'Root Cause Analysis'],
    tier: 'premium',
    learningProgress: 85,
    efficiency: 92,
    healthScore: 92,
    weeklyGrowth: 5,
    trend: 'stable',
    recentActions: ['Auto-resolved 12 tickets', 'Escalated priority issue', 'Updated knowledge base'],
    metrics: { activeConversations: 12, resolvedToday: 78, avgResponseTime: '2.4s', customerSatisfaction: 4.5 },
  },
  {
    id: 'ce-4',
    name: 'AI Complaint Handling Agent',
    description: 'Manages complaints with empathy, efficiency, and resolution tracking',
    category: 'customer-experience',
    enabled: true,
    status: 'training',
    tasksCompleted: 1560,
    successRate: 88,
    lastActive: '10 min ago',
    capabilities: ['Complaint Analysis', 'Resolution Suggestions', 'Follow-up Automation', 'Sentiment Detection', 'Escalation Protocols', 'Compensation Management'],
    tier: 'enterprise',
    learningProgress: 78,
    efficiency: 86,
    healthScore: 85,
    weeklyGrowth: 15,
    trend: 'up',
    recentActions: ['Processed refund request', 'De-escalated angry customer', 'Offered loyalty discount'],
    metrics: { activeConversations: 6, resolvedToday: 38, avgResponseTime: '3.1s', customerSatisfaction: 4.3 },
  },
  {
    id: 'ce-5',
    name: 'AI Retention Specialist',
    description: 'Prevents churn through proactive engagement and personalized offers',
    category: 'customer-experience',
    enabled: true,
    status: 'active',
    tasksCompleted: 890,
    successRate: 95,
    lastActive: '3 min ago',
    capabilities: ['Churn Prediction', 'Win-back Campaigns', 'Loyalty Offers', 'Journey Optimization', 'Risk Scoring', 'Personalized Outreach'],
    tier: 'enterprise',
    learningProgress: 91,
    efficiency: 97,
    healthScore: 97,
    weeklyGrowth: 22,
    trend: 'up',
    recentActions: ['Saved at-risk customer', 'Launched win-back campaign', 'Applied retention offer'],
    metrics: { activeConversations: 4, resolvedToday: 62, avgResponseTime: '1.5s', customerSatisfaction: 4.9 },
  },
  {
    id: 'ce-6',
    name: 'AI Loyalty & Engagement Agent',
    description: 'Drives loyalty programs and engagement through gamification',
    category: 'customer-experience',
    enabled: false,
    status: 'inactive',
    tasksCompleted: 650,
    successRate: 92,
    lastActive: '1 hour ago',
    capabilities: ['Rewards Management', 'Engagement Tracking', 'Program Optimization', 'Gamification', 'Points Management', 'Tier Progression'],
    tier: 'premium',
    learningProgress: 72,
    efficiency: 88,
    healthScore: 70,
    weeklyGrowth: 0,
    trend: 'stable',
    recentActions: ['Paused - awaiting activation'],
    metrics: { activeConversations: 0, resolvedToday: 0, avgResponseTime: '-', customerSatisfaction: 4.4 },
  },
  {
    id: 'ce-7',
    name: 'AI Feedback & Survey Agent',
    description: 'Collects, analyzes, and acts on customer feedback in real-time',
    category: 'customer-experience',
    enabled: true,
    status: 'active',
    tasksCompleted: 1120,
    successRate: 97,
    lastActive: '8 min ago',
    capabilities: ['Survey Creation', 'Sentiment Analysis', 'Insight Generation', 'NPS Tracking', 'Trend Detection', 'Action Recommendations'],
    tier: 'standard',
    learningProgress: 94,
    efficiency: 99,
    healthScore: 99,
    weeklyGrowth: 18,
    trend: 'up',
    recentActions: ['Analyzed 234 feedback responses', 'Generated NPS report', 'Flagged trending issue'],
    metrics: { activeConversations: 0, resolvedToday: 78, avgResponseTime: '0.5s', customerSatisfaction: 4.7 },
  },
  {
    id: 'ce-8',
    name: 'AI Billing Support Agent',
    description: 'Handles billing inquiries, payments, and dispute resolution',
    category: 'customer-experience',
    enabled: true,
    status: 'active',
    tasksCompleted: 550,
    successRate: 94,
    lastActive: '15 min ago',
    capabilities: ['Invoice Queries', 'Payment Processing', 'Dispute Resolution', 'Subscription Management', 'Refund Processing', 'Payment Plans'],
    tier: 'premium',
    learningProgress: 89,
    efficiency: 93,
    healthScore: 93,
    weeklyGrowth: 7,
    trend: 'stable',
    recentActions: ['Processed 5 refunds', 'Set up payment plan', 'Resolved billing dispute'],
    metrics: { activeConversations: 3, resolvedToday: 31, avgResponseTime: '1.8s', customerSatisfaction: 4.5 },
  },
];

const salesRevenueSubAgents: SubAgent[] = [
  {
    id: 'sr-1',
    name: 'AI Lead Development Rep (SDR)',
    description: 'Qualifies and nurtures leads through intelligent outreach',
    category: 'sales-revenue',
    enabled: true,
    status: 'active',
    tasksCompleted: 2340,
    successRate: 87,
    lastActive: '4 min ago',
    capabilities: ['Lead Scoring', 'Outreach Automation', 'Lead Qualification', 'Nurturing Sequences', 'Email Personalization', 'Follow-up Management'],
    tier: 'enterprise',
    learningProgress: 86,
    efficiency: 91,
    healthScore: 92,
    weeklyGrowth: 15,
    trend: 'up',
    recentActions: ['Qualified 12 new leads', 'Sent personalized outreach', 'Scheduled 5 demos'],
    metrics: { dealsWon: 156, revenue: '$245K', conversionRate: 23, pipelineValue: '$1.2M', avgDealSize: '$8.5K', activeDeals: 45 },
  },
  {
    id: 'sr-2',
    name: 'AI Sales Rep',
    description: 'Handles sales conversations, demos, and negotiations',
    category: 'sales-revenue',
    enabled: true,
    status: 'active',
    tasksCompleted: 1890,
    successRate: 85,
    lastActive: '2 min ago',
    capabilities: ['Product Demo', 'Objection Handling', 'Quote Generation', 'Follow-up', 'Meeting Scheduling', 'Needs Assessment'],
    tier: 'premium',
    learningProgress: 82,
    efficiency: 88,
    healthScore: 88,
    weeklyGrowth: 12,
    trend: 'up',
    recentActions: ['Completed demo for Acme Corp', 'Generated quote #2341', 'Handled pricing objection'],
    metrics: { dealsWon: 89, revenue: '$178K', conversionRate: 19, pipelineValue: '$890K', avgDealSize: '$12K', activeDeals: 32 },
  },
  {
    id: 'sr-3',
    name: 'AI Sales Executive',
    description: 'Full cycle sales from qualification to close',
    category: 'sales-revenue',
    enabled: true,
    status: 'active',
    tasksCompleted: 1120,
    successRate: 91,
    lastActive: '6 min ago',
    capabilities: ['Deal Management', 'Contract Negotiation', 'Account Planning', 'Revenue Forecasting', 'Strategic Selling', 'Executive Presentations'],
    tier: 'enterprise',
    learningProgress: 90,
    efficiency: 94,
    healthScore: 96,
    weeklyGrowth: 22,
    trend: 'up',
    recentActions: ['Closed $120K enterprise deal', 'Updated pipeline forecast', 'Prepared board presentation'],
    metrics: { dealsWon: 67, revenue: '$890K', conversionRate: 34, pipelineValue: '$2.4M', avgDealSize: '$45K', activeDeals: 18 },
  },
  {
    id: 'sr-4',
    name: 'AI CRM Assistant',
    description: 'Manages CRM data, pipeline insights, and enrichment',
    category: 'sales-revenue',
    enabled: true,
    status: 'active',
    tasksCompleted: 1560,
    successRate: 94,
    lastActive: '1 min ago',
    capabilities: ['Data Entry', 'Pipeline Management', 'Reporting', 'Contact Enrichment', 'Activity Logging', 'Duplicate Detection'],
    tier: 'standard',
    learningProgress: 95,
    efficiency: 98,
    healthScore: 99,
    weeklyGrowth: 5,
    trend: 'stable',
    recentActions: ['Enriched 45 contacts', 'Updated 23 deal stages', 'Generated weekly report'],
    metrics: { dealsWon: 0, revenue: '-', conversionRate: 0, pipelineValue: '-', avgDealSize: '-', activeDeals: 0 },
  },
  {
    id: 'sr-5',
    name: 'AI Proposal Generator',
    description: 'Creates customized proposals with dynamic pricing',
    category: 'sales-revenue',
    enabled: true,
    status: 'active',
    tasksCompleted: 780,
    successRate: 92,
    lastActive: '12 min ago',
    capabilities: ['Template Creation', 'Personalization', 'Approval Workflow', 'Document Assembly', 'E-Signature Integration', 'Version Control'],
    tier: 'premium',
    learningProgress: 88,
    efficiency: 92,
    healthScore: 91,
    weeklyGrowth: 18,
    trend: 'up',
    recentActions: ['Generated enterprise proposal', 'Applied custom pricing', 'Sent for e-signature'],
    metrics: { dealsWon: 45, revenue: '$320K', conversionRate: 41, pipelineValue: '$780K', avgDealSize: '$18K', activeDeals: 28 },
  },
  {
    id: 'sr-6',
    name: 'AI Negotiator',
    description: 'Handles deal negotiations with strategic pricing',
    category: 'sales-revenue',
    enabled: true,
    status: 'training',
    tasksCompleted: 450,
    successRate: 86,
    lastActive: '20 min ago',
    capabilities: ['Price Negotiation', 'Term Discussion', 'Win-Win Solutions', 'Deal Structuring', 'Concession Strategy', 'BATNA Analysis'],
    tier: 'enterprise',
    learningProgress: 75,
    efficiency: 84,
    healthScore: 82,
    weeklyGrowth: 25,
    trend: 'up',
    recentActions: ['Negotiated 15% discount approval', 'Structured payment terms', 'Identified win-win scenario'],
    metrics: { dealsWon: 34, revenue: '$456K', conversionRate: 28, pipelineValue: '$1.6M', avgDealSize: '$32K', activeDeals: 15 },
  },
  {
    id: 'sr-7',
    name: 'AI Upsell & Cross-sell Agent',
    description: 'Identifies and executes expansion opportunities',
    category: 'sales-revenue',
    enabled: true,
    status: 'active',
    tasksCompleted: 340,
    successRate: 88,
    lastActive: '9 min ago',
    capabilities: ['Opportunity Detection', 'Product Recommendations', 'Bundle Offers', 'Timing Optimization', 'Customer Analysis', 'Revenue Expansion'],
    tier: 'premium',
    learningProgress: 84,
    efficiency: 90,
    healthScore: 89,
    weeklyGrowth: 20,
    trend: 'up',
    recentActions: ['Identified 8 upsell opportunities', 'Created bundle offer', 'Increased ARR by $12K'],
    metrics: { dealsWon: 78, revenue: '$234K', conversionRate: 31, pipelineValue: '$560K', avgDealSize: '$6K', activeDeals: 42 },
  },
  {
    id: 'sr-8',
    name: 'AI Account Manager',
    description: 'Manages key accounts for retention and growth',
    category: 'sales-revenue',
    enabled: false,
    status: 'inactive',
    tasksCompleted: 290,
    successRate: 90,
    lastActive: '2 hours ago',
    capabilities: ['Relationship Management', 'Health Scoring', 'Growth Planning', 'QBR Preparation', 'Executive Alignment', 'Risk Mitigation'],
    tier: 'enterprise',
    learningProgress: 79,
    efficiency: 87,
    healthScore: 70,
    weeklyGrowth: 0,
    trend: 'stable',
    recentActions: ['Paused - awaiting activation'],
    metrics: { dealsWon: 23, revenue: '$567K', conversionRate: 45, pipelineValue: '$890K', avgDealSize: '$28K', activeDeals: 0 },
  },
  {
    id: 'sr-9',
    name: 'AI Pricing Strategist',
    description: 'Optimizes pricing for maximum revenue',
    category: 'sales-revenue',
    enabled: true,
    status: 'active',
    tasksCompleted: 180,
    successRate: 93,
    lastActive: '30 min ago',
    capabilities: ['Dynamic Pricing', 'Competitor Analysis', 'Margin Optimization', 'Discount Strategy', 'Price Testing', 'Revenue Modeling'],
    tier: 'enterprise',
    learningProgress: 92,
    efficiency: 96,
    healthScore: 95,
    weeklyGrowth: 10,
    trend: 'up',
    recentActions: ['Optimized enterprise tier pricing', 'Analyzed competitor rates', 'Increased margins by 8%'],
    metrics: { dealsWon: 0, revenue: '+$123K', conversionRate: 0, pipelineValue: '-', avgDealSize: '-', activeDeals: 0 },
  },
];

const marketingGrowthSubAgents: SubAgent[] = [
  {
    id: 'mg-1',
    name: 'AI Chief Marketing Officer (AI-CMO)',
    description: 'Strategic leadership with budget allocation and oversight',
    category: 'marketing-growth',
    enabled: true,
    status: 'active',
    tasksCompleted: 890,
    successRate: 94,
    lastActive: '5 min ago',
    capabilities: ['Strategy Planning', 'Budget Allocation', 'Performance Review', 'Market Analysis', 'Brand Strategy', 'Campaign Oversight'],
    tier: 'enterprise',
    learningProgress: 93,
    efficiency: 97,
    healthScore: 97,
    weeklyGrowth: 18,
    trend: 'up',
    recentActions: ['Approved Q1 budget allocation', 'Reviewed campaign performance', 'Set new OKRs'],
    metrics: { campaignsRun: 45, reach: '2.4M', engagement: 8.5, impressions: '12.5M', conversions: 4520, roi: '320%' },
  },
  {
    id: 'mg-2',
    name: 'AI Campaign Optimizer',
    description: 'Optimizes campaigns through A/B testing and adjustments',
    category: 'marketing-growth',
    enabled: true,
    status: 'active',
    tasksCompleted: 2340,
    successRate: 92,
    lastActive: '3 min ago',
    capabilities: ['A/B Testing', 'Bid Optimization', 'Creative Testing', 'Budget Reallocation', 'Performance Tracking', 'ROI Optimization'],
    tier: 'premium',
    learningProgress: 89,
    efficiency: 94,
    healthScore: 94,
    weeklyGrowth: 22,
    trend: 'up',
    recentActions: ['Optimized ad spend by 23%', 'Launched 3 A/B tests', 'Reallocated budget to top performers'],
    metrics: { campaignsRun: 234, reach: '5.6M', engagement: 7.2, impressions: '28.4M', conversions: 8920, roi: '285%' },
  },
  {
    id: 'mg-3',
    name: 'AI Digital Marketer',
    description: 'Manages PPC, display, and retargeting campaigns',
    category: 'marketing-growth',
    enabled: true,
    status: 'active',
    tasksCompleted: 3120,
    successRate: 89,
    lastActive: '1 min ago',
    capabilities: ['PPC Management', 'Display Ads', 'Retargeting', 'Attribution', 'Channel Optimization', 'Conversion Tracking'],
    tier: 'premium',
    learningProgress: 85,
    efficiency: 91,
    healthScore: 91,
    weeklyGrowth: 15,
    trend: 'up',
    recentActions: ['Launched Google Ads campaign', 'Set up retargeting pixels', 'Optimized landing pages'],
    metrics: { campaignsRun: 312, reach: '8.9M', engagement: 6.8, impressions: '45.2M', conversions: 12340, roi: '245%' },
  },
  {
    id: 'mg-4',
    name: 'AI Content Generator',
    description: 'Creates compelling content across all channels',
    category: 'marketing-growth',
    enabled: true,
    status: 'active',
    tasksCompleted: 2890,
    successRate: 93,
    lastActive: '7 min ago',
    capabilities: ['Copywriting', 'Blog Posts', 'Social Content', 'Video Scripts', 'Ad Copy', 'Landing Pages'],
    tier: 'enterprise',
    learningProgress: 91,
    efficiency: 95,
    healthScore: 95,
    weeklyGrowth: 28,
    trend: 'up',
    recentActions: ['Generated 15 blog posts', 'Created email sequences', 'Wrote product descriptions'],
    metrics: { campaignsRun: 0, reach: '-', engagement: 9.1, impressions: '-', conversions: 0, roi: '-' },
  },
  {
    id: 'mg-5',
    name: 'AI Social Media Manager',
    description: 'Manages social presence with scheduling and engagement',
    category: 'marketing-growth',
    enabled: true,
    status: 'active',
    tasksCompleted: 1560,
    successRate: 91,
    lastActive: '2 min ago',
    capabilities: ['Scheduling', 'Community Management', 'Analytics', 'Trend Detection', 'Influencer Outreach', 'Crisis Management'],
    tier: 'premium',
    learningProgress: 87,
    efficiency: 93,
    healthScore: 93,
    weeklyGrowth: 35,
    trend: 'up',
    recentActions: ['Scheduled 45 posts', 'Responded to 123 comments', 'Identified viral trend'],
    metrics: { campaignsRun: 89, reach: '3.2M', engagement: 8.9, impressions: '18.7M', conversions: 3450, roi: '180%' },
  },
  {
    id: 'mg-6',
    name: 'AI SEO Agent',
    description: 'Optimizes search rankings through keyword research',
    category: 'marketing-growth',
    enabled: true,
    status: 'training',
    tasksCompleted: 670,
    successRate: 88,
    lastActive: '15 min ago',
    capabilities: ['Keyword Research', 'On-Page SEO', 'Link Building', 'Technical SEO', 'Content Optimization', 'Rank Tracking'],
    tier: 'premium',
    learningProgress: 76,
    efficiency: 85,
    healthScore: 82,
    weeklyGrowth: 12,
    trend: 'up',
    recentActions: ['Analyzed 500 keywords', 'Fixed technical SEO issues', 'Built 12 backlinks'],
    metrics: { campaignsRun: 0, reach: '1.8M', engagement: 0, impressions: '8.4M', conversions: 2890, roi: '420%' },
  },
  {
    id: 'mg-7',
    name: 'AI Email Marketing Agent',
    description: 'Manages email campaigns with segmentation',
    category: 'marketing-growth',
    enabled: true,
    status: 'active',
    tasksCompleted: 450,
    successRate: 90,
    lastActive: '10 min ago',
    capabilities: ['Campaign Creation', 'Segmentation', 'Automation', 'Deliverability', 'Personalization', 'A/B Testing'],
    tier: 'standard',
    learningProgress: 88,
    efficiency: 92,
    healthScore: 90,
    weeklyGrowth: 8,
    trend: 'stable',
    recentActions: ['Sent newsletter to 50K subscribers', 'Created drip campaign', 'Improved open rates by 15%'],
    metrics: { campaignsRun: 156, reach: '890K', engagement: 24.5, impressions: '4.2M', conversions: 1890, roi: '380%' },
  },
  {
    id: 'mg-8',
    name: 'AI Competitive Intelligence Agent',
    description: 'Monitors competition and market opportunities',
    category: 'marketing-growth',
    enabled: false,
    status: 'inactive',
    tasksCompleted: 230,
    successRate: 95,
    lastActive: '3 hours ago',
    capabilities: ['Competitor Tracking', 'Market Analysis', 'Trend Detection', 'Pricing Intel', 'SWOT Analysis', 'Opportunity Alerts'],
    tier: 'enterprise',
    learningProgress: 81,
    efficiency: 89,
    healthScore: 70,
    weeklyGrowth: 0,
    trend: 'stable',
    recentActions: ['Paused - awaiting activation'],
    metrics: { campaignsRun: 0, reach: '-', engagement: 0, impressions: '-', conversions: 0, roi: '-' },
  },
  {
    id: 'mg-9',
    name: 'AI Audience Targeting Agent',
    description: 'Identifies and segments target audiences',
    category: 'marketing-growth',
    enabled: true,
    status: 'active',
    tasksCompleted: 190,
    successRate: 87,
    lastActive: '20 min ago',
    capabilities: ['Audience Segmentation', 'Lookalike Creation', 'Persona Development', 'Intent Signals', 'Behavioral Analysis', 'Custom Audiences'],
    tier: 'premium',
    learningProgress: 83,
    efficiency: 88,
    healthScore: 88,
    weeklyGrowth: 16,
    trend: 'up',
    recentActions: ['Created 5 lookalike audiences', 'Refined buyer personas', 'Identified new segment'],
    metrics: { campaignsRun: 67, reach: '4.5M', engagement: 5.2, impressions: '22.1M', conversions: 5670, roi: '210%' },
  },
];

const operationsManagementSubAgents: SubAgent[] = [
  {
    id: 'om-1',
    name: 'AI Operations Manager',
    description: 'Oversees all operational processes and KPIs',
    category: 'operations-management',
    enabled: true,
    status: 'active',
    tasksCompleted: 1890,
    successRate: 96,
    lastActive: '3 min ago',
    capabilities: ['Process Oversight', 'KPI Tracking', 'Resource Management', 'Bottleneck Detection', 'Performance Reviews', 'Strategic Planning'],
    tier: 'enterprise',
    learningProgress: 94,
    efficiency: 97,
    healthScore: 97,
    weeklyGrowth: 8,
    trend: 'up',
    recentActions: ['Reviewed weekly KPIs', 'Identified efficiency gaps', 'Reallocated resources'],
    metrics: { processesManaged: 45, efficiency: '97%', costSavings: '$45K', uptime: '99.9%' },
  },
  {
    id: 'om-2',
    name: 'AI Workflow Automation Agent',
    description: 'Automates repetitive workflows and processes',
    category: 'operations-management',
    enabled: true,
    status: 'active',
    tasksCompleted: 3450,
    successRate: 98,
    lastActive: '1 min ago',
    capabilities: ['Workflow Design', 'Task Automation', 'Integration', 'Error Handling', 'Notifications', 'Scheduling'],
    tier: 'premium',
    learningProgress: 96,
    efficiency: 99,
    healthScore: 99,
    weeklyGrowth: 12,
    trend: 'up',
    recentActions: ['Automated 23 workflows', 'Reduced manual tasks by 40%', 'Created approval chain'],
    metrics: { workflowsAutomated: 156, hoursaved: 890, errorRate: '0.1%', activeWorkflows: 78 },
  },
  {
    id: 'om-3',
    name: 'AI Task Coordinator',
    description: 'Coordinates tasks across teams and departments',
    category: 'operations-management',
    enabled: true,
    status: 'active',
    tasksCompleted: 2340,
    successRate: 94,
    lastActive: '5 min ago',
    capabilities: ['Task Assignment', 'Priority Management', 'Deadline Tracking', 'Dependencies', 'Progress Monitoring', 'Team Coordination'],
    tier: 'premium',
    learningProgress: 91,
    efficiency: 95,
    healthScore: 95,
    weeklyGrowth: 10,
    trend: 'up',
    recentActions: ['Assigned 45 tasks', 'Resolved 3 blockers', 'Updated project timeline'],
    metrics: { tasksCoordinated: 890, onTimeDelivery: '96%', teamProductivity: '+23%', activeTasks: 234 },
  },
  {
    id: 'om-4',
    name: 'AI Process Optimization Agent',
    description: 'Analyzes and optimizes business processes',
    category: 'operations-management',
    enabled: true,
    status: 'active',
    tasksCompleted: 780,
    successRate: 92,
    lastActive: '12 min ago',
    capabilities: ['Process Mining', 'Bottleneck Analysis', 'Optimization Suggestions', 'A/B Testing', 'ROI Calculation', 'Implementation'],
    tier: 'enterprise',
    learningProgress: 88,
    efficiency: 93,
    healthScore: 93,
    weeklyGrowth: 18,
    trend: 'up',
    recentActions: ['Optimized onboarding process', 'Reduced cycle time by 30%', 'Identified 5 bottlenecks'],
    metrics: { processesOptimized: 34, efficiencyGain: '28%', costReduction: '$67K', implementedChanges: 89 },
  },
  {
    id: 'om-5',
    name: 'AI Resource Planner',
    description: 'Plans and allocates resources efficiently',
    category: 'operations-management',
    enabled: true,
    status: 'active',
    tasksCompleted: 560,
    successRate: 91,
    lastActive: '8 min ago',
    capabilities: ['Capacity Planning', 'Resource Allocation', 'Forecasting', 'Budget Management', 'Skill Matching', 'Utilization Tracking'],
    tier: 'premium',
    learningProgress: 85,
    efficiency: 90,
    healthScore: 90,
    weeklyGrowth: 14,
    trend: 'up',
    recentActions: ['Allocated Q2 resources', 'Forecasted hiring needs', 'Optimized team utilization'],
    metrics: { resourcesManaged: 120, utilization: '87%', budgetVariance: '+2%', forecastAccuracy: '94%' },
  },
  {
    id: 'om-6',
    name: 'AI Compliance Monitoring Agent',
    description: 'Monitors and ensures regulatory compliance',
    category: 'operations-management',
    enabled: true,
    status: 'training',
    tasksCompleted: 340,
    successRate: 97,
    lastActive: '20 min ago',
    capabilities: ['Regulatory Tracking', 'Audit Preparation', 'Risk Assessment', 'Policy Enforcement', 'Documentation', 'Reporting'],
    tier: 'enterprise',
    learningProgress: 79,
    efficiency: 94,
    healthScore: 85,
    weeklyGrowth: 6,
    trend: 'stable',
    recentActions: ['Completed SOC2 audit prep', 'Updated compliance policies', 'Flagged 2 risks'],
    metrics: { complianceScore: '98%', auditsCompleted: 12, risksIdentified: 8, policiesEnforced: 45 },
  },
  {
    id: 'om-7',
    name: 'AI Vendor Management Agent',
    description: 'Manages vendor relationships and contracts',
    category: 'operations-management',
    enabled: false,
    status: 'inactive',
    tasksCompleted: 230,
    successRate: 89,
    lastActive: '2 hours ago',
    capabilities: ['Vendor Evaluation', 'Contract Management', 'Performance Tracking', 'Negotiation Support', 'Risk Assessment', 'Cost Optimization'],
    tier: 'premium',
    learningProgress: 72,
    efficiency: 86,
    healthScore: 70,
    weeklyGrowth: 0,
    trend: 'stable',
    recentActions: ['Paused - awaiting activation'],
    metrics: { vendorsManaged: 45, contractValue: '$2.3M', savings: '$120K', renewalRate: '92%' },
  },
  {
    id: 'om-8',
    name: 'AI Quality Control Agent',
    description: 'Ensures quality standards across operations',
    category: 'operations-management',
    enabled: true,
    status: 'active',
    tasksCompleted: 1120,
    successRate: 95,
    lastActive: '6 min ago',
    capabilities: ['Quality Audits', 'Defect Detection', 'Process Control', 'Standards Enforcement', 'Improvement Suggestions', 'Reporting'],
    tier: 'premium',
    learningProgress: 90,
    efficiency: 96,
    healthScore: 96,
    weeklyGrowth: 9,
    trend: 'up',
    recentActions: ['Conducted 15 quality audits', 'Detected 3 defects', 'Improved quality score by 5%'],
    metrics: { qualityScore: '97%', defectsDetected: 23, auditsCompleted: 156, improvementsMade: 67 },
  },
];

const dataIntelligenceSubAgents: SubAgent[] = [
  {
    id: 'di-1',
    name: 'AI Data Analyst',
    description: 'Analyzes data and generates actionable insights',
    category: 'data-intelligence',
    enabled: true,
    status: 'active',
    tasksCompleted: 2340,
    successRate: 94,
    lastActive: '2 min ago',
    capabilities: ['Data Analysis', 'Visualization', 'Report Generation', 'Trend Detection', 'Anomaly Detection', 'Predictive Models'],
    tier: 'enterprise',
    learningProgress: 92,
    efficiency: 96,
    healthScore: 96,
    weeklyGrowth: 15,
    trend: 'up',
    recentActions: ['Generated weekly analytics report', 'Identified 3 trends', 'Created dashboard'],
    metrics: { reportsGenerated: 456, insightsDelivered: 890, dataProcessed: '12TB', accuracy: '98%' },
  },
  {
    id: 'di-2',
    name: 'AI Sales Data Analyst',
    description: 'Analyzes sales data for revenue optimization',
    category: 'data-intelligence',
    enabled: true,
    status: 'active',
    tasksCompleted: 1890,
    successRate: 92,
    lastActive: '4 min ago',
    capabilities: ['Sales Analytics', 'Pipeline Analysis', 'Win/Loss Analysis', 'Territory Planning', 'Quota Setting', 'Forecasting'],
    tier: 'premium',
    learningProgress: 89,
    efficiency: 94,
    healthScore: 94,
    weeklyGrowth: 12,
    trend: 'up',
    recentActions: ['Analyzed Q1 pipeline', 'Identified top performers', 'Optimized territories'],
    metrics: { salesInsights: 234, revenueImpact: '$890K', forecastAccuracy: '94%', pipelineHealth: '87%' },
  },
  {
    id: 'di-3',
    name: 'AI Financial Analyst',
    description: 'Analyzes financial data and forecasts',
    category: 'data-intelligence',
    enabled: true,
    status: 'active',
    tasksCompleted: 1230,
    successRate: 95,
    lastActive: '8 min ago',
    capabilities: ['Financial Modeling', 'Budget Analysis', 'Cash Flow Forecasting', 'Cost Analysis', 'ROI Calculation', 'Risk Assessment'],
    tier: 'enterprise',
    learningProgress: 91,
    efficiency: 97,
    healthScore: 97,
    weeklyGrowth: 8,
    trend: 'up',
    recentActions: ['Updated financial model', 'Forecasted Q2 revenue', 'Analyzed cost centers'],
    metrics: { modelsCreated: 89, forecastAccuracy: '96%', costSavings: '$234K', budgetVariance: '1.2%' },
  },
  {
    id: 'di-4',
    name: 'AI Customer Insights Agent',
    description: 'Generates deep customer behavior insights',
    category: 'data-intelligence',
    enabled: true,
    status: 'active',
    tasksCompleted: 980,
    successRate: 93,
    lastActive: '6 min ago',
    capabilities: ['Behavioral Analysis', 'Segmentation', 'Journey Mapping', 'Lifetime Value', 'Churn Prediction', 'Persona Development'],
    tier: 'premium',
    learningProgress: 87,
    efficiency: 92,
    healthScore: 92,
    weeklyGrowth: 18,
    trend: 'up',
    recentActions: ['Mapped customer journey', 'Identified 5 segments', 'Predicted churn risk'],
    metrics: { customersAnalyzed: '45K', segmentsCreated: 12, churnPredicted: 234, ltv: '$1.2M' },
  },
  {
    id: 'di-5',
    name: 'AI Forecasting Agent',
    description: 'Creates predictive forecasts for business metrics',
    category: 'data-intelligence',
    enabled: true,
    status: 'active',
    tasksCompleted: 670,
    successRate: 91,
    lastActive: '12 min ago',
    capabilities: ['Time Series Analysis', 'Demand Forecasting', 'Trend Prediction', 'Scenario Planning', 'Confidence Intervals', 'Model Selection'],
    tier: 'enterprise',
    learningProgress: 88,
    efficiency: 93,
    healthScore: 93,
    weeklyGrowth: 14,
    trend: 'up',
    recentActions: ['Updated demand forecast', 'Created scenario models', 'Improved accuracy by 8%'],
    metrics: { forecastsCreated: 156, accuracy: '93%', modelsDeployed: 34, scenariosAnalyzed: 89 },
  },
  {
    id: 'di-6',
    name: 'AI Risk Analyst',
    description: 'Identifies and assesses business risks',
    category: 'data-intelligence',
    enabled: true,
    status: 'training',
    tasksCompleted: 450,
    successRate: 94,
    lastActive: '18 min ago',
    capabilities: ['Risk Identification', 'Impact Assessment', 'Mitigation Planning', 'Monitoring', 'Compliance Tracking', 'Reporting'],
    tier: 'enterprise',
    learningProgress: 78,
    efficiency: 89,
    healthScore: 85,
    weeklyGrowth: 10,
    trend: 'up',
    recentActions: ['Assessed 12 risks', 'Created mitigation plan', 'Updated risk register'],
    metrics: { risksIdentified: 67, mitigated: 45, riskScore: 'Low', complianceRate: '98%' },
  },
  {
    id: 'di-7',
    name: 'AI Fraud Detection Agent',
    description: 'Detects and prevents fraudulent activities',
    category: 'data-intelligence',
    enabled: true,
    status: 'active',
    tasksCompleted: 3450,
    successRate: 98,
    lastActive: '1 min ago',
    capabilities: ['Pattern Recognition', 'Anomaly Detection', 'Real-time Alerts', 'Investigation Support', 'Rule Engine', 'Machine Learning'],
    tier: 'enterprise',
    learningProgress: 95,
    efficiency: 99,
    healthScore: 99,
    weeklyGrowth: 5,
    trend: 'stable',
    recentActions: ['Blocked 12 fraudulent transactions', 'Updated detection rules', 'Investigated 3 cases'],
    metrics: { fraudDetected: 234, amountSaved: '$890K', falsePositives: '0.1%', responseTime: '0.5s' },
  },
  {
    id: 'di-8',
    name: 'AI Competitive Analyst',
    description: 'Analyzes competitive landscape and market position',
    category: 'data-intelligence',
    enabled: false,
    status: 'inactive',
    tasksCompleted: 340,
    successRate: 90,
    lastActive: '3 hours ago',
    capabilities: ['Competitor Tracking', 'Market Analysis', 'Pricing Intelligence', 'Feature Comparison', 'SWOT Analysis', 'Strategic Recommendations'],
    tier: 'premium',
    learningProgress: 74,
    efficiency: 85,
    healthScore: 70,
    weeklyGrowth: 0,
    trend: 'stable',
    recentActions: ['Paused - awaiting activation'],
    metrics: { competitorsTracked: 23, reportsGenerated: 45, insightsDelivered: 89, marketShare: '24%' },
  },
];

const allSubAgents = [
  ...customerExperienceSubAgents,
  ...salesRevenueSubAgents,
  ...marketingGrowthSubAgents,
  ...operationsManagementSubAgents,
  ...dataIntelligenceSubAgents,
];

const mainAgents: MainAgent[] = [
  {
    id: 'customer-experience',
    name: 'Customer Experience AI',
    shortName: 'Customer AI',
    description: 'Customer Interaction & Support',
    category: 'customer-experience',
    color: '#007AFF',
    gradient: ['#007AFF', '#5856D6'],
    enabled: true,
    status: 'active',
    subAgentCount: 8,
    activeCount: 7,
    tasksToday: 1234,
    successRate: 96,
    healthScore: 95,
    trend: 'up',
    trendValue: 12,
  },
  {
    id: 'sales-revenue',
    name: 'Sales & Revenue AI',
    shortName: 'Sales AI',
    description: 'Lead Generation → Deal Closing',
    category: 'sales-revenue',
    color: '#34C759',
    gradient: ['#34C759', '#30B050'],
    enabled: true,
    status: 'active',
    subAgentCount: 9,
    activeCount: 8,
    tasksToday: 892,
    successRate: 91,
    healthScore: 92,
    trend: 'up',
    trendValue: 18,
  },
  {
    id: 'marketing-growth',
    name: 'Marketing & Growth AI',
    shortName: 'Marketing AI',
    description: 'Customer Acquisition & Brand Growth',
    category: 'marketing-growth',
    color: '#FF9500',
    gradient: ['#FF9500', '#FF6B00'],
    enabled: true,
    status: 'active',
    subAgentCount: 9,
    activeCount: 8,
    tasksToday: 567,
    successRate: 93,
    healthScore: 93,
    trend: 'up',
    trendValue: 22,
  },
  {
    id: 'operations-management',
    name: 'Operations & Management AI',
    shortName: 'Operations AI',
    description: 'Business Execution & Operations',
    category: 'operations-management',
    color: '#5856D6',
    gradient: ['#5856D6', '#7B68EE'],
    enabled: true,
    status: 'active',
    subAgentCount: 8,
    activeCount: 7,
    tasksToday: 445,
    successRate: 97,
    healthScore: 94,
    trend: 'stable',
    trendValue: 5,
  },
  {
    id: 'data-intelligence',
    name: 'Data & Intelligence AI',
    shortName: 'Data AI',
    description: 'Analytics & Decision Support',
    category: 'data-intelligence',
    color: '#FF2D55',
    gradient: ['#FF2D55', '#FF6B6B'],
    enabled: true,
    status: 'active',
    subAgentCount: 8,
    activeCount: 7,
    tasksToday: 678,
    successRate: 94,
    healthScore: 93,
    trend: 'up',
    trendValue: 15,
  },
];

export const getAgentsProcedure = publicProcedure
  .input(z.object({
    category: z.enum(['customer-experience', 'sales-revenue', 'marketing-growth', 'operations-management', 'data-intelligence', 'analysis-performance', 'core-intelligence', 'all']).optional(),
    includeSubAgents: z.boolean().optional().default(true),
  }).optional())
  .query(({ input }) => {
    const category = input?.category;
    const includeSubAgents = input?.includeSubAgents ?? true;

    let filteredMainAgents = mainAgents;
    let filteredSubAgents = allSubAgents;

    if (category && category !== 'all') {
      filteredMainAgents = mainAgents.filter(a => a.category === category);
      filteredSubAgents = allSubAgents.filter(a => a.category === category);
    }

    return {
      mainAgents: filteredMainAgents,
      subAgents: includeSubAgents ? filteredSubAgents : [],
      stats: {
        totalMainAgents: filteredMainAgents.length,
        totalSubAgents: filteredSubAgents.length,
        activeSubAgents: filteredSubAgents.filter(a => a.enabled).length,
        avgSuccessRate: Math.round(filteredSubAgents.reduce((acc, a) => acc + a.successRate, 0) / filteredSubAgents.length),
        avgHealthScore: Math.round(filteredSubAgents.reduce((acc, a) => acc + a.healthScore, 0) / filteredSubAgents.length),
      },
    };
  });
