import React from 'react';
import { AgentPageWrapper } from '@/components/ai-agent/AgentPageWrapper';

export default function AgentPage() {
  const agent = {
    id: 'ai-analytics-specialist',
    uid: 'ktx-08-analytics-specialist',
    name: 'AI AI Analytics Specialist',
    title: 'AI Analytics Specialist',
    description: 'AI AI Analytics Specialist coordinates team activities and ensures quality output for the Legal & Compliance department. This AI agent automates complex workflows, provides intelligent insights, and collaborates with other agents to achieve organizational goals with maximum efficiency.',
    capabilities: ['Audit Management', 'Contract Management', 'Regulatory Compliance', 'Risk Assessment', 'Legal Research'],
    color: '#3F51B5',
    type: 'agent' as const,
    humanCost: '$65k/year',
    aiCost: '$800/mo',
    efficiency: '76% efficiency',
    replacesRole: 'AI Analytics Specialist',
    subAgents: [
      { id: 'ai-data-strategy-advisor', uid: 'ktx-08-data-strategy-advisor', name: 'AI AI Data Strategy Advisor', title: 'AI Data Strategy Advisor', route: '/ai-agent/legal/data-strategy-advisor' },
      { id: 'ai-ai-governance-enforcer', uid: 'ktx-08-ai-governance-enforcer', name: 'AI AI AI Governance Enforcer', title: 'AI AI Governance Enforcer', route: '/ai-agent/legal/ai-governance-enforcer' },
      { id: 'ai-data-monetization-planner', uid: 'ktx-08-data-monetization-planner', name: 'AI AI Data Monetization Planner', title: 'AI Data Monetization Planner', route: '/ai-agent/legal/data-monetization-planner' },
      { id: 'ai-research-direction-setter', uid: 'ktx-08-research-direction-setter', name: 'AI AI Research Direction Setter', title: 'AI Research Direction Setter', route: '/ai-agent/legal/research-direction-setter' },
      { id: 'ai-model-validation-overseer', uid: 'ktx-08-model-validation-overseer', name: 'AI AI Model Validation Overseer', title: 'AI Model Validation Overseer', route: '/ai-agent/legal/model-validation-overseer' },
      { id: 'ai-publication-coordinator', uid: 'ktx-08-publication-coordinator', name: 'AI AI Publication Coordinator', title: 'AI Publication Coordinator', route: '/ai-agent/legal/publication-coordinator' },
      { id: 'ai-pipeline-architect', uid: 'ktx-08-pipeline-architect', name: 'AI AI Pipeline Architect', title: 'AI Pipeline Architect', route: '/ai-agent/legal/pipeline-architect' },
      { id: 'ai-data-platform-planner', uid: 'ktx-08-data-platform-planner', name: 'AI AI Data Platform Planner', title: 'AI Data Platform Planner', route: '/ai-agent/legal/data-platform-planner' },
      { id: 'ai-data-cost-optimizer', uid: 'ktx-08-data-cost-optimizer', name: 'AI AI Data Cost Optimizer', title: 'AI Data Cost Optimizer', route: '/ai-agent/legal/data-cost-optimizer' },
      { id: 'ai-analytics-roadmap-planner', uid: 'ktx-08-analytics-roadmap-planner', name: 'AI AI Analytics Roadmap Planner', title: 'AI Analytics Roadmap Planner', route: '/ai-agent/legal/analytics-roadmap-planner' },
      { id: 'ai-insight-delivery-manager', uid: 'ktx-08-insight-delivery-manager', name: 'AI AI Insight Delivery Manager', title: 'AI Insight Delivery Manager', route: '/ai-agent/legal/insight-delivery-manager' },
      { id: 'ai-stakeholder-communicator', uid: 'ktx-08-stakeholder-communicator', name: 'AI AI Stakeholder Communicator', title: 'AI Stakeholder Communicator', route: '/ai-agent/legal/stakeholder-communicator' },
      { id: 'ai-dashboard-architect', uid: 'ktx-08-dashboard-architect', name: 'AI AI Dashboard Architect', title: 'AI Dashboard Architect', route: '/ai-agent/legal/dashboard-architect' },
      { id: 'ai-kpi-definition-specialist', uid: 'ktx-08-kpi-definition-specialist', name: 'AI AI KPI Definition Specialist', title: 'AI KPI Definition Specialist', route: '/ai-agent/legal/kpi-definition-specialist' },
      { id: 'ai-report-scheduler', uid: 'ktx-08-report-scheduler', name: 'AI AI Report Scheduler', title: 'AI Report Scheduler', route: '/ai-agent/legal/report-scheduler' },
      { id: 'ai-data-catalog-curator', uid: 'ktx-08-data-catalog-curator', name: 'AI AI Data Catalog Curator', title: 'AI Data Catalog Curator', route: '/ai-agent/legal/data-catalog-curator' },
      { id: 'ai-metadata-enforcer', uid: 'ktx-08-metadata-enforcer', name: 'AI AI Metadata Enforcer', title: 'AI Metadata Enforcer', route: '/ai-agent/legal/metadata-enforcer' },
      { id: 'ai-data-lineage-tracker', uid: 'ktx-08-data-lineage-tracker', name: 'AI AI Data Lineage Tracker', title: 'AI Data Lineage Tracker', route: '/ai-agent/legal/data-lineage-tracker' },
      { id: 'ai-analytics-project-coordinator', uid: 'ktx-08-analytics-project-coordinator', name: 'AI AI Analytics Project Coordinator', title: 'AI Analytics Project Coordinator', route: '/ai-agent/legal/analytics-project-coordinator' },
      { id: 'ai-priority-planner', uid: 'ktx-08-priority-planner', name: 'AI AI Priority Planner', title: 'AI Priority Planner', route: '/ai-agent/legal/priority-planner' },
      { id: 'ai-quality-reviewer', uid: 'ktx-08-quality-reviewer', name: 'AI AI Quality Reviewer', title: 'AI Quality Reviewer', route: '/ai-agent/legal/quality-reviewer' },
      { id: 'ai-feature-engineer', uid: 'ktx-08-feature-engineer', name: 'AI AI Feature Engineer', title: 'AI Feature Engineer', route: '/ai-agent/legal/feature-engineer' },
      { id: 'ai-experiment-designer', uid: 'ktx-08-experiment-designer', name: 'AI AI Experiment Designer', title: 'AI Experiment Designer', route: '/ai-agent/legal/experiment-designer' },
      { id: 'ai-model-tuner', uid: 'ktx-08-model-tuner', name: 'AI AI Model Tuner', title: 'AI Model Tuner', route: '/ai-agent/legal/model-tuner' },
      { id: 'ai-query-builder', uid: 'ktx-08-query-builder', name: 'AI AI Query Builder', title: 'AI Query Builder', route: '/ai-agent/legal/query-builder' },
      { id: 'ai-visualization-creator', uid: 'ktx-08-visualization-creator', name: 'AI AI Visualization Creator', title: 'AI Visualization Creator', route: '/ai-agent/legal/visualization-creator' },
      { id: 'ai-anomaly-detector', uid: 'ktx-08-anomaly-detector', name: 'AI AI Anomaly Detector', title: 'AI Anomaly Detector', route: '/ai-agent/legal/anomaly-detector' },
      { id: 'ai-report-builder', uid: 'ktx-08-report-builder', name: 'AI AI Report Builder', title: 'AI Report Builder', route: '/ai-agent/legal/report-builder' },
      { id: 'ai-dashboard-tester', uid: 'ktx-08-dashboard-tester', name: 'AI AI Dashboard Tester', title: 'AI Dashboard Tester', route: '/ai-agent/legal/dashboard-tester' },
      { id: 'ai-data-connector-builder', uid: 'ktx-08-data-connector-builder', name: 'AI AI Data Connector Builder', title: 'AI Data Connector Builder', route: '/ai-agent/legal/data-connector-builder' },
      { id: 'ai-model-deployer', uid: 'ktx-08-model-deployer', name: 'AI AI Model Deployer', title: 'AI Model Deployer', route: '/ai-agent/legal/model-deployer' },
      { id: 'ai-model-performance-monitor', uid: 'ktx-08-model-performance-monitor', name: 'AI AI Model Performance Monitor', title: 'AI Model Performance Monitor', route: '/ai-agent/legal/model-performance-monitor' },
      { id: 'ai-pipeline-automator', uid: 'ktx-08-pipeline-automator', name: 'AI AI Pipeline Automator', title: 'AI Pipeline Automator', route: '/ai-agent/legal/pipeline-automator' },
      { id: 'ai-data-quality-scorer', uid: 'ktx-08-data-quality-scorer', name: 'AI AI Data Quality Scorer', title: 'AI Data Quality Scorer', route: '/ai-agent/legal/data-quality-scorer' },
      { id: 'ai-standard-enforcer', uid: 'ktx-08-standard-enforcer', name: 'AI AI Standard Enforcer', title: 'AI Standard Enforcer', route: '/ai-agent/legal/standard-enforcer' },
      { id: 'ai-issue-resolver', uid: 'ktx-08-issue-resolver', name: 'AI AI Issue Resolver', title: 'AI Issue Resolver', route: '/ai-agent/legal/issue-resolver' },
      { id: 'ai-advanced-statistician', uid: 'ktx-08-advanced-statistician', name: 'AI AI Advanced Statistician', title: 'AI Advanced Statistician', route: '/ai-agent/legal/advanced-statistician' },
      { id: 'ai-segmentation-expert', uid: 'ktx-08-segmentation-expert', name: 'AI AI Segmentation Expert', title: 'AI Segmentation Expert', route: '/ai-agent/legal/segmentation-expert' },
      { id: 'ai-forecast-builder', uid: 'ktx-08-forecast-builder', name: 'AI AI Forecast Builder', title: 'AI Forecast Builder', route: '/ai-agent/legal/forecast-builder' }
    ],
    infrastructure: {
      status: 'online',
      health: 94,
      uptime: '99.3%',
      lastActive: 'Now',
      processingPower: 'standard',
    },
    roiMetrics: {
      savingsPerMonth: '$4047',
      tasksAutomatedDaily: 491,
      responseTime: '2.1s',
      accuracyRate: '99.3%',
    },
    hierarchy: {
      department: 'Legal & Compliance',
      level: 'team_lead',
      departmentId: 8,
    },
  };
  return <AgentPageWrapper agent={agent} />;
}
